### ISSUE TITLE
Research Zone Billing to make sure it works for PLG

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1000]
Should enable us to satisfy the requirements here: https://docs.google.com/document/d/1xsDCv_WRsWS275-LhWg4-MS1EywcSjcQq9tXVoFnezM/edit#heading=h.j2a5mawn8wx9

**Comment by vdavid** [comment]
Update: I've looked into their [API docs](https://zab-docs.zoneandco.com/) and shared my findings and next actions with finance on Slack.

**Comment by vdavid** [comment]
Fwiw, leaving a link [here](https://sourcegraph.slack.com/archives/C05RJTUSR7Z/p1694524942276439) to the private conversation. I'm closing this as it sounds like the answer is a confident "Yes"
