### ISSUE TITLE
Cody doesn't refer to the current file in some cases where obvious

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#1010]
Customer reports:
- [x] https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1694454085492699
- [x] https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1693507735454299
- [x] https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1696581801738459

**Comment by chenkc805** [comment]
I hit this as well: https://sourcegraph.slack.com/archives/C05AGQYD528/p1694206443472349
