### ISSUE TITLE
Add /embeddings command

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#1013]
Currently, the only way to create embeddings for any open-source repository is by using the Discord bot. I want to propose adding a new command ` /embeddings [repo url]`, which would let the users create the embeddings directly from the extension. 

To add this command, two changes need to be made:
- Add a new command under the VSCode extension
- Configuring the embeddings admin API endpoint to submit a request

Why this would be helpful?
Adding this command would reduce the friction of creating embeddings for the users. Later, the support to develop the private repository embeddings can also be done for users with Enterprise instances.

CC: @philipp-spiess @abeatrix WDYT?

**Comment by jdorfman** [comment]
I think that is a great idea.
