### ISSUE TITLE
Add company role data to Amplitude to measure internal Lovability

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1024]
@kelsey-brown , can I get your help uploading this company role data into Amplitude, and then joining that with event data so I can track lovability data directly in Amplitude (rather than my own custom built/hacky Google sheets?)

Role data: https://docs.google.com/spreadsheets/d/1-lLVUr5cFSxNEj0v5_m0PjpO5YFuGik5qJfz_gbgC0g/edit#gid=779671194

How I'm joining email data: https://docs.google.com/spreadsheets/d/1-lLVUr5cFSxNEj0v5_m0PjpO5YFuGik5qJfz_gbgC0g/edit#gid=1530973111

**Comment by kelsey-brown** [comment]
@akalia25 can we add this as a lookup in Amplitude?

**Comment by chenkc805** [comment]
Hey @kelsey-brown and @akalia25 , any update on this?

**Comment by kelsey-brown** [comment]
@akalia25 we can take a look at this during data review today!

**Comment by akalia25** [comment]
Hey @chenkc805, this is completed and the data is in Amplitude. You now add the role/dept to the internal lovability charts on Amplitude :) 

<img width="368" alt="image" src="https://github.com/sourcegraph/cody/assets/32119652/808989ba-cc38-4835-9723-a8c9955115cb">
