### ISSUE TITLE
Non-Stop Cody

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/cody#103]
Fixups: as a quick UX improvement, we could make the current UI way clearer for a new user.
- When you have no code selected and click on the fixup recipe, the error message says "sprinkle code with inline comments describing improvements, select it, then get if fixed up"
- Instead of seeing  the Cody blinking terminal prompt (which I find confusing in general, kinda tells me I need to be writing stuff whereas it should be clearer that it's a loading state), show a "Working on it..." and three dots cycling
- Replace the Here is my attempt at rewriting the selected code: by, "done", or "Here you go!". The current message makes me expect something in the chat UI, and when nothing comes it just feels broken

**Comment by dominiccooney** [comment]
Closing this stale issue. Non-stop has been integrated into inline editing.
