### ISSUE TITLE
Autocomplete: Backspace on displayed completion should remove suggestion

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1030]
RE https://sourcegraph.slack.com/archives/C05AGQYD528/p1694037206283699
Spin off from https://github.com/sourcegraph/cody/issues/969

> Deleting a line should force a new creation always

Pressing backspace on displayed completion should remove the suggestion and replace with a new one

Currently, there is no way to force regen unless the prefix is changed.

**Comment by abeatrix** [comment]
> The normal behavior of backspace showing the old completion until the new one is loaded is pretty reasonable IMO, what do you think?

Personally I found it annoying because it won't go away when I already found it unhelpful and wanted a new one 😝 but I'm speaking for myself not for the users though.

We can go with your suggestions first and see what people think? I think as long as a new one will show up then I'm fine with having it stay

**Comment by philipp-spiess** [comment]
> We can go with your suggestions first and see what people think? I think as long as a new one will show up then I'm fine with having it stay

Yeah, makes sense. To fix the fact that the old completion is visible before the new one is loaded would need a change of the  the insertion range again (which is currently always from the beginning of the current line). This was added specifically to address UX jankieness issues in this PR: https://github.com/sourcegraph/cody/pull/442 

Let's try to make sure we always generate a new completion first (i.e remove the network cache) and then we can still revisit.

We should also double-check what other completion providers do (IIRC Copilot does the exact same thing that we do)

**Comment by abeatrix** [comment]
working on it!
