### ISSUE TITLE
Update context UI for multi-repo

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#104]
As part of sourcegraph/cody#101 we need to figure out out how to support multiple repos in the context UI for both VS Code and the web.

Across both VS Code and web we want to:
- Show any repos/files/dirs inferred from environment (repos, current files/tabs)
- Add and remove repos (from SG endpoint, search filter query, +filesystem when in VS Code or App?)
- Ignore repos + files
- Flag if any repos may have degraded quality, actions/links to fix
- Show anything else being included 
- Respect and mirror user settings
- If repos are flagged for quality problems (e.g. no embeddings), link to repo page or buttons for remediation (might need to differ between VS Code and web)

For web, we also want to adapt it to work (and make sense) when a chat is opened on a web search results page.

Open questions/investigations:
- When loading up previous conversations, how does context work? I imagine it should be persisted against each chat, vs being global.
- Design wise, we have sourcegraph/sourcegraph#51097 to iterate on, adapt, or reference. Perhaps there's a version of that adapts the existing "Context" UI below the message input, doesn't have any modes, and might even follow the same UI pattern. We also need to critically look at whether we really want to rename it from "Context" to "Context Scope".

Related:
- https://github.com/sourcegraph/sourcegraph/issues/51097
- https://github.com/sourcegraph/sourcegraph/issues/51618
- https://github.com/sourcegraph/cody/issues/236
- https://github.com/sourcegraph/cody/issues/199

Similar issues in other products:
- https://github.com/microsoft/vscode-copilot-release/issues/144

**Comment by thenamankumar** [comment]
@toolmantim What is the state of this issue? Should we close this and open a new one for VS Code?
