### ISSUE TITLE
Remove certain events as DAU events

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1048]
I'm working on tracking Lovability (70% of EPD using Cody >15x a day) and I'm filtering for events where is_cody_product_DAU_event = TRUE. 

Currently the following two events are marked as DAU events, when IMO they shouldn't be, because they don't need any explicit prompting. Having this currently inflates our usability numbers:

- CodyVSCodeExtension:chatResponse:noCode (fires passively for every chat response)
- CodyVSCodeExtension:chatResponse:hasCode (fires passively for every chat response)
- CodyVSCodeExtension:recipe:next-questions:executed ([context](https://sourcegraph.slack.com/archives/C05AGQYD528/p1693006011952129))

Query:
SELECT
name,
count(*),
count(distinct user_id)
FROM
dotcom_events.events
WHERE
LOWER(name) LIKE '%cody%'
AND timestamp > '2023-08-24'
AND is_cody_product_DAU_event = TRUE
GROUP BY 1
ORDER BY 2 DESC

**Comment by chenkc805** [comment]
This begs the question for me: Should we include the following events as also DAU metrics (which count towards Lovability)?

- CodyVSCodeExtension:restoreChatHistoryButton:clicked
- CodyVSCodeExtension:insertButton:clicked
- CodyVSCodeExtension:keyDown:Copy:clicked
- CodyVSCodeExtension:keyDown:Paste:clicked

One could argue that while these are users interacting with Cody, they're not "fundamental" actions like an autocomplete acceptance or chat question. Curious what others think CC: @dadlerj

**Comment by kelsey-brown** [comment]
@chenkc805 Those 4 events all fit our definition of product DAU. Full definition is [here](https://docs.google.com/document/d/1dejSoH5PwDjjNzlk81dlE7Zph0TnjHpsiWJip5AdYy8/edit) but here's the TLDR

> A product DAU represents a user who (1) makes a choice to interact or engage with Cody and (2) likely gets value from it.

If you think we need to update our product DAU definition, I'm open to having that discussion (though we should move it to somewhere with a broader audience) but within our current definition, those events are product DAU events.

**Comment by dadlerj** [comment]
Yeah I agree with you Kevin about the first message at the top of this thread—nocode/hascode seem irrelevant, and I'm not even sure what the next-questions one is, but I trust you that it shouldn't be included if not a user-driven event.

I agree with Kelsey too, particularly about the copy and insert ones. What does the "Paste:clicked" event actually mean?

I would also say that for most of these, it's impossible to trigger them without having previously done a product DAU-qualifying action. E.g. you can't copy/paste Cody-generated code without first prompting Cody to generate code, you know? Hopefully these aren't material either way.

**Comment by chenkc805** [comment]
> I would also say that for most of these, it's impossible to trigger them without having previously done a product DAU-qualifying action. E.g. you can't copy/paste Cody-generated code without first prompting Cody to generate code, you know? Hopefully these aren't material either way.

This is true, and doesn't affect DAU metrics at all, so we're good there. 

It would, however, effect frequency metrics (ie. 15x + / day usage). These likely have a material impact on how we're measuring lovability today. 

So all in all I'm good with removing:
- CodyVSCodeExtension:chatResponse:noCode
- CodyVSCodeExtension:chatResponse:hasCode
- CodyVSCodeExtension:recipe:next-questions:executed
From the DAU definition. 

And I'm good with keeping these 4 events as DAU metrics since it fits the definition:
- CodyVSCodeExtension:restoreChatHistoryButton:clicked
- CodyVSCodeExtension:insertButton:clicked
- CodyVSCodeExtension:keyDown:Copy:clicked
- CodyVSCodeExtension:keyDown:Paste:clicked

(not urgent, but something we should think about) It does make me think if it's worth thinking about an even smaller subset of events that purely measures a "Cody interaction", because that's what I think of as a "core valuable action" that user takes, not just, for example, accessing their chat history. These seems like the really valuable actions that we should measure success on. Curious what ya'll think. Specifically:

In my mind the only events that fit this category are:
- accept and autocomplete
- submit a chat/command/fixup
- successfully embed a repo

other things such as:
- copy/paste events
- navigation events
- passive events like autocomplete suggestions the next-question experience
- even creating a custom command (since you're not interfacing with Cody until you execute it)

**Comment by akalia25** [comment]
> CodyVSCodeExtension:chatResponse:noCode
> CodyVSCodeExtension:chatResponse:hasCode 
> CodyVSCodeExtension:recipe:next-questions:executed 

Regarding the initial three event DAU updates, I have made those changes. These are now `FALSE` to productDAU.

 It still makes sense to have those as `billingDAU` events based on our [definition](https://docs.google.com/document/d/1dejSoH5PwDjjNzlk81dlE7Zph0TnjHpsiWJip5AdYy8/edit#heading=h.c4gnfs91hqi0) and these events should not affect billing DAU counts in a meaningful way 

<img width="1107" alt="image" src="https://github.com/sourcegraph/cody/assets/32119652/e3a84484-397e-4d52-bb77-24426222e058">

**Comment by chenkc805** [comment]
Thanks team. Closing this out

**Comment by dadlerj** [comment]
Regarding your questions above about the future of the metric:

>(not urgent, but something we should think about) It does make me think if it's worth thinking about an even smaller subset of events that purely measures a "Cody interaction", because that's what I think of as a "core valuable action" that user takes, not just, for example, accessing their chat history. These seems like the really valuable actions that we should measure success on. Curious what ya'll think. Specifically:
>
>In my mind the only events that fit this category are:

We'd be happy to modify our definition of a product DAU. The goal is to provide the best view of "real" product usage to the team. But that said, I don't necessarily agree with your list. In my eyes, if I copy some code that the AI generated... That is a sign of true value being delivered—even more so than creating an embedding, for example. As a user, I'm taking Cody's output and actually doing something with it (versus setting Cody up to do something in the future, like with an embedding).

Some of the others are definitely a bit more on the line, though, such as accessing chat history, and I think we could reasonably exclude that one without even modifying our definition.

Feel free to request changes either way (to the definition or to specific inclusions/exclusions).
