### ISSUE TITLE
Non-Stop Cody: Fixups UX Polish

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#106]
- [ ] Promote dogfooding and monitor use. 
- [ ] Diff highlighting is too noisy. Try a traditional line, then intraline diff in more muted colors; try no diff with fences around the whole region like a "lock."
- [ ] Consider highlighting edits after they are applied.
- [ ] Diff view needs buttons for accepting changes.
- [ ] Diff view should focus on Cody's changes and not local changes; no blue rectangles in diff view.
- [ ] Cancel, Discard buttons need to be available everywhere.
- [ ] Cody button in top nav bar should not be in color; weight of lines, size, etc. are wrong.
- [ ] Order of icons in tree view should match actions in code lens.
- [ ] Use a sparkle for items ready to apply, instead of a pencil.
- [ ] Automatically respin tasks when there’s a conflict. Communicate the reason for failures—excessive respins—through the CodeLens, etc.
- [ ] Support a keyboard-only workflow using a Code Action to apply.
- [ ] Support a keyboard-only workflow by applying through a QuickPick items in the typing UI.
- [ ] Put a tiny part of the prompt with CodeLens prefix.
- [ ] Add tooltips with instructions to Code Lens/tree view/editor title buttons/etc.
- [ ] Implement "Apply All" in a way that accounts for progressively applying changes.
- [ ] Highlight in the overview where Cody has edits working and ready to accept.
- [ ] Remove the fixup tasks if you close and reopen the file
- [ ] Later: Consider the right design for "edit" so you can adjust the prompt and respin.

**Comment by dominiccooney** [comment]
@deepak2431 sorry I missed this message 😭 

@umpox is there anything on this list worth keeping around? Let's bring this issue back to life, or mothball it.

**Comment by deepak2431** [comment]
@dominiccooney No problem. Let me know if there's anything I can help with.

**Comment by umpox** [comment]
I think we can close this now. Many of these items have been implemented or we have gone in a different direction - and we have more dedicated individual issues for some of the items that we still need to add
