### ISSUE TITLE
Classify the types of responses Cody gives back to measure high quality responses vs low quality responses

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1066]
**Problem**: Currently we don't have visibility into when Cody gives back low quality answers, which hinders our ability to know when we are giving users subpar user experiences. 

**Goal**: to measure the common areas where users are running into errors or "low quality responses" to inform our product roadmap of what to improve. 

For example, look for Cody responses where:
- Cody gives errors back to the users explicitly 
- Cody says “sorry I can’t do that”, but doesn't show an explicit answer

**Comment by chenkc805** [comment]
@kelsey-brown I'm curious if you think we can do this using our existing telemetry today + any services that Google BigQuery has, as opposed to building some inference tool with our eng resources.

**Comment by dadlerj** [comment]
Hey @chenkc805 for both of these (this one and https://github.com/sourcegraph/cody/issues/1067) the challenge is going to be that we don't actually log the transcript (the prompt OR the response) for privacy reasons, so we can't do this post-hoc. 

I do think logging events on errors would be an easy addition for the Cody client eng teams, but that addition, and any further quality analysis, would have to happen in the product unless we expand our logging here (which is certainly possible, but would be a bigger, more complex conversation). Thoughts?
