### ISSUE TITLE
Bug: FixupTasks are not cleaned from the fixup view on failure

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#1088]
Currently the failure of a fixup task at any point will leave a pending job in the fixup view. 

https://github.com/sourcegraph/cody/assets/11155207/81810737-31a5-424e-b654-c6278f13e76d

I added a minor change to solve it for atleast the usecase where I saw it ([code](https://github.com/sourcegraph/cody/commit/9acd10a378b2daaca858bd0d7acb2f3c2bdc4c8a))

https://github.com/sourcegraph/cody/assets/11155207/a0e73968-fcd5-445a-80a7-431e23c95bfb

I would be happy to spin up a more clean solution in a PR for this but I wanted to know if people had other more elaborate plans for error handling that are yet to be implemented. CC @umpox  coz you wrote [this](https://github.com/sourcegraph/cody/pull/510/files#diff-319a8ef4cd07ac92062243b56f5f5aee5e906b82918cc35c08f28b526ef10937R95)

**Comment by jdorfman** [comment]
Thanks @arafatkatze

**Comment by abeatrix** [comment]
Thanks for looking into this. What you have looks good to me for unblocking the current issue! 

IIRC FixupTask has a method for displaying error, or somewhere in fixupController 😀

**Comment by arafatkatze** [comment]
We have moved far ways from this UX so this needs to be closed.

Thanks bot!!
