### ISSUE TITLE
Unable to use personal OpenAI token with Cody extension in VSCode

### ISSUE THREAD

**Issue by samwalters3** [sourcegraph/cody#1100]
Hello,

I am experiencing an issue using my personal openai token with the cody extension in vscode. I have added the following settings to my vscode settings:

Cody › Autocomplete › Advanced › Access Token: MY-TOKEN
Cody › Autocomplete › Advanced › Model: null
Cody › Autocomplete › Advanced › Provider: unstable-openai
Cody › Autocomplete › Advanced › Server Endpoint: https://api.openai.com/v1/chat/completions

However, after the configuration, when I attempt to use cody's chat, I get the following error :
Request failed: {"message": "rate limit exceeded"}

I have verified that my token is valid by using it directly with the openai api in colab. 

Is this a feature that is currently supported or is it still under development? if it is supported, could you please advise me on how to configure my vscode settings to fix the issue?

Thank you,

**Comment by samwalters3** [comment]
thanks for response, but really I don't know where to insert that config code?

**Comment by arafatkatze** [comment]
I recently used an OpenAI key with enterprise cody and that worked just fine.

Raise this again if folks face any issues.
