### ISSUE TITLE
"logEvent: CodyVSCodeExtension:restoreChatHistoryButton:clicked" fires when the button wasn't clicked

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1115]
Steps to repro:

- Uninstall Cody from VSCode. Don't clear local storage
- Install the pre-release version (I was on v0.11.1695136020)
- Have "testing.simplified-onboarding": true in settings.json (not sure if this makes a difference)
- Open debug console to see events
- Click "Cody" in the VSCode sidebar
- 🐛  See restoreChatHistoryButton:clicked event fire, even when there's no chat history button to click

![Image](https://github.com/sourcegraph/cody/assets/3654603/e6d0cd3e-4867-44eb-837b-5bc33cbe1f3d)

**Comment by chenkc805** [comment]
CC: @akalia25 and @kelsey-brown for viz

**Comment by akalia25** [comment]
Thanks @chenkc805, good to know! Our current volume for `CodyVSCodeExtension:restoreChatHistoryButton:clicked` looks like the below, so no _recent_ spikes in the data volume, but I'm sure once this is resolved we should see this go down. 

<img width="1467" alt="image" src="https://github.com/sourcegraph/cody/assets/32119652/a8cf5280-7e30-4979-8e50-2b0b9fd9d44e">

**Comment by vdavid** [comment]
We don't seem to be working on this so moving this back to the backlog
