### ISSUE TITLE
Hide Feedback Button on Error Response

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#112]
The feedback button is still shown whenever there's an error assistant response. This can cause bias with the feedback we collect for the actual Cody's response. I suggest hiding the feedback button in case of an error assistant response. 

Initially, I made a PR [here](https://github.com/sourcegraph/sourcegraph/pull/54424) for this, and there was some discussion, so I wanted to confirm this before I make a new PR. 

@abeatrix @toolmantim What do you think of this?

**Comment by deepak2431** [comment]
@toolmantim Your views on this?

**Comment by toolmantim** [comment]
It's nice to have, and as long as we keep in mind the comments from the other PR I don't see a problem accepting a new PR for it.

**Comment by deepak2431** [comment]
Great, I will make a new PR for this. As we don't have the web app and the Cody app code in this repo so it would be better to keep it optional for now.
