### ISSUE TITLE
Anthropic API keys not working because the cody mac app is out of date

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#1135]
I kept hitting the API rate limits in my experiments etc because I was manipulating cody's internal code and some of that made very high token LLM requests so I decided it's best if I use my own Anthropic keys.

Here's the problem with them 

<img width="993" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/3310eb9e-32cb-4df4-95dc-1a7dbff1a2c9">

And here's my config 
<img width="831" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/e467aa7e-0258-4c2f-9308-d698e8f0534f">

The causality is that the header does exist on the gateway where we make a request to anthropic but it was added in August -> https://github.com/sourcegraph/sourcegraph/pull/55532 

However the latest app version is July 11 so it doesn't have the header
<img width="389" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/62125db4-77f0-4a27-9d0d-f2ca9a6fe5bc">

I tried the API key on my machine for many other things and it works just fine. 

@jdorfman said `Yeah we paused on the App until we figure out if we just want to bring everything into the client plugins. We have gotten mixed reviews` so I understand there might be very valid reasons not to update the app but still this issue is something to keep in mind.

**Comment by taylorsperry** [comment]
Closing because the Cody app was [deprecated](https://docs.sourcegraph.com/cody/faq#what-happened-to-the-cody-app) as part of the December launch.
