### ISSUE TITLE
Build telemetry to measure lines of code written by humans to understand the % of lines of code that Cody helps a developer write

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1138]
Problem:

- Ultimately we want to be able to tell the market that Cody makes you X% more effective. X% = # lines of code written by Cody / # of lines of code written by a human + Cody
- While we [currently measure](https://docs.google.com/document/d/1UcjUdon1XO5GoLDIJJCGBq1zyhR6VfL2FE_apSPeLQo/edit#heading=h.ep0mac2hydrj) the numerator (# of lines of code that Cody people actually put in their editor), we don't know much code people write in a given day. 

Goal
- The deliverable for this issue is to measure the lines of code & characters of code written by a DAU over a certain time period. Looking at this on a daily or hourly basis should be enough. 
- Event name: CodyVSCodeExtension:amountOfCodeWritten:logged {“charCount”:X,“lineCount”:Y}

**Comment by chenkc805** [comment]
@beyang @csells can I get your help implementing this telemetry for VS Code? The PLG team doesn't have bandwidth to take this on at the moment.

**Comment by chenkc805** [comment]
CC @kelsey-brown @akalia25 for visability

**Comment by akalia25** [comment]
Hey @chenkc805, thanks for the visibility. This may be considered sensitive data, so we should probably get security and legal sign-off before collecting. And define if we should only collect for free users or for paid customers too.

**Comment by chenkc805** [comment]
Asking legal here: https://sourcegraph.slack.com/archives/C01GJFE26BX/p1695396452056459
