### ISSUE TITLE
[Bug] number line rerender annoying

### ISSUE THREAD

**Issue by BachiMjavanadze** [sourcegraph/cody#1149]
This feature is buggy:

![image](https://github.com/sourcegraph/cody/assets/38082501/a5730894-fc41-40fc-84fa-2becd1843517)

Every time I open new script the column splashes (rerender) and it's very annoying. So I disabled it:

`"cody.inlineChat.enabled": false,`

but now it does not works:

![image](https://github.com/sourcegraph/cody/assets/38082501/e6a15657-d955-4e0f-a071-da79570b780f)

I just want to disable buggy column splash (rerender) feature and remain `Ask Cody Inline` menu item.

Please fix it.

**Comment by jdorfman** [comment]
Thanks for reporting @BachiMjavanadze.  We will dig in.

cc @beyang
