### ISSUE TITLE
JetBrains: Chat: Add "Stop generating" button

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/cody#115]
It would be very useful to be able to stop Cody while it's talking.

This is how it looks in VS Code:

<img src="https://github.com/sourcegraph/sourcegraph/assets/2552265/31187510-980d-4dc4-a24a-a4fc7a99826b" width=600 />

I suggest we copy this in v1.

**Comment by szymonprz** [comment]
This issue was resolved by the https://github.com/sourcegraph/sourcegraph/pull/54710
