### ISSUE TITLE
Tree-sitter: use parse-trees to trigger multiline or singleline completions

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/cody#1157]
Currently, we decide which completion (multi vs. single) to trigger based on hardcoded block start symbols and a couple of regexes. We can use tree-sitter to categorize completion triggers and use them instead of the current approach for supported languages.

**Comment by beyang** [comment]
Examples:
* Function signature + open parens => generate full function body (even for long functions)
* Struct definitions => line by line (see how this affects CAR)

**Comment by valerybugakov** [comment]
Let's consider this issue closed by:
1. https://github.com/sourcegraph/cody/pull/1259
2. https://github.com/sourcegraph/cody/pull/1318

The follow-up work will be tracked here: https://github.com/sourcegraph/cody/issues/1455
