### ISSUE TITLE
Generate a daily email that summarizes diffs that happened in branches relevant to you as a re-engagement / retention tactic

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1183]
**Problem**

- There are many users who churn and stop using Cody over a period of time. For example, we have a D1 retention of ~20%, which means 80% of users don't come back the next day after signup/install. 
- A problem that developers encounter is that if there are changes in branches relevant to the branch they're working on, then their branches may have conflicts with other branches. Developers also just generally need to be up-to-date on these changes. 

**KPI**

- Retention rate (for users who used the product on Day N, who return on Day N+1?
- Resurrection rate (for users who haven't used the product in the past 7 days, how many return on Day N)

**Potential solution**

- Cody can take all the diffs in relevant branches for a developer and prioritize the highest value information in an email. The main CTA should somehow drive the user back to the IDE to use Cody.

**Comment by chenkc805** [comment]
@dominiccooney @umpox documenting the idea we were chatting about here. Feel free to change the description if anything looks off! 

Going from "Email for diffs" to "Use Cody in IDE" feels like a stretch. What useful flow could we meaningfully drive users to from the email back to ultimately end the user back to using Cody in IDE?

**Comment by dominiccooney** [comment]
> Going from "Email for diffs" to "Use Cody in IDE" feels like a stretch.
