### ISSUE TITLE
[bug] `Copy` problem on Windows

### ISSUE THREAD

**Issue by BachiMjavanadze** [sourcegraph/cody#1184]
Can't copy selected text with mouse click:

![image](https://github.com/sourcegraph/cody/assets/38082501/fbc3edc6-727a-4d11-ac25-d6f7b291f4fa)

The same problem when I try to copy from chat:

![image](https://github.com/sourcegraph/cody/assets/38082501/9b0f6bb2-dad2-4d92-b442-a11bf40074a5)

Shortcut works but I'm on `Windows`, do not want `Ctrl+Insert`, give me `Ctrl+C`.

Please fix it

P.S. does not work `Cut` and `Paste` on context menu (as you see on the image) but I don't understand who wants the feature?! What is the reason of these menu items?! my questions relate to the first image

**Comment by jdorfman** [comment]
Thanks for reporting @BachiMjavanadze 

I alerted the team.
