### ISSUE TITLE
JetBrains: Telemetry: Pass params to autocomplete event logging

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/cody#123]
Our class in `telemetry/Event.java` has `eventProperties` and `publicArgument`, and currently, they are both always empty. We ought to use them to provide more info on what's happening. The VS Code code gives us some pointers on how to do it.

We didn't do this at the time of launch because we ran out of time, and didn't prioritize this because Cody Agent might just give us this for free.

**Comment by vdavid** [comment]
We want to know:
- How many completions do we have that we filter out
- How long the inline hint is visible
- Track rejections unless the inline hint wasn't visible for a long enough time

There is a single canonical event (could be called `AutocompleteEvent`) we want to track with three attributes:
1. llmLatencyMs: number – from last keystroke until we display the inline hint
2. hintVisibleDurationMs: number – from the time we displayed the inline hint until it's accepted or rejected
3. didAccept: boolean – accepted or rejected.

Tasks:
- [ ] See the shape of the events that VS Code sends
    - How: the easiest way might be to start the VS Code extension in dev mode and see the events it logs.
- [ ] Copy that structure for now
    - But internally, we can model the logging the way we described above
    - Ideally, we want to 100% match the structure, but if we roughly achieve it, it might be enough.

Goodie: In VS Code, we're using a bunch of hacks to achieve this logging because many things happen under the hood. We have more control, so it'll be much easier.

**Comment by vdavid** [comment]
VS Code event analysis result:

In case of an accepted completion, these four items are logged:

- `CodyVSCodeExtension:completion:started` {"multiline":true,"providerIdentifier":"anthropic","languageId":"typescript","type":"inline","multilineMode":"block"}
- `CodyVSCodeExtension:completion:networkRequestStarted` {"multiline":true,"providerIdentifier":"anthropic","languageId":"typescript","type":"inline","multilineMode":"block","contextSummary":{"duration":6.322709083557129}}
- `CodyVSCodeExtension:completion:suggested` {"multiline":true,"providerIdentifier":"anthropic","languageId":"typescript","type":"inline","multilineMode":"block","latency":1754.8648748397827,"displayDuration":5912.106917142868,"read":true,"otherCompletionProviderEnabled":false}
- `CodyVSCodeExtension:completion:accepted` {"multiline":true,"providerIdentifier":"anthropic","languageId":"typescript","type":"inline","multilineMode":"block","lines":2,"otherCompletionProviderEnabled":false}

In case of a rejected completion, these three items are logged:

- `CodyVSCodeExtension:completion:started` {"multiline":false,"providerIdentifier":"anthropic","languageId":"typescript","type":"inline","multilineMode":null}
- `CodyVSCodeExtension:completion:networkRequestStarted` {"multiline":false,"providerIdentifier":"anthropic","languageId":"typescript","type":"inline","multilineMode":null,"contextSummary":{"duration":5.251167058944702}}
- `CodyVSCodeExtension:completion:suggested` {"multiline":false,"providerIdentifier":"anthropic","languageId":"typescript","type":"inline","multilineMode":null,"latency":899.7096660137177,"displayDuration":6421.2282910346985,"read":true,"otherCompletionProviderEnabled":false}

Evaluation:
- I don't think networkRequestStarted is needed.
- We already log all three other events in JetBrains. But not the arguments.

We lack these arguments:

```typescript
{
"multiline": boolean,
"providerIdentifier": string
"languageId": string,
"type": string,
"multilineMode": string,
"latency": number, // only for completion:suggested
"displayDuration": number, // only for completion:suggested
"read": boolean, // only for completion:suggested
"otherCompletionProviderEnabled": boolean, // only for completion:suggested
}
```

Of these, I think we only need "latency" and "displayDuration", and only for completion:suggested.

**Comment by philipp-spiess** [comment]
> I don't think networkRequestStarted is needed.

Yeah I removed this already from VS Code too :)
