### ISSUE TITLE
Autocomplete: Fix 26 year rate limit bug

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#1240]
The warning message when you exceed the rate limit is wrong

**Comment by abeatrix** [comment]
pic for ref: 
<img width="1404" alt="Screenshot 2023-09-27 at 10 22 54 AM" src="https://github.com/sourcegraph/cody/assets/68532117/2da86dc3-f22b-4419-b60d-3477326f77da">

**Comment by philipp-spiess** [comment]
![image](https://github.com/sourcegraph/cody/assets/458591/08adb9ba-3e06-4554-8c38-af765a4fa278)

🤔
