### ISSUE TITLE
Users who are logged in with email A on sourcegraph.com and then try to log in/signup with email B via VSCode aren't able to successfully log in

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1266]
If a user is logged in with X email on [sourcegraph.com](http://sourcegraph.com/) but tries to login with Y email via the VSCode extension, then we can:

- **Option 1**: create a new account with Y, log the user out of X on [sourcegraph.com](http://sourcegraph.com/) and log the user into Y on [sourcegraph.com](http://sourcegraph.com/) as new user and take email Y through the new user flow
- **Option 2**: Throw a message that says "The email you just selected doesn't match the email that's logged on in [sourcegraph.com](http://sourcegraph.com/). Do you wish to associate email Y with your sourcegraph account that's currently associated with email X?"
  - <CTA 1 = Yes associate them>. Associates the 2 emails under 1 login and redirects the user to the new user sign in flow, so we can associate whether or not email Y is a work or personal email address.
  - <CTA 2= Don't associate them, Retry with another login" Takes the user back to VSCode to try another login
- **Option 2.5**: Automatically associate the 2 emails under 1 account and log the user in, taking them through the new user sign in flow to associate whether or not email Y is a work or personal email address.
- **Option 3**: throw an error and say "The email you just selected doesn't match the email that's logged on in [sourcegraph.com](http://sourcegraph.com/). Either log out of [sourcegraph.com](http://sourcegraph.com/) or log into email X in VSCode"
- **Option 4**: remove the SSO options on the signup flow and take the user to [sourcegraph.com](http://sourcegraph.com/) (what we're doing for JetBrains)
  - I think this is why JetBrains isn't running into this same bug, because the JetBrains login flow directs the user directly to [sourcegraph.com](http://sourcegraph.com/), instead of taking them to an SSO provider like what we do in VSCode. so if:
    - the user is already logged in in [Sourcegraph.com](http://sourcegraph.com/), we'll sign in with that account.
    - if the user is not logged in sourcegraph, then we take them to https://sourcegraph.com/sign-in

Order of my preferences:
- option 1 - easiest user experience, doesn't require the user to remember what account they were signed in on on [sourcegraph.com](http://sourcegraph.com/)
- option 4 - it introduces 1 extra step (and onto a page that needs a bit of design polish but it'll work for now)
- option 2 - it gives the user an extra important step to know what's going on with their accounts, but it's an extra step
- option 3 - introduces an extra step, but confusing and requires too many extra steps.
- option 2.5 - smooth, but potentially too aggressive of a user experience, especially if it's a shared computer (low likelihood but associating 2 emails from 2 different people in 1 account is too confusing to risk happening a few times. the disassociation process may be easy but I haven't looked into it yet)

**Comment by chenkc805** [comment]
CC: @dominiccooney @vdavid @unknwon

**Comment by vdavid** [comment]
More context in [this Slack thread](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1695990336951169)

**Comment by vdavid** [comment]
Problem definition by @pjlast (edited for brevity):

> The same-email issue we are experiencing is a side-effect of VS Code linking directly to the sign-in page for each provider instead of going through the normal Sourcegraph flow. It's going straight to the sign-in page, but you actually have a valid Sourcegraph session active. If you log out of sourcegraph.com before you click the button in VS Code, then it works fine.

(Note: the new account isn't getting associated with the old account, at least.)

@pjlast think about the solution:

> I think we can maybe just not hard link like that 🥲  feels like it's an unnecessary coupling.
> I also think if it recognizes the session, it will still be confusing.

So, I guess the solution would be to remove the GitHub/GitLab/Google buttons from the VS Code UI, and instead, just link directly to `https://sourcegraph.com/user/settings/tokens/new/callback` like we do in the JetBrains plugin [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/SourcegraphAuthService.kt?L36). Did I understand correctly the solution you suggested, @pjlast?

**Comment by pjlast** [comment]
@vdavid that's correct yes, but just minor correction: The new account is being associated with the old account.

Since there's an active Sourcegraph session in the browser, the new sign-in is being associated with that active session, which is the old account. But, because we don't expect this to happen, there are now multiple Google accounts associated with that Sourcegraph account, but the new one isn't visible because only the first account is displayed in the Admin Security page

**Comment by pjlast** [comment]
I'm not sure how possible Option 1 is, because then we have no way of distinguishing between whether a user is trying to sign in with a new account, or if they are trying to link it to their existing account (like clicking on the Connect button in the Account Security page for example)

**Comment by chenkc805** [comment]
@toolmantim came up with an elegant way of doing Option 3 that I can get behind. Adds very little friction and I think is a straightforward user experience. 

Essentially it's this: 
![Image](https://github.com/sourcegraph/cody/assets/3654603/8d5907b6-264a-4021-bee5-6cb44102cf89)

Here's the Figma to the interstitial link: https://www.figma.com/file/INGthyKM1cYki5H02JPDpW/VS-Code-Beta-2-%3C%3E-App-Onboarding?type=design&node-id=228-2365&mode=design&t=SSiAx0TJjYuBLOew-4

What do folks think on the eng side? I'm hoping this is a straightforward eng implementation since we're logging one user out and logged them in with another.

**Comment by pjlast** [comment]
@chenkc805 I think something like this could work. I think the important bits here are:

1. Make it very visible as to what Sourcegraph account is active and being used
2. Make it easy to switch to a different account right from there

This way a user can spot if something looks off, and correct it before continuing. And the ideal case where it is a completely new user still proceeds as before.
