### ISSUE TITLE
JetBrains: Make the plugin more convenient to debug

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/cody#128]
The first step here is to think about what low-hanging fruits we have to make plugin development more convenient for ourselves

Ideas:
- Add logging
- Enable tracing messages to the LLM (will be solved by the Agent)
- Improve docs

One of the goals is to easily compare our communication with the LLM to what other clients are doing.

**Comment by olafurpg** [comment]
Closing since we can improve debugging on demand. The situation is somewhat improved with the agent through the `build/sourcegraph/cody-agent-trace.json` file.
