### ISSUE TITLE
VScode/Cody App does not show progress generating embeddings

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#1288]
This came up in user testing [here](https://app.usertesting.com/v/b039bcfa-fd9a-4bc5-9f4f-b7737aeb35fe?encrypted_video_handle=10dc929e-ed71-4363-a6a4-4c540025c50c&note_id=annotation-14487503&start=759&shared_via=link&share_id=hhFg5mZeqk)

@thenamankumar any idea why App isn't showing a progress bar here? Maybe they have an old version of App?

**Comment by alessandro-newzoo** [comment]
FWIW I'm also not seeing any progress bar on Cody for macOS (Silicon).

```Version 2023.9.22+1398.91e4161d32 (20230922.170246)```

I've been stuck here for about half an hour and have no idea how long I need to keep waiting, or if it's even working at all:

<img width="1060" alt="image" src="https://github.com/sourcegraph/cody/assets/47320294/8e84ef7e-c340-440f-9525-506faa059143">
