### ISSUE TITLE
the appimage will not run on nixos - reporting libthai.so.0 is missing

### ISSUE THREAD

**Issue by stuzenz** [sourcegraph/cody#1305]
**Feature request description**

Love using Cody. I think your team has done an amazing job. I found when the desktop app was released it would no longer work for me with vscode. I am hoping that you could include libthai.so.0 in the appimage to allow it to run on Linux systems that do not have the library available (or available in the Linux FHS location).

**Is your feature request related to a problem? If so, please describe.**

The appimage will not run on some Linux distributions. In my case it will not run on NixOS.
I think the issue is that the appimage is missing the libthai.so.0 library.

On that note, the libthai.so.0 library is on the following [exclusion list](https://github.com/AppImageCommunity/pkg2appimage/blob/master/excludelist). Although it probably should not be on the exclusion list because it does cause issues for other distributions as well.

The below provides some information that makes me think that the missing library might be the issue.
```bash
stuart@T14:~/Downloads/ > ./cody_2023.9.22+1398.91e4161d32_amd64.AppImage --appimage-extract            
cody_2023.9.22+1398.91e4161d32_amd64.AppImage installed in /home/stuart/.cache/appimage-run/83119ead237227c8c3ddff6d10fcd6859832539ce5abca1b9d444757c1abe2b4
cody: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

```

**Describe alternatives you've considered.**

Requesting the appimage has the library included or the ability to package Cody for NixOS.

**Additional context**
```bash
stuart@T14:~/Downloads/ > gnome-shell --version
GNOME Shell 44.4

stuart@T14:~/Downloads/ > uname -r
6.1.54

NixOS unstable channel with flakes
```

Many thanks if you can do something to help. Others are also hoping Cody can be packaged to work with NixOS either as a working appimage or as a natively built NixOS pkg - there are some notes on this at the below location.

https://github.com/NixOS/nixpkgs/issues/240568

I am available to test any builds if it helps.

**Comment by jdorfman** [comment]
Hey @stuzenz thanks so much for the details. Cody is still in beta and we're working on an app-less indexing solution that's high on our priority list.

We <3 the nixOS community. Would love to send you some swag. Email community@sourcegraph.com if interested or just want to say hi.

**Comment by beyang** [comment]
Thanks for the bug report! FYI, we'll be sunsetting the desktop app soon. Currently, it's main function is to handle embeddings indexes for private repositories, but we'll be rolling that into the extension itself.

**Comment by stuzenz** [comment]
@beyang  @jdorfman 
Hi Justin and Beyang, thank you for the great response. 

Sunsetting the app sounds like a good way forward if you can do the same work from within the extension. Thanks!

Beyang, I have been following your posts for a long time. I really appreciate the work sourcegraph does - I have been a fan of Sourcegraph's approach since the days before LLMs brought super-powers to sourcegraph.

I would love some swag and will send an email through to the address above.

Thanks again. 
Stuart
