### ISSUE TITLE
[vscode] Move panel to the bottom

### ISSUE THREAD

**Issue by kjvdven** [sourcegraph/cody#1323]
In VS Code I would like to place the cody pannel at the bottom instead of the sidebar.
The sidebar feels cramped for cody, I have more space in the bottom drawer.

**Comment by philipp-spiess** [comment]
Hey there! I believe this is already possible today by simply dragging the window on the title bar:

https://github.com/sourcegraph/cody/assets/458591/ca90f254-2dae-41a2-836a-44c3c42ad8f5

Does that work for you or did you have something more specific in mind? 😎

**Comment by kjvdven** [comment]
Thanks, learned something new about VS Code 2day :).

**Comment by jdorfman** [comment]
Thanks @kjvdven and @philipp-spiess !
