### ISSUE TITLE
Bug: Cody Chat Generates Response At The Top Of Chat Window

### ISSUE THREAD

**Issue by alexAtSourcegraph** [sourcegraph/cody#1338]
- **Cody Version:** 0.14.0
![image](https://github.com/sourcegraph/cody/assets/86978415/defa882b-e016-48c4-9305-e91882308728)
![image](https://github.com/sourcegraph/cody/assets/86978415/2b76cfc5-3377-4b75-92ac-1017d84b5859)

#### Steps to reproduce:

1. Install Cody VSCode Client on macOS Sonoma
2. Begin a Cody chat session.

#### Expected behavior:
Cody will generate the message in the chat window and the window focus stays at the bottom of the chat window while generating the response.

#### Actual behavior:
Cody generates the message in the chat window and the window focus moves to the top of the chat window while generating the response.

Cody was previously working as intended right before macOS Sonoma update.

**Comment by arafatkatze** [comment]
See https://github.com/sourcegraph/cody/issues/1341 and https://github.com/sourcegraph/cody/pull/1343
