### ISSUE TITLE
VScode: Chat scrolls to top for each new message

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#1341]
Every time I input a new chat message, the scoll jumps to the top of the chat history.

Cody: 0.14.0
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by arafatkatze** [comment]
Yeah I faced this too all the time
