### ISSUE TITLE
Opt+/ shortcut does not focus chat input if a notification is shown

### ISSUE THREAD

**Issue by sqs** [sourcegraph/cody#1344]
Repro:

After a recent update (or anything else that _would_ cause the sidebar to show a notification at the top about the new version), with the sidebar closed, press <kbd>Opt+/</kbd> (the hotkey to open the sidebar).

* Expected: the sidebar opens with the chat input focused, so I can start typing my question to Cody
* Actual: the sidebar opens, but the chat input is NOT focused, so I can't start typing my question to Cody. I need to use my mouse to close the notification. This adds friction.

**Comment by ryuusama09** [comment]
Hello , I am a new comer  and would like to give this a try  !
