### ISSUE TITLE
In black themes, hard to distinguish between messages vs. responses in chat sidebar 

### ISSUE THREAD

**Issue by sqs** [sourcegraph/cody#1345]
It's hard to tell which are my messages to Cody and which are Cody's responses. Really the only way to tell is that my messages have a gray border on the far left. It turns out that there IS a slight difference in background color between the two, but it's so hard to see.

<img width="585" alt="image" src="https://github.com/sourcegraph/cody/assets/1976/eb75f3a3-0e31-4bb5-804f-5affd8ed0aa0">

It seems the root cause is that my theme's background is black. Even though we apply this style to slightly brighten the bg color of my messages, it doesn't do much on a black bg:

<img width="422" alt="image" src="https://github.com/sourcegraph/cody/assets/1976/80ca88af-185b-476d-84ac-7422844aa64d">

Repro: use any theme with a black background (such as `Dark High Contrast`, which is built in).

---

Note: Here's a screenshot on the default VS Code dark theme, where the contrast is much more noticeable, for the record.

<img width="414" alt="image" src="https://github.com/sourcegraph/cody/assets/1976/a71f1668-dcb6-45fa-b316-5fea6c0999cb">

**Comment by The5cheduler** [comment]
Hey, I would love to take this one!
As I am new to the project!
Can anyone brief me on what files might be responsible for this issue?

**Comment by The5cheduler** [comment]
assign
