### ISSUE TITLE
Autocomplete: Context management

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#1366]
Insert a mechanism to combine multiple context sources and find a way to rank completions. Make sure to dedupe ranges etc.

**Comment by ramsey-coding** [comment]
@philipp-spiess what do you mean by multiple context sources? Do you have any documentation about this?

**Comment by philipp-spiess** [comment]
@ramsey-coding We want to have multiple retrieval methods that we can use at the same time and need a way to rank the results relative to each other :) There's not more documentation at this point, this is pretty early right now.

**Comment by philipp-spiess** [comment]
@ramsey-coding Sure take a look at this function which is currently the main entry point for autocomplete retrieval https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/completions/context/context.ts?L36

**Comment by kalanchan** [comment]
@philipp-spiess does this work need to be collaborated with @rishabhmehrotra?

**Comment by philipp-spiess** [comment]
Going to close this out for some smaller, more specific issues
