### ISSUE TITLE
Autocomplete: CAR standard definition + LoC committed

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#1369]

**Comment by chenkc805** [comment]
Hello, I'm unclear of the ask here. Can you clarify what we're trying to achieve with this issue?

CC: @kelsey-brown

**Comment by philipp-spiess** [comment]
I think this is done now with our updated CAR and WCAR metrics

**Comment by chenkc805** [comment]
Completed here: https://docs.google.com/document/d/1nSwQbOF7Xmd_SBV9PkfALzL1_ZeNN2QOaSEhAT1qmuE/edit
