### ISSUE TITLE
/edit results are not displayed in VS Code

### ISSUE THREAD

**Issue by contentfree** [sourcegraph/cody#1378]
After applying /edit to a selection, Cody does its work and then merely displays a line that says "Apply Edits | Show Diff | Discard": 
<img width="187" alt="image" src="https://github.com/sourcegraph/cody/assets/10958/d5be4e3a-f35a-49e0-877f-3b4c75aed0e9">

What's _not_ shown are the actually edits to be applied. One must click "Show Diff" to see them, verify them, close the diff and then click "Apply Edits".

Ideally, the edits to be applied would be displayed somehow (probably similar to how autocomplete is displayed).

**Comment by jdorfman** [comment]
Thanks @contentfree we will look into it!

**Comment by umpox** [comment]
We now apply the edits automatically, which gives a cleaner flow. You can still diff, but now you can also undo + retry now too.

We'll be working to improve the decorations that are displayed once an edit has been applied
