### ISSUE TITLE
[suggestion] context understanding improvement

### ISSUE THREAD

**Issue by BachiMjavanadze** [sourcegraph/cody#1405]
I don’t understand how it works, it seems to read scripts, but it says it can’t read without permission. But I give permission...

![image](https://github.com/sourcegraph/cody/assets/38082501/fe6002d2-8f55-46f1-aa93-8a92e5f7ed43)

Desired behavior: If I give to `Cody` the right to read all scripts in the project, it should do this and should not answer so:

![image](https://github.com/sourcegraph/cody/assets/38082501/7b1c6fb3-81b2-4ede-a696-3ea35aed58a1)

the desired answer in this situation:

![image](https://github.com/sourcegraph/cody/assets/38082501/60251d03-2cc3-45f7-bc8c-d1e26dbef302)

**Comment by umpox** [comment]
Cody's context fetching is a little too "magic" right now, we'll be working on improving this and making adding context much more explicit. This should make things clearer. Tracking this in this issue: https://github.com/sourcegraph/cody/issues/1377

Will close this in favour of the other issue.

Thank you for raising, @BachiMjavanadze!
