### ISSUE TITLE
App-less: Local Indexes without App

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#1443]
In #632 we removed App from the onboarding flow and found it improved the product. Now we want to remove app entirely

Related links:
- [Planning spreadsheet.](https://docs.google.com/spreadsheets/d/1-Nd1FSEURFBgLtTSVMt3i3OypPaR4FSN4WgCyJoSrBI/edit#gid=0)

**Comment by dominiccooney** [comment]
The only thing remaining here is to toast users to remove App, the language is in #1966.

**Comment by beyang** [comment]
Can close?

**Comment by dominiccooney** [comment]
Let's close this because technically it is done: You can have local embeddings indexes without App. I will keep #1966 around for the toast to remove app.
