### ISSUE TITLE
JetBrains: Completions: Avoid block closing completions when they are wrong

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/cody#146]
- Check out sourcegraph/sourcegraph#52615 for more explanation and the solution we used in VS Code

We'll support these IDEs:
- IntelliJ IDEA Ultimate
- IntelliJ IDEA Community Edition
- PhpStorm
- WebStorm
- PyCharm
- PyCharm Community Edition
- Rider
- RubyMine
- AppCode
- CLion
- GoLand

So it'd be awesome if we could make this work for
- Java
- Scala
- Kotlin
- PHP
- JS
- TS
- Python
- C#
- Ruby, 
- Objective-C
- Swift
- C
- C++
- Go
- XML
- HTML
- CSS

but that's probably too broad for the first time around, so if we just support whatever our VS Code extension supports, that should be fine.

**Comment by olafurpg** [comment]
Closing this as wontfix now that we have headless cody
