### ISSUE TITLE
Copy/Paste does not work inside of Cody

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/cody#1485]
### Discussed in https://github.com/sourcegraph/cody/discussions/1459

<div type='discussions-op-text'>

<sup>Originally posted by **Akinevz** October 23, 2023</sup>
My current environment is: 
- VSCode
- Neovim Extension
- Jupyter Workbook (Python)

When I go to select some output in the Cody window (anchored to the right), and hit Ctrl-C, it sends the input to the Workbook cell, rather than the Cody output, and Pasting results in noise rather than selecting the code. Below are the before/after screenshots:

![image](https://github.com/sourcegraph/cody/assets/1402632/f661fcfd-4b37-4129-9648-689a43d544c0)

After Ctrl-V

![image](https://github.com/sourcegraph/cody/assets/1402632/5dc68bd2-21fb-461f-943e-07d96b4be4be)
</div>

### Confirmed:
![BrowserPreview_tmp](https://github.com/sourcegraph/cody/assets/398230/1819aded-5173-4264-9487-a932cb911bf2)

Download `.ipynb`: https://github.com/donnemartin/data-science-ipython-notebooks/blob/master/pandas/pandas.ipynb

**Comment by abeatrix** [comment]
@jdorfman this looks like an issue from Notebook and not with Cody specifically so the user might want to open an issue at the vs code repo. 

I can reproduce the same issue with other extensions, like GitLens in this example:

https://github.com/sourcegraph/cody/assets/68532117/0660e316-78d5-4c5f-81c7-0e7a507dd8a4

The Insert Code button under the code block works for me as a workaround tho:
<img width="549" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/ea4070a1-1b3a-4cd1-9ead-da9ef9a60438">

**Comment by Akinevz** [comment]
Thank you for the update, I will try to chase with with Jupyter extension developers!

**Comment by jdorfman** [comment]
Thanks @abeatrix!

@Akinevz keep us posted :)
