### ISSUE TITLE
User should be able to evaluate the Enterprise plan and reach out to sales to inquire more about this plan

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1498]
- User can click a link that goes to <FORM LINK> that takes the user to upgrade to Enterprise tier
- When the user navigates to the form, the form pre-fills everything as much as possible based on information we already have.
- When user submits form, we log what tier the user is currently on as a hidden field so that our GTM teams have context

**Comment by thenamankumar** [comment]
Designs for this? Do we need to show a form? Do we use any 3rd part tool to create a form? Do the engineering team need to handle this or marketing can?

**Comment by chenkc805** [comment]
Marketing can handle this, but we need to provide a link over to a URL. I'll sync with Marketing to create the page for this.

**Comment by chenkc805** [comment]
CC: @Shannonking456 for visibility

**Comment by chiptests** [comment]
Hi @chenkc805 @thenamankumar , Any reason why we wouldn't want to use the pre-existing form? - https://about.sourcegraph.com/get-started?t=enterprise

This is definitely a work in progress but we've been working on an Enterprise landing page to point paid enterprise traffic - https://2762526.hubspotpreview-na1.com/_hcms/preview/template/multi?hs_preview_key=Jvpd_FflEpgDqT5C9w74Kw&is_buffered_template_layout=true&portalId=2762526&tc_deviceCategory=undefined&template_layout_id=142183637014&updated=1698344140732&

Is this in line with what you are thinking or are you looking for something more slimmed down?

**Comment by chenkc805** [comment]
We could use the pre-existing form, as long as it fulfills the criteria I outlined:
- When the user navigates to the form, the form pre-fills everything as much as possible based on information we already have.
- When user submits form, we log what tier the user is currently on as a hidden field so that our GTM teams have context

If so, then the pre-existing form works. Otherwise, if we need another form then I'd need your help setting that up.

**Comment by chenkc805** [comment]
Let's use this URL: https://sourcegraph.com/contact/request-info

@chiptests lmk if you disagree

**Comment by chenkc805** [comment]
Hm this looks different from the other one we were discussing. I'll edit the top comment and close this one out, because the intended behavior is met here.
