### ISSUE TITLE
Community users should not be able to use Cody anymore (neither chats or autocompletes) when they hit their limit

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1500]
Limit is:

- 500 autocomplete suggestions
- 20 chat/command invocations

**Comment by thenamankumar** [comment]
@chenkc805 What is the timeframe for these limits? Are these daily limits or monthly?

**Comment by chenkc805** [comment]
Monthly

**Comment by vdavid** [comment]
This is done
