### ISSUE TITLE
Pro users should not have any autocomplete or chat limits

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1501]
- Create Pro & Free tier mapping for users
- Set tier-specific usage limits

**Comment by Maziar123** [comment]
i have same problem

**Comment by thenamankumar** [comment]
@chenkc805, what are the abuse protection safeguard limits for Pro users?

Do we still set an hourly rate limit?

120/hour chat limit & 300/hour autocomplete is my recommendation. 

We can also pull data around how the current free unlimited tier users utilise Cody. 

cc: @rafax

**Comment by chenkc805** [comment]
Pro and Community users should have the same abuse safeguards, which we currently have in place. 

For Pro users, we can start throttling usage at 1000 suggestions and 50 chats per month. After this point, one idea I had is we can add 0.5s delay to suggestions and 1s delay to chats to both usage to slow down both's usage. We can then adjust from there.

**Comment by chenkc805** [comment]
Update: for Pro users, up this to 2000 suggestion LLM requests and 100 chat LLM requests / day to prevent abuse

**Comment by chenkc805** [comment]
This is done

**Comment by chenkc805** [comment]
Final limit discussion here: https://sourcegraph.slack.com/archives/C05SZB829D0/p1702493986615889
