### ISSUE TITLE
add update changelog history to the extension and extesion page

### ISSUE THREAD

**Issue by fisforfaheem** [sourcegraph/cody#1512]
it will help people understand the issues fixed in preview version as well

**Comment by jdorfman** [comment]
Hey @fisforfaheem we have them:

* https://marketplace.visualstudio.com/items/sourcegraph.cody-ai/changelog
* https://github.com/sourcegraph/cody/releases

<img width="978" alt="Image 2023-10-26 at 2 24 54 PM png" src="https://github.com/sourcegraph/cody/assets/398230/8e4de80f-9361-4099-9b61-349b45c3b381">

**Comment by fisforfaheem** [comment]
but it needs to be updated visually and improved with dates and details.
Also update the dekstop app

**Comment by jdorfman** [comment]
@fisforfaheem you are right, it should be uniform with the other changelog. @abeatrix is this something we can start doing? If I can help in anyway LMK.

> Also update the dekstop app

We will no longer be updating or supporting the desktop app. We will eventually be bringing that functionality into the plugins.

**Comment by abeatrix** [comment]
@jdorfman i think he's referring to changelog for App and not just VS code. 

The vs code changelog includes link to PR for each change already, and we also have blog and release notes.

**Comment by fisforfaheem** [comment]
Okay got it.

Kindly focus on improving the chat and it should work better alongside
copilot and intellisence as well
