### ISSUE TITLE
VSCE: “Sign Out” needs a confirmation

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1520]
“Sign Out” needs a confirmation

@tooltim

> Yeah, that was me removing it before :upside_down_face: I think because it's a treeview item and not a button or menu, and we want people to click around and explore… it makes me a bit more nervous than usual. A standard VS Code confirmation dialog (rather than the quickpick) would be fine though!

**Comment by abeatrix** [comment]
@toolmantim @deepak2431 is interested in working on this issue. Instead of showing a confirmation dialog `Are you sure you want to sign out?`, should we show the `Switch Account` quick pick instead, and add a new `Sign Out` option at the top / bottom?


![image](https://github.com/sourcegraph/cody/assets/68532117/b0de2d9e-ad42-47df-a9bf-b7ff50f09acd)

**Comment by deepak2431** [comment]
@abeatrix @toolmantim Yeah, I can work on this issue. 

It would also be a good idea to do what @abeatrix suggested. A Sign Out at the bottom would open a dialogue with a final confirmation message before the final Sign Out.

Will wait for the final confirmation about the working flow of this.

**Comment by toolmantim** [comment]
Let me design/spec this out properly if we want it to include account switching.

@abeatrix can I ignore the current design and focus on the new UI? Or are there shared concerns?

**Comment by abeatrix** [comment]
Not a shared concern, i mentioned because I didn't see the Account switching option in the new design 😄

**Comment by deepak2431** [comment]
> Let me design/spec this out properly if we want it to include account switching.
> 
> @abeatrix can I ignore the current design and focus on the new UI? Or are there shared concerns?

That sound great, @toolmantim. Looking forward to it!

**Comment by deepak2431** [comment]
@toolmantim Just wanted to follow up on the updated design changes, Is it done?

**Comment by abeatrix** [comment]
@deepak2431 Hey thanks for following up! Unfortunately, Tim is out sick this week so we might not be able to get back to this until next week, but I can find other issues for you if you want to get started on something 😄

**Comment by deepak2431** [comment]
@abeatrix I see, Thanks a lot for the update! Yeah, I can take up other issues to work on it until Tim is back if there's any :)

**Comment by abeatrix** [comment]
Just created one! If you're interested feel free to assign it to yourself 😄  

https://github.com/sourcegraph/cody/issues/1692

**Comment by deepak2431** [comment]
Thanks, @abeatrix for creating it, Sure I can take that up. Can you please assign it to me as I don't have access to do?

**Comment by toolmantim** [comment]
Thank you for offering to take this issue @deepak2431. I ended up doing the design and code at the same time in #2233, but I really appreciate the offer.

**Comment by deepak2431** [comment]
@toolmantim No problem, just checked your PR, and it looks good :)
