### ISSUE TITLE
VSCE: New Chat - Enhance Context selector

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1524]
<img width="811" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/9705d045-7c7a-48dd-8946-3abfc9cf344f">

<img width="582" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/5fa4f9c1-2c27-4dd3-8236-edda730b35b8">

**Comment by dominiccooney** [comment]
Thanks for starting on this @abeatrix.

Burn-down list:

- [ ] [This design ("v4 enhanced context states")](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=209-43481&mode=design&t=o1Exs32m5DuBy9n7-0)
- [ ] Folder tree view w/ sources
- [ ] Graph, search, embeddings sources
- [ ] "Indexing" states
- [ ] Enable Embeddings
- [ ] Enterprise UX for missing embeddings "No repository matching ..."
- [ ] a11y: Keyboard needs work. Once it is open, you can't dismiss it; activating it checks and unchecks the context.
- [ ] Pixels: Popup needs rounded corners.
- [ ] Pixels: Add the "Learn More" link.
- [ ] Pixels: Box shadow is a bright focused color, should be a receding color.
- [ ] Pixels: Check box—widget needs a border and fill; check is a dim color
- [ ] Pixels: "Enhanced Context" heading, weight.
- [ ] Stretch: Add Repository

**Comment by abeatrix** [comment]
> Thanks for starting on this @abeatrix.
> 
> 
> 
> Burn-down list:
> 
> 
> 
> - [ ] [This design ("v4 enhanced context states")](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=209-43481&mode=design&t=o1Exs32m5DuBy9n7-0)
> 
> - [ ] Folder tree view w/ sources
> 
> - [ ] Graph, search, embeddings sources
> 
> - [ ] "Indexing" states
> 
> - [ ] Enable Embeddings
> 
> - [ ] Enterprise UX for missing embeddings "No repository matching ..."
> 
> - [ ] a11y: Keyboard needs work. Once it is open, you can't dismiss it; activating it checks and unchecks the context.
> 
> - [ ] Pixels: Popup needs rounded corners.
> 
> - [ ] Pixels: Add the "Learn More" link.
> 
> - [ ] Pixels: Box shadow is a bright focused color, should be a receding color.
> 
> - [ ] Pixels: Check box—widget needs a border and fill; check is a dim color
> 
> - [ ] Pixels: "Enhanced Context" heading, weight.
> 
> - [ ] Stretch: Add Repository

No problem! As mentioned, the one I added was for temporary use since we just wanted to start getting people to dogfood the chat quality and experience with the option to enable and disable context. Please feel free to discard the current one and recent with the one you worked on previously :) 

I will keep working on polishing the other parts chat ui following the design and start adding tests, but if there's anything I can help you with please let me know!

**Comment by dominiccooney** [comment]
WIP at https://github.com/sourcegraph/cody/pull/new/dpc/enhanced-context-ux
