### ISSUE TITLE
Edit code default keyboard shortcut takes precedence over terminal paste

### ISSUE THREAD

**Issue by jwlarocque** [sourcegraph/cody#1536]
This is a minor gripe, because the shortcut can easily be rebound by the user, but I'd like to suggest the default be changed from Ctrl+Shift+V, as this is the default shortcut for paste in many modern terminals (in my case, Bash in VS Code in Gnome on Fedora).  Alternatively perhaps it could be limited to not activate when the terminal is focused.

**Comment by vadi2** [comment]
This is still a problem for new Cody installations.

**Comment by fig** [comment]
This can be resoled by adding `editorFocus` to the _When Expression_ of Cody's keybinding.

**Comment by vadi2** [comment]
Still needs fixing afaik.

**Comment by umpox** [comment]
Hi all, sorry this issue was left open longer than it should have. This is now fixed, we no longer use this shortcut but instead Opt+K (or Alt+k)
