### ISSUE TITLE
Custom commands don't know when the prefix slash is missing

### ISSUE THREAD

**Issue by vadi2** [sourcegraph/cody#1538]
I defined a custom command using the UI wizard in VSCode, but the command was not showing up anywhere at all - which was confusing.

Eventually I worked out that I missed the / prefix. Would be nice if this was more intuitive!

**Comment by arafatkatze** [comment]
@vadi2 I used the UI to make the custom command and I could not replicate this behaviour. 

```
    "Talker": {
      "prompt": "Talk about this code",
      "context": {
        "codebase": false,
        "selection": true
      },
      "description": "Talk about this code"
    }
 
```

Works perfectly for me

**Comment by vadi2** [comment]
It works great for me now as well.
