### ISSUE TITLE
Newly-defined custom commands don't show in chat until reload

### ISSUE THREAD

**Issue by vadi2** [sourcegraph/cody#1540]
Newly-defined custom commands don't show up in this menu until you reload vscode:

<img width="507" alt="Screenshot 2023-10-28 at 09 44 15" src="https://github.com/sourcegraph/cody/assets/110988/bae02cd6-1972-484b-8948-1ee0ac8c9029">

**Comment by arafatkatze** [comment]
@vadi2 Reloading makes them show up in the command list but just typing the name alone lets me see them. So if I add a new command say `Talker` doing `/T` will show me `/Talker` in the list

**Comment by jdorfman** [comment]
@abeatrix is this  a known issue?

**Comment by jdorfman** [comment]
Thanks @arafatkatze for the insight!

and thanks @vadi2 for reporting, I was unaware of that even though I create custom commands. 🤦‍♂️

**Comment by abeatrix** [comment]
@vadi2 I can't reproduce the issue on my side, can you tell me more about your current setup, please? Which Cody version, VS Code version, and how did you create the new custom command?

**Comment by vadi2** [comment]
I'm not able to reproduce it either anymore. Sorry! Maybe it was an outdated version that I was running.
