### ISSUE TITLE
Pipeline Optimizations in Cody

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#1544]
Hey Folks, 
Inspired by this Issue → https://github.com/sourcegraph/cody/issues/1464(Improve fixup response speed) I tried out a few other AI coding editors. I've noticed that certain operations in Cody are slower, leading to a sub-optimal user experience."

## Current Pipeline for Fixup
<img width="1336" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/e5fdb5bd-d42c-42b2-b93c-00499501279f">

Here’s a few optimizations that I found for different cases. 

### 1. Intent Detection 
- Problem: It’s often skipped depending on the kind of fixup recipe(Skipped when you select code and do the Cmd+Shift+V shortcut) and isn’t helpful for results. It might be worthwhile to just keep `add` when no selection is made and `edit` for adding documentation/anything else. The edit case works perfectly fine for adding comments/docstrings etc. The added `document` intent seems frivolous and not worth the extra seconds on LLM calls. 
- Solution: It makes a lot of sense to get rid of intent detection LLM call altogether and just have these two scenarios:
A. No selection → Intent = “add”
B. Selection → Intent = “edit”
The time benefit of this change isn’t much but this can be a change worth doing. 

### 2. LLMReranker 
- Problem: This is simply not necessary for fixup recipes because for most of these the short context of the input selection itself is the most important thing, the additionally imported embeddings and their orderings make mostly no difference to the output because the functionality of a fixup is limited to the scope of selected code anyway. 

- Solution:  Getting Rid of LLM Reranker should be quite easy. Adding an extra field in ContextSearchOptions works easily to stop reranking only in fixup recipes while keeping the other cases untouched. It should be easy to turn on/off reranking based on the case
```
export interface ContextSearchOptions {
    numCodeResults: number
    numTextResults: number
    reranking: boolean
}
```

### 3. Prompt Sizing 
- Problem: The major latency in the Fixup Recipe comes from the massive prompt length. Once the prompt is sent to Claude it takes roughly 8-12 seconds for the prompt to start streaming and once the streaming starts it takes another 2-6 seconds for the streaming to finish and only once the whole thing is done can the user apply the fixup. You can try this from this script →  [Script Link](https://gist.github.com/arafatkatze/054cd8c58c4d1fcf1d2ee61c67f736dd)

- Solution:  It might make a lot of sense to change the [numCodeResults](https://github.com/arafatkatze/cody/blob/timeline-logs/lib/shared/src/chat/recipes/fixup.ts#L138) to a lower number like 1 or even 0 for the fixup recipes case because most of the added context from embeddings is frivolous and the speed increment from this is incredible(I saw it in my local tests). 

### Additional Observation:
- Problem: There’s also room for optimizations in other places like [LocalStorageProvider](https://github.com/arafatkatze/cody/blob/timeline-logs/vscode/src/services/LocalStorageProvider.ts#L77). The set function takes 2 seconds on my local machine because even a tiny update has the entire history of Cody but because of async nature of the code it doesn’t interfere with the user experience and is a background thing so its not worth it to optimize this part for now.
- Solution: If this does become a problem in the future then optimizing to only save the changes introduced and not the whole blob could be helpful.

### Optimized Pipeline(Includes all 3 optimizations from above)
<img width="1340" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/dd76b1de-c1f5-431d-bc99-099ba4c1ac42">

If you want to see how I made these timelines you can play with this branch in the debug mode([link](https://github.com/arafatkatze/cody/tree/timeline-logs))

I am happy to spin up PRs for all 3 of the above optimizations. Looking forward to your insights to enhance Cody's performance.

CC @beyang @umpox @toolmantim @abeatrix

**Comment by arafatkatze** [comment]
NOTE: A similar speedup can also help with the chat experience of the user by removing the Reranker. 

## Current Pipeline for Chat 
<img width="1374" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/91d5e8d3-3740-40bc-baf5-e65889f7dce9">

Problem: The simultaneous activation of two LLMRanker calls induces an added latency of 4-5 seconds.

Solution: My understanding for the causality of having LLM ranker comes from [this paper](https://arxiv.org/pdf/2307.03172.pdf). Quoting

*Model performance is highest when relevant information occurs at the beginning or end of its input context. As the position of relevant information is changed, we see a distinctive U-shaped curve in model performance—models are much
better at identifying and using relevant information that occurs at the very beginning and very end of contexts, and suffer degraded performance when forced to use information within the middle of its input context.*
<img width="304" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/340a8d8a-c00a-4e2f-abe6-2a30e4265a65">

While the LLMRanker's inclusion in Chat can be understood given its advantages, the dual LLMrerankers per chat request (with one presumably addressing related request options) considerably elongate response times. A staggering 12-16 second wait precedes any visual feedback, which might be streamlined by placing the LLMrerankers behind a feature flag.

### Future Pipeline for Chat
<img width="1354" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/20a63028-9240-4bac-9324-a6de51069176">


SideNote: Typically, GPT-4 boasts a response time of 1-2 seconds in the UI. Considering this, a user, especially one posing a straightforward query, might be disinclined to endure prolonged waits. As Cody's response time presently outstrips many AI editors, it could be beneficial to accelerate the visual feedback post-request. For less complex queries, users may find quick keyboard shortcuts, like pressing 'tab', more efficient than awaiting Cody's feedback.

**Comment by umpox** [comment]
@arafatkatze Thank you for the detailed writeup and investigation! I agree with a lot of these points and they align with my own investigation too

## Intent Detection

Yep, fully agree this isn't providing much value now and is often skipped. The approach you proposed is also what I agree with:
- No selection → Intent = “add”
- Selection → Intent = “edit”

Everything else we can skip. One aspect that the intent detection does also add, is to slightly change the prompt sent to the LLM. This is a minor change but it's something we should check for when making this change. [Here is the relevant code.](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/chat/recipes/fixup.ts?L38). 

@arafatkatze If you want to spin up a PR for this then please go ahead! 

## LLMReranker / Prompt sizing

Fully agree that we can skip the reranker and possibly reduce the prompt. I am going to experiment deeper with how much context we want to provide. One of the original plans for the intent detection was to be able to dynamically pull in different levels of content depending on the ask. I think we can significantly reduce the context for most cases, but I want to experiment to make sure we don't reduce quality for different scenarios here. At a high level, we could possibly apply the same determined intent to context fetching here too:

- No selection → Intent = “add” -> Context = attempt to fetch context from the users instructions.
- Selection → Intent = “edit” -> Context = only current file

I will work on this next so please hold off making any changes here, will tag you on the PR!


## Current Pipeline for Chat

@abeatrix please check out this really helpful investigation into some areas where we can improve chat latency!

@arafatkatze I believe @abeatrix is currently looking at making the context fetching less automatic for chat, which should help with these changes. I think it's best to wait for @abeatrix's changes to land before making any further changes here!

**Comment by arafatkatze** [comment]
> Intent Detection

I made the change you suggested in #1548  

>LLMReranker / Prompt sizing
No selection → Intent = “add” -> Context = attempt to fetch context from the users instructions.
Selection → Intent = “edit” -> Context = only current file


Yeah your reasoning for prompt reduction makes perfect sense. I shall wait for your PR. 

> Current Pipeline for Chat

I shall wait for the upcoming PRs from you.

**Comment by abeatrix** [comment]
@arafatkatze I'm currently working on the UI for explicit context so probably wont get to LLMReranker anytime soon, and what you proposed for LLMReranker looks good to me 😃

**Comment by arafatkatze** [comment]
@abeatrix Thanks for the comment, explicit context would be a great speedup and @umpox is working on LLMReranker so I shall wait for PRs from you folks.

**Comment by arafatkatze** [comment]
Thoughts mentioned in this PR are already implemented so this is being closed.
