### ISSUE TITLE
Create user stories for February GA

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1547]

**Comment by vdavid** [comment]
Could you either label the issues with "user story" or prefix the titles with "Story: " so that it's easy to tell them apart from more granular issues and tracking issues?

**Comment by chenkc805** [comment]
Yup I'm going to use a Custom Field for that

**Comment by chenkc805** [comment]
Added a bunch of stories for February. I've covered our bases for PLG, but will need to do more for the PLG --> Enterprise transition. 

I will write those in once I have more clarity about those.

**Comment by vdavid** [comment]
This is a reminder for @chenkc805 to create issues for the Feb GA, then we'll close it
