### ISSUE TITLE
Ensure all clients respect site.isCodyEnabled

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/cody#156]
https://github.com/sourcegraph/sourcegraph/pull/52941 added a new GraphQL field that determines if Cody is enabled on the instance. Our clients should check this flag and render a nice message if not.

- [x] VSCode
- [x] JetBrains
- [ ] Neovim

**Comment by olafurpg** [comment]
This is now implemented by the JetBrains plugin ✔
