### ISSUE TITLE
"Applying" spinner stays there even though I've already applied the fix

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1564]
Steps to repro:

- Find a broken piece of code in VSCode (with red squigglies) 
- Highlight the code
- Right click
- Go to Cody > Edit code > type "Fix this"
- Wait for LLM response
- Get LLM response, click "Apply"
- See the apply made, but continue to see the spinning "Applying..." text 🐛 

![Image](https://github.com/sourcegraph/cody/assets/3654603/24edc6cc-8e2f-4e72-90a7-7c3fec7950b3)

**Comment by deepak2431** [comment]
@chenkc805 There is a discussion on the same issue here at #1552.

 @umpox mentioned that it should have been fixed, but I have to test it on my side :)

**Comment by umpox** [comment]
Closing this in favour of https://github.com/sourcegraph/cody/issues/1552 to avoid duplicate discussion
