### ISSUE TITLE
JetBrains: Build Q3 roadmap, incl. Agent integration

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/cody#157]

**Comment by vdavid** [comment]
Ideas:
- autocomplete in the Terminal
- ask #chat-jetbrains

**Comment by olafurpg** [comment]
The roadmap for the JetBrains plugin over the next ~6 weeks is going to focus on closing feature gaps with the VS Code extension, in particular with respect to autocomplete and onboarding.
