### ISSUE TITLE
Cody doesn't parse ssh url with org-id for cloning git repos 

### ISSUE THREAD

**Issue by rakeshjosh2003** [sourcegraph/cody#1572]
**Feedback**
Cody is not able to parse ssh urls when cody.codebase setting is not set explicitly. The remote url is located but not able to parse , here's the error message fom vscode

Cody could not extract repo name from clone URL [org-id@github.com](mailto:org-id@github.com):redacted/redacted.git: TypeError: Invalid URL
at new NodeError (node:internal/errors:387:5)
at URL.onParseError (node:internal/url:564:9)
at new URL (node:internal/url:640:5)
at convertGitCloneURLToCodebaseName

**Customer**
[Customer](https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001xdnmlAAA/view)

[Slack thread](https://sourcegraph.slack.com/archives/C02842Z6YAK/p1691109639814509)

This issue was fixed in PR 567 but [PR 692](https://github.com/sourcegraph/cody/pull/692) removed [these](https://github.com/sourcegraph/cody/pull/567/files/6bf5c166f8ceeec895d0d8b0e124b5e3bf420455#diff-e7c2dcd45c261d1485c51f2963195cc6639c724d4ea9f0e5926c0792836304dc) changes made in [PR 567](https://github.com/sourcegraph/cody/pull/567)

**Comment by deepak2431** [comment]
@rakeshjosh2003 I can make a PR to bring the changes back but would like to know if there was any reason it was removed in #692.

If not, just let me know! I can make a PR to make those changes and add a few more tests.

**Comment by rakeshjosh2003** [comment]
Hey @deepak2431, I am not sure why the changes were reverted, cody team asked me to lodge this bug.
