### ISSUE TITLE
PRD: Ability to upgrade your account from VS Code

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1576]
Description:

As a new user who's signed up to Cody, I want to understand my usage limits and be able to upgrade my account. And once I've upgraded, I want that to be reflected in Cody so I can have confidence the upgrade completed, and to be able to take advantage of any features or limits available on my new plan.

The main interactions that have limits and will trigger a CTA for upgrading:

- Autocomplete
- Commands
- Chat
- Embeddings

Objectives:

- Create an intuitive, reliable, and motivating upgrade flow from the free to pro Cody plans
- Setup measuring and monitoring for future iterations

Acceptance Criteria:

```[tasklist]
### Acceptance Criteria:
- [x] Signing up shows correct plan type in nav
- [x] Signing back in shows correct plan type in nav
- [x] All interactions that can trigger rate limits gracefully handle them and provide CTA to upgrade
- [x] UI updates to reflect plan changes without manual reload
- [x] New navigation layout has links to open web URLs
- [x] Copy is readable, clear and concise
```
Designs

- [Figma](https://www.figma.com/file/f7bzmpYrwalyYOQJcWLRTP/Untitled?type=design&node-id=0-3&mode=design)

```[tasklist]
### Design Tasks
- [x] New nav items
- [x] Updated autocomplete notice (update to #634)
- [x] New chat error notice notice
- [x] Update Embeddings in Enhanced Context popover with limits and CTA (update to #1377)
```

```[tasklist]
### Engineering Tasks
- [x] Add "Upgrade" menu item for free plan
- [x] Add "Usage" menu item
- [x] Update autocomplete rate limit notice quickpick
- [ ] https://github.com/sourcegraph/cody/issues/2123
- [x] Add Chat rate limit handling to show a nicer message for rate limits
- [x] Post-upgrade: Update account plan after account upgraded
- [x] Post-upgrade: Remove "Upgrade" sidebar item
```

### Follow-up Tasks:

```[tasklist]
### Follow-up
- [ ] https://github.com/sourcegraph/cody/issues/2517
- [ ] Track data for all this
```

**Comment by toolmantim** [comment]
The two new nav items to add at the top of the new "Settings & Support" treeview:

![image](https://github.com/sourcegraph/cody/assets/153/0ca2c7c3-6d1f-4e69-b6bd-6272027c2de6)

The first is only shown when you're on the free plan. The second will always be shown.

**Comment by kalanchan** [comment]
@Danny Tuppeny this is what we’ll need to do for the client work as part of Dec GA:

- No auth endpoint changes, we’ll be sticking with existing auth.
  - auth endpoint switch over to SAMS (Sourcegraph Account Management System) will happen in Feb CC
- use the existing SourcegraphAPIClient to check for account status, it should return a bool `codyProEnabled` that can be used for the upgrade and usage buttons, they should only be rendered after successful auth and connected to dotcom. 
  - use the existing auth token thats used for dotcom queries, for Dec GA the PLG account settings are retrieved using the sourcegraph graphql api
  - if that query returns empty, it might be because it’s behind a flag. let’s also do that on our side and hide both buttons using the same feature flag cody_pro_dec_ga

that should be enough for you to add in the setting page updates, the rest we’ll wait for designs!

**Comment by toolmantim** [comment]
I've updated the ticket with a Figma link containing designs for autocomplete, chat and embeddings rate limit upgrade experiences

**Comment by taylorsperry** [comment]
It looks like the designs above cover autocomplete and chat, but what about commands? What will a user see if they execute a command that opens a new chat window (I assume it'll be the same as what they see if they exceed the chat rate limit) vs if they execute a command that generates code within the file (e.g. `/doc` or `/edit, or VS Code Actions "Ask Cody to Fix," "Ask Cody to Edit," "Ask Cody to Generate")? 

Is this, plus the embeddings notification the work that still needs to be done here?

**Comment by taylorsperry** [comment]
It looks like the designs above cover autocomplete and chat, but what about commands? What will a user see if they execute a command that opens a new chat window (I assume it'll be the same as what they see if they exceed the chat rate limit) vs if they execute a command that generates code within the file (e.g. `/doc` or `/edit, or VS Code Actions "Ask Cody to Fix," "Ask Cody to Edit," "Ask Cody to Generate")? 

Is this, plus the embeddings notification the work that still needs to be done here?

**Comment by chenkc805** [comment]
@taylorsperry IMO if they hit a limit via commands, they should see the same UX as if they hit a limit in chat. 

So if they do /doc or /edit and they hit the limit, a chat should pop open and show the usage limit message. Will that be troublesome to implement?

**Comment by chenkc805** [comment]
What we're doing in https://github.com/sourcegraph/cody/issues/2123 looks fine to me for now, thanks for surfacing this! 

AFAIK we're not handling embeddings rate limiting UI until after Dec GA. It's a squeeze to get the new embeddings widget in VS Code working as it is for Dec GA, we didn't want to add additional scope that would make it more difficult. 

We'll still have embeddings rate limiting in the back end to cover us.
