### ISSUE TITLE
Embeddings get confused by translations

### ISSUE THREAD

**Issue by vadi2** [sourcegraph/cody#1584]
Cody's context / embeddings retrieval seems to consider translation files far too often. This is likely because translation files contain a lot of the relevant / matching words, however, they seldomly offer value to the task at hand 😅 

An example of a repository with translation files is here: https://github.com/Mudlet/Mudlet/tree/development/translations/translated

One can see that translation files get picked up very often in queries:

![image](https://github.com/sourcegraph/cody/assets/110988/ea3b1641-bb2e-41cb-ad5a-6ce890562f16)
![image](https://github.com/sourcegraph/cody/assets/110988/646b5aa4-ff9f-43d8-a958-23d72acfda01)

**Comment by jdorfman** [comment]
@vadi2 can you try again with v0.16?

**Comment by vadi2** [comment]
Still the same:

![image](https://github.com/sourcegraph/cody/assets/110988/465e63e8-ebd2-45b7-a32b-9b1f19d813d1)

**Comment by vadi2** [comment]
This is also an issue for dictionary files - they contain a lot of tokens that all get indexed: 

https://github.com/Mudlet/Mudlet/blob/development/src/de_AT_frami.dic
https://github.com/Mudlet/Mudlet/blob/development/src/de_CH_frami.dic
https://github.com/Mudlet/Mudlet/blob/development/src/de_DE_frami.dic

Having some sort of a .gitignore for embeddings would be great here.

**Comment by jdorfman** [comment]
@dominiccooney is this something that you've seen happen?

**Comment by vadi2** [comment]
https://sourcegraph.com/github.com/sourcegraph/cody@bb8feec56821d49e0fc95378521a7e09ea61d4e0/-/blob/vscode/doc/codyignore.md can be used to help deal with this.
