### ISSUE TITLE
[Annual Plans] Notify Cody Pro annual subscribers via email shortly before renewal date

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1594]
As a billing owner on an annual plan, when I am 7 and 3 days away from my renewal date, I should get an email notifying me that my Cody Pro renewal is coming up.

Notes:

- Do not implement this for monthly billed users. This is spammy and other monthly software businesses don't do this (eg. Spotify, Netflix)

**Comment by chrsmith** [comment]
We won't have annual plans for the February launch. Changing deadline.

**Comment by rrhyne** [comment]
Should this also appear in the UI?

**Comment by chrsmith** [comment]
@rrhyne I'd presume not? It would be kinda weird to see a butter bar or something like "yo dawg, we'll charge your credit card in T-minus 6 days"? (And instead an email might strike the right balance between "notification" and not being "in your face"? (But I'm happy to defer to you or Kevin and what you think on this.)
