### ISSUE TITLE
As a user, I can swipe a credit card to begin paying for Cody Pro. When I swipe and my transaction is successful, me and everyone on my team should immediately get Cody Pro access

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1599]
Requirements:

- Each member on the team should get an email notifying them they have Cody Pro access
- Each member on the team should get some in-product notification that they have Cody Pro access 
- If the credit card is declined, do not upgrade them to Cody Pro

**Comment by chrsmith** [comment]
This has been fixed.

We have unit tests for our interactions with the Stripe API directly, and I just verified this locally when using an invalid card on the Stripe Checkout UI.

(See https://stripe.com/docs/testing, use card number `4000000000000002`.)


![Image](https://github.com/sourcegraph/cody/assets/4029847/4386c0a6-f5d2-4d95-b97e-7e94c86b2588)
