### ISSUE TITLE
Cody VSCode extension response quality

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#1613]
I am experiencing this frequently these days while using either the codebase context/keyword context with Cody.  Whenever I ask any direct question while working with any codebase, it says this:

This example is in the case of the keyword context.
![iScreen Shoter - Code - 231102163025](https://github.com/sourcegraph/cody/assets/44617923/1bd43095-c5f3-45e5-845d-55a2ec024f0c)

This is for the case of the codebase context with the Cody codebase. The interesting thing I saw here is that when I asked the question using the prompt in the extension, I did not get any response. While using the same prompt, I got a response in the Cody web.
![iScreen Shoter - Code - 231031091833](https://github.com/sourcegraph/cody/assets/44617923/df5e82cc-8054-4c4e-a5b2-26eec290dfcf)

Looking at the behaviour, I can only think that the issue is, for now, the Prompt Quality, but also I guess we need to cross-check once if there's any bug when it reads the current file context etc while working with any codebase.

CC: @abeatrix @umpox @beyang

**Comment by abeatrix** [comment]
@deepak2431 Were you connected to the sourcegraph/cody codebase when you asked the question in VS Code, or was it using keyword context?

Cody was able to answer when using embeddings context:
![image](https://github.com/sourcegraph/cody/assets/68532117/edd09fdb-0ed0-4b89-8972-333186112bdb)

**Comment by deepak2431** [comment]
@abeatrix Yes, I was using the sourcegraph/cody codebase context for that question.

Hmm, for you the same prompt works. Not sure of this behaviour!

**Comment by abeatrix** [comment]
@deepak2431 i noticed there were only 5 files in yours vs 12 files used as context in mine 👀 Maybe there was a connection issue to the codebase that was causing the issue? If you are able to reproduce it, can you share the logs in the Output channel with me so i can investigate further please?

**Comment by deepak2431** [comment]
@abeatrix I tried again the same prompt, it is working now but it still says in the beginning that it doesn't have the context about the codebase.
![iScreen Shoter - Code - 231102233841](https://github.com/sourcegraph/cody/assets/44617923/5430c1aa-60b2-4328-8f0d-8a34d4fa86df)

So, might be the case that it won't be able to connect to the codebase at that time. Btw, just a thought if this is the case sometimes Cody fails to connect to the codebase then we should show a VSCode warning message for the user. WDYT?
