### ISSUE TITLE
Deleting chats shouldn't reset context selector.

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/cody#162]
This issue is part of this umbrella:
- sourcegraph/cody#166 

---

## Issue:
Deleting chats (either with the trash can icon on a single chat or with "Clear all chats" from the triple dot menu) resets the configured repositories.

https://github.com/sourcegraph/sourcegraph/assets/64257673/09dce206-56c0-4bfc-b1b4-0d15e04b8b98

## Solution:
Deleting chats shouldn't reset or reconfigure the context selector setup.

**Comment by thenamankumar** [comment]
Fixed
