### ISSUE TITLE
PRD: [VSC] Users can easily manage conversations with Cody

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1650]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

### Description:

As a user, I want to have conversations with Cody without interrupting my flow. When I ask Cody a chat question, I want to be able to follow up on Cody's response with a new question. I also want to be able to organize several conversations with Cody by creating new chats, viewing old chats (persisted across sessions), deleting chats, and renaming chats. I want to be able to do all of this easily and intuitively so that I can spend my time getting the answers I need instead of figuring out how chatting with Cody works. 

### Objectives:

Chatting with Cody is easy and intuitive. Users don't have to think about _how_ to chat with Cody because the core workflows (create, chat, view, delete, rename) are obvious. 

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria:
- [x] Chats support conversations consisting of multiple prompts and responses.
- [x] Users can create new chats, view old chats (persisted across sessions), and delete chats.
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/cody/pull/1486
- [ ] https://github.com/sourcegraph/cody/issues/1526
- [ ] https://github.com/sourcegraph/cody/pull/1698
- [ ] https://github.com/sourcegraph/cody/issues/1699
- [ ] https://github.com/sourcegraph/cody/pull/1550
- [ ] https://github.com/sourcegraph/cody/issues/1760
```

### After GA Tasks:

```[tasklist]
### After GA
- [ ] https://github.com/sourcegraph/cody/issues/1763
```

**Comment by kalanchan** [comment]
@taylorsperry 

This is largely completed with the new experimental chat panel, see https://github.com/sourcegraph/cody/pull/1486 

Only item that is missing is being able to _rename chats_, is that a core requirement?

**Comment by taylorsperry** [comment]
Nah, renaming can be P1

**Comment by taylorsperry** [comment]
Related [issue](https://github.com/sourcegraph/cody/issues/2009) to add shortcuts that make it easier to navigate between editing code and chatting with Cody.
