### ISSUE TITLE
PRD: [VSC] Chats are easy to read

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1653]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

### Description:

As a user, I want my conversations with Cody to be easy to read so that I can stay in flow. 

ChatGPT does this well: responses are readable and skimmable, with clear visual distinctions between prompt and response. Code blocks are also clearly distinguishable from the response's surrounding text. Responses are loaded in a "stream," which makes them feel lightning fast, but not jumpy; as a user, it feels less like you're "waiting" for ChatGPT to respond. 

As a user, I want it to be clear when Cody is "thinking" (ie, clear loading state) and be able to pause Cody from generating a response if I can tell Cody's off on the wrong track, or I realize I want to submit a different prompt. 

### Objectives:

Make Cody's responses to chat prompts easy to read so that users can quickly identify the parts of the response that are most relevant to their goal and stay in flow. When Cody's responses are difficult to read or a user has to wait for a response that they no longer want, it slows them down. 

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria:
- [x] Chat responses are readable and skimmable (like ChatGPT)
- [x] Chat responses feel fast, but not jumpy
- [x] Loading states are clear
- [x] Users can stop Cody from generating a response
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/cody/pull/1782
- [ ] https://github.com/sourcegraph/cody/pull/1690
```

### After GA Tasks:

```[tasklist]
### After GA
```

**Comment by kalanchan** [comment]
I think this is done, will groom this with Beyang after

![CleanShot 2023-11-07 at 14 04 17@2x](https://github.com/sourcegraph/cody/assets/51868853/911163bc-9588-49e4-8c83-8df27cca46c7)

**Comment by taylorsperry** [comment]
When testing in the latest release, chat felt very slick to me. @toolmantim I'd love your input on whether or not you think there's anything else we need to call this requirement ("Chats are easy to read") complete.

**Comment by taylorsperry** [comment]
A few clean-up items that I'd like to ship before GA: 

1. I don't need to see the "Hello! I'm Cody" preamble every time I open a new chat. I think it should only show for the first chat in a session, or maybe even just the first chat after a fresh install. 


![Image](https://github.com/sourcegraph/cody/assets/43555476/fff9090a-af2d-49c1-8205-358629daeab0)

2. I also don't need the preamble when I run a command and Cody answers in a chat window. 

![Image](https://github.com/sourcegraph/cody/assets/43555476/09f1cba9-99e9-4c95-90ce-7fdaaabd4cf5)

3. It looks like my chats have different labels if I run them from a Code Action vs the side panel or the right-click drop down. This feels messy. 

![Image](https://github.com/sourcegraph/cody/assets/43555476/6c972e4d-ab39-45b8-9d0a-cb88845c1eef)

4. There are lingering traces of slash commands in the chat panel,  command palette, and chat list. 

![Image](https://github.com/sourcegraph/cody/assets/43555476/3427e98c-a0c6-4787-9e8a-c6e53f2f2075)
![Image](https://github.com/sourcegraph/cody/assets/43555476/a4ccb9eb-4edd-4b8a-bed0-3f7799895d0e)

**Comment by abeatrix** [comment]
> There are lingering traces of slash commands in the chat panel, command palette, and chat list.

@taylorsperry [as discussed with Tim on slack](https://sourcegraph.slack.com/archives/C05AGQYD528/p1700173517887689), we will be keeping the slash commands at GA. Can revisit after that if needed

> I don't need to see the "Hello! I'm Cody" preamble every time I open a new chat.

IMO this type of "Introduction" is quite standard for a chat bot / assistant , but I saw that the starting window is also shown as empty in  @toolmantim 's design, does it mean all chat should start with an empty window with no preamble, for both new and existing users?

![image](https://github.com/sourcegraph/cody/assets/68532117/6bac770b-ca61-4fb8-9a2f-93efc29157ae)

**Comment by taylorsperry** [comment]
Created a separate issue regarding the welcome message https://github.com/sourcegraph/cody/issues/2461
