### ISSUE TITLE
PRD: [VSC] It's easy to copy code the Cody generates in chats

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1654]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

### Description:

As a user, I want to copy and paste code that Cody suggests in a chat. Instead of having to highlight the code and press command+c and command+v, I want to see options to copy the code with one click or insert the code at my cursor in my project file. 

### Objectives:

Make copy and pasting code easy with one-click options to copy code or insert code at cursor. It's important that these are easily discoverable for the user. 

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria:
- [x] Easily discoverable "copy code" option
- [x] Easily discoverable "insert at cursor" option
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### After GA Tasks:

```[tasklist]
### After GA
```

**Comment by kalanchan** [comment]
this is done, will groom with Beyang before closing

Copy code:
![CleanShot 2023-11-07 at 14 08 22@2x](https://github.com/sourcegraph/cody/assets/51868853/9756fec0-cc80-4432-9331-814974c48371)

Insert at cursor:
![CleanShot 2023-11-07 at 14 09 22@2x](https://github.com/sourcegraph/cody/assets/51868853/492bb853-fb1e-4e5a-b6f1-a15623f7040f)

**Comment by taylorsperry** [comment]
- ✅ Easily discoverable "copy code" option
- ✅ Easily discoverable "insert at cursor" option
- ✅ Bonus "Save code to new file" option

All worked as expected.
