### ISSUE TITLE
PRD: [VSC] Users can edit a previous prompt and get a new response from Cody

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1655]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

### Description:

As a user, I want to be able to edit and resubmit an existing prompt and get a new response. This is a feature that ChatGPT supports and is likely to be an expectation among Cody users as well. 

### Objectives:

P1: Allow Cody users to edit and resubmit an existing prompt and get a new response; P2: Support this without destroying the initial prompt and response, so that users can see all iterations of their initial prompt. 

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria:
- [ ] https://github.com/sourcegraph/cody/issues/1760
```
### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/cody/issues/1780
```
### After GA Tasks:

```[tasklist]
### After GA
- [ ] https://github.com/sourcegraph/cody/issues/1800
```

**Comment by kalanchan** [comment]
I don't think this is currently being worked on, will groom with Beyang for prioritization

**Comment by abeatrix** [comment]
We used to have this but not sure why it's not showing up, will investigate and should be available by GA

**Comment by taylorsperry** [comment]
@kalanchan Reopening and marking the status as "Follow up" since it sounds like @abeatrix was investigating. I'm on v0.16.1 and don't see this feature.

**Comment by kalanchan** [comment]
@taylorsperry switch to nightly, the edit icon should be available
![CleanShot 2023-11-28 at 18 11 48@2x](https://github.com/sourcegraph/cody/assets/51868853/92beb55d-afc8-4820-836f-f4f75f340a13)
