### ISSUE TITLE
PRD: [VSC] Chats expose the context Cody used to generate a response

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1656]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

### Description:

As a user, I want to know exactly what Cody used as context when providing a response to a chat prompt. While I may tag particular repos, files, or symbols to help guide Cody in the right direction, I know that Cody won't send _everything_ in a given repo or file to the LLM when generating a response. I want to know which chunks of code were sent to the LLM and be able to navigate to that part of my codebase. For example, if I ask Cody where auth is defined and give `my-repo` as context, Cody may send `my-repo/auth.js/15-34` to the LLM. I'd want to understand that `my-repo/auth.js/15-34` was used as context and be able to navigate to line 15 of that file. 

We know that confusion about context is a serious pain point among users, which is why we're introducing more visibility (and, in a separate PRD issue, more configurability). We also know that users go to Cody chat for onboarding, brainstorming, and help figuring out "where to start," which means that they might not always be very prescriptive in the context that they give Cody, even when we're able to support pretty granular configurability. 

### Objectives:

Give users clear visibility into what Cody used as context when generating a response and allow them to navigate to those parts of their codebase. 

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria:
- [x] The user can see exactly what Cody used a context when providing a response to a chat prompt
- [x] The user can navigate to the parts of the codebase that Cody used as context
```
### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/cody/issues/1525
```

### After GA Tasks:

```[tasklist]
### After GA
```

**Comment by abeatrix** [comment]
@taylorsperry I think the described behavior happens when the file you're trying to open doesn't exist in your current workspace, then we will try to open it in web. 
We can't open files outside of your current workspace due to security concerns, what does product and design think is the ideal behavior in this case?

**Comment by toolmantim** [comment]
@taylorsperry could you share a step-by-step of how to reproduce this situation? I want to understand how someone would get into this situation.

**Comment by taylorsperry** [comment]
@toolmantim Sorry, I should have done that in the first place! Here's a [loom](https://www.loom.com/share/5f146432d9df4958b79ded7baa737fbb) where I bumped into it again.

**Comment by kalanchan** [comment]
@taylorsperry from the loom, I think what might be happening is the files on your branch no longer matches `ChatPanelProvider.ts 117-141` that was used as context. I'm guessing there might be some discrepancy from the code snippet retrieved from embeddings vs what you have in your local editor. 

can you confirm if your branch is rebased with the latest changes from main?

**Comment by toolmantim** [comment]
Let's file this as a separate issue! We might want to rethink how we handle that situation… and in general how we handle drift/differences between embeddings and branches.

**Comment by taylorsperry** [comment]
Issue to handle drift started here (needs to be fleshed out) https://github.com/sourcegraph/cody/issues/2462
