### ISSUE TITLE
PRD: [VSC] Explain command

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1657]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit#heading=h.2wolyguph1ml)

### Description:

As a user, I want Cody to help me understand code. 

### Objectives:

Provide an easily discoverable, pre-packaged prompt that allows Cody to help users understand their code. 

### Acceptance Criteria:

```[tasklist]
### Acceptance Criteria
- [x] In a new chat window, Cody provides an explanation of selected code
- [x] The Explain command can be triggered from the sidebar
- [x] The Explain command can be triggered from the right-click menu
- [x] The Explain command can be triggered from the Code Actions
- [x] The Explain command can be triggered from a keyboard shortcut
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### After GA Tasks:

```[tasklist]
### After GA
```

**Comment by kalanchan** [comment]
this is done, will confirm with Beyang

![CleanShot 2023-11-07 at 14 23 46@2x](https://github.com/sourcegraph/cody/assets/51868853/4573948b-a31e-49ba-8820-4720ee357696)

**Comment by taylorsperry** [comment]
I don't see a keyboard shortcut for this command yet. I think we should have one and add it to the Keyboard Shortcuts list (screenshot below). @toolmantim what are your thoughts on having the keyboard shortcut right next to the command in the sidepanel? I saw this in one of your designs, but I don't know if you ultimately decided it was too noisy. 

![Image](https://github.com/sourcegraph/cody/assets/43555476/4a8ffdaa-d734-4878-bf67-24bffd7f3d09)

**Comment by kalanchan** [comment]
@taylorsperry does the `opt c` Cody Commands shortcut meet the keyboard shortcut requirement? I think the default behaviour is to activate commands using that shortcut

**Comment by taylorsperry** [comment]
I think it would be nicer if it had its own command (as it is, I still have to do `opt c` and then start typing "explain") but I'm open to arguments for why that's not a good idea.

**Comment by taylorsperry** [comment]
I believe we decided ~2 weeks ago that we don't need to add shortcuts to *every* command because users can always create their own, and it's bad UX to change key bindings after the fact if, for some reason, we decide to. Is that your recollection as well, @kalanchan? In that case, we can ignore the shortcut part of the acceptance criteria here.

**Comment by kalanchan** [comment]
yup I think we can call this done, keybindings can be left up to the user
