### ISSUE TITLE
PRD: [VSC] Edit command

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1658]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit#heading=h.2wolyguph1ml)

### Description:

As a user, I want Cody to edit my code according to my instructions. 

### Objectives:

Provide an easily discoverable, pre-packaged prompt that allows Cody to edit users' code according to their instructions.

### Acceptance Criteria:

```[tasklist]
### Acceptance Criteria
- [x] In the open project file, Cody automatically applies edits to the selected code, per the user’s instructions
- [x] Users can see a diff view of the edit
- [x] Users can undo an edit
- [x] The edit command can be triggered from the sidebar, right-click menu, or a keyboard shortcut
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/cody/issues/1407
- [ ] https://github.com/sourcegraph/cody/issues/1406
- [ ] https://github.com/sourcegraph/cody/issues/1464
- [ ] https://github.com/sourcegraph/cody/pull/1445
- [ ] https://github.com/sourcegraph/cody/pull/1411
- [ ] https://github.com/sourcegraph/cody/pull/1582
- [ ] https://github.com/sourcegraph/cody/pull/1722
- [ ] https://github.com/sourcegraph/cody/pull/1724
- [ ] https://github.com/sourcegraph/cody/issues/1725
- [ ] https://github.com/sourcegraph/cody/issues/1726
```
### After GA Tasks:

```[tasklist]
### After GA
```

**Comment by kalanchan** [comment]
this is done, will confirm with Beyang

edit command:
![CleanShot 2023-11-07 at 14 25 22@2x](https://github.com/sourcegraph/cody/assets/51868853/e9de1d12-d8bc-4c8b-8072-ac5aaa8d9101)

diff view:
![CleanShot 2023-11-07 at 14 26 31@2x](https://github.com/sourcegraph/cody/assets/51868853/2e660077-1c30-4f88-9d99-da0865919807)

edit applied, undo, done:
![CleanShot 2023-11-07 at 14 27 25@2x](https://github.com/sourcegraph/cody/assets/51868853/65aab58d-d6e0-4435-b067-4499c4b7f628)

**Comment by taylorsperry** [comment]
- ✅ In the open project file, Cody automatically applies edits to the selected code, per the user’s instructions
- ❌ Users can see a diff view of the edit
- ❌ Users can undo an edit
- The edit command can be triggered from:
  - ✅ the sidebar
  - ✅ right-click menu
  - keyboard shortcut

When I tried this the lens (is that what it's called?) to retry / undo / see diff disappeared before I could even click on them. See [Loom](https://www.loom.com/share/53226db7f87444d68926713a3a2af988). 

I also ran into some weird/inconsistent behavior in which Cody didn't always apply my edits: 
- I highlighted some code, used the Edit command to ask Cody to add a new input, and saw this behavior (Cody just added two <selectedCode> and </selectedCode> tags. [Loom.](https://www.loom.com/share/73be306b001a43d492725d0c05b61409)
- Cody also didn’t consistently perform the edit at all. ([Loom](https://www.loom.com/share/0fad7efa54e147f4b91991c5d94469e5))

**Comment by kalanchan** [comment]
@taylorsperry can you show screenshots of being unable to see the diff view and unable to undo an edit? 

In my comments above I've captured where that functionality is

**Comment by taylorsperry** [comment]
@kalanchan do the looms I linked in my comment not do the trick?

**Comment by umpox** [comment]
@taylorsperry Do you have `files.autoSave` set in your VS Code settings by any chance? The code lens goes away on save so it might be related to that 🤔 

Maybe we should disable it if that setting is true.

**Comment by umpox** [comment]
> I highlighted some code, used the Edit command to ask Cody to add a new input, and saw this behavior (Cody just added two <selectedCode> and </selectedCode> tags.

PR to fix: https://github.com/sourcegraph/cody/pull/1765

**Comment by umpox** [comment]
@taylorsperry PR to fix the disappearing retry/undo/diff options: https://github.com/sourcegraph/cody/pull/1767

I believe this should fix the issue (it seems like the file auto saved from watching your loom). Would appreciate another test either on the branch or when this fix is released if you have chance!
