### ISSUE TITLE
PRD: [VSC] Document

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1660]
### Related Docs:

[PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit#heading=h.2wolyguph1ml)

### Description:

As a user, I want Cody to generate inline documentation for code that I've selected. 

### Objectives:

Provide an easily discoverable, pre-packaged prompt that allows Cody to provide inline documentation for selected code. 

### Acceptance Criteria:

```[tasklist]
### Acceptance Criteria:
- [x] In the open project file, Cody automatically generates documentation for the selected code
- [x] Users can undo the documentation
- [x] The documentation command can be triggered from the sidebar, right-click menu, or keyboard shortcut
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### After GA Tasks:

```[tasklist]
### After GA
```

**Comment by kalanchan** [comment]
this is done, will confirm with Beyang

document trigger:
<img width="828" alt="CleanShot 2023-11-07 at 14 30 42@2x" src="https://github.com/sourcegraph/cody/assets/51868853/53bd1860-6d3d-49cf-9b30-4be2af759870">

output:
![CleanShot 2023-11-07 at 14 31 58@2x](https://github.com/sourcegraph/cody/assets/51868853/8fabba7c-2dab-47cc-8a3e-3070a527a8ac)

**Comment by taylorsperry** [comment]
The first time I generated documentation, I triggered the command from the side panel and Cody provided documentation but the lens disappeared (same thing I reported for "Edit").

The second time, I triggered the command from the right-click menu, and applying edits failed. (Maybe this was because I was trying to generate documentation for the same section of code as my first attempt, above?)

![Image](https://github.com/sourcegraph/cody/assets/43555476/885a4ad1-9098-4cc8-999c-6435c21c0fad)

**Comment by taylorsperry** [comment]
Marking this as closed. We'll address any other bugs/fixes as they come up, but requirements above have been met.
