### ISSUE TITLE
PRD: [VSC] Smell command

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1661]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit#heading=h.2wolyguph1ml)

### Description:

As a user, I want Cody to provide suggestions for how I can improve the quality of the code that I've selected. 

### Objectives:

Provide an easily discoverable, pre-packaged prompt that allows Cody to help users improve the quality of their code.

### Acceptance Criteria:

```[tasklist]
### Acceptance Criteria:
- [x] In a new chat window, Cody provides suggestions for how to improve selected code
- [x] The smell command can be triggered from the sidebar, right-click menu, or keyboard shortcut
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### After GA Tasks:

```[tasklist]
### After GA
```

**Comment by kalanchan** [comment]
this is done, will confirm with Beyang

command trigger:
![CleanShot 2023-11-07 at 14 32 53@2x](https://github.com/sourcegraph/cody/assets/51868853/36fd5137-9abf-4bbe-a2f4-5beec0a514ab)

output:
![CleanShot 2023-11-07 at 14 34 28@2x](https://github.com/sourcegraph/cody/assets/51868853/79ff8c56-8a00-4f5d-b7b2-7006197aea43)

**Comment by taylorsperry** [comment]
- ✅ In a new chat window, Cody provides suggestions for how to improve selected code
- ✅ The smell command can be triggered from the sidebar, right-click menu 
   - TBD keyboard shortcut
