### ISSUE TITLE
PRD: [VSC] Custom commands

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1663]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit#heading=h.2wolyguph1ml)

### Description:

As a user, I want to be able to create my own custom commands that help me accomplish tasks that are specific to my workflow. I want this to be as easy as possible. 

I'd also (P2) like to be able to share any custom commands I create with my team, or publish them somewhere anyone can use them. Likewise, I'd like to be able to use custom commands that other people create, even if they're still under development. 

I'd also (P3) like to be able to sync custom commands that I've created (or that others have created and I want to use) across multiple Cody clients so they're available from whichever client I'm using, whether that's VSC, Cody web, etc. 

### Objectives:

Enable users to easily create and share custom commands, or discover and use custom commands created by others. 

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria:
- [x] P1: Users can write custom commands within their IDE
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/cody/pull/1731
- [ ] https://github.com/sourcegraph/cody/issues/1798
```

### After GA Tasks:

```[tasklist]
### After GA
- [ ] https://github.com/sourcegraph/cody/issues/1802
- [ ] https://github.com/sourcegraph/cody/issues/1803
- [ ] https://github.com/sourcegraph/cody/issues/1804
```

**Comment by kalanchan** [comment]
Items in P1 are done, will groom with Beyang to see if he wants to prioritize the rest of the P2s
