### ISSUE TITLE
PRD: Users can provide feedback on Cody's helpfulness

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1666]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

### Description:

As a member of the Sourcegraph team, I want to understand the quality of Cody's responses. Users should be able to submit a thumbs up/thumbs down reaction to any chat or command response that Cody provides. P2: If the user submits a "thumbs down," they should have an option to categorize the reason for the negative response (categorizations TODO). 

### Objectives:

Learn more about when Cody is helpful/unhelpful to users. 

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria:
- [x] There are thumbs up / thumbs down reactions available when Cody provides a response to:
- [x] A chat prompt
- [x] An explain prompt
- [x] A smell prompt
- [x] We have event loggers on all thumbs up / thumbs down reactions, including the type of prompt that the user submitted (eg, chat vs. explain vs. smell)
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### After GA Tasks:

```[tasklist]
### After GA
- [ ] https://github.com/sourcegraph/cody/issues/1801
```

**Comment by kalanchan** [comment]
thumbs up/down is done, will check on telemetry

![CleanShot 2023-11-07 at 14 42 01@2x](https://github.com/sourcegraph/cody/assets/51868853/522c1cc2-500e-42d1-a001-c99c9461244a)

![CleanShot 2023-11-07 at 14 41 06@2x](https://github.com/sourcegraph/cody/assets/51868853/a5274c7f-601d-46ef-b2db-8b4968bde5a8)

**Comment by kalanchan** [comment]
@taylorsperry i've confirmed telemetry is in place, so everything but the P2 is done, if it's higher priority we can revisit after Dec GA - will close this after grooming with Beyang

**Comment by taylorsperry** [comment]
There are thumbs up / thumbs down reactions available when Cody provides a response to:

- ✅ A chat prompt
- ✅ An explain prompt
- ✅ A smell prompt

The P2 (categorize thumbs down reactions) can def wait until after GA. @kalanchan, if you'd like to create a separate issue for that, feel free. Whatever you think is easiest to track.

**Comment by taylorsperry** [comment]
I've created an [RFC](https://docs.google.com/document/d/179o8m5NbsE5oa_RhWnf1UjRe4cLa5RPGq4tWRQy_A-A/edit) to address the P2 (categorizing thumbs up/thumbs down feedback). Once we've aligned on a plan, we can create a new issue to execute.
