### ISSUE TITLE
PRD: [VSC] Users understand what's available as context

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1673]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

### Description:

As a user, I want to be able to understand what's available for Cody to use as context, and what _kind_ of context is available for a given project (ie, embeddings context vs. graph context vs. search context). 

As a free community user, I want to see all the projects that I have added as context for Cody and their status if they're in the process of being indexed. 

As an enterprise user, I want to see all the projects that my admin has added as context for Cody and their status if they're in the process of being indexed. 

When I'm working in a given project, whether I'm a community or enterprise user, I want to know whether or not the project is available to Cody as context. 

I also want to understand that if Cody does _not_ have my project as context, I should add the project to Cody's context (as an individual user - P1) or switch to dotcom account/request that my admin add the project to Cody's context (as an enterprise user - P2), so that Cody can provide more helpful responses to chats and commands. 

### Objectives:

Whether a user is a free community user or an enterprise user, they should understand what is available to Cody as context. We know that understanding context is a major pain point among our users (and it's also one of Cody's primary differentiators), so it's critical that we make this clear. 

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria:
- [x] Individual community users can see all the projects that they've given to Cody as context (including projects that are in the process of being indexed for embedding, graph, or local context)
- [x] The UX makes it clear whether or not the currently open project has been indexed
- [ ] P1 The UX makes it clear that Cody’s responses to chats and commands will be better if a project has been indexed and included in Cody’s current context
```

### Design Tasks:

```[tasklist]
### Design Tasks
- [x] Design ->  https://github.com/sourcegraph/cody/issues/1377
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/cody/issues/1524
- [ ] https://github.com/sourcegraph/cody/issues/1525
- [ ] https://github.com/sourcegraph/cody/issues/2027
- [ ] https://github.com/sourcegraph/cody/issues/2028
- [ ] https://github.com/sourcegraph/cody/issues/2032
- [ ] https://github.com/sourcegraph/cody/issues/2070
- [ ] https://github.com/sourcegraph/cody/issues/2083
- [ ] https://github.com/sourcegraph/cody/issues/2089
- [ ] https://github.com/sourcegraph/cody/issues/2090
```

### After GA Tasks:

```[tasklist]
### After GA
```

**Comment by taylorsperry** [comment]
@toolmantim we have as part of our acceptance criteria "P1 The UX makes it clear that Cody’s responses to chats and commands will be better if a project has been indexed and included in Cody’s current context". This feels related to discovering Enhanced Context _and_ understanding it. Do you have any design thoughts that might help us close this out?

**Comment by dominiccooney** [comment]
Ping @toolmantim, the "after GA" tasks are relevant in that the repo picker doesn't tell people what to do if the repo is missing; and the status is subtle (if you get a result you can mouse over it and get a tooltip which shows you the revision that was indexed, but that's useless for cut and paste, etc.)

Can you add this to your design backlog?

**Comment by taylorsperry** [comment]
I'm removing the "post-GA" items from this parent issue (so we can close it out), but keeping them as standalone items to address:

- [Make Enhanced Context more discoverable - Add CTA to chat transcript for Free/Pro users ](https://github.com/sourcegraph/cody/issues/2838)
- [Enterprise users are prompted to request that their admin index the project or switch to their personal account](https://github.com/sourcegraph/cody/issues/3041) 

Assigning those issues to @abeatrix since she was assigned to this parent issue.
