### ISSUE TITLE
PRD: [VSC] Users can configure Cody's current chat context

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1675]
### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

### Description:

As a user, I want to be able to easily manage what Cody uses as context for a given chat prompt. I want to understand that Cody won't use any of my code as context by default, and will only use my code as context when explicitly configured. 

P0: As a user, I want to easily add a single repo to Cody's current chat context. 
P0: As a user, I want to easily add multiple repos to Cody's current chat context. 
P0: As a user, I want to easily configure Cody's current chat context at a more granular level, eg, by folder, file, symbol, or line.

### Objectives:

Enable users to configure Cody's current chat context across multiple levels of granularity. 

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria:
- [x] Users understand that Cody will use code as context, unless explicitly disabled.
- [x] Users can add a single repo to Cody's chat context
- [x] Users can add multiple repos to Cody's chat context
- [x] Users can configure context at deeper levels of granularity for a given chat (e.g., folder-, file-, symbol-level, or line(s)-level)
- [ ] #2965
- [x] By default, new chats use the same context configuration as the previous chat
```

### Design Tasks:

```[tasklist]
### Design Tasks
- [x] Design issue -> https://github.com/sourcegraph/cody/issues/1377
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/cody/issues/1523
- [ ] https://github.com/sourcegraph/cody/issues/1525
- [ ] https://github.com/sourcegraph/cody/issues/1522
- [ ] https://github.com/sourcegraph/cody/issues/1526
- [ ] https://github.com/sourcegraph/cody/issues/1741
- [ ] https://github.com/sourcegraph/cody/issues/1524
- [ ] https://github.com/sourcegraph/cody/issues/2027
- [ ] https://github.com/sourcegraph/cody/issues/2028
- [ ] https://github.com/sourcegraph/cody/issues/2618
- [ ] https://github.com/sourcegraph/cody/issues/2622
- [ ] https://github.com/sourcegraph/cody/issues/2623
- [ ] https://github.com/sourcegraph/cody/issues/2624
- [ ] https://github.com/sourcegraph/cody/issues/2625
- [ ] https://github.com/sourcegraph/bfg-private/issues/145
- [ ] https://github.com/sourcegraph/cody/issues/2942
```

**Comment by kalanchan** [comment]
@taylorsperry I got some questions around the asks:

- `P0: As a user, I want to easily add a single repo to Cody's current chat context`
  - does the new [Enhanced Context Selector](https://github.com/orgs/sourcegraph/projects/387/views/3?pane=issue&itemId=43496140) satisfy this ask?
- `P1: As a user, I want to easily add multiple repos to Cody's current chat context.`
  - I don't think multi repo context is being worked on, is this a important requirement for GA? I will check with Beyang and the team to see how this would work. 
- `P1: As a user, I want to easily configure Cody's current chat context at a more granular level, eg, by folder, file, symbol, or line.`
  - I'm assuming this is the new "@ command" feature, should this  be a P0 instead to complement the new [context widget](https://github.com/orgs/sourcegraph/projects/387/views/3?pane=issue&itemId=43496140)?

**Comment by kalanchan** [comment]
> Users understand that Cody will not use any code as context, unless explicitly configured.

FYI @taylorsperry enhanced context selector is default to ON, and users can select whether to turn it off or not

**Comment by taylorsperry** [comment]
Post-GA follow-ups on the existing "Acceptance Criteria" above. @toolmantim and @beyang I would love your input here. 

**Users can add a single repo to Cody's chat context**
When I have "Enhanced Context" enabled today (v1.1.1703430406) and only one project open in my workspace, I can ask Cody a question like "What does this repo do?" and Cody provides a suitable answer. However, when I have multiple projects in a workspace, I don't see a way to use `@-` tagging to direct Cody to one project in my workspace instead of another. This feels like something we need to enable (or make more discoverable). 

**Users can add multiple repos to Cody's chat context**
This is, of course, a feature that's in high demand. What considerations do we need to make in order to support it? Some questions I have are: 
- What "kind" of context is included when a user adds a repo as part of Cody's chat context? Is it search- and embeddings-based? What about BFG?
- An enterprise user should be able to include as context any project that's been indexed on their Sourcegraph instance. Can Free/Pro users include anything they have locally? Anything in their workspace? Anything that's in their workspace and has embeddings? 
- In Cody Web, we have a limit of 10 repos to be added as context. Is that the same limit we should use here (I assume there are performance tradeoffs the more you allow)? 

**Users are notified when a folder or file is too large to be used as context.**
If a folder or file is too large to be used as context, does Cody still look for the most relevant snippets, or ignore the folder or file altogether? 

**By default, new chats use the same context configuration as the previous chat**
Today (afaik) this means that if the user has Enhanced Context enabled for one chat, it'll be enabled by default for a new chat. I think we should allow Free/Pro users to set a default LLM. Should Free/Pro/Enterprise users be allowed to also set default repos as context? I can see it being annoying to have to select the same, say, 3 projects over and over again, but I can also imagine someone thinking, "Why don't I just default to all the repos I ever use so I don't have to think about it" and that causing performance issues/poorer responses.

**Comment by dominiccooney** [comment]
@toolmantim Could you push the general question of "how do consumer users use multi-repo context?"

Some related questions:

- Can they/how do they choose or focus the context on specific repositories, like Enterprise can?
- Can they tag whole repositories?
- Can they add something that's outside their workspace?

@taylorsperry it would be great to get some use case input here, I think. As a consumer, I think I would have use cases like:

- I'm using a framework/libraries that I have pulled in with a package manager like npm
- I'm using a framework/libraries that I have added as git submodules
- I'm using a framework through the system, like a macOS Framework or library /usr/include on Linux

**Comment by toolmantim** [comment]
Those are great questions… and they apply to both Enterprise and PLG.

**Comment by toolmantim** [comment]
@dominiccooney @taylorsperry I think you've mentioned this before, but it's only clicked that there's the important case of a user opening a repository on their computer than isn't available in their Enterprise instance.

Currently we show the following confusing UI:

<img src="https://github.com/sourcegraph/cody/assets/153/c9e83877-3205-4aa7-996c-82b84d4a0224" width="352">

---

I've just done up a design ([Figma](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1575-34418&mode=design&t=ZS3LbV6wv5KVFGp1-4)) with the follow repository row, representing the repository for the active file:

<img src="https://github.com/sourcegraph/cody/assets/153/e616cab1-b6b9-4e04-a06e-57f9d9994a31" width="525">

**Comment by dominiccooney** [comment]
@beyang notes [in Slack](https://sourcegraph.slack.com/archives/C05AGQYD528/p1708478771071029) that we should make multi-repo selection work for multi-root workspaces in the consumer product.

**Comment by fazo96** [comment]
Hi, I am evaluating Cody for my team at Flexhire and we have this  folder set up:

```
- flexhire (git repo)
  - backend
  - frontend
```

We use a VSCode workspace with the following `folders`:

```
- flexhire
- flexhire/backend
- flexhire/frontend
```

I am getting this in the enhanced context popover:

![image](https://github.com/sourcegraph/cody/assets/2546805/22614fd3-bdd5-4990-b4e1-dd64e11e7f69)

We hoped we would be able to let Cody search across backend and frontend code but it doesn't seem to be the case. I have to say the product shows a lot of promise for us though

I am happy to try it again once it's able to recognize the folders correctly and index across both codebases.
