### ISSUE TITLE
Cody Agent: shim vscode.workspace.fs

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1684]
Implement [vscode.workspace.fs with FileWatcher](https://sourcegraph.com/github.com/microsoft/vscode/-/blob/src/vscode-dts/vscode.d.ts?L9034-9138) for vscode shim in agent for .cody/.ignore

VS Code File System API Doc: https://code.visualstudio.com/api/references/vscode-api#FileSystem

Example created by Olaf: https://github.com/sourcegraph/cody/commit/51c58e8b6f2cdbb534ceba0d405fabeb6fad439d

Example of creating a file watcher with node.js fs package: https://medium.com/@muhammadtaifkhan/watch-file-system-using-nodejs-7d4f9f16ce02

**Comment by The5cheduler** [comment]
Hey, I would love to take on this issue!
could anyone brief me on this so I can get started?
Thanks
