### ISSUE TITLE
[VSCode][Bug] Gutter icon show multiline when toggle word wrap

### ISSUE THREAD

**Issue by LatenPath** [sourcegraph/cody#1689]
### Summary
Gutter icon show multiline when toggle word wrap in `Settings.json` (JSON with comments).

### Details
![Code_ExEbg423sf](https://user-images.githubusercontent.com/145383056/281531040-94331166-5e2d-4985-a7ac-0ea71633f96b.png)

Gif image:
![Code_Hzcyakxts3](https://user-images.githubusercontent.com/145383056/281531705-a45a9cff-2507-4a18-9ae6-19027540c9e4.gif)

In some long word wrap, it will become a trouble:
![image](https://user-images.githubusercontent.com/145383056/281531936-a95defc0-65d3-4a1d-a8b4-d25a8f7c7c25.png)

VSCode version: 1.84.1
Cody version: v0.14.5

**Comment by LatenPath** [comment]
I will close it because it looklike VSCode issue itself.
![image](https://github.com/sourcegraph/cody/assets/145383056/9815c0f5-7239-481d-9d4b-13e469c4a6c9)

**Comment by jdorfman** [comment]
Thanks for following up @LatenPath
