### ISSUE TITLE
VSCE: Replace "New Chat" icon

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1693]
context: https://sourcegraph.slack.com/archives/C05AGQYD528/p1699402968832279

Add this [svg](https://github.com/sourcegraph/cody/pull/1560#issuecomment-1788464054) to cody-icons.woff and replace the current "new chat" icon with the new one.

Tim: 

> The instructions are in the readme there, let me know if that works!

> Also: it’d be nice to hide the Cody logo button in the chat window editor title. So it would be Restart Chat, New Chat, Chat History if we keep this new restart button.

Here is the current new chat icon:

![Image](https://github.com/sourcegraph/cody/assets/68532117/27714b85-fb15-4fc8-a4ef-736f419262ba)

**Comment by abeatrix** [comment]
Thanks for looking into this @iswarmondal !

Basically, we want to replace the current "New Chat" icon (["icon": "$(comment)"](https://sourcegraph.com/github.com/sourcegraph/cody@vscode-v0.14.5/-/blob/vscode/package.json?L481-486)) for the `cody.chat.panel.new` command with the icon mentioned in https://github.com/sourcegraph/cody/pull/1560#issuecomment-1788464054

But the new icon is not built-in, so we will need to convert the SVG image into text but adding it into the [vscode/resources/cody-icons.woff](https://sourcegraph.com/github.com/sourcegraph/cody@vscode-v0.14.5/-/blob/vscode/resources/cody-icons.woff) file first before we can use it in the package.json. You can find the instructions on how to convert it into font in this [README.md
](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/icons/README.md?L13). Let me know if you have other questions 😄

**Comment by iswarmondal** [comment]
On it

**Comment by iswarmondal** [comment]
<img width="565" alt="image" src="https://github.com/sourcegraph/cody/assets/73457704/4ea58149-eeff-4a9e-bbe8-2fdd3a6af07e">


This is my progress so far. I was able to indirectly edit the `.woff` file.
Let me know if this is what we need.

**Comment by abeatrix** [comment]
@iswarmondal yes, that's what the task is about, thank you so much for the quick turnaround! 

The image looks out of place to me compare to the nearby icons. Cc @toolmantim who requested this change - does this look alright to you?

**Comment by iswarmondal** [comment]
Thanks @abeatrix, after hearing from @toolmantim and fixing the alignment of the icon I'll create a PR for this

**Comment by toolmantim** [comment]
Thanks @iswarmondal! How did you generate the woff there? It appears the baseline is incorrect for both the new icon, but also the Cody icon seems to have changed too.

**Comment by toolmantim** [comment]
You'll need to follow https://github.com/sourcegraph/cody/tree/main/lib/icons, not the README.md linked above. I'd recommend we skip some letters in case we need more variants of the Cody logo… so go with "H" for this new one.

**Comment by iswarmondal** [comment]
Hey @toolmantim, I converted the WOFF file into a TTF file and then edited that TTF file, then converting back the edited TTF file. 

So as you said, I have to add the SVG icon with the name of `H.svg` inside `svg-origional` table and regenerate the icons using `pnpm run font` command.

This will generate me a new WOFF file which we will be using (Also need to update the MD file).

Is that right?

**Comment by toolmantim** [comment]
@iswarmondal yep, that's it! I believe it's the `svg-outlined` folder that's used, the originals are just for reference, but I'd add it to both directories just for consistency.

**Comment by iswarmondal** [comment]
On it...

**Comment by iswarmondal** [comment]
<img width="355" alt="Screenshot 2023-11-13 at 9 36 08 PM" src="https://github.com/sourcegraph/cody/assets/73457704/0cb62a43-0de5-44eb-a046-5d0309db761e">

#
Here's the updated icon

**Comment by iswarmondal** [comment]
I have raised a PR for this #1727

@abeatrix  @toolmantim please take a look

**Comment by abeatrix** [comment]
@iswarmondal thank you! Will review the PR first thing tomorrow!
