### ISSUE TITLE
User experience for a user to go from Cody Free / PLG to Cody Enterprise

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1729]
Spec: https://docs.google.com/document/d/1tBCJFPsgjv3tdIql8SwHskB0pwwgWb1Gm8nm_HmZbvE/edit

Diagram: https://docs.google.com/drawings/d/1w6FucqKtzlIte0sCBSiX6nFxSfS01BPchYrF_moLMUI/edit

**Comment by chenkc805** [comment]
@ryphil @chrsmith @vdavid @thenamankumar @danielmarquespt @unknwon 

As per our discussion last Friday, I took a stab at creating a user flowchart about the PLG --> Enterprise experience in the "Diagram" link above. Please give it a look and poke holes in it! Thank you

**Comment by vdavid** [comment]
Duplicate of https://github.com/sourcegraph/cody/issues/1547
