### ISSUE TITLE
Remove Slash from Slash Command

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1730]
Remove Slash from Slash Command

Requested by @toolmantim, will wait for detail

**Comment by iswarmondal** [comment]
I cannot understand the issue, please help me with a bit more info 🙂

**Comment by iswarmondal** [comment]
<img width="562" alt="Screenshot 2023-11-15 at 7 04 54 PM" src="https://github.com/sourcegraph/cody/assets/73457704/0391ed37-e233-454c-a73a-e33397b65bf2">

#
I found these two slashes in the new chat panel.
Are we talking about these @abeatrix ?

**Comment by abeatrix** [comment]
@iswarmondal sorry for the late reply and thanks for your interest in working on this issue. 
I don't have enough information on how to proceed this atm, will close this issue for now. If there is something else you're interested in feel free to let me know :)

**Comment by abeatrix** [comment]
Closing issue as discussed with Tim in this slack thread: https://sourcegraph.slack.com/archives/C05AGQYD528/p1700173517887689
