### ISSUE TITLE
VSCE Bug: Sidebar during initial startup

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1757]
In the new chat panel UI, if you restart VS Code and then click on the Cody icon during the start up stage, you will see the sidebar is opened and then closed again, before you can click on it to open the sidebar again.

https://github.com/sourcegraph/cody/assets/68532117/918de800-61d9-47b0-9c8a-78f1be830331

**Comment by iswarmondal** [comment]
Hey @abeatrix👋🏻 ,

I see in version `0.16.0` I am unable to reproduce this issue. So is this issue still persists from your side?

**Comment by abeatrix** [comment]
@iswarmondal sorry for not updating the issue properly, as you mentioned, this issue has been resolved in the linked issues!
