### ISSUE TITLE
VSCE: add edit button to chat

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1780]
Part of https://github.com/sourcegraph/cody/issues/1655 & https://github.com/sourcegraph/pfp/issues/2

> Users can edit a previous prompt and get a new response from Cody 

This is something we had but somehow not working. Will look into this

**Comment by kalanchan** [comment]
@abeatrix can we also lump this [ticket](https://github.com/sourcegraph/cody/issues/1763) in? Adding the ability to edit the chat name in the chat history panel

**Comment by abeatrix** [comment]
That's a different type of edit lol will work on that separately

**Comment by abeatrix** [comment]
Closed by https://github.com/sourcegraph/cody/pull/1781
