### ISSUE TITLE
Autocomplete: Experimentation with Treesitter

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#179]
The idea here is to use tree sitter for various problems:

- How to chunk code snippets of context snippets
- Creating an "interface only" representation of context snippets
- Better truncation of multiline text

**Comment by valerybugakov** [comment]
Closing in favor of [smaller tree-sitter-related issues](https://github.com/sourcegraph/cody/issues?q=is%3Aissue+is%3Aopen+tree-sitter).
