### ISSUE TITLE
P2: Users can discover and test a custom command while it's still under development (ie, without requiring it to be installed into a well-known folder first)

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#1802]

**Comment by abeatrix** [comment]
Users can create custom commands at User level instead of Workspace level, which does not require it to be installed into their repository folder as it goes to their user settings in VS Code - would that satisfy the scope of this request?

**Comment by abeatrix** [comment]
More detail here: https://sourcegraph.com/notebooks/Tm90ZWJvb2s6MzA1NQ==#tutorial-create-a-new-custom-command-to-make-code-more-robust-384711b8-4f60-4fac-95b4-a18c04f0f067

**Comment by toolmantim** [comment]
I think we can mark this as done, as it's supported by User Settings: https://sourcegraph.com/docs/cody/capabilities/commands#configuring-file-paths
