### ISSUE TITLE
P2: Users can sync custom commands across multiple Cody clients

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#1804]

**Comment by taylorsperry** [comment]
Closing this out. I've added it to [PRD Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit) so we don't forget, and I'll create a new issue once it's better scoped and prioritized.
