### ISSUE TITLE
bug: update notice on new chat UI too high

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1811]
### Version

0.16.0

### Describe the bug

The update notice sits too high on the new chat UI:

<img width="658" alt="Screenshot 2023-11-19 at 10 24 57 pm" src="https://github.com/sourcegraph/cody/assets/153/fcd6cbb3-f949-4726-a66d-fd1fe45d35bb">

### Expected behavior

Needs to be 15px further down

**Comment by iswarmondal** [comment]
On it...

**Comment by abeatrix** [comment]
@iswarmondal LGTM :D How does it look on the old sidebar?

**Comment by iswarmondal** [comment]
@abeatrix  it seems like I once dismissed the notification now I'm unable show the notification again for a screenshot 🙂

**Comment by kalanchan** [comment]
@iswarmondal thanks so much for helping us out! submit the PR and let's review there :)

**Comment by iswarmondal** [comment]
Hey @kalanchan, here's my PR - https://github.com/sourcegraph/cody/pull/1887
