### ISSUE TITLE
bug: reloading page with new chat UI shows empty tabs

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1814]
### Version

0.16.0

### Describe the bug

If you have a chat open, and you quit and re-open VS Code (or reload the window) your chat is no longer visible (you only get an empty tab)

https://github.com/sourcegraph/cody/assets/153/6dcdb02a-3763-4ac8-bb74-b7be01870642

### Expected behavior

* Chats reappear on reload
* If Cody sidebar is visible before reload, it reopens on reload (possibly related to #1810)

**Comment by iswarmondal** [comment]
Hey @toolmantim 👋🏻

I see this issue has been present in previous version also. To fix this issue I might need some guidance from the devs.
