### ISSUE TITLE
bug: external file warning when clicking files included via @ in new chat UI

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1819]
### Version

0.16.0

### Describe the bug

Clicking file attachment tokens in the chat transcript causes VS Code to show a warning about an external application wanting to open the file:

<img width="781" alt="Screenshot 2023-11-20 at 2 27 37 pm" src="https://github.com/sourcegraph/cody/assets/153/9c938a77-8958-4f42-9ee4-aee511fa4378">

### Expected behavior

No warning would be shown

**Comment by abeatrix** [comment]
This is because of a new setting added by vs code and the setting can only be configured by users for security reason: 
https://code.visualstudio.com/updates/v1_84#_confirmation-for-opening-protocol-links


> When a protocol link for a file or workspace opens in VS Code, a dialog will now ask for confirmation:

**Comment by toolmantim** [comment]
@abeatrix would it be possible to send a message/command instead of using the `vscode://file` URI and avoid it?

**Comment by abeatrix** [comment]
@toolmantim Yea that worked! Here is the PR: https://github.com/sourcegraph/cody/pull/1919
