### ISSUE TITLE
bug: Cody editor title button should not show on non-editable editors

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1821]
### Version

0.16.0

### Describe the bug

The editor title button shows on all editors, even those that are non-editable:

![image](https://github.com/sourcegraph/cody/assets/153/1b515af7-12c2-482e-a86d-34eba6dc5f39)

### Expected behavior

The Cody editor should only appear on editable files

**Comment by abeatrix** [comment]
the editor icon opens the main menu that has actions not restrained to editable editors , for example, ask a question and start a new chat, or notebook editors etc.

Do we still want to remove it from non-editable editors?
