### ISSUE TITLE
feedback: Allow user to configure autocomplete's text formatting style

### ISSUE THREAD

**Issue by aaronliu0130** [sourcegraph/cody#1834]
### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

Currently, Cody always makes autocomplete suggestions in italics. However, I have my font set to display comic sans for all italics.	

### Why is this feedback important? Please describe the rationale.

Regardless of font choice, users should be able to configure how they like Cody's suggestions to look like

### Describe the solution you'd like to see

Allow the user to configure cody's autocomplete suggestions' style just like vscode's textmaterules

**Comment by jdorfman** [comment]
Thanks @aaronliu0130 

> Allow the user to configure cody's autocomplete suggestions' style just like vscode's textmaterules

Not seeing that in the marketplace. Can you send a link or better yet, attach a screenshot? 

Thanks

**Comment by aaronliu0130** [comment]
https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

No need for configuring tokenization though, just a subset where we assume everything is already inside a scope would be fine

**Comment by aaronliu0130** [comment]
Is there a label that can stop an issue from being marked as stale? @jdorfman have ou seen my link?

**Comment by jdorfman** [comment]
@abeatrix is this something we would consider?

**Comment by jdorfman** [comment]
@valerybugakov what do you think?

**Comment by valerybugakov** [comment]
Thanks for creating the issue, @aaronliu0130! Did you encounter the desired behavior with other inline completion providers? If so, could you share an example? 

From the quick read on the linked API doc, it's unclear how we can apply specific styles to the ghost text generated by Cody or other inline completion providers.

**Comment by aaronliu0130** [comment]
Not sure about other extensions. https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#custom-token-types-and-modifiers seems like it could provide an extension with the capabilities I've described.

**Comment by valerybugakov** [comment]
Yeah, I understand your idea, but I do not see a way to integrate it with [InlineCompletionItemProvider](https://code.visualstudio.com/api/references/vscode-api#InlineCompletionItemProvider)`. It looks like the VS Code extension API does not directly support applying custom semantic tokens to [InlineCompletionItems](https://code.visualstudio.com/api/references/vscode-api#InlineCompletionItem).

**Comment by aaronliu0130** [comment]
Well, this was inspired by the monaspace website. According to https://github.com/githubnext/monaspace/issues/6 though, it's actually customized through a CSS class. I assume Cody has its own?

**Comment by valerybugakov** [comment]
Thanks for sharing. It gave me breadcrumbs to find [the relevant source code](https://github.com/microsoft/vscode/blob/feff7c8a7e1c82320380f42d898a1e03051fefb7/src/vs/editor/contrib/inlineCompletions/browser/inlineCompletionsController.ts#L118-L125). Customizing these classes is currently impossible; they are the same for all VS Code plugins. Recently, the support for `editor.inlineSuggest.fontFamily` [was added](https://github.com/microsoft/vscode/pull/202671) to VS Code, so it might address your request once it's available in the stable version. 

It means that we can only address this on our side once the API changes to allow it. Closing this for now, feel free to reopen if you see a way to achieve that.

**Comment by aaronliu0130** [comment]
Got it. So Cody's autocompletion also produces the ghost-text-decoration & co. classes?

**Comment by valerybugakov** [comment]
Yes! Based on the code, all the completion providers in VS Code use the same classes.
