### ISSUE TITLE
bug: @-file is case sensitive

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1838]
### Version

0.16.0

### Describe the bug

@-file results are missing some of the same results that VS Code would show for the same query, due to case sensitivity:

<img width="688" alt="Screenshot 2023-11-21 at 1 26 12 pm" src="https://github.com/sourcegraph/cody/assets/153/08524e84-87cf-49da-8100-8a6715ea3c38">

### Expected behavior

The search returns the same results as VS Code

**Comment by abeatrix** [comment]
this is limited by the VS Code API we depend on. This should be resolved once bfg and other context that support fuzzy search are available to use: https://github.com/sourcegraph/cody/issues/1840#issuecomment-1820985414

**Comment by toolmantim** [comment]
It looks like there is a workaround we could do: https://github.com/microsoft/vscode/issues/10633#issuecomment-680928105

According to Cody:
> Write a typescript function that for each letter converts it into a regex glob that is case insensitive. e.g. ""VeryLongFilePathThatGoesOnAndOnAndOn" becomes "{V,v}{E,e}{R,r}{Y,y}{L,l}{O,o}{N,n}{G,g}{F,f}{I,i}{L,l}{E,e}{P,p}{A,a}{T,t}{H,h}{T,t}{H,h}{A,a}{T,t}{G,g}{O,o}{E,e}{S,s}{O,o}{N,n}{A,a}{N,n}{D,d}{O,o}{N,n}{A,a}{N,n}{D,d}{O,o}{N,n}"

Here is a function that converts a string to a case insensitive regex glob:

```typescript
function stringToRegexGlob(str: string): string {
  return str.split('').map(char => `{${char.toUpperCase()},${char.toLowerCase()}}`).join('')
}
```

To test:

```typescript
const input = "VeryLongFilePathThatGoesOnAndOnAndOn";
const output = stringToRegexGlob(input);

console.log(output);
// "{V,v}{E,e}{R,r}{Y,y}{L,l}{O,o}{N,n}{G,g}{F,f}{I,i}{L,l}{E,e}{P,p}{A,a}{T,t}{H,h}{T,t}{H,h}{A,a}{T,t}{G,g}{O,o}{E,e}{S,s}{O,o}{N,n}{A,a}{N,n}{D,d}{O,o}{N,n}{A,a}{N,n}{D,d}{O,o}{N,n}"
```

**Comment by kalanchan** [comment]
@toolmantim lmao this actually works, nice find 🤣 

Previously the @ command wouldn't be able to find `readme" as its usually README but this workaround is neat. 

I wonder how this affects context retrieval though, I don't know if this glob affects other search mechanisms

![CleanShot 2023-11-23 at 14 39 28@2x](https://github.com/sourcegraph/cody/assets/51868853/4caba8f8-2b9d-4739-8b68-8c14ea366a6f)

**Comment by toolmantim** [comment]
I have a PR in the works to fix this

**Comment by abeatrix** [comment]
Nice found Tim ❤️ :galaxybrain:

**Comment by kalanchan** [comment]
gogogogo polish!!
