### ISSUE TITLE
bug: @-file excludes doesn't include file extension in the match

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1840]
### Version

0.16.0

### Describe the bug

Unlike VS Code’s search, @-file excludes results when you include the file extension (which is useful for reducing the results to a known file type):

<img width="1406" alt="Screenshot 2023-11-21 at 3 03 14 pm" src="https://github.com/sourcegraph/cody/assets/153/418aa536-574f-4187-8d8d-2d4b3aba2e6a">

<img width="1406" alt="Screenshot 2023-11-21 at 3 03 06 pm" src="https://github.com/sourcegraph/cody/assets/153/0c8d94c9-0b8f-4836-a145-4ee3dad2e90b">

### Expected behavior

The search returns the same results as VS Code (file extensions are included in the matching & ranking)

**Comment by abeatrix** [comment]
The findFiles API we are using behaves similarly as the Sidebar Search. It supports regex search, but not fuzzy search like the one from the command palette, which they don't have a public API for that yet.

![image](https://github.com/sourcegraph/cody/assets/68532117/5a0cbae3-fc9e-49b9-8bbc-edcee3b68bbf)

![image](https://github.com/sourcegraph/cody/assets/68532117/2acb31f5-aa8b-4617-a0db-4ab323140cfb)

![image](https://github.com/sourcegraph/cody/assets/68532117/fafbd46c-c784-465d-a184-03bc3e063f01)

We can try to implement this but I think we can wait and[ implement bfg to the search results ](https://sourcegraph.slack.com/archives/C05AGQYD528/p1699377305598369)instead (after GA), what do you think?

**Comment by toolmantim** [comment]
Bummer! Would bfg support fuzzy file search? I thought that only dealt with symbols.
