### ISSUE TITLE
bug: Ctrl+Delete does not work in chat input

### ISSUE THREAD

**Issue by sqs** [sourcegraph/cody#1869]
### Version

v0.17.1700665592

### Describe the bug

In the chat textbox, Ctrl+Delete does not work.
![image](https://github.com/sourcegraph/cody/assets/1976/e25e61b5-bcf9-4f68-a734-91c943979c37)

### Expected behavior

I expect Ctrl+Delete to delete the word before the cursor (as it does in every other text box on my OS (Linux)).

It does nothing.

**Comment by iswarmondal** [comment]
I'm using MacOS `14.1.1` and in my case the `command` `option` keys are working fine. 
Just the `control` key is not doing any action while deleting text (nothing is getting deleted)


https://github.com/sourcegraph/cody/assets/73457704/418dca0c-77d5-4636-80c8-ae69b44553bc
