### ISSUE TITLE
bug: chats should open as locked groups

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1874]
### Version

0.16.0

### Describe the bug

It's rare you want a file to open into a chat group by default. Similar to the Sidekick AI extension, we should start our chat groups as locked groups to avoid this.

### Expected behavior

New chat tab groups are locked by default

**Comment by abeatrix** [comment]
The VS Code API doesn't have access to create locked tab group. Only user can do that from what I gathered. See https://github.com/microsoft/vscode/issues/100335

**Comment by toolmantim** [comment]
Closing as it's not possible (the other extension was using a private API and obfuscated code)

**Comment by toolmantim** [comment]
@abeatrix later, could we file an enhancement request (or pull request) to VS Code to get the API added?
