### ISSUE TITLE
bug: The requested URL could not be retrieved

### ISSUE THREAD

**Issue by cfrikke** [sourcegraph/cody#1896]
### Version

0.16.0

### Describe the bug

My input: Hello

Cody Output:

**Request failed:**
### **The requested URL could not be retrieved**
The following error was encountered while trying to retrieve the URL: https://sourcegraph.com/.api/completions/stream

**Read Error**

The system returned: (104) Connection reset by peer

An error condition occurred while reading data from the network. Please retry your request.

Your cache administrator is [webmaster](#).

Generated Mon, 27 Nov 2023 13:18:23 GMT by test (squid/3.1.20)

### Expected behavior

I expected it to work and say hello back

### Additional context

This may be an issue on my end, but I don't know for sure

**Comment by jdorfman** [comment]
@cfrikke we had an issue with our Gateway. Please try again. If you are still having issues please reopen this issue.

**Comment by cfrikke** [comment]
so It should be back up and running now?

**Comment by jdorfman** [comment]
@cfrikke yes and if not open and close your IDE.
