### ISSUE TITLE
PRD: [VSC] PLG Pro users can choose the LLM they'd like to use for a given chat

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1902]
### Description:

As a PLG pro user, I want to be able to experiment with different LLMs for chat and choose the one that is best suited to my use cases. 

This feature differentiates Cody from AI coding assistants that only support default LLMs for chat and supports our messaging that "Cody is about choice." 

### Objectives:

The goal is to allow PLG pro users to choose between the following LLMs for *chat only*: 
- Claude Instant 1.2
- Claude 2
- ChatGPT 3.5 Turbo
- ChatGPT 4 Turbo Preview

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria
- [ ] https://github.com/sourcegraph/cody/issues/1939
- [ ] https://github.com/sourcegraph/cody/issues/1940
- [ ] https://github.com/sourcegraph/cody/issues/1941
- [ ] https://github.com/sourcegraph/cody/issues/1938
```
### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)
- [PRD: Cody Context](https://docs.google.com/document/d/1maukq6wAcLpCf5PUzzRrGE2g9M1MiPyurPtFyglIWdg/edit#heading=h.zgi67dag77i9)

**Comment by kalanchan** [comment]
@taylorsperry just to confirm, for GA **only** **Pro** users can change the LLM? at the moment free users can change as well.

**Comment by taylorsperry** [comment]
@kalanchan Yep, that's what we discussed in the Cody Context PRD, but I tagged @csells and @chenkc805 in that doc to ask them to review this issue and make sure we're all aligned.

**Comment by toolmantim** [comment]
@abeatrix for the design side of this, we’ll want to show the model selector still but disable all the non-pro items with a “Pro” badge/CTA on them. I’ll put a design together for it, but just a heads up.

**Comment by abeatrix** [comment]
@toolmantim I have the PR ready 😅  I can adjust it once the design is ready, thanks for the heads up!

**Comment by chenkc805** [comment]
> @abeatrix for the design side of this, we’ll want to show the model selector still but disable all the non-pro items with a “Pro” badge/CTA on them. I’ll put a design together for it, but just a heads up.

@toolmantim not a launch blocker for Dec GA, but I'd like to think about how we can relay those Free users that encounter this "Pro" badge in the dropdown over to the Upgrade flow at some point. Something for us to think about!

**Comment by toolmantim** [comment]
Cool, let's make sure to include design in the loop before we consider something fixed/closed 🤗

**Comment by toolmantim** [comment]
I've updated the chat model selector designs here:
https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=763-165099&mode=design&t=GBsnBjtyAb1LuxsC-4

![image](https://github.com/sourcegraph/cody/assets/153/cd612439-5b24-4e5a-8af5-42285af2cce9)

Clicking on any of those "Pro" rows would open the PLG web URL to upgrade their account.

**Comment by vdavid** [comment]
- Just to have everything nice and linked, let me post the PR for restricting access for Free users: https://github.com/sourcegraph/sourcegraph/pull/58817
(Also waiting for code review 😉 😉)
