### ISSUE TITLE
Create email address whitelist for Cody QA purposes

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1905]
We currently require a 14 day age limit for Google SSO signups for someone to create a Cody account. This hinders our ability to QA with fresh email addresses, so we want to create a whitelist of email addresses that Sourcegraph employees create to enable us to QA Cody. 

Emails and pws here: https://docs.google.com/spreadsheets/d/1V1t-AaR2f-BfX8dVM6xPrX789XF48etGmLHaP3Q9-T0/edit#gid=344236988

**Comment by chenkc805** [comment]
@danielmarquespt @vdavid @thenamankumar I created 2 email addresses here. I was limited to 2 before Google blocked me for using the same phone number twice in a short span of time. 

If I could get some help from y'all creating 2 more per person each, then that would give us 8 email addresses to work off of for testing. Please put the email and pw's in the above spreadsheet.

**Comment by vdavid** [comment]
This should be done now. @chenkc805, please confirm and close if we covered everything

**Comment by chenkc805** [comment]
Let's close when this is actually deployed and we can start QA'ing

**Comment by vdavid** [comment]
- It is deployed: https://github.com/sourcegraph/sourcegraph/pull/58792
So closing this
