### ISSUE TITLE
Autocomplete: replace completion post processing logger with OpenTelemetry spans

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/cody#1921]
We need a way to see the stage the streamed completion response goes through to quickly locate bugs and debug efficiently streaming/truncation/post-processing logic. Each generated partial response can start a new OpenTelemtry trace, with spans being stages of our processing pipeline with an ability to log all this information in a readable way to the trace view or the console output.

- Part of https://github.com/sourcegraph/cody/issues/1619
- Follow up for https://github.com/sourcegraph/cody/pull/1894

**Comment by beyang** [comment]
Closeable?

**Comment by valerybugakov** [comment]
Yes, it will be closed by the three PRs I opened last week. The are linked above.
