### ISSUE TITLE
[EZ UI] /subscription page copy updates

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1931]
Spreadsheet with copy to use on the /subscription and pricing page: https://docs.google.com/spreadsheets/d/1_esdhy01y7Xk0JCGBFGoa2Jf_5Nt8WbWl48IvBpDG4s/edit#gid=0

**Comment by chenkc805** [comment]
Currently in review with @ryphil and @connoro13c

**Comment by vdavid** [comment]
@chenkc805 is this still in review?

**Comment by chenkc805** [comment]
Yes this will be finalized by EOD tomorrow. This should be just copy changes, except I'd like to use tooltips like what the marketing pricing page is doing here for some overflow text: https://github.com/sourcegraph/about/pull/6600

We have a tooltip component here: https://github.com/sourcegraph/about/blob/7e510b2f32a869ac0189a4d43f383e2a9da56658/src/components/Tooltip.tsx

Think this is possible before Dec GA? It's ok if not, we can mark this as a fast follow.

**Comment by chenkc805** [comment]
Ok @thenamankumar , copy for the pricing page is finalized here for rows 1-26: https://docs.google.com/spreadsheets/d/1_esdhy01y7Xk0JCGBFGoa2Jf_5Nt8WbWl48IvBpDG4s/edit#gid=0

The Google sheet "notes" (little black triangles in the top right of the cell) are what goes in the tooltips. LMK if you want a walkthrough.

**Comment by chenkc805** [comment]
@thenamankumar  reopening this - some bugs I found on `/cody/subscription`

- The "code context and personalization" section doesn't match what we have in the spreadsheet. See [rows 11-12](https://docs.google.com/spreadsheets/d/1_esdhy01y7Xk0JCGBFGoa2Jf_5Nt8WbWl48IvBpDG4s/edit#gid=0&range=11:12)
- The "LLM support" section under pro is missing the tooltip 
- The prices should show with the dollar sign in front: ("$9", not "9$")
- Enterprise should show "Up to $19 / user / month", not just "$19 / user / month"

![Screenshot 2023-12-12 at 9 44 02 AM](https://github.com/sourcegraph/cody/assets/3654603/e4b77995-2bca-4b8b-a9ab-ed05a723d554)
