### ISSUE TITLE
[EZ UI] Add a "Skip" button to the "Choose your editor" page

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1937]
Expected behavior:
- Perhaps there's some users that don't want to use Cody in the IDE and just want to use the Web. They should be able to skip this step
- Remove the "Skip" button in the bottom left
- Make a "Skip for now" CTA at the bottom right. 
![Image](https://github.com/sourcegraph/cody/assets/3654603/d9ef7f07-d45f-435b-9a56-86d13edea9f1)

**Comment by chenkc805** [comment]
CC: @danielmarquespt

**Comment by vdavid** [comment]
- Closed by https://github.com/sourcegraph/sourcegraph/pull/58828
