### ISSUE TITLE
P0: PLG free users see that Cody uses Claude 2 for chat by default

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1940]
Claude 2.0 to be exact

**Comment by vdavid** [comment]
@abeatrix, I'm working on the Cody Gateway side of this restriction (see [this issue](https://github.com/sourcegraph/sourcegraph/issues/58753)). Do you know which exact model we should let through for Free users? I have this list: "anthropic/claude-v1", "anthropic/claude-2", "anthropic/claude-2.0", "anthropic/claude-2.1", "anthropic/claude-instant-v1", "anthropic/claude-instant-1"
I suppose it'll be `anthropic/claude-2.1`?

**Comment by vdavid** [comment]
Nice, PR is done here: https://github.com/sourcegraph/sourcegraph/pull/58817
