### ISSUE TITLE
bug: typing / in the chat input only shows custom commands

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1943]
### Version

v0.16.1

### Describe the bug

Typing a `/` in the chat input only opens up custom commands, but if slash commands are accessible from the chat input, I'd expect to see all of the supported commands. 

v0.16.1
![Image](https://github.com/sourcegraph/cody/assets/43555476/44302717-8f83-4c2c-9805-891cc9814e5c)

This is UX we had in the old chat UX (v0.14.2)
![Image](https://github.com/sourcegraph/cody/assets/43555476/bb30550f-4f81-463d-aa57-f2e695202620)

### Expected behavior

I'd expect to see the full list of supported commands when I type `/` in the chat input.

**Comment by abeatrix** [comment]
@taylorsperry The full list of supported commands is available on `/`.  You should be able to see them if you scroll down:

https://github.com/sourcegraph/cody/assets/68532117/6923ff00-f775-43c4-a2b6-c6910956db3b

Will update to make sure the container box is the same width and height as the window for the @ command

**Comment by abeatrix** [comment]
Nice catch btw, thanks for reporting the issue!

**Comment by abeatrix** [comment]
PR: https://github.com/sourcegraph/cody/pull/1962

**Comment by taylorsperry** [comment]
Thank you, @abeatrix ! I didn't even see that there was a scroll bar in there. I don't suppose there's any way to make the scroll bar a little more visible?

**Comment by abeatrix** [comment]
Yea for sure! [The changes made in the linked PR ](https://github.com/sourcegraph/cody/pull/1962)has expanded the width and height of the box so it is more obvious that it's scrollable and make it easier to discover 😄 

![image](https://github.com/sourcegraph/cody/assets/68532117/df11970b-a2d5-4f55-8088-53112088560f)

**Comment by taylorsperry** [comment]
Oh waaaay better, thank you!
