### ISSUE TITLE
feedback: confusing that edit command diff view opens in a new tab?

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1945]
### Areas for Improvement

- [x] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [x] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

v0.16.1

When viewing the diff after running an edit command, I didn't realize that the diff was opening in a new tab and I felt confused about how to undo or accept it. [Loom](https://www.loom.com/share/322f245c2c264a73bd5e5e28380f075f). 

### Why is this feedback important? Please describe the rationale.

Behavior wasn't intuitive to me. It felt like a bug when I didn't see the ghost text to undo/apply. 

### Describe the solution you'd like to see

Is it possible to apply the diff inline (with the ghost text to accept/undo) instead of opening a new tab?

**Comment by kalanchan** [comment]
closing due to old UI
