### ISSUE TITLE
As a billing owner on Cody Pro, I should be able to see previous charges regarding my Cody Pro plan

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1946]

**Comment by chrsmith** [comment]
We have the ability to retrieve the invoice history for a subscription. So the work remaining here is to just wire this up to the frontend.

**Comment by chrsmith** [comment]
We show the list of invoices in the UI, leading to an unauthenticated page hosted by Stripe. So we should be good on this front.
