### ISSUE TITLE
As a team owner, I can do specific actions that only team owners can do

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1954]
Requirements

- As a team owner with @acmecorp.com domain, I can:
  - transfer ownership of the team to someone else on my team with the same email domain only
  - invite people to my team
  - remove people from my team
- As a team owner with @personalemail.com domain, I can:
  - invite people to my team
  - remove people to my team
  - transfer ownership to someone else on my team

**Comment by vdavid** [comment]
This is done, although implemented differently: users can use whatever email domains and get all the functionality.
