### ISSUE TITLE
Implement telemetry for billing interactions

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1958]
Events outlined here in the "February Launch [reduced scope]" tab: https://docs.google.com/spreadsheets/d/1QXnrHkgGLXdbfHEhI_VjtDTy-mCtnK1qri3IMQu7rNk/edit#gid=1509442061

**Comment by chrsmith** [comment]
Moving to blocked as it isn't clear (to me at least) where exactly we want this telemetry to be sent. (BigQuery? Segment? A new `events` table? etc.) @chenkc805 , is there a particular data lake we are expecting this to start showing up?

**Comment by chenkc805** [comment]
Yes, please send these events to BigQuery. I believe the "events" table is the canonical dumping ground and then a bunch of ETLs flow from there. @kelsey-brown can you confirm?

**Comment by chrsmith** [comment]
Note to self: If it's just a matter of pushing data into BigQuery, then perhaps we can reuse/pattern it after how SAMS is using it. (Perhaps that is how it is pushing telemetry data.)
https://github.com/sourcegraph/accounts.sourcegraph.com/pull/206/files

**Comment by kelsey-brown** [comment]
For web/client-side events we can use our [telemetry service](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/tracking/eventLogger.ts) for logging. 

IIRC we (you, me, @akalia25) had a brief and very high-level discussion about this a few months back, and I think that's what we landed on for things like this, but @akalia25 correct me if I'm wrong or if there's nuance here.

**Comment by akalia25** [comment]
Yes, you're right @kelsey-brown. We should be leveraging our telemetry service for logging web/client-side events.

**Comment by chrsmith** [comment]
I'm looking into this now. I'm going to to start by pushing backend events to BigQuery. But we'll need to create a separate ticket and use a different approach for emitting client-side telemetry. (Which may involve porting the linked [telemetry service](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/tracking/eventLogger.ts) to our frontend, or adding the dependency if possible.)

References to how we implemented this on the SAMS-side:

- https://github.com/sourcegraph/accounts.sourcegraph.com/issues/114
- https://github.com/sourcegraph/accounts.sourcegraph.com/pull/211)

**Comment by akalia25** [comment]
CC: @nathan-downs for visibility and V2 telemetry input

**Comment by akalia25** [comment]
If you need any support with telemetry and getting things working/testing, let us know @chrsmith, and we (@akalia25 @nathan-downs) would be more than happy to help!

**Comment by vdavid** [comment]
@chrsmith, could you help break this down to what's needed to have telemetry on everything we want by Feb 8th / Feb 15th?

**Comment by chrsmith** [comment]
So @vdavid , I don't know exactly off the top of my head. It's a matter of reviewing what data we would like to have ([Kevin's doc](https://docs.google.com/spreadsheets/d/1QXnrHkgGLXdbfHEhI_VjtDTy-mCtnK1qri3IMQu7rNk/edit#gid=1509442061)) and then seeing what data/triggers we have available.

But for sure, we would need to do the following:

- Now that [the BigQuery tables have been created](https://github.com/sourcegraph/managed-services/pull/446) we need to add a "BigQuery Pusher" similar to what the SAMS backend does. (I don't see any reason why we wouldn't want to use the same pattern/design.) See [accounts/backend/internal/bigquery/bigquery.go](https://github.com/sourcegraph/accounts.sourcegraph.com/blob/main/accounts/backend/internal/bigquery/bigquery.go) and friends.
- We'll want to wire _ALL_ Stripe webhook events to the `stripe_events` BigQuery table. "something something write the raw payload data from Stripe [here](https://github.com/sourcegraph/accounts.sourcegraph.com/blob/main/cody/backend/internal/api/stripe.go#L60).
- As far as `cody_event`s to write, We should probably just add an event for every function call into the `product` package. (e.g. `CreateTeam(...)` or `UpdateTeam(...)`, etc.

**Comment by thenamankumar** [comment]
I am taking this over.

**Comment by vdavid** [comment]
@thenamankumar, could you give us a status on this, including the steps needed here?  This item was slated for Feb 21, but I've seen no progress on it.

**Comment by vdavid** [comment]
@thenamankumar, is there a (draft) PR for the bullets you listed as done?

As this has been taking a while, would it make sense to split this work into two and deliver the server-side logging first, then add the client-side events in a separate PR?

If I understand correctly, `cody_event`s from the `product` package are also to be added, right?

**Comment by chrsmith** [comment]
@thenamankumar, any update on this ticket? There is a growing collection of other telemetry related things piling up, and I'd hate to just start from scratch if you've already gotten most of the things nearly ready.

**Comment by thenamankumar** [comment]
Here is a dump of the progress I made earlier: https://github.com/sourcegraph/accounts.sourcegraph.com/pull/637

Happy if anyone else can pick it up from here.

**Comment by chrsmith** [comment]
Just a quick update:

(1) At this point it looks like there are two pieces. First, pushing user telemetry data to the Telemetry Gateway (see [RFC 897 WIP: Unified user events table/data store](https://docs.google.com/document/d/1OberM_s04DdkCmo8WUN9mrjn5agNNoGtVKYESQyiuxo/edit#heading=h.trqab8y0kufp) and the proto updates in https://github.com/sourcegraph/sourcegraph/pull/60991#issuecomment-1997444234.)

(2) The second is finishing up Naman's PR and pushing the raw Stripe webhook event data to BigQuery. (From prior experience, this will be helpful for debugging, and is kinda sorta required if we want to fully understand how a certain customer/billing situation arose.)

I told @dadlerj  we'd have ~1 done "in a couple weeks" almost "a couple weeks ago". So I'll try to get to that soon so he does not dispatch goons to break my legs.

**Comment by chenkc805** [comment]
Hey @chrsmith , 

Do you have an update for this one? We've been working on this one for a couple of months now and we don't have any visibility into how users are going through our billing flow without this.

**Comment by chrsmith** [comment]
@chenkc805 Sorry about the lack of progress here. This literally was at the top of my queue, but I got side tracked with battling abuse and some other fires. I'll have a PR out to address this once and for all by the EOD tomorrow. <--- Hold me to that!
