### ISSUE TITLE
Sunset Cody App plan

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1963]
Message:
-  "On December 14, we are migrating the Cody App functionality to the IDEs. You will be able to set up your embeddings directly in VS Code and chat with your embedded codebase via the Cody extension in VS Code. JetBrains users will soon have this functionality as well. After December 14, the Cody App will no longer support chats and embeddings functionality." 

Mechanism to send this message in the Cody App already exists: 
- See this Slack message: https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1699558185499319?thread_ts=1699553868.780979&cid=C052G9Y5Y8H

Requirements after we send out this message:
```[tasklist]
### Requirements
- [ ] Turn off the ability for users to chat in the Cody App
- [ ] Turn off the ability for users to set up embeddings in the Cody App
- [ ] Show a message in the Cody App that tells users the Cody App is going away
- [ ] For users who have authenticated into VS Code with the Cody App, log them out and instead log them into their dotcom account
```

**Comment by chenkc805** [comment]
@taylorsperry @iskyOS can you review this copy?

**Comment by taylorsperry** [comment]
If this is the mechanism I'm thinking of, it's just a little blue banner that appears above the nav bar (the same as the notifications you'd see on s2), so I'm not sure how much room we have for copy. Maybe we just say "On December 14, we will begin migrating the Cody App functionality to the IDEs and sunsetting the app. Learn more [link to docs]." Do we have someone on tap to implement this change? IIRC it's a very simple code change. 

<img width="1624" alt="Screenshot 2023-11-28 at 3 57 43 PM" src="https://github.com/sourcegraph/cody/assets/43555476/21c4e79c-58db-47dc-a3bf-f4970ad9433d">

**Comment by chenkc805** [comment]
CC: @dominiccooney for visibility

**Comment by chenkc805** [comment]
CC: @MaedahBatool  for some potential docs updates incoming
