### ISSUE TITLE
PRD: [VSC] PLG users can manage their local embeddings without the Cody app

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1965]
### Description:

PLG users (both free and pro) will be able to generate local embeddings up to certain rate limits. (Embeddings for enterprise users are managed by an admin and cannot be generated by individual users.) We need UX to support several scenarios: 
- Embeddings that were initially generated through the app and have now been "transferred over" and are available locally through the extension itself
- New embeddings that the user can generate for an open project through the extension
- Embeddings that are available via open source projects indexed on dotcom

### Objectives:

Make it clear to the user when embeddings are or are not available to a user for an open project, and enable them to generate embeddings for an open project (when possible) up to their individual rate limit. 

The acceptance criteria below reflect MVPs, but in the future, we'll want to iterate on providing more visibility into the "freshness" of embeddings and whether they reflect remote or local versions. 

## As a user who generated embeddings for `my-project` through the Cody app, I see via the context selector that embeddings for `my-project` are available.
<img width="216" alt="Screenshot 2023-11-28 at 5 33 38 PM" src="https://github.com/sourcegraph/cody/assets/43555476/8edc3967-c037-481c-8bef-73d1f5bfd94a">

## As a user working in a project that hasn't been embedded yet (either through the app or the extension), I see via the context selector that I can generate embeddings for the open project. 
<img width="216" alt="Screenshot 2023-11-28 at 5 37 15 PM" src="https://github.com/sourcegraph/cody/assets/43555476/a9e428db-b0d3-4473-b8ab-83f2c381c1e2">

## As a user working in an open source project that has embeddings on Sourcegraph.com, I see via the context selector that embeddings are available and inherited. 
<img width="193" alt="Screenshot 2023-11-28 at 5 47 13 PM" src="https://github.com/sourcegraph/cody/assets/43555476/fde24a94-f4a8-408b-9dfa-ba848497f3dc">

## As a user who wants to generate embeddings for a project, but the project would exceed my embeddings quota, I see that I cannot generate embeddings for the project and an explanation for why. 
@toolmantim Is there already a design for this that I've missed? In place of the "The repository's contents will be uploaded to OpenAI . . ." copy, I think we need a notification and link to sourcegraph.com/cody/manage where users can view their various rate limit quotas or upgrade. "Generating embeddings for this repository would exceed your rate limit. Upgrade [link]." *Note: the PLG team is handling sourcegraph.com/cody/manage and users' visibility into their rate limit quotas.*

## As a user who wants to remove embeddings that I've generated for my project, I can remove them via TODO but I understand that this will not change my remaining embeddings quota. 
@toolmantim what do you think is the best UX for this? I can imagine a section in the Cody Setting with a list of all the projects that have embeddings generated and options to delete them, or potentially an option within the "Enhanced Context" window (though I worry that may feel busy and give us less room to explain what is happening when a user removes local embeddings. 

 

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)
- [PRD: Cody Context](https://docs.google.com/document/d/1maukq6wAcLpCf5PUzzRrGE2g9M1MiPyurPtFyglIWdg/edit#heading=h.zgi67dag77i9)
- [Cody App Sunset Plan PRD](https://docs.google.com/document/d/1b4Q10Tq-aXOtmHhOXp3cAYEykF48_itg2CPruYa3wao/edit)

**Comment by dominiccooney** [comment]
@toolmantim, @taylorsperry there's another reaction I had while testing local embeddings. This is me as a *user.* If I start a job, and open a different workspace, does indexing pause? (Today we keep churning in the background.)

**Comment by taylorsperry** [comment]
Another thought just occurred to me, @toolmantim and @dominiccooney: When a user clicks the "Enable embeddings" button, I assume that the "Embeddings" context source in the Enhanced Context selector will update to show something like this. Correct? They don't need to click anything else? 

<img width="159" alt="Screenshot 2023-11-28 at 7 34 00 PM" src="https://github.com/sourcegraph/cody/assets/43555476/10fc54f2-9946-4e7d-ab95-e3139dfb7760">

**Comment by toolmantim** [comment]
I can dig into these.

What are some use cases/scenarios for them wanting to remove embeddings?

**Comment by toolmantim** [comment]
@taylorsperry yep, it would change to indexing

**Comment by toolmantim** [comment]
> "As a user who wants to generate embeddings for a project, but the project would exceed my embeddings quota, I see that I cannot generate embeddings for the project and an explanation for why."

@taylorsperry I like the words you suggested: "Generating embeddings for this repository would exceed your rate limit." — is "rate limit" the right word to be using for quota/usage though? @chenkc805 what words are we using on the PLG side?

@dominiccooney will there need to be a "Calculating estimated embeddings size…" stage with a spinner etc that needs to happen?

**Comment by chenkc805** [comment]
We should market it not as a rate limit (ie. implies it resets after some period of time), but instead as a lifetime quota. So something like:
- Generating embeddings for this repository would exceed your total embeddings quota of {200mb|1 GB}

**Comment by toolmantim** [comment]
For the design, let's start by adding usage estimates in a paragraph of text here:

![image](https://github.com/sourcegraph/cody/assets/153/069c3110-2133-435a-b279-7fc4bde5fc34)

**Comment by toolmantim** [comment]
I accidentally closed the ticket. But I think this is probably good to close yeah @taylorsperr?
