### ISSUE TITLE
App users will be automatically signed in through dotcom (instead of app) for GA

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1966]
When app users download the app, the first thing they have to do to get setup is create/login to their Sourcegraph.com account. However, when connecting the app to VS Code, they login to their VS Code extension "through the app." 

As part of the work to sunset the app, we have the ability to automatically log the user into their dotcom account instead of their app account in VS Code. This feels like the most seamless experience and nothing changes about the user's dotcom account, but we should include an indication that the login method has been updated.

**Comment by dominiccooney** [comment]
Technical idea here is look at the origin we're signed in to. If it looks like App (localhost:3900 IIRC) then flip to sourcegraph.com instead, automatically.

Question for @toolmantim is whether we should do this silently, or give some notice that this is happening. My $0.02 is that we're *probably* talking to App, and App is talking to dotcom, so there's no harm in silently making this switch.

**Comment by toolmantim** [comment]
Here's the UX outline for how this should work, taking into account embeddings importing too:

1. Cody for VS Code updates behind the scenes for the user
1. We silently migrate the auth to dotcom (ensuring Cody App is removed from account switcher history etc too)
1. We send a progress notification (https://code.visualstudio.com/api/ux-guidelines/notifications#progress-notification) with the words "Importing Cody App embeddings…". This closes automatically on completion.
1. After embeddings import completes (or if Cody App has no embeddings — doesn't matter if this is near-immediate speed wise), we send an information notification:

> Cody App is deprecated and your embeddings have been successfully imported into VS Code. You can now safely move Cody App to the bin.
> [Move to Bin] [Learn More]"

The "Move to Bin" button would be primary color, and would be a nice-to-have. "Learn More" would open a docs URL.

How's that sound @dominiccooney @taylorsperry?

**Comment by taylorsperry** [comment]
That sounds fantastic. Thank you, @toolmantim and @dominiccooney !

**Comment by dominiccooney** [comment]
I have #2099 for this.

It does not do the toasting to delete App yet.

Adds local embeddings support for classic sidebar chats, although the context status indicator says embeddings are not found. I assume it is not worth wiring this up at this point.

There's no App index "import" step or UI, we are just reading App's files directly. I can work on this but error reporting, restarting failed index jobs, etc. is probably more important.

**Comment by dominiccooney** [comment]
@taylorsperry , @kalanchan we will automatically log people into dotcom where possible. Worst case they will see the login panel and have to hit login again.

Can we move the toast for removing App to post-GA?
