### ISSUE TITLE
Add Graph and Search to simplified chat context and display status

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#1970]
Simplified chat does not have graph and search as context sources. We need to add them back, and make them display status in the Enhanced Context settings widget.

Blocked on #1897.

**Comment by taylorsperry** [comment]
This will just be Search (not Graph) based on [this thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1701702901721609?thread_ts=1701684757.160339&cid=C05AGQYD528), right @dominiccooney ?
