### ISSUE TITLE
bug: `[_${path}_]` should be hidden from the user

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1975]
### Version

main (2ecded4fd9ae240edbc3233f545b32205e30abb3)

### Describe the bug

If a user types the following question:

<img width="382" alt="Screenshot 2023-11-29 at 3 37 30 pm" src="https://github.com/sourcegraph/cody/assets/153/647816f7-4a7b-4319-8a6e-f6d881cff9d1">

We display the internal representation in the treeview and tab labels:

* <img width="310" alt="Screenshot 2023-11-29 at 3 37 27 pm" src="https://github.com/sourcegraph/cody/assets/153/579aa749-ca08-4072-aae3-96ea58c1034d">
* <img width="222" alt="Screenshot 2023-11-29 at 3 37 19 pm" src="https://github.com/sourcegraph/cody/assets/153/6df4b7f5-5672-4e46-9859-042e57715cfc">

### Expected behavior

The `[_` and `_]` parts are never shown to the user

**Comment by abeatrix** [comment]
addressed in https://github.com/sourcegraph/cody/pull/1967
