### ISSUE TITLE
Autocomplete: figure out why starcoder generates syntactically incorrect if conditions

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/cody#1983]
Tested on starcoder-16b. It consistently completes `if █` string incorrectly without parentheses around a condition:

```ts
if featureFlagProvider.enabled {
```

This behavior is so consistent that we might want to handle it on the client side manually.

**Comment by philipp-spiess** [comment]
@valerybugakov Can you log one of the exact prompt this happens? I tried to reproduce it via the Fireworks API playground directly where the issue does not seem to occur 🤔 

<img width="975" alt="Screenshot 2023-11-29 at 12 54 17" src="https://github.com/sourcegraph/cody/assets/458591/2645f575-7db8-4338-982f-64a8e6cf5d90">

The prompt I used for this test was only:


```
<filename>test.ts <fim_prefix>function myFunction(flag: boolean) {   if <fim_suffix>} } <fim_middle>
```

**Comment by philipp-spiess** [comment]
(It also works if I remove the space between `if` and `<fim_suffix>`

**Comment by valerybugakov** [comment]
I got an even worse variation of this just now: 
<img width="768" alt="Screenshot 2023-11-29 at 20 07 32" src="https://github.com/sourcegraph/cody/assets/3846380/0f4d26fe-4af5-4078-9cc1-0c21c96c6e26">

**Comment by philipp-spiess** [comment]
@valerybugakov Possible, yeah. The prompt is also very short, maybe it doesn't know it's in a TS file example yet 😓

**Comment by valerybugakov** [comment]
I had the same behavior in bigger TS files. I am going to monitor it and share examples here.

**Comment by taylorsperry** [comment]
@valerybugakov and @philipp-spiess can you help me understand what the user impact is here?

**Comment by valerybugakov** [comment]
I set the priority to P2 because this behavior is inconsistent. Sometimes StarCoder generates incorrect syntax for if statements in Javascript and Typescript:

```ts
// StarCoder completion
if value && anotherValue {

// Valid syntax
if (value && anotherValue) {
```
