### ISSUE TITLE
When I upgrade to Cody Pro or downgrade to Cody Free, the IDE should reflect this change ASAP

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1992]
Steps to repro:
- Start on Cody Free
- Open VS Code with Cody installed
- Click "Upgrade to Pro" in the bottom right settings area
- Navigate to /cody/subscription
- Upgrade to Cody Pro
- Go back to VS Code
- 🐛 The user sees no indication that they've upgraded, and the "Upgrade" button is still there.
  - **Expected behavior:** The "Upgrade" button should be gone, and the user should see a chat message that tells them they're upgraded. Design for the message is here: https://www.figma.com/file/f7bzmpYrwalyYOQJcWLRTP?node-id=73:522&mode=design#622905778

**Comment by chenkc805** [comment]
Adding @kalanchan @taylorsperry since I think we need support on the clients teams to fix this. CC: @thenamankumar to support from the PLG side

**Comment by kalanchan** [comment]
Will get back to you once I have a game plan figured out with the clients

**Comment by thenamankumar** [comment]
What is the status on this @kalanchan ?

**Comment by vdavid** [comment]
@kalanchan, I think you said this was done. Could you close it if that's the case?

**Comment by chenkc805** [comment]
@kalanchan looks like this was merged 3 days ago, can we close this out?

**Comment by kalanchan** [comment]
hahahah thanks for TPMing me guys! I appreciate it :) 

yes closed by #2049 - if you upgrade/downgrade in web, it will reflect the change in VSC. If you notice a bug feel free to re-open and tag me

**Comment by DataDog3331** [comment]
This issue actually persists. i was using cody free version and hot rate limits. i followed the upgrade button to web to purchase a plan, completed it but im still stuck in vs code where it says "UNABLE TO SEND MESSAGE You've used all of your chat messages and commands for today. Learn More Usage will reset in 28 days (08/28/2024 at 9:36 AM)"

My question is, how to let cody vs extension know i have purchased a plan?
