### ISSUE TITLE
There are no images in the new onboarding flow

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1993]
There's no images in the onboarding flow here, when there should be. https://www.figma.com/file/FMSdn1oKccJRHQPgf7053o?node-id=2598:2845&mode=design#631089734

<img width="920" alt="Screenshot 2023-11-29 at 11 06 46 AM" src="https://github.com/sourcegraph/cody/assets/3654603/90164295-de0a-418e-a390-4794218f890a">

**Comment by danielmarquespt** [comment]
These are designed, I'll push the code today :)

**Comment by thenamankumar** [comment]
@danielmarquespt, the images are still not there for JetBrains and other IDEs. For VS Code, they are added as part of this PR: https://github.com/sourcegraph/sourcegraph/pull/58788

**Comment by danielmarquespt** [comment]
Noted. I have them locally: https://sourcegraph.slack.com/archives/C05SZB829D0/p1701877986525129

Going to merge them soon. Waiting to include NeoVim in the same PR

**Comment by thenamankumar** [comment]
@danielmarquespt this is done right?

**Comment by chenkc805** [comment]
I checked this on prod, works correctly. I have some very small nits that we can fix after GA, but overall LGTM
