### ISSUE TITLE
[EZ UI] Fix links on the IDE section of the dashboard

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1994]
Currently only the VS Code "Install" and "How to use" links work

**Fixes**:
Here's where the JetBrains links should take the user:
- "Install": https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search
- "How to use": https://docs.sourcegraph.com/cody/overview/install-jetbrains#verifying-the-installation

Here's where the Neovim links should take the user:
- "Install and setup guide": https://docs.sourcegraph.com/cody/overview/install-neovim

Emacs:
- Remove the links, Emacs should just have a "Coming soon" badge attached to it.

Side note:
- @danielmarquespt instead of having "How to use" for VS Code pop a modal, should we just open a new tab and take them to the VS Code docs? https://docs.sourcegraph.com/cody/overview/install-vscode#verifying-the-installation

**Comment by danielmarquespt** [comment]
Yes, the how to use should link to the documentation. That was not the initial plan, but in fact there is a lot more detail and information in the proper docs

> Also those links and pop-ups are still missing for all the IDEs except VS Code & Jet Brains.

All of the other IDEs will use the JetBrains insctructions (they are the same) but I haven't linked everything properly yet.

NeoVim is still missing. Working on it

**Comment by chenkc805** [comment]
@danielmarquespt I already have Neovim's copy and link in my original comment at the top, so I think we should be good to go. All JetBrains links should share the same links as defined above as well. 

@thenamankumar you're clear to continue building this, you should be unblocked.

**Comment by danielmarquespt** [comment]
Closed by: https://github.com/sourcegraph/sourcegraph/pull/58901
