### ISSUE TITLE
PRD: bug: Visible keyboard shortcuts for core chat and editing flows

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#2009]
### Designs

* [Figma: Overall layout w/ keyboard shortcuts](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=538-110741&mode=design&t=p3hjW7ZKlohimeZl-4)
* [Figma: Specific keyboard shortcut elements](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1028-31608&mode=design&t=p3hjW7ZKlohimeZl-4)
* [Figma: Editor ghost text](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1161-33280&mode=design&t=p3hjW7ZKlohimeZl-4)

### Description:

As a user I want to be able to use keyboard shortcuts to perform key actions. To do this the keyboard shortcuts need to be supported and to be visible.

The core actions we want to support are:
  - Returning to a chat when editing code (i.e. refocusing the message input of the most recently active visible chat)
  - Starting a new chat
  - Starting a code edit
  - Accepting, retrying and undoing a code edit

### Objectives:

- Allow the user to perform key actions without using the mouse
- Allow the user to build expertise and speed

### Acceptance Criteria:

Must have:
- Keyboard shortcuts should be visible on the command treeview, code lenses, and chat message inputs
- Platform specific keys are displayed (following how VS Code displays them across platforms)

Nice to have:
- Modifying or removing keybindings should be reflected in the UI (would require reading the users’s keybindings.json file)

### Design Tasks:

```[tasklist]
### Design Tasks
- [x] Code lenses
- [x] Command treeview
- [x] Chat message inputs
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] TODO
```

### Related Docs:

How VS Code ouputs the modifier characters per-platform:

| Mac | Windows |
| - | - |
| <img width="629" alt="Screenshot 2023-11-30 at 11 07 32 pm" src="https://github.com/sourcegraph/cody/assets/153/f45c6aaa-abac-497d-8064-e080e618b8d7"> | <img width="629" alt="Screenshot 2023-11-30 at 11 06 45 pm" src="https://github.com/sourcegraph/cody/assets/153/3693db99-89b2-46a9-8a14-94d89238f178"> |

Design (see [Figma](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1028-31608&mode=design&t=qRJhOmJ70FKN2M3g-4)) for latest and comments:

![image](https://github.com/sourcegraph/cody/assets/153/b1fbd167-aa15-4451-b0ce-0384cfe9c61b)

**Comment by taylorsperry** [comment]
I love this, thank you, @toolmantim! I'm marking as P0 since I think this would be amazing to ship for GA (and I expect it's not too, too heavy a lift?), but we should bump to P1 if we get bug reports that are more important to fix. cc @kalanchan

**Comment by toolmantim** [comment]
This was partially improved in the new welcome message content and styles in #2298, but we should still do this.

**Comment by taylorsperry** [comment]
@kalanchan I'd love to see this get prioritized in the next eng sprint. What's the best way for me to get it on the board?

**Comment by kalanchan** [comment]
we'll do a grooming session with Beyang to get this on the board!

**Comment by toolmantim** [comment]
I've updated the above description with clearer Figma links, and designs for ghost text Edit discoverability too @umpox @beyang

**Comment by beyang** [comment]
Closing, please reopen if still an issue
