### ISSUE TITLE
Don't save the onboarding state past the Work/Personal step

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/cody#2012]
Most likely the user will be getting out of the browser when they install the extension. If they go back to the page for some reason, the onboarding window should not be open because by then is not that helpful. And we also include a list of other ides and instructions right on the dashboard anyway.

Example:
https://www.loom.com/share/25fa1598daa64ced95c93c730556e4b1?sid=57536b4d-f014-4c80-aea2-80e612cbed90

**Comment by vdavid** [comment]
- Closed by https://github.com/sourcegraph/sourcegraph/pull/58828
