### ISSUE TITLE
bug: enhanced context selector toggles off after initial chat

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#2026]
### Version

v0.17.1701356806

### Describe the bug

On first chat when Enhanced Context Selector is turned on, relevant context is fetched and it shows the files used. On a followup question, the Enhanced Context Selector gets toggled off automatically and defaults to whatever the user has selected.

https://github.com/sourcegraph/cody/assets/51868853/a4ef5eb6-63a8-4e7d-bf77-a69444e7b74b

### Expected behavior

I expected the enhanced context selector to stay ON until I toggle it off

**Comment by toolmantim** [comment]
Duplicate of #1971

**Comment by kalanchan** [comment]
@toolmantim nice catch, thanks!
