### ISSUE TITLE
Local *and* remote embeddings appear in Enhanced Context Selector with "simplified" chats

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#2028]
This is kind of the dual of #2027, where "non-simplified" chats show too few context sources in the Enhanced Context Selector, "simplified" chats show a promotion to set up local embeddings when remote embeddings are available:

![Screenshot 2023-12-01 at 10 23 48](https://github.com/sourcegraph/cody/assets/55120/ae36728b-f1e3-492c-8557-a67ca705936a)

This could actually be kind of a feature, because if you fork something and change it, you might want to index it. But the product design says only show one, so that's what we should do.

Note: "Restored" chats do show context providers there. So there's an issue where they're dropped out at some early point.

**Comment by dominiccooney** [comment]
ff9e1c6107048415ccf1cfba4f99bb9180acfe1f mitigated this to a degree. If you set up local embeddings, and later dotcom adds remote embeddings, I think you will still see and use two sources of embeddings. But this is probably fine for GA.

**Comment by toolmantim** [comment]
I think to start, let's always prefer the local embeddings and ignore any dotcom embeddings if they both exist.

Agreed it could be a feature in a future iteration… though I think they'd be grouped under a single "Embeddings" heading design-wise.

**Comment by dominiccooney** [comment]
Remote embeddings are gone, so this is not an issue any more.
