### ISSUE TITLE
bug: reviving new chat panel loses chat model selector

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#2029]
### Version

main (c48e141768c669aa16dd23c4d27c764806b7bbe8)

### Describe the bug

When you reload a new chat, the chat model selector is not visible:

https://github.com/sourcegraph/cody/assets/153/57bc1caf-a590-4b18-b188-04302f699268

### Expected behavior

The chat model selector is still there after reload

**Comment by abeatrix** [comment]
I can't reproduce the issue on 0.16.2 anymore.

@kalanchan Can you give it a try and let me know if you are able to reproduce the issue?


https://github.com/sourcegraph/cody/assets/68532117/f47d4eff-2f0c-48ed-a16e-3253cc312ac1

**Comment by kalanchan** [comment]
Also can't reproduce in v0.16.2 or v0.17.1701443218

https://github.com/sourcegraph/cody/assets/51868853/d61e7b7a-097b-49fc-aaeb-e3d4bdb92a87
