### ISSUE TITLE
Enhanced Context Selector sources empty when chat started with non-workspace file open

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#2032]
Loom demonstrating the issue: https://www.loom.com/share/78b8d65ec64e42059d7f03c405885bd2?sid=4fefc54d-d2c9-46b6-9439-82398b2fd1b5

This repro is from around 1b6459fa9247ca515e8d1a7af389ec92b7f342fe.

Repro steps:

0. `"cody.experimental.simpleChatContext"` should be *off.* This affects new, but "non-simplified" chat panels.
1. Open a repo with any kind of embeddings
2. Open the user settings JSON file (a non-workspace path)
3. Start a new chat (alternatively, restore a chat in this state)

Expected:
- See some embeddings context providers

Actual:
- See no context providers.
![Screenshot 2023-12-01 at 13 24 49](https://github.com/sourcegraph/cody/assets/55120/6e4e2b40-4868-4c64-8872-2ebc839dcf3e)

This is an issue because chatting there *will* pull context from embeddings.

**Comment by dominiccooney** [comment]
Note, simple chat context is now the default (5c9d1cd32b355b1e2897db6bac7a87f9c5955b9c) so the priority of this is low to none.

**Comment by toolmantim** [comment]
We've removed Simple Chat Context from the settings quickpick, so it's a completely hidden setting.

**Comment by dominiccooney** [comment]
Closing this; all chats are simplified chats now.
