### ISSUE TITLE
bug: Custom Commands papercuts

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2050]
### Version

v0.17.1701443218

### Describe the bug

Using the Custom Command builder, I ran into a few papercuts: 

#### New Custom Cody Command: Prompt
The builder tells me I can create up to five prompts for my custom command, but I don't know how to add more than one. If the QuickPick limitations are such that we can't add optional "substeps" (prompt 1, prompt 2, etc), then we should just update the instruction to say you can only use the builder to add one prompt, but you can add more in the JSON file. 

![Image](https://github.com/sourcegraph/cody/assets/43555476/fca58d06-7aca-48a1-8dc2-09c7ad937dd4)

#### New Custom Cody Command: Context Options
- I can't scroll to the right, and if I'm just experimenting with Custom Commands, "Codebase" feels like the one I'm most likely to try out. I can't scroll to the right here, to see more about what it means. 
- I think we should remove the checkbox next to "For accurate responses . . . " in include one below that says "All" 

![Image](https://github.com/sourcegraph/cody/assets/43555476/c3c42a5f-6926-4476-b150-438a55b4186a)

#### Back button? 
It doesn't [look](https://code.visualstudio.com/api/ux-guidelines/quick-picks) like the QuickPick allows for a back button, but I would love one if it's possible. My sense is that the QuickPicks are better suited to builders that are a little simpler than what we're trying to accomplish here, and we should rethink the UX we're including. I owe @toolmantim some product docs on that. 

### Expected behavior

Expected / desired behavior detailed above.

**Comment by abeatrix** [comment]
@taylorsperry @toolmantim is there any updated design for custom command that requires eng work?

**Comment by toolmantim** [comment]
@abeatrix in general, or based on the above? I don't think there's anything. The only actionable thing I can see is adding back button support to the builder (which is possible @taylorsperry) but I don't think it's a priority.
