### ISSUE TITLE
Ensure the autocomplete limits are showing up when on the Free tier

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2056]
Current behavior:
- I'm not seeing any autocomplete or chat/command limits for the Free tier (see 0 / 0) in screenshot
![Screenshot 2023-12-01 at 2 50 35 PM](https://github.com/sourcegraph/cody/assets/3654603/b5d3a2cd-cd4a-4f00-89ee-8238335d1533)

Expected behavior:
- 500 suggestions and 20 chat/command as the denominator for the limits for users in the Free tier.

**Comment by thenamankumar** [comment]
![Uploading CleanShot 2023-12-07 at 20.56.46@2x.png…]()
