### ISSUE TITLE
Cody autocomplete hanging and causing VS Code to freeze

### ISSUE THREAD

**Issue by AJKemps** [sourcegraph/cody#2063]
Sourcegraph version: 5.2.2
Reported by: https://github.com/sourcegraph/accounts/issues/6938

Steps to reproduce:

Here's a short clip showing the issue: https://hello.chorus.ai/listen?guid=2cc4306dddd84b84bc5bb6f1ca5f73da
And a clip showing no logging output: https://hello.chorus.ai/listen?guid=93fbdcdc0f8344458ed500735f6d8106
Here's a clip where we discuss the size of the repo he's working in: 

Worth noting that this user was in a relatively large repo with thousands of files, and the specific directory he was in had hundreds of files, and the file itself was about 1800 lines.

Expected behavior:
Cody VS Code extension doesn't hang and cause VS Code to freeze up.

Actual behavior:
Cody autocomplete hanging and causing VS Code to freeze.

**Comment by AJKemps** [comment]
This was the version before the 0.18.0 release. Unclear if the user is still seeing this issue on latest version, I'll follow up.

**Comment by philipp-spiess** [comment]
Wow this looks really bad, sorry about that. This is definitely not expected and we haven't heard this feedback before, either. 

We will need CPU traces to understand what's going on here and what is causing the computation. The only real "work" we do on keystrokes is the context retrieval and that has a lot of checks to ensure it doesn't go unbounded. Nevertheless, we can find this out more easily:

- Open the Autocomplete Trace View (cmd+shift+p)
- Trigger a completion
- Look at the "Context" field and the "duration" logged there.

To get CPU profiles is a bit more involved:

- VS Code needs to be started with the debug protocol. This means starting VS Code from the terminal and setting the ENV var `TSS_DEBUG=5859`
- Then, you can connect a NodeJs debugger to the port and start a CPU trace
- After that, trigger an autocomplete request that experiences the latency
- Once done, export the trace and post it here!
