### ISSUE TITLE
Fixups LLM output may be worse than cutting and pasting into chat

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#207]
Feedback from @beyang via @abeatrix is that Fixups may perform worse than cutting and pasting the same code into chat. There's a hard error "The amount of text selected exceeds Cody’s current capacity" which isn't true because the same thing *is* possible in chat.

Personally, I have noticed Fixups performs better earlier in files and in small files.

Both of these things indicate that the context we're grabbing surrounding the selection is too large. We should use less—maybe even none—and rely on context fetching to provide it.

**Comment by abeatrix** [comment]
We have addressed this with the changes we made in the past few sprints  👍
