### ISSUE TITLE
[EZ UI] Update copy in the upsell CTA

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2081]
Today's copy:
![Screenshot 2023-12-04 at 1 01 12 PM](https://github.com/sourcegraph/cody/assets/3654603/0195aa18-f155-4ad6-a503-76007bb5827c)

Revised copy:

- UPGRADE TO CODY PRO
- Second line:
  - You've used up your {limit} chat and commands for the month. Upgrade to Cody Pro for unlimited autocomplete suggestion and chat/command usage. 
- Buttons
  - Upgrade (link: /cody/subscription)
  - See plans (link: /cody/subscription)
- Your chat/commands usage will reset in X days.

**Comment by chenkc805** [comment]
@danielmarquespt can I get your feedback on this upsell? It looks a bit weird with so many different font sizes. 

CC: @kalanchan @vdavid @thenamankumar

**Comment by kalanchan** [comment]
I like the suggestion of changing "Learn More" to "See Plans". Let me know the decision and i'll get that updated

**Comment by toolmantim** [comment]
Is this for VS Code @kalanchan? We already have designs for this as part of https://github.com/sourcegraph/cody/issues/1576 (https://www.figma.com/file/f7bzmpYrwalyYOQJcWLRTP/Account-upgrading-from-VS-Code?type=design&node-id=7-37642&mode=design&t=Uq0zNjZZIu0cksAQ-4) it just needs engineering assistance.

If you want to make any changes to that design (which I'm hoping to do the engineering for myself this week), could you drop comments on the Figma?

**Comment by chenkc805** [comment]
Yup looks like it is. Thanks @thenamankumar
