### ISSUE TITLE
Add docs links into the Enhanced Context Status dialog

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#2090]
Add the links removed in #2075 back once these docs changes land:
- https://github.com/sourcegraph/sourcegraph/pull/58761
- https://github.com/sourcegraph/sourcegraph/pull/58288
- https://github.com/sourcegraph/sourcegraph/pull/58358

Note, local embeddings may not support `.cody/.ignore` for Dec GA and the wording should be sensitive to that to not create a misleading impression.

**Comment by toolmantim** [comment]
We added the docs link in there, but not for Cody Ignore. That will need to be done as part of that feature, but I'll close this out.
