### ISSUE TITLE
bug: Context selector overflows

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/cody#2094]
### Version

v0.17.1701702451

### Describe the bug

When VSCode is half the screen size of my 16" MBP, this UI overflows.

![Screenshot 2023-12-05 at 05 28 09@2x](https://github.com/sourcegraph/cody/assets/19534377/72b7b427-2ebb-4e42-b209-fdafac9b2b59)

### Expected behavior

It does not overflow.

**Comment by kalanchan** [comment]
hey we actually work on bugs here @eseliger 😄 

closed by https://github.com/sourcegraph/cody/pull/2102
