### ISSUE TITLE
bug: Thumbs-up state not persisted

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/cody#2095]
### Version

v0.17.1701702451

### Describe the bug

After reloading the vscode window, I can +1 a response again, the state is not persisted.
That makes me wonder if it was actually ever submitted.

![Screenshot 2023-12-05 at 05 32 49@2x](https://github.com/sourcegraph/cody/assets/19534377/bdd2cd8f-2de6-4471-a365-0e5c4899572f)

### Expected behavior

I expected that rating to be persisted.

**Comment by kalanchan** [comment]
closing for now, if it surfaces again please re-open!
