### ISSUE TITLE
bug: /doc command hijacks scroll when code is in view

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#2101]
### Version

main (18afbe650fe052bfc3a22100d3cedd33f0d22b7e)

### Describe the bug

When you execute the `/doc` command it scrolls your editor, first when it's run and then again afterwards, even if the code is visible:

https://github.com/sourcegraph/cody/assets/153/46c907a4-b91c-4d52-9ba5-34dddac3d685

### Expected behavior

* No scroll occurs if the top of the edit range is within view
* If scroll is triggered, it needs to be the line before the range so that the codelens is in the scrolled view

**Comment by taylorsperry** [comment]
Marking as P1. We should fix, but I don't think it's a GA blocker.
