### ISSUE TITLE
Update Edit Code command rate limit handling

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#2123]
After hitting the rate limit, users should be displayed an error notification that prompts them to follow PLG onboarding flows. 

This affects all edit related commands (Document, Edit)

https://github.com/sourcegraph/cody/assets/51868853/d2bab807-aba9-4071-99ba-056fe7faec9c

**Comment by toolmantim** [comment]
"Applying Edits Failed" → "Quota Exceeded. Upgrade to Cody Pro" (link to Cody Pro upgrade URL)

**Comment by toolmantim** [comment]
I ended up implementing a slightly nicer experience in #2201, that shows the rate limit error message and reset time in a confirmation, and gives them the option to "See Plans" if they're not quite ready to click "Upgrade"
