### ISSUE TITLE
Generate Unit Tests command never works the 1st time

### ISSUE THREAD

**Issue by sqs** [sourcegraph/cody#2125]
Version v0.17.1701788840 on VS Code

Repro:

1. Select an entire code file
2. Right click -> Cody -> Generate Unit Tests
3. See error
4. Repeat steps 1 and 2, and it works the 2nd time (I can repro this consistently)

![image](https://github.com/sourcegraph/cody/assets/1976/30d77997-3067-4966-81ad-56206267cc83)

**Comment by beyang** [comment]
@sqs are you still able to repro on the latest Cody? I cannot: https://www.loom.com/share/bdffab817941451b9ef37d1acc2414d1?sid=6a5112b7-eada-4759-920f-40193a0c6f81

I suspect some of the recent changes to address race conditions on command startup may have fixed this?
