### ISSUE TITLE
bug: New Search UI is missing

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/cody#2128]
### Version

v0.17.1701788840

### Describe the bug

I dragged the Search UI to the right sidebar and when I closed it I could no longer see it when enabled.

<img width="526" alt="Image 2023-12-05 at 1 17 41 PM" src="https://github.com/sourcegraph/cody/assets/398230/a01ffe82-d1f6-4b48-93ff-a752ca085022">

### Expected behavior

When "New Search UI" is Enabled, it should show up in the left sidebar.

<img width="710" alt="Image 2023-12-05 at 3 39 53 PM png" src="https://github.com/sourcegraph/cody/assets/398230/cfa628af-4f17-415b-8052-07b6b943c9ba">

**Comment by taylorsperry** [comment]
Ah, so the bug is that when you drag the Search panel to the right, it no longer has the "Search (Experimental)" header? That's a good catch. 

<img width="1437" alt="Screenshot 2023-12-05 at 5 52 30 PM" src="https://github.com/sourcegraph/cody/assets/43555476/3376ea61-11a7-49e8-ad6b-bf1056078e66">

**Comment by toolmantim** [comment]
These are both issues with the way VS Code handles panels, and I'm not sure there's much we can do about them (there's no APIs to help users reset this situation, once they've customised it)

**Comment by taylorsperry** [comment]
I wonder if we should (can?) prevent them from customizing it, in that case? I'd hate for someone to try to customize the search configuration, X out of it, and then never be able to search again!

**Comment by taylorsperry** [comment]
I actually can't repro Justin's bug now that I'm on v0.18, but I do see that I'm having a hard time moving the search (or any of the other panels around). [Loom.](https://www.loom.com/share/20d4f8391e7942fe96a5e28693b24130). P2.

**Comment by toolmantim** [comment]
Sadly I don’t think there’s anything we can do here, these are VS Code usability issues that apply to all panes/views in VS Code. We could look at reporting them (and contributing fixes) to the upstream VS Code repository.
