### ISSUE TITLE
Cody readily hallucinates Sourcegraph App is available for Windows

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#213]
- **Sourcegraph version:** VScody 0.1.3

#### Steps to reproduce:

![image](https://github.com/sourcegraph/sourcegraph/assets/55120/d61c6fc3-39fb-4f2d-af5b-17e89d20b31b)

1. Ask Cody whether Sourcegraph App is available for Windows.

#### Expected behavior:

Cody says something apologetic about it not being available with a link to an email list or something.

Maybe we should not promote App when running on Windows.

#### Actual behavior:

Cody says it is available without any context.

**Comment by jdorfman** [comment]
This is now fixed 
<img width="327" alt="Image 2023-07-13 at 2 03 21 PM png" src="https://github.com/sourcegraph/cody/assets/398230/3da447d2-b3e9-48e6-922e-7c39f6ba78e6">
