### ISSUE TITLE
bug: Cody users losing auth in VS Code

### ISSUE THREAD

**Issue by AJKemps** [sourcegraph/cody#2131]
### Version

unknown but presumably most recent one because these users just downloaded the extension

### Describe the bug
![Screenshot 2023-12-05 at 7 22 49 PM](https://github.com/sourcegraph/cody/assets/62579992/3bbf9bf1-f219-4389-ba8f-512244fd9bed)

### Expected behavior

Cody extension user auth is persisted if e.g. VS Code updates overnight.

### Additional context

Reported by: https://github.com/sourcegraph/accounts/issues/6938

**Comment by dominiccooney** [comment]
Would be great to have the VSCode version and Cody Extension version that is causing this to help track this down.

**Comment by abeatrix** [comment]
context: https://sourcegraph.slack.com/archives/C05AGQYD528/p1701905684534839?thread_ts=1701822479.971739&cid=C05AGQYD528
