### ISSUE TITLE
bug: Autocomplete rate limits display inconsistent error messages

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#2134]
### Version

v0.17.1701788840

### Describe the bug

This bug has 2 parts to it:
1. Using the rate limited demo accounts, by design the headers `retry-after` return back the same time as when the request was made. This causes the error messages to constantly be displayed in the quick pick view
2. Also using the rate limited demo account, if you hard code the retry time to a regular interval (like 1 day after), the error message does not display anymore after dismissing it once. 

### Expected behavior

Rate limit error message to only display once, and to display again even after dismissed

**Comment by philipp-spiess** [comment]
> Using the rate limited demo accounts, by design the headers retry-after return back the same time as when the request was made. This causes the error messages to constantly be displayed in the quick pick view


Can you clarify what exactly you mean by this?

> Also using the rate limited demo account, if you hard code the retry time to a regular interval (like 1 day after), the error message does not display anymore after dismissing it once.

If we don't do that, it will mean that a user will constantly see a warning color in their IDE when they code. Is this a better UX?

**Comment by toolmantim** [comment]
I think keeping it as the warning color is probably ideal. Same as other autocompletion AI extensions when they're disabled.

**Comment by toolmantim** [comment]
I think by "This causes the error messages to constantly be displayed in the quick pick view" @kalanchan is referring to the following (from the video in https://github.com/sourcegraph/cody/pull/2135):

<img width="388" alt="Screenshot 2023-12-06 at 9 25 20 pm" src="https://github.com/sourcegraph/cody/assets/153/faedc768-ec09-4cb4-b6eb-6b23961ff4be">

**Comment by philipp-spiess** [comment]
Oh I didn't see the PR! Looking. Thanks @toolmantim :)

**Comment by taylorsperry** [comment]
Marking as P0 (since this is part of the PLG flow) and "In Progress" given @kalanchan 's PR.
