### ISSUE TITLE
bug: Highlight code and asking questions doesn’t work with chat with simplified chat

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#2139]
### Version

tested on main - commit d2ac7f2e

### Describe the bug

Highlight code and asking question doesn’t work with chat, gave an unrelated answer to the code snippet highlighted

### Expected behavior

Use the highlighted code as context, but instead gave a random answer

### Additional context

https://github.com/sourcegraph/cody/assets/51868853/55a74c70-332b-4b84-961d-c14bfaaface0

**Comment by beyang** [comment]
This is by design. The contract of the new chat is that all context must be explicitly @-mentioned if you don't have "enhanced context" checked.
