### ISSUE TITLE
bug: command preamble leak on simplified chat

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#2140]
### Version

tested on main - commit d2ac7f2e

### Describe the bug

Highlight code and using a non edit command (explain, explain, smell, or test) causes a preamble leak

### Expected behavior

use the highlighted code as context and hides the preamble used for the response

### Additional context

https://github.com/sourcegraph/cody/assets/51868853/bd41aec4-d3a1-46e3-abc4-ae0e7dc6a015

**Comment by philipp-spiess** [comment]
My 2ct: I personally like this. Much less magic and it seems like I can even go in and update the prompt to fit to my problem even better.
