### ISSUE TITLE
bug: active chats block new chats being started (simplified chat)

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#2150]
### Version

main (377bfbb54d3226b8b18e8f1350322a2e1d6455bb)

### Describe the bug

When you start a new chat, type a message (or run a command) and then try to start a new one, you're prevented from creating a new chat:

https://github.com/sourcegraph/cody/assets/153/521a8c48-b927-4081-875f-bfeb92c4be3e

### Expected behavior

A new chat is created

**Comment by kalanchan** [comment]
closed by #2171
