### ISSUE TITLE
bug: Switch Search from Experimental -> Beta

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2162]
### Version

v0.18

### Describe the bug

Not really a bug, just something we need to update before GA. This "(Experimental)" should become "(Beta)". 

![Image](https://github.com/sourcegraph/cody/assets/43555476/2e06286c-a6be-453b-b3c0-5b246ecff2c0)

### Expected behavior

Switch to Beta

**Comment by taylorsperry** [comment]
Is this closed? I'm still seeing "Experimental" in `v0.19.1702409542`

**Comment by toolmantim** [comment]
Good catch, this one got accidentally closed
