### ISSUE TITLE
[Fast Follow] Update Sourcegraph.com nav bar and URL redirect cleanup for logged in and logged out users

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2163]
These requirements only refer to the nav bar on sourcegraph.com/search and similar web pages. 

**Both logged in and logged out requirements**
- remove "Install Cody Locally" for both logged in and logged out users  

**Logged in Requirements:**
- redirect logged in users from `/get-cody` with `/cody/manage`
- when a user clicks "Cody" in the nav, take them to `/cody/manage`
- There's a dropdown in the "Cody" nav bar, and when clicked it opens a dropdown with 2 URLs (see screenshot below):
  - Dashboard[/cody/manage]
  - Web Chat[/cody/chat]

**Logged out Requirements**  
- if the user is not logged in on /cody/manage, redirect them to https://sourcegraph.com/sign-in?returnTo=/cody/manage
- if the user is not logged in on /cody/subscription, redirect them to https://sourcegraph.com/sign-in?returnTo=/cody/subscription
- When a user clicks "Cody" in the nav bar, they should get taken to sourcegraph.com/cody/chat 
- There's no dropdown next to "Cody" in the nav bar for logged out users.

**Comment by thenamankumar** [comment]
The log out part is fixed as part of https://github.com/sourcegraph/sourcegraph/pull/58828

The nav bar changes will be addressed separately soon.

**Comment by chenkc805** [comment]
Nice looks good
