### ISSUE TITLE
bug: File not in context when it is in context

### ISSUE THREAD

**Issue by AJKemps** [sourcegraph/cody#2164]
### Version

0.18.0

### Describe the bug

User tags a file that is in context but Cody responds by saying it can't see the file.

However, if you look at the files Cody searched through to generate its response, the tagged file is included in context, so the user thinks Cody does in fact have access to the file.

### Expected behavior

If a file is included in the list of files Cody browsed before generating a response, the user expects that Cody has access to the file.

### Additional context
Reported by: https://github.com/sourcegraph/accounts/issues/6938
_No response_

**Comment by kalanchan** [comment]
@AJKemps we'll look into this once the version is included. It looks like the customer is on a older version from the last image
