### ISSUE TITLE
bug: pre-instruction config not working in simplified chat

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#2165]
pre-instruction config does not work in simplified chat

**Comment by csells** [comment]
what's the user impact here? should this be a P0?

**Comment by taylorsperry** [comment]
Existing users who have already been using this feature will have a worse experience (the feature no longer works) and new users will expect the feature to work and it won't. P0. @toolmantim is working on it.

**Comment by taylorsperry** [comment]
I was testing this and tried adding the "pre-instruction" to "Respond to chat prompts in Spanish." Cody was not responding in Spanish, so I deleted the pre-instruction. However, now when I run commands, I'm seeing responses in Spanish. 

Triggering the `/doc` command from the command palette: 
![Image](https://github.com/sourcegraph/cody/assets/43555476/268846d4-b83b-489c-aa6d-327439c09d7d)

Triggering the `/edit` command from the command palette (with no instructions):
![Image](https://github.com/sourcegraph/cody/assets/43555476/8ad25c4b-249b-4140-a63e-f19fa8e214d1)

Pre-instruction setting is empty: 
![Image](https://github.com/sourcegraph/cody/assets/43555476/1293d1ae-3c54-4ea6-8b30-ca23edba6354)

**Comment by toolmantim** [comment]
I would consider that a bug — the setting is a chat pre-instruction, but it's being applied to non-chat things. Either we need to make it more global, or we introduce a 'cody.edit.preInstruction' too.

There could also be a bug where you're required to reload the window to have it take effect on commands — could you check @taylorsperry if reloading the window stops it?
