### ISSUE TITLE
Simple chat: Cannot add a user message after a user message

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#2179]
### Version

latest

### Describe the bug

- Open a new chat window
- Close all editor buffers
- type `/test`
- type `/test `again
- Observe an error being rendered: `command custom-prompt failed: Error: Cannot add a user message after a user message`

### Expected behavior

- I can not insert a text when there is no LLM reply yet

**Comment by deepak2431** [comment]
@philipp-spiess I tried to reproduce this issue to work on a fix but cannot reproduce it. I am on the latest version of Cody.

**Comment by csells** [comment]
@philipp-spiess can you confirm that this repros on the latest version of Cody?

**Comment by taylorsperry** [comment]
I can't repro either. Appears to be fixed.

**Comment by philipp-spiess** [comment]
Yep, sorry everyone, this seems fixed 🙏

**Comment by philipp-spiess** [comment]
@chenkc805 also ran into this: https://sourcegraph.slack.com/archives/C05AGQYD528/p1702409943265599

Perhaps there is a race condition somewhere?
