### ISSUE TITLE
bug: `replace` mode on custom commands not working as expected

### ISSUE THREAD

**Issue by joaotextor** [sourcegraph/cody#2186]
### Version

0.18.1

### Describe the bug

I have created the following custom command:

```
{
  "commands": {
    "jsdocs": {
      "prompt": "Generate JSDocs documentation for this code",
      "mode": "replace",
      "context": {
        "codebase": false,
        "selection": true
      },
      "description": "Generate JSDocs documentation"
    }
  }
}
```
With it created, I select my code and then execute this custom command by pressing Alt+C and selecting my `/jsdocs` slash name.
Cody opens a new window with the following information and nothing else happens:

![image](https://github.com/sourcegraph/cody/assets/57375819/40907376-de7d-4f47-b3b7-5eb8183294c7)

Above the selected code, the message 'Cody is working...' is not being shown.

I've tried replacing the "mode" to `insert` instead, and it works as expected. The message 'Cody is working...' appears and Cody duplicates the selected code with JSDocs correctly generated.

So, my conclusion is that the `replace` "mode" is bugged.

### Expected behavior

The expected behavior should be Cody replacing my selected code with the output code.

**Comment by abeatrix** [comment]
@joaotextor Thanks for reporting the issue. It looks like there was a mix-up in our docs as there is no `replace` mode. and the correct mode should be `edit` for your use case. I have created a PR to update our docs with the correct information: https://github.com/sourcegraph/sourcegraph/pull/59281

We apologize for the confusion caused.
