### ISSUE TITLE
bug: LLM choices not showing correctly

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2188]
### Version

v0.19.17019 . . . 

### Describe the bug

As a PLG user, I should be able to experiment with different LLMs (today, it should be any PLG user, for GA it should be only Pro users).

As an enterprise user, I should only see the LLM that's been selected by my administrator and NOT be able to update it. 

Here's what I'm seeing when connected to my dotcom account: 
![Image](https://github.com/sourcegraph/cody/assets/43555476/dde6d690-34b7-48be-9c85-fcb960549880)

Here's what I'm seeing when connected to my s2 (enterprise) account: 
![Image](https://github.com/sourcegraph/cody/assets/43555476/dc0c9878-1b84-467f-bdef-bf7be3e547ff)

### Expected behavior

Described above.

**Comment by kalanchan** [comment]
In the first image, could you try hitting new chat and see if it you can choose the LLMs? 

I think this is by design, the LLM gets locked in after initial chat

**Comment by taylorsperry** [comment]
Discussed in bug triage. Can confirm it's working as expected. Will open separate post-GA follow-up issues.
