### ISSUE TITLE
bug: unable to resume chat after stop generation using commands

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#2190]
### Version

main - commit a8d1fb32

### Describe the bug

Chat unable to resume after hitting "stop generation" using commands.  

https://github.com/sourcegraph/cody/assets/51868853/6a797033-d5aa-4514-80cb-c3a577199e81

### Expected behavior

Not expecting to resume previous conversation, but users should still be able to use chat after stop generation.

**Comment by csells** [comment]
this seems like a potential P0 to me, since it stops the user from using a portion of the product

**Comment by taylorsperry** [comment]
This is [working as expected](https://www.loom.com/share/6539171ebf3c439dbc32bd6574939704) on v0.19.1702328753. @kalanchan were you trying this before that release was cut?

**Comment by kalanchan** [comment]
thanks @taylorsperry it does look fixed! closing now
