### ISSUE TITLE
[Launch blocker] Ensure brand new signups are routed from sourcegraph.com to /cody/manage, and not /post-sign-up

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2192]
Steps to repro (see screenshots below):
- Signup with a brand new account (using k17390134@gmail.com from https://docs.google.com/spreadsheets/d/1V1t-AaR2f-BfX8dVM6xPrX789XF48etGmLHaP3Q9-T0/edit#gid=344236988) 
- After signup, get taken to /post-sign-up 🐛 BUG
- After filling out the /post-sign-up form, get redirected to /cody/manage

Expected behavior:
- Signup with a brand new account
- After signup, get taken to /cody/manage

![Screenshot 2023-12-07 at 3 57 46 PM](https://github.com/sourcegraph/cody/assets/3654603/198e5c32-daf1-4cc5-9d7a-c5b743cf1da0)
![Screenshot 2023-12-07 at 3 57 58 PM](https://github.com/sourcegraph/cody/assets/3654603/2f600b7a-6b1a-4023-8772-a6304175ec3e)
![Screenshot 2023-12-07 at 3 58 05 PM](https://github.com/sourcegraph/cody/assets/3654603/9a7deb81-d328-4386-8b02-01ada70f21b5)
![Screenshot 2023-12-07 at 3 58 17 PM](https://github.com/sourcegraph/cody/assets/3654603/55d9128e-17e0-40ed-9f3c-bc293b47067e)
![Screenshot 2023-12-07 at 3 58 22 PM](https://github.com/sourcegraph/cody/assets/3654603/a4b0ad92-016f-4704-89e5-2455e8b99ac1)
![Screenshot 2023-12-07 at 3 58 25 PM](https://github.com/sourcegraph/cody/assets/3654603/5e2de13d-9138-49ce-9bf4-2196c54f0e82)
![Screenshot 2023-12-07 at 3 58 32 PM](https://github.com/sourcegraph/cody/assets/3654603/f6c9ba09-a868-4a10-998d-939976ebd5fa)
![Screenshot 2023-12-07 at 3 58 37 PM](https://github.com/sourcegraph/cody/assets/3654603/8a7cee29-00d5-42da-b3cf-367889133a58)
![Screenshot 2023-12-07 at 3 58 51 PM](https://github.com/sourcegraph/cody/assets/3654603/df04e8c9-bfa5-46f1-b935-4f5abad1a6ca)

**Comment by thenamankumar** [comment]
@chenkc805 is this still an issue?

**Comment by chenkc805** [comment]
No can't repro. Closing
