### ISSUE TITLE
bug: Chat responding with "Claude" or "Anthropic" when talking with Cody

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2194]
### Version

v0.19.1701961592

### Describe the bug

https://sourcegraph.slack.com/archives/C05AGQYD528/p1701991061674619

### Expected behavior

Cody responds back as Cody, not as "Anthropic" or "Claude"

**Comment by csells** [comment]
related to #2172

**Comment by beyang** [comment]
Let's keep the limited preamble for now.
