### ISSUE TITLE
bug: hit up, resend @-tagged file does not include the file, highlight the link, etc.

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#2195]
### Version

Main a8d1fb32916d7f08ce26277cbbf0c186d5fb78f8

### Describe the bug

Repro steps:

1. Start a chat
2. @-mention a file, chat about it.
3. Hit up to bring up the same message again, chat that.

https://github.com/sourcegraph/cody/assets/55120/b7a09274-c584-4905-9da6-9dd628c3457b

### Expected behavior

Expected behavior: File is highlighted like a link, sent every time I mention it.

Actual behavior: File isn't highlighted like a link, I have just sent Cody the file *name.*

**Comment by dominiccooney** [comment]
Related, if I @ and "type through" the autocomplete, then there's no file included. I feel like this is a *good* thing, because sometimes you do really want to talk about things that start with that symbol. So probably the chat history needs to remember, not only what the text of the message is, but where did that text come from?

**Comment by csells** [comment]
shouldn't hitting Up and resubmitting a chat prompt do the same thing it did before?

**Comment by DanTup** [comment]
I started looking at this, but it wasn't as straight forward as I thought. I pushed the changes that I started to https://github.com/sourcegraph/cody/pull/2473 and would like some pointers/validation that this I'm going in the right direction. Thanks!
