### ISSUE TITLE
bug: Cody running out of memory and crashing VS Code

### ISSUE THREAD

**Issue by AJKemps** [sourcegraph/cody#2227]
### Version

0.18.1

### Describe the bug

User reported that he saw an error in VS Code saying that Cody had run out of memory, and then VS Code crashed with a Code 4.

User was also not able to open certain directories locally, when he tried he'd see a spinning wheel on the directory and then it would crash.

User was also not able to tag files within that directory in Cody.

User confirmed that when he uninstalled Cody, he was able to navigate to that directory without issue. When he reinstalled Cody and attempted to open the directory, it crashed again with a Code 4.

This is also a Perforce version control repo. The repo has less than 1GB of code in the version control system, but locally it is in the 30-50GB range because there are many binary files in the repo locally that are handled differently in their main version control system.

Here's a private video showing the user experience (user later confirmed that it was being caused by Cody after uninstalling the plugin): https://hello.chorus.ai/listen?guid=2d162ed9fe0443f6832c3bc3080ff90a

### Expected behavior

Cody does not run out of memory and cause VS Code to crash.

### Additional context
Reported by: https://github.com/sourcegraph/accounts/issues/6938
_No response_

**Comment by philipp-spiess** [comment]
I wonder if this is related to #2063. I posted some follow-up questions on how we can get some helpful data in that issue!

**Comment by toolmantim** [comment]
Maybe related to @valerybugakov’s experience https://sourcegraph.slack.com/archives/C05AGQYD528/p1702270234830099 with runaway `rg` processes.
