### ISSUE TITLE
Non-Stop Cody: Intelligent Selection

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#223]
We should use code intelligence to pick better boundaries for letting Cody edit stuff. Today we use selection plus ~50 lines.

**Comment by sqs** [comment]
Fixup does not work well when there is an empty selection.

For example, with Ctrl+Shift+V "add comments", this is what I get. Note the unhelpful addition plus the lack of newline.

![image](https://github.com/sourcegraph/cody/assets/1976/52ae103c-d34d-4010-ab38-54be20beef19)
