### ISSUE TITLE
[Launch blocker] [EZ UI] Update copy for Cody functionality

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2231]
**Autocomplete:**
- Let Cody automatically write code for you. Start writing a comment or a line of code and Cody will suggest the next few lines. 

**Chat:**
- Answer questions about programming topics generally or your codebase specifically with Cody chat.

**Commands:**
- Streamline your development process by using Cody commands to understand, improve, fix, document, and generate unit tests for your code.

**Feedback:**
- Feel free to join our Discord to leave feedback or ask questions about Cody. 

Today's copy:
![image (7)](https://github.com/sourcegraph/cody/assets/3654603/74af2723-0e4a-49b8-a25f-73f205dd24c4)

**Comment by danielmarquespt** [comment]
I can take this!

**Comment by danielmarquespt** [comment]
Closed by: https://github.com/sourcegraph/sourcegraph/pull/58901
