### ISSUE TITLE
bug: "Ask Cody to Fix" jumps when fix applied

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2259]
### Version

v0.19.1702220762

### Describe the bug

"Ask Cody to Fix" jumps when fix applied. See [Loom](https://www.loom.com/share/a403c9454727437282d6b4b126f414fb) at 0:28.  Also seems pretty slow? 

### Expected behavior

Shouldn't jump when edits are applied.

**Comment by umpox** [comment]
Related: https://github.com/sourcegraph/cody/issues/2259
