### ISSUE TITLE
bug: Chats persist between accounts

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2261]
### Version

v0.19.1702220762

### Describe the bug

When I switch between by dotcom account and my enterprise account, I’m surprised that my chats persist across the two. Presumably, a user who has two accounts (one enterprise, one free/personal) is using them for different things in different codebases, and the LLMs used to create those chats may be different. 

### Expected behavior

When logged in to a given account, I should only see that chats that I created while logged into that account. Ie, When I'm logged into s2, I should see the chats that I created as an enterprise user logged into sourcegraph.sourcegraph.com; when I'm logged into dotcom, I should see the chats that I created as a community user.

**Comment by philipp-spiess** [comment]
@csells Yes, same machine (and VS Code installation if you have multiple) only. Agree that this should not be possible. We need to prefix the storage keys with the individual user accounts to prevent this. Looking into it (this might become a fast follow up after GA though, depending on other priorities today)

**Comment by csells** [comment]
Agreed that this is not a GA blocker .
