### ISSUE TITLE
bug: Can't delete an individual chat from the individual chat panel

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2263]
### Version

v0.19.1702220762

### Describe the bug

Delete chat in the individual chat panel is no longer there.

### Expected behavior

I should be able to delete the open chat with an option in the title. 

![Image](https://github.com/sourcegraph/cody/assets/43555476/b12361ce-ee03-4a98-bd6e-a57a472e5ea4)

**Comment by valerybugakov** [comment]
@toolmantim, do we have a design for this icon? AFAIU, @taylorsperry means the "delete chat" functionality in the sidebar. Please correct me if I'm wrong.

<img width="224" alt="Screenshot 2023-12-15 at 15 34 07" src="https://github.com/sourcegraph/cody/assets/3846380/8ca179d1-6229-49d0-8112-817e8ebfb299">

**Comment by taylorsperry** [comment]
I'd meant the title (not the sidebar), but tbh, I don't know why I thought I needed that. I think being able to delete an individual chat from the sidebar is sufficient, unless we hear otherwise from users. Closing for now.
