### ISSUE TITLE
bug: Cody always answers no to "can you access this repo?" in new chat

### ISSUE THREAD

**Issue by morgangauth** [sourcegraph/cody#2270]
### Version

0.18.2 (this is also reproducible in Cody web)

### Describe the bug

1. Open a repo which has embeddings generated
2. Ask Cody the question `can you access this repo?` in a new chat 
3. Cody will  always say no even when it does have access
![image (7)](https://github.com/sourcegraph/cody/assets/113058716/fc15d12a-ff95-48ca-9b0f-bf347b017679)

5. Ask Cody a concrete question, like `what language is this repo written in?`
6. Cody will respond as expected

### Expected behavior

Cody should respond "yes" to the second step above if the repository is embedded and Cody can access its contents 

### Additional context

This was reported by users who were troubleshooting embeddings issues. Cody answering no created a lot of confusion as to whether the embeddings issues were resolved or not

Relevant Slack threads:
https://sourcegraph.slack.com/archives/C039TJ9TJ2Y/p1702321706228949?thread_ts=1701991391.380359&cid=C039TJ9TJ2Y
https://sourcegraph.slack.com/archives/C039TJ9TJ2Y/p1702318890615049?thread_ts=1700525009.442989&cid=C039TJ9TJ2Y
https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1702462706658779

**Comment by mibali** [comment]
Hey @sourcegraph/cody-clients,

One of our customers is also getting ` Unfortunately I do not have access to the actual state of code on Cody web` when the following prompt is given `what is the tech stack of this repo`  even tho the repo is embedded and added to the chat context.

I inputted the same prompt on our test instance and I got valid answers for embedded repos but got a similar feedback to the above for a repo not yet embedded.

**Comment by morgangauth** [comment]
I also have a customer from https://github.com/sourcegraph/accounts/issues/285 who is experiencing this. Even on embedded repos, Cody will respond that they do not have context or access to the code

**Comment by kalanchan** [comment]
this will be fixed for enterprise customers when we switch models, see https://github.com/sourcegraph/cody/issues/3321 for more context. 

@morgangauth if your customer is still facing this, please reach out to corey to get a better understanding of the problem

**Comment by spirelab** [comment]
i am also having this issue, no matter what, even local files is the same, i am pro user
