### ISSUE TITLE
bug: Cody Pro chat limit copy says "monthly" when the limit should be "daily"

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2272]
### Version

v0.19.1702310776

### Describe the bug

Steps to repro:
- Log into @vdavid 's [Cody Pro dummy account](https://sourcegraph.slack.com/archives/C066F85TE80/p1701712911448229?thread_ts=1700694252.150349&cid=C066F85TE80)
- Send a chat message
- See the following rate limit message:
![Screenshot 2023-12-11 at 11 47 58 AM](https://github.com/sourcegraph/cody/assets/3654603/1e45e5b2-274b-4faa-9c5f-2cd62068a0b7)
- Bugs:
  - "for the month" should be "for the day" since Cody Pro has daily abuse limits
  - "Usage" should update 1 day later, not the same day (maybe this is just a dummy account thing?)

### Expected behavior

Intended copy:
- "You've used all {LIMIT} chat messages and commands for the day."
- Usage will reset at {whatever the PLG API gives back, but it should be ~1 day later}
- Everything else (header and CTA) stay the same

**Comment by kalanchan** [comment]
> "Usage" should update 1 day later, not the same day (maybe this is just a dummy account thing?)

Yeah it's a dummy account thing, it will reflect the proper reset timestamp for a PLG user. 

> "for the month" should be "for the day" since Cody Pro has daily abuse limits

I can get this fixed!

**Comment by chenkc805** [comment]
Thanks @kalanchan !

**Comment by burakugar** [comment]
hello, the issue still persists.
