### ISSUE TITLE
If I click "Start Trial" too quickly on this page, because there's some latency between clicking the CTA and then loading the next modal, this page hangs

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2276]
Steps to repro:
- From Free --> Pro
  - Go to `/cody/subscription` as a Free user
  - Click "Get Pro Trial" 
  - Click "Start Trial" very quickly. See bug 🐛 . It thinks the user is already Cody Pro, and so throws an error

- From Pro --> Free
  - Go to `/cody/subscription` as a Pro user
  - Click "Cancel" 
  - Click "Switch to Free" very quickly. See bug 🐛 . It thinks the user is already Cody Free, and so throws an error

Intended behavior for both:
- No matter if clicking once or 10x quickly, the user state should switch based on the users intention. 

![Screenshot 2023-12-11 at 4 26 43 PM](https://github.com/sourcegraph/cody/assets/3654603/9d04088d-d6e3-44b7-b10c-33c592a39ec7)
![Screenshot 2023-12-11 at 4 28 44 PM](https://github.com/sourcegraph/cody/assets/3654603/1dd7c663-5dd8-4634-942f-e280c6f3ddd5)

**Comment by thenamankumar** [comment]
Don't be so quick!

Kidding, I'll take a look at this tomorrow.
