### ISSUE TITLE
Add copy to all Cody Free tier upsells about refreshing their IDE

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2277]
### Version

NA

### Describe the bug

Problem:
- Currently sometimes VS Code doesn't correctly grab the state of the user if they've upgrade to Pro from Free. This is a fallback to ensure Pro users get the Pro functionality 

### Expected behavior

Requirements:

Append the following text to all completion and chat/command Free tier upsells:
- "(Already upgraded to Pro? Restart your IDE for changes to take effect)"

**Comment by toolmantim** [comment]
I'm just going to close this for the moment, until we're sure this is happening. I have alternative UX suggestions in #2220 if we need, otherwise we can reopen.

**Comment by chenkc805** [comment]
Fair enough - I can't repro it. In my experience it's spotty: sometimes it work and sometimes it doesn't.
