### ISSUE TITLE
bug: /reset fails with "command custom-prompt failed"

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#2301]
### Version

main e75560d7d7380a662a663ed2c10bc1607c7db60b

### Describe the bug

Running `/reset` in a chat gives the following error:

<img width="1160" alt="Screenshot 2023-12-12 at 11 53 00 pm" src="https://github.com/sourcegraph/cody/assets/153/bd3deecd-1ca0-42c4-904d-466743e0efef">

### Expected behavior

It resets the chat transcript (same as the "Restart Chat Session" button)

**Comment by deepak2431** [comment]
Working on to fix this!
