### ISSUE TITLE
JetBrains: Strange chat scrollbar behavior

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/cody#231]
### Discussed in https://github.com/sourcegraph/sourcegraph/discussions/54900

- Plugin version: same behavior for v3.0.3 and v3.0.4
- IDE: IntelliJ IDEA Ultimate v2023.1.4
- OS: macOS v13.4 (22F66), Intel chip
- Server: an Enterprise instance. Sourcegraph search works fine, so the connection is set up correctly.
- Theme: reproducible with both [Gruvbox](https://plugins.jetbrains.com/plugin/12310-gruvbox-theme) and the built-in light theme.
- UI: reproducible with both the legacy and the new UI

Bug report:
> Often when using a recipe or asking something more freeform, the response seems to extend far below the actual space needed to show the response, meaning the scrollbar is able to scroll down much further than is necessary. This sometimes means I need to scroll up a bunch to find the response, and sometimes it means that the response is inaccessible, like not possible to see ever.
> Additionally, for some queries the size of the response pane keeps increasing even when it seems likely that the response will have already been generated.
> I included a screen recording with a generic example below.

https://github.com/sourcegraph/sourcegraph/assets/43481597/ec6ea389-62cb-4dff-90fd-cc530385d19b

**Comment by szymonprz** [comment]
The issue does no longer exists https://github.com/sourcegraph/cody/discussions/242#discussioncomment-6533163
