### ISSUE TITLE
bug: Change the copy of the VS Code Cody Pro tier abuse usage limit

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2353]
### Version

NA

### Goal
To prevent Cody Pro users from abusing Cody Pro by spamming a bunch of chat/command and autocomplete requests.

### Describe the bug

Current chat/commands copy: 
- **UNABLE TO SEND MESSAGE**
- You've used all X chat messages and commands for today.

Current autocomplete copy:
- **Autocomplete Disabled Due to Rate Limit**
- You've used all "XYZ" autocompletions. Usage will reset in "time".

### Expected behavior

Requested copy for chat/commands:
- **Thank you for using Cody so heavily today!**
- To ensure that Cody can stay operational for all Cody users, please come back tomorrow for more chats and commands. [Learn more](https://docs.sourcegraph.com/cody/core-concepts/cody-gateway#rate-limits-and-quotas)

Requested copy for autocompletes:
- **Thank you for using Cody's autocomplete so heavily today!**
- To ensure that Cody can stay operational for all Cody users, please come back tomorrow for more autocompletes. [Learn more](https://docs.sourcegraph.com/cody/core-concepts/cody-gateway#rate-limits-and-quotas)

### Additional context

Reference Figma: https://www.figma.com/file/f7bzmpYrwalyYOQJcWLRTP/Account-upgrading-from-VS-Code?type=design&node-id=0-3&mode=design&t=3UFgFj2sgJHp2kMX-0

**Comment by EvicorKGB** [comment]
it's awesome to get scammed by the website saying "unlimited usage" and when you get to use it, its clearly LIMITED, disgusting

**Comment by Fresh-ex** [comment]
Which part of unlimited is difficult for sourcegraph to understand? I hope this is a bug, I woke up this morning and submitted maybe 4 messages before I got this:

"UNABLE TO SEND MESSAGE
You've used all chat messages and commands for today.


Learn More
Usage will reset today at 10:51 AM"

**Comment by ACE-DVLPT** [comment]
It's unacceptable to be limited when the PRO plan is supposed to be unlimited. This needs to be rectified immediately or else ensure the service we're paying for! This is a complete joke...
