### ISSUE TITLE
bug: Downloading cody-engine forever

### ISSUE THREAD

**Issue by phisanti** [sourcegraph/cody#2354]
### Version

v0.19.1702493193

### Describe the bug

It's been a while since I got an _ad eternum_ notification that Cody is "Downloading Cody-engine" in VSCode remote (working on WSL2 via remote VScode 1.85.0 on Windows 11). See image attached.
![image](https://github.com/sourcegraph/cody/assets/33370667/69726e4d-df20-4a24-a78e-b80fbfc11e11)

My question is, does this affect Cody's performance? How can I get rid of it?

### Expected behavior

No notification

### Additional context

None

**Comment by dominiccooney** [comment]
Thanks for filing this issue. Can you tell me a bit more about your setup so I can try to recreate it?

> does this affect Cody's performance?

In general Cody is designed to use cody-engine. The specific impact of the download hanging right now is:

- You won't be able to use local embeddings as a source of context for chat messages. The enhanced context selector will show an endless spinner next to an "embeddings" source. Embeddings from sourcegraph.com will still be used for context when available.
- Some autocomplete experiments will behave differently.

> How can I get rid of it?

Once the download completes the message should disappear. You can restart the download by reloading the extension. Is there anything relevant about the network environment you're in that would block, throttle, etc. downloads?

**Comment by phisanti** [comment]
In general, I have normal access to internet, both from the Windows 11 interface and the WSL2 (Ubuntu 22.04 LTS) interface. I am not sure how could I debug that. Is there any command I can use in order to check the connectivity of the Cody extension?
