### ISSUE TITLE
bug: Name of open file appears appended to chat message

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#2360]
### Version

v0.19.1702493193 also main 5c34645ba74614b2beda3217e250ea07e2c1bbd2

### Describe the bug

When I chat, the name of a file I have open in VSCode is appended to my chat message.

Loom: https://www.loom.com/share/c4a63c41eefc4fe7afe41be7384eee81

### Expected behavior

The message I wrote should be the one that appears in the transcript. If there's editor context, that's great, but let's put it in context. The name is appended to every single message I send.

**Comment by abeatrix** [comment]
@dominiccooney thanks for the loom that's super helpful! We append the file name to a chat message if the file is currently active and has selection as we automatically add active file with selection as context.

The file name appending was originally meant for command though so user can easily identity the file name where they run the command on, and not for chat questions. I will work on a PR to remove that from chat questions!
