### ISSUE TITLE
Implement some fixes to telemetry for dotcom-hosted Cody onboarding flow

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2361]
Expected telemetry:
- When a user reaches the below two pages, we're currently not seeing these events:
  - CodyEditorSetUpViewed
  - CodyEditorSetUpOpenMarketplace
  - CodyEditorFeaturesViewed
- For all of these events, they should have the following metadata:
  - editor - which editor the user is viewing this page for

Reference: https://docs.google.com/spreadsheets/d/1QXnrHkgGLXdbfHEhI_VjtDTy-mCtnK1qri3IMQu7rNk/edit#gid=1704312181&range=24:26

**Comment by chrsmith** [comment]
cc https://github.com/sourcegraph/cody/issues/2771. Perhaps this is another symptom of the same underlying problem.

**Comment by vdavid** [comment]
@chenkc805, is this still a problem?
