### ISSUE TITLE
Implement FAQ on /cody/subscription page

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2363]

**Comment by vdavid** [comment]
@chenkc805, do you still plan on adding this? Do you need any help?

**Comment by chenkc805** [comment]
Yes I'd like to add this, it can just be a duplicate of the FAQ we currently have on the cody pricing page: https://sourcegraph.com/pricing

<img width="1840" alt="Screenshot 2024-01-25 at 1 29 28 PM" src="https://github.com/sourcegraph/cody/assets/3654603/f1fc669d-0262-4f6e-8373-9cc073c91127">

**Comment by vdavid** [comment]
@chenkc805, what's needed here? I guess the copy is done, so is this eng work? Or is it design work?
I guess this could be a P1, helping users be less lost seems to be pretty important at this point.

**Comment by chenkc805** [comment]
I'm still not seeing any FAQs at the bottom of the /cody/subscription page. Not a launch blocker for today but would like to get this in before 2/21.

**Comment by vdavid** [comment]
@chenkc805, this task is currently assigned to you. It seems like you need engineering help on this then? Shall I reassign it to one of us engs?

**Comment by chenkc805** [comment]
yes please, can you assign to whoever is the right person to work on this? Thanks!
