### ISSUE TITLE
Telemetry for "Settings and Support" sidebar

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2365]
### Description:

Requirements:
Log the following events for VS Code users when they interact with the Settings and Support panel
- [x] CodyVSCodeExtension:sidebar:upgrade:clicked
- [x] CodyVSCodeExtension:sidebar:usage:clicked
- [x] CodyVSCodeExtension:sidebar:settings:clicked
- [x] CodyVSCodeExtension:sidebar:keyboardShortcuts:clicked
- [x] CodyVSCodeExtension:sidebar:preReleaseNotes:clicked
- [x] CodyVSCodeExtension:sidebar:documentation:clicked
- [x] CodyVSCodeExtension:sidebar:feedback:clicked
- [x] CodyVSCodeExtension:sidebar:discord:clicked
- [x] CodyVSCodeExtension:account:clicked
<img width="442" alt="Screenshot 2023-12-13 at 9 32 03 PM" src="https://github.com/sourcegraph/cody/assets/3654603/54837ecd-c928-4ebf-a680-c8829c85b302">

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### Related Docs:

- [PRD: Your-Title]()

**Comment by chenkc805** [comment]
@kelsey-brown you sanity check my telemetry names?

**Comment by kelsey-brown** [comment]
Looks good! One thing I'd recommend is starting all these event names with `CodyVSCodeExtension:sidebar:` to specify where the user is clicking - helpful when if/when we have more than one path to get to one of these things (e.g. I know there are other places where a user can choose to upgrade, so it would be good to be able to distinguish where users are most commonly going to do that).

**Comment by chenkc805** [comment]
Ah so something like:
- CodyVSCodeExtension:sidebar:upgrade:clicked
- CodyVSCodeExtension:sidebar:usage:clicked
- CodyVSCodeExtension:sidebar:settings:clicked

Does that break our current schema, which seems to only have 2 colons instead of 3?

**Comment by chenkc805** [comment]
Sounds good. The requirements in the original comment have been updated to reflect this
