### ISSUE TITLE
When users click the final CTA when upgrading/downgrading, show a loading symbol to give feedback to the user that this is processing

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2378]
Problem:
- When users go to upgrade/downgrade in the below CTAs, sometimes it takes 2-3 seconds for the change to process. 
![Image](https://github.com/sourcegraph/cody/assets/3654603/205a2262-9fe8-47be-9160-c66def1c2ecc)
![Image](https://github.com/sourcegraph/cody/assets/3654603/3ec501d9-0dae-441f-9554-5ef37e9a2e7a)

Solution:
- When the user clicks the "Start Trial" or "Switch to free" CTAs, swap out the text and show a loading symbol in the CTA in its place to tell the user that we're processing the request.

**Comment by chenkc805** [comment]
@danielmarquespt do we have a loading symbol we can use here?

**Comment by thenamankumar** [comment]
This is handled in the new SSC flow, where @vdavid has already added the spinners.
