### ISSUE TITLE
bug: Telemetry for CodyVSCodeExtension:upsellUsageLimitStatusBar:shown seems to be firing too often

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2379]
### Version

v1.0.0

### Describe the bug

Seeing a lot of events fired for `CodyVSCodeExtension:abuseUsageLimitStatusBar:shown`, a lot higher than I expected (screenshot below).
![Screenshot 2023-12-14 at 11 38 56 AM](https://github.com/sourcegraph/cody/assets/3654603/395f2558-f913-4a38-a054-14fa75a6a4b2)

Looks like in the code this error fires very often, instead of just when the dropdown error shows (screenshot below).
![Screenshot 2023-12-14 at 11 43 52 AM](https://github.com/sourcegraph/cody/assets/3654603/237c5399-7077-406d-8270-208322d04022)

In an unrelated bug, it also seems like the `const = tier` line is incorrect. There should be a NOT in front of the `this.config.isDotComUser`. Line here: https://sourcegraph.com/github.com/sourcegraph/cody@5076bb39cb401b28efb7ae964418739fde39e31e/-/blob/vscode/src/completions/inline-completion-item-provider.ts?L595

### Expected behavior

Only fire `CodyVSCodeExtension:abuseUsageLimitStatusBar:shown ` when users open the dropdown AND see the autocomplete upsell as as Free user
![Screenshot 2023-12-14 at 11 43 52 AM](https://github.com/sourcegraph/cody/assets/3654603/237c5399-7077-406d-8270-208322d04022)

Relevant Figma: https://www.figma.com/file/f7bzmpYrwalyYOQJcWLRTP/Account-upgrading-from-VS-Code?type=design&node-id=0-3&mode=design&t=EFE09KKPvJeJjw9u-0

**Comment by valerybugakov** [comment]
@chenkc805 

1. `CodyVSCodeExtension:upsellUsageLimitCTA:shown` is sent when the error message is rendered, as you posted on the screenshot.
2. `CodyVSCodeExtension:upsellUsageLimitStatusBar:shown` is sent when the rate limit error is raised for the first time.

Based on the above, the expected behavior you shared means the replacement of the `CodyVSCodeExtension:upsellUsageLimitCTA:shown` with `CodyVSCodeExtension:upsellUsageLimitStatusBar:shown`. But I suspect this is not what you want. Could you elaborate?

> Expected behavior
> Only fire CodyVSCodeExtension:upsellUsageLimitStatusBar:shown when users open the dropdown AND see the autocomplete upsell as as Free user

**Comment by chenkc805** [comment]
Ok thanks for clarifying. I'm looking at the data too and the data seems to show these events dropping off heavily after GA. Maybe we were hitting these events very often pre-GA because of our testing dummy users? 

<img width="1840" alt="Screenshot 2023-12-15 at 2 57 43 PM" src="https://github.com/sourcegraph/cody/assets/3654603/2d81d302-809c-41ea-9efd-e3c3fc70448b">

In any case I think we can close this for now and re-open if I see another issue. 

However, before I close this, can you look at this callout I had above? I think the logic here is incorrect:

> In an unrelated bug, it also seems like the const = tier line is incorrect. There should be a NOT in front of the this.config.isDotComUser. Line here: https://sourcegraph.com/github.com/sourcegraph/cody@5076bb39cb401b28efb7ae964418739fde39e31e/-/blob/vscode/src/completions/inline-completion-item-provider.ts?L595

**Comment by valerybugakov** [comment]
>However, before I close this, can you look at this callout I had above?

Sure! Looks like I fixed this issue as a part of https://github.com/sourcegraph/cody/issues/2311 in https://github.com/sourcegraph/cody/pull/2372. Feel free to reopen if it's not the case.
