### ISSUE TITLE
bug: Embeddings Incomplete with no way to fix it

### ISSUE THREAD

**Issue by rileysiemens** [sourcegraph/cody#2381]
### Version

1.0.0

### Describe the bug

Embeddings progress is stuck at 19% (hasn't changed in hours).  The error tooltip says click to resolve but clicking does nothing.

![image](https://github.com/sourcegraph/cody/assets/23223158/8f70746e-db30-4299-b42f-057657377163)

### Expected behavior

Clicking the "Embeddings Incomplete" button in status bar would open a new tab to walk me through the process of re-generating embeddings index (or some other process that would  enable me to resolve the issue)

**Comment by prandelicious** [comment]
I'm also experiencing this. Has this been fixed?
