### ISSUE TITLE
bug: it give me "Applying edits failed" When i click on document command

### ISSUE THREAD

**Issue by AhmedElTabarani** [sourcegraph/cody#2382]
### Version

1.85.1

### Describe the bug

I just when I click on the document command
![image](https://github.com/sourcegraph/cody/assets/69223584/ff3bccad-4ffb-42ba-8090-46f4835d5283)

it keeps displaying `Applying edits failed`
![image](https://github.com/sourcegraph/cody/assets/69223584/a277c3c6-d3ea-4619-99be-e534c11666d6)

Note that all the commands worked, except document 

### Expected behavior

Document the code

### Additional context

I just downloaded the extension today and using the free tier, I signed up with GitHub, if that important

**Comment by AhmedElTabarani** [comment]
It solved now somehow

**Comment by webenadam** [comment]
i am getting this error all the time when trying to add code.
