### ISSUE TITLE
bug: Can not type @ to include files in chat

### ISSUE THREAD

**Issue by elemental-mind** [sourcegraph/cody#2383]
### Version
v1.0.0
v1.1.1702572663

### Describe the bug

When in the chat interface, I can not type `@` to include files for context. Even though I type an `@` no `@` appears in the chat editor - and subsequently no files can be included.

I am working on a german keyboard (QWERTZ) so the keyboard combination should be [ALT GR] + [Q]. 

Current workaround is using the alt-code: [ALT] + ([NUM-6] + [NUM-4])

### Expected behavior

When typing `@` to have an `@` appear in the chat window and subsequently get suggestions for files to include as context.

### Additional context

There seems to be a similar issue with other foreign keyboards already posted on discord: https://discord.com/channels/969688426372825169/1179099930258833540

**Comment by elemental-mind** [comment]
For context: OS is Win 10 Version 10.0.19045

**Comment by arafatkatze** [comment]
As an additional note: I do not face this with my Latin American(Spanish) keyboard but I do face this with some other key combinations(Like make a new chat for example). 

For new chat the normal symbols are `⌥ /` but I also have to press shift coz that's how my keyboard works. 

My recommendation is 
1. Go to keyboard shortcuts
<img width="580" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/91fedc31-d6ce-46d5-98b3-56b94e7f076d">

2. Go to record keys
<img width="444" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/1726f3ae-325c-40f2-a120-837532b46abf">

3. Record the exact keys that the cody command requires 
4. The search results will show you if there is something within your VScode settings that overrides those commands. And when you find something truly frivolous you can just delete that shortcut and when you do that the Cody shortcut takes over.

**Comment by manfromtunis** [comment]
hello i'm having the same problem, ENG FR keyboard layouyt the usual alt + @ won't open the menu in vscode, but using ALT + 6 + 4 worked

**Comment by elemental-mind** [comment]
Thanks @abeatrix , just tried it and works!
