### ISSUE TITLE
bug: Permanently Rate-limited after Pro upgrade

### ISSUE THREAD

**Issue by RXminuS** [sourcegraph/cody#2394]
### Version

1.0.0 (and web)

### Describe the bug

After upgrading to pro I can no longer use any chat/commands as it says I've used all my messages and commands for today. 

### Expected behavior

After upgrading to pro rate-limits should be reset and follow the plan.

### Additional context

- I noticed that the times reported as to when my usage will reset seem to be random. I've had ones where it reported usage would be reset in a minute, and ones where it said it would be reset in a month.
- I'm having the exact same issue when I use the web chat version, so it doesn't seem to be related to the VSCode extension specficially
- Just to be sure it wasn't some weird token issue I tried it on two accounts (one sign-in with Email, the other with GitHub) both of which have the same problem.
- I was working on a PR for Cody so happened to have tracing open. I noticed that `completions` do seem to work.
- I tried several models (Claude, GPT, etc). None of them seem to work for chat.

<img width="1199" alt="image" src="https://github.com/sourcegraph/cody/assets/3949285/fc8b684e-48be-4622-9ac1-c4a443d8a5f3">
<img width="1164" alt="image" src="https://github.com/sourcegraph/cody/assets/3949285/9cbf9605-edff-461c-bd8b-90eeeb047b56">
<img width="496" alt="image" src="https://github.com/sourcegraph/cody/assets/3949285/e0ed42eb-7017-4c44-994a-c6427ab29d86">

**Comment by philipp-spiess** [comment]
Hey @RXminuS. This clearly should not happen. Is this still an issue (I know we had some initial hiccups directly as we rolled out the 1.0.0 release).

I'll share this with the team to take a closer look. Sorry!

**Comment by RXminuS** [comment]
Absolutely no problem, I'm just missing my Cody friend ☺️ I much rather see the high rate of innovation and features at the cost of a bug every now and then, especially if remedied by such a friendly team

**Comment by philipp-spiess** [comment]
@RXminuS Thanks for understanding! 

Is this issue still occurring to you? If yes, do you mind reaching out to me via email so we can discuss things to investigate further. We looked into the backend side of things and everything looks normal there 🤔 

You can reach me via email at philipp.spiess@sourcegraph.com

**Comment by RXminuS** [comment]
Yes, it's still happening. I'll give you a ping.

**Comment by philipp-spiess** [comment]
The issue should be fixed now. I followed up with some details via Email but it looks like you were mistakenly flagged from our platform. Sorry about the issue!
