### ISSUE TITLE
bug: files in `bin/` are filtered out of @-mention in chat

### ISSUE THREAD

**Issue by DanTup** [sourcegraph/cody#2401]
### Version

main 2a00da01

### Describe the bug

When I typed `@`, my open file `bin\\main.dart` was already in the results, but as I started typing `bin` it vanished.

https://github.com/sourcegraph/cody/assets/1078012/9a997f6e-42d3-4904-b564-8b05f35e2fb3

### Expected behavior

Files that exist and match my query should not be filtered out.

**Comment by DanTup** [comment]
This turned out to be very specific... The default exclude list includes `bin/`:

https://github.com/sourcegraph/cody/blob/9d48eeb94c3674807c4815151510181943026364/vscode/src/editor/utils/editor-context.ts#L16

This is something I've hit before... When I did .NET, I would have `bin/` in by global gitignore (because in .NET it's compiled binaries). It's quite common in Dart to use `bin/` for the entry points of packages:

https://dart.dev/tools/pub/package-layout#:~:text=make_lunch.dart%0A%20%20bin/-,enchilada,-doc/%0A%20%20%20%20api/%20***%0A%20%20%20%20getting_started

@toolmantim any thoughts on this (since you picked the original defaults)? I'm not familiar with how many languages use `bin/`.. For .NET, probably explicitly including `bin/Debug/` and `bin/Release/` would filter out the garbage, although perhaps the real fix here is to use gitignore/etc.

**Comment by toolmantim** [comment]
Best to ask @abeatrix when she’s back, or @beyang — unsure how that initial exclude list was chosen.

**Comment by abeatrix** [comment]
We can just remove the keyword from the exclude list if the keyword is included in the exclude list, or just remove the exclude list in general from the @ search if you want. I was just using the same exclude list I used for the generate unit test to filter out uncommon files for unit tests and thought the same list could be used, no other particular reasons.

**Comment by abeatrix** [comment]
I'd recommend keeping it and remove it only if the keyword is included because those files will always show up on top of the list from those folder compared to the actual ones with the same names

**Comment by DanTup** [comment]
It may look odd if the user is typing `@bin/main.dart` if it's missing from the list until they've typed `@bin/`?

I wonder if it should be included (not in the exclude list) but penalised in the ranking unless the query starts with it?

That way if your project is small, it won't be obvious `bin/main.dart` is missing, but it may be further down the list until you've typed `bin/`?

**Comment by toolmantim** [comment]
The fuzzysort ranking algo is easy to tweak, I like the idea of just downscoring it.

**Comment by toolmantim** [comment]
If we do keep the exclude list, we should probably make it less invisible and hard-coded into the source by moving it to a user setting with the default value. With a cog icon in the popover, similar to the chat window, that opens the settings filtered to this feature.

**Comment by DanTup** [comment]
Maybe we should switch it to using the ignore file (https://github.com/sourcegraph/cody/pull/1382)? Seems pointless showing the user something in the dropdown to then filter it out later.

For now, I'll remove bin from the hard-coded ignore list and reduce the relevance.

**Comment by DanTup** [comment]
https://github.com/sourcegraph/cody/assets/1078012/2ad0ef3b-b2f9-45bd-bfc0-54fd77811511
