### ISSUE TITLE
bug: Cody.codebase setting is no longer respected in chat

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/cody#2409]
### Version

v1.0.1

### Describe the bug

When I am working in a repo that is not indexed on my enterprise sourcegraph instance, or the git remote detection does not match a repo on my instance, I am not able to set the cody codebase manually.

### Expected behavior

I should be able to set the cody.codebase setting and see it's value reflected in enhanced context selection for chat.

### Additional context

With no git remote
<img width="1036" alt="image" src="https://github.com/sourcegraph/cody/assets/6098507/ff4a3764-de1d-47a2-8b0a-97f4c13b817a">

overriding the git remote 
<img width="1122" alt="image" src="https://github.com/sourcegraph/cody/assets/6098507/965a362f-ab55-4994-957d-529efc493390">

**Comment by morgangauth** [comment]
A [customer](https://github.com/sourcegraph/accounts/issues/8825) also reported being impacted by this issue

**Comment by chwarwick** [comment]
> A [customer](https://github.com/sourcegraph/accounts/issues/8825) also reported being impacted by this issue

I'm just testing a fix for this now.
