### ISSUE TITLE
bug: Chat context files sometimes doesn't include explicitly mentioned files

### ISSUE THREAD

**Issue by DanTup** [sourcegraph/cody#2417]
### Version

main 2a00da01

### Describe the bug

Sometimes when I mention files they're sent to the LLM, but they don't appear in the expandable files section.

![image](https://github.com/sourcegraph/cody/assets/1078012/01545383-240b-4539-9f34-3f9720c8eec7)

### Expected behavior

All files being included should be listed here (with an appropriate source in the tooltip).

**Comment by deepak2431** [comment]
I'm looking into this issue.

**Comment by DanTup** [comment]
User-mentioned files aren't supposed to show up here but were due to another bug that will be fixed with https://github.com/sourcegraph/cody/pull/2408. Once that lands, the user-specified files will never show up here.
