### ISSUE TITLE
bug: Ipad clipboard access

### ISSUE THREAD

**Issue by zavx0z** [sourcegraph/cody#2445]
### Version

1.0.2

### Describe the bug

error
`
Unable to read from the browser's clipboard. Please make sure you have granted access for this website to read from the clipboard.
`

### Expected behavior

not error

### Additional context

https://github.com/sourcegraph/cody/assets/7262706/314cd9a3-1e80-48c3-abf5-13d84bce23d0

**Comment by Koopzington** [comment]
I'm having the same issue while using the extension inside a web hosted VS Code instance accessed through Firefox (which only has partial support for the Clipboard API right now). Setting the following two flags in `about:config` to true didn't change anything either.
`dom.events.asyncClipboard.clipboardItem`
`dom.events.asyncClipboard.readText`

**Comment by kingprawn22** [comment]
I'm having this issue currently, when using LinuxServer.io's code-server container. It looks to be isolated to Firefox, but since this is my browser of choice, I'm currently unable to use my Cody Pro account. Disappointing...
