### ISSUE TITLE
Add Cody chat back to sidebar

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#2450]
Some users have indicated they preferred having chat available in the sidebar: ![Image](https://github.com/sourcegraph/cody/assets/1646931/42b103ea-a3de-4c84-9c97-7b7481f58916)

I've seen other plugins that enabling drag/drop from sidebar to editor panes.

**Comment by kalanchan** [comment]
additional discord feedback: 
- https://discord.com/channels/969688426372825169/969688427232641136/1219423097967349810
