### ISSUE TITLE
feedback: Generate descriptive chat title using LLMs

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#2451]
### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

Currently, the history chat title for each chat can be of two types:
- Last interaction human message
- Edited chat title name if edited by the user

When the user does not edit the chat titles, it would be better to generate the descriptive chat titles using LLM's.

### Why is this feedback important? Please describe the rationale.

This request came through #2250, and also is being discussed over other issue to have this. 

### Describe the solution you'd like to see

Make use of LLM to generate a descriptive chat title.

**Comment by deepak2431** [comment]
I am working to spin up a PR for this issue.

CC: @dominiccooney

**Comment by philipp-spiess** [comment]
I’m excited but if we go ahead with this we need to make sure to loop in the PLG team (I can do that on the PR) as this would effect rate limit calculations.

**Comment by deepak2431** [comment]
@philipp-spiess Agree with you here, as it would affect the rate limit calculations. I will mention you on the PR during the review.

**Comment by deepak2431** [comment]
This is on my list to work on, I will get to this probably this weekend.
