### ISSUE TITLE
bug: Context limit reached

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#2455]
### Version

1.1.17

### Describe the bug

The context limit is reached just after two messages. Also, Cody reads unnecessary files as context.

https://github.com/sourcegraph/cody/assets/44617923/5d4023e8-dd2c-486b-a943-7c81d8784578
https://github.com/sourcegraph/cody/assets/44617923/e75825a5-52eb-49a3-a72a-ece7e11a8e5c

### Expected behavior

The context limit should not reach so quickly. I'm unsure what is happening here as if it considers the whole context files as the context in the chat or just the conversation. Ideal would be to consider all the chat messages human, assistant response under the complete chat context.

### Additional context

Reported by one more user: https://discord.com/channels/969688426372825169/1187340593635004426/1187340593635004426

Related issue: #2452

**Comment by deepak2431** [comment]
CC: @philipp-spiess @beyang @dominiccooney 

Another unrelated comment: When considering the enhanced context, it inherits the context automatically for the unindexed repository and uses that under context file results for each response, which I don't think should happen.

**Comment by jdorfman** [comment]
cc @chenkc805

**Comment by kalanchan** [comment]
Addressed this in multi turn chat, there will be follow ups on how to surface context limits coming soon
