### ISSUE TITLE
Remove Cody chat welcome message when a new chat has been triggered by a command 

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2461]
The "Welcome to Cody!" message that appears at the top of new chats triggered by a command execution (ie, "Explain") clutters the chat window with information the user doesn't need. We should remove this message for new chats that are triggered by a command.

**Comment by taylorsperry** [comment]
Tagging @toolmantim for design approval.

**Comment by toolmantim** [comment]
👍🏼

**Comment by kalanchan** [comment]
It should be blank, double check with integration test that it doesn't break
