### ISSUE TITLE
Button to edit a previous chat prompt can overlap with the prompt text

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2463]
Something with the pencil icon alignment looks off here (it overlaps with the word "javascript"). 

<img width="530" alt="Screenshot 2023-12-21 at 3 20 34 PM" src="https://github.com/sourcegraph/cody/assets/43555476/66f5d590-f1e7-4f98-a4ab-0b77c5821c4f">

**Comment by kalanchan** [comment]
closed as done
