### ISSUE TITLE
bug: Cody code lens doesn't show up for class method

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#2465]
From Discord:

> Hi, I turn on Code Lenses feature in setting and I see that Cody icon only show up for Class and Function definition. As you can see in the picture, I think it good if the feature support constructor() and in class method (sleep(),...) too, I can use it for quick create jsdoc and other things.

![Image](https://github.com/sourcegraph/cody/assets/1646931/449658be-e5fc-40f9-9c47-24370dfb99e4)
![Image](https://github.com/sourcegraph/cody/assets/1646931/b6c9a55d-8b2c-4220-b466-9ad5a7c1dfb0)

> Also I found that app.get() have Cody code lenses but app.listen() dont.

![Image](https://github.com/sourcegraph/cody/assets/1646931/78b876cb-7517-4e1e-b79d-4fc937ca028b)

**Comment by kalanchan** [comment]
I think this is fixed, please reopen if it's still a concern
