### ISSUE TITLE
Log "tier" telemetry in all Cody VS Code events

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2466]
Purpose:
- To track the number of "mDAU", or monetized DAU (pro + enterprise DAU), which is going to be a top-line product metric for 2024. 

Requirements:
- For all VS Code Cody telemetry, add what `tier` the user is in to the `public_argument` metadata field. 
- tier = free | pro | enterprise

This has already been approved by @kelsey-brown

**Comment by chenkc805** [comment]
@kalanchan do you think we can get this prioritized before Feb launch? It's ok if not, we can do some data transformations on our end to proxy this

**Comment by philipp-spiess** [comment]
@kelsey-brown / @chenkc805 is this still something we want to add? :)

**Comment by kelsey-brown** [comment]
Yes it is!

**Comment by philipp-spiess** [comment]
Need some help from @bobheadxi getting this into telemetry v2 too. PR for V1 is here: https://github.com/sourcegraph/cody/pull/3508

**Comment by philipp-spiess** [comment]
@kelsey-brown @chenkc805 Tiny change: We'll use an enum mapping to number for easier v2 support, so:

```ts
enum CodyTier {
    Free = 0,
    Pro = 1,
    Enterprise = 2,
}
```
