### ISSUE TITLE
Tag repositories, packages, or documentation corpi as context in Cody chat

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#2469]
Examples of things it would be cool to tag as context:
* Other repositories (prior art: https://github.com/sourcegraph/cody/issues/101)
* Language level packages (e.g., from NPM, PyPI, Maven, etc)
* Popular doc corpi, like MDN
* Python embeddings: https://twitter.com/nicolas_ouporov/status/1722293094752628986

**Comment by kalanchan** [comment]
going to close this for now until we have more clear direction on how we want to ingest additional context sources
