### ISSUE TITLE
bug: Request failed: failed to decode event payload: unexpected end of JSON input

### ISSUE THREAD

**Issue by tifaucz** [sourcegraph/cody#2476]
### Version

1.0.4

### Describe the bug

Sometimes, when cody is writing a long code answer, in the middle of it this error shows up and the answer disappear:

`Request failed: failed to decode event payload: unexpected end of JSON input - body: {"id":"chatcmpl-8Ye1uFnwNVNdCFiL7ux8OLaLRbSFn","object":"chat.completion.chunk","created":1703267718,"model":"`

### Expected behavior

It should finish the answer without the error appearing.

**Comment by deepak2431** [comment]
I have also faced this issue when using the GPT-4 model.

![iScreen Shoter - Code - 231222005414](https://github.com/sourcegraph/cody/assets/44617923/e2be7560-7c61-4671-9747-096114d3f73d)

**Comment by tifaucz** [comment]
Some more examples. For context, at least for me this is only happening when asking about CSS
![image](https://github.com/sourcegraph/cody/assets/15833226/543bee5a-631b-44c5-8ed3-e07eb5438446)
![image](https://github.com/sourcegraph/cody/assets/15833226/913cb7cf-4ddc-455d-bc46-0b3afd8122fa)

**Comment by tifaucz** [comment]
Sorry, not only CSS. I asked it to review a 32 line JS code, without using embeddings and it also failed with a similar error: 
![image](https://github.com/sourcegraph/cody/assets/15833226/7d18ffbc-dd96-470c-bd25-a074cfbfd803)
