### ISSUE TITLE
bug: Cody autocomplete rate limit did not reset on a daily basis for Pro plan, as mentioned in the docs

### ISSUE THREAD

**Issue by bayodesegun** [sourcegraph/cody#2477]
### Version

v1.0.4

### Describe the bug

I'm getting a message that says that the autocomplete rate limit will reset in 22 days. I expected that this would reset the next day, according to the [rate limit](https://sourcegraph.com/docs/cody/troubleshooting#rate-limits) docs.

![image](https://github.com/sourcegraph/cody/assets/15055526/6dafc85f-0779-49d7-8de1-40e6bec1d163)

![image](https://github.com/sourcegraph/cody/assets/15055526/d77b149d-8cf3-4d3f-a51d-ef8564f98fc5)

### Expected behavior

I expected that this would reset the next day, according to the [rate limit](https://sourcegraph.com/docs/cody/troubleshooting#rate-limits) docs.

### Additional context

This limit was already set before I upgraded to the Pro plan. Perhaps this has something to do with this bug.

**Comment by sqs** [comment]
Sorry about this issue. We have fixed it manually for all affected users. Are you still seeing it?

And the permanent fix is in https://github.com/sourcegraph/sourcegraph/pull/59330#issuecomment-1878658295.
