### ISSUE TITLE
bug: Free trial not working as expected in VsCode

### ISSUE THREAD

**Issue by ampinkus** [sourcegraph/cody#2480]
### Version

1.85.1

### Describe the bug

Hi I have a Cody free trial but in VsCode it shows me that autocomplete is disabled due rate limit.  The trial is supposed to have unlimited autocomplete suggestions.  Before I agreed on the trial I was using Cody autocomplete for free.  
![cody free trial](https://github.com/sourcegraph/cody/assets/34650255/27e742fa-a4b6-4aca-913a-6611c91696d6)
![cody notice](https://github.com/sourcegraph/cody/assets/34650255/46254973-cc2c-440d-97de-5d80328b4131)

### Expected behavior

I expected to have unlimited autocomplete due the trial subscription.

### Additional context

![cody free trial](https://github.com/sourcegraph/cody/assets/34650255/6c3672b6-c292-45d5-beee-d3705c38d0dc)
![cody notice](https://github.com/sourcegraph/cody/assets/34650255/e35e36c5-9d7a-4854-938c-10d8013a2d0a)

**Comment by saadfrhan** [comment]
Same with me.

**Comment by melMass** [comment]
Same here using the latest insider and prerelease version
