### ISSUE TITLE
bug: Code inside chat - Lines get overlapped.

### ISSUE THREAD

**Issue by falcon-Z** [sourcegraph/cody#2485]
### Version

v1.0.4

### Describe the bug

When Cody generates code in Chat window it looks like the image attached. Every line of code overlaps above previous line which makes it hard to read and understand.

I prefer using large font sizes (around 24px) and High Contrast dark theme.

### Expected behavior

Code in chat window should not overlap with other lines.

### Additional context

![image](https://github.com/sourcegraph/cody/assets/28111283/acdd7f39-e625-4656-8f58-afb67ecc017b)

**Comment by jason-shen** [comment]
i have this too lol, and i did subscribe to premium too, please fix this
![CleanShot 2024-06-05 at 04 16 46@2x](https://github.com/sourcegraph/cody/assets/1794291/7c2db826-39be-4806-99cd-c8fef074346d)

**Comment by jason-shen** [comment]
its something to do with font size, if zoom out its fine, but still this is bad
