### ISSUE TITLE
bug: Rate Limit won't go away for Pro account

### ISSUE THREAD

**Issue by jeremysexton** [sourcegraph/cody#2488]
### Version

1.0.4

### Describe the bug

I had the Cody AI extension installed and it was operating properly. I ran into a rate limit and decided that I wanted to upgrade to a Pro account. After doing so, the extension shows that I have a Pro account, but I cannot use autocomplete. It still says that it's rate limited.

I've tried logging out and back in to my account. I've tried uninstalling and reinstalling the extension, neither helped. It currently says it will reset in 26 days.

### Expected behavior

I expected that when I upgraded to the Pro account, the rate limit would be lifted from my account and I could continue using the extension.

**Comment by melMass** [comment]
Same but 17 days, IIRC the rate reset was daily before Pro was introduced.
I haven't been able to use cody for days now because of that unfortunately

**Comment by sqs** [comment]
Sorry about this issue. We have fixed it manually for all affected users. Are you still seeing it?

And the permanent fix is in https://github.com/sourcegraph/sourcegraph/pull/59330#issuecomment-1878658295.

**Comment by ShankhadeepBanerjee** [comment]
I am facing this issue right now.

my cody account: @shankhadeep17.sb

**Comment by jeremysexton** [comment]
Found the form on the Discord to fill out to have it fixed and it was! Seems to be working now. If anyone else is still experiencing this, I'd point you there.
