### ISSUE TITLE
For new users creating an account from the IDE, they should go through only part of the Cody onboarding flow before getting pushed back to the editor

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2490]
Today's behavior:

1. User installs Cody in IDE (eg. VS Code)
2. User creates a new Sourcegraph account via GitHub, GitLab, or Google
3. User gets taken to /post-sign-up and has to fill out the work/personal form
4. After filling out the form, user gets pushed back to the IDE

Expected behavior with new PLG onboarding flow:

1. User installs Cody in IDE (eg. VS Code)
2. User creates a new Sourcegraph account via GitHub, GitLab, or Google
3. User gets taken to /cody/manage and goes through some of the onboarding flow (not all of it)
4. After filling out the work/personal form, user gets pushed back to the IDE

See screenshot below of expected changes for steps 3 and 4. See highlighted Yellow text for some headline changes on the work/personal form to indicate that after this step, we're taking them back to the editor.
![Screenshot 2023-12-01 at 2 26 35 PM](https://github.com/sourcegraph/cody/assets/3654603/070af91e-3ceb-42ab-aa95-d18a386c5295)

Side note: I also highlighted yellow the new form we want to show in the work/personal step, but that's being addressed elsewhere here: https://github.com/sourcegraph/cody/issues/1936

**Comment by thenamankumar** [comment]
We are not moving the Cody Manage and onboarding from dotcom to SSC. This is already solved in the current version.
