### ISSUE TITLE
Add "Are you sure" modal if a user tries to downgrade from Pro to Free tier

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2498]

**Comment by thenamankumar** [comment]
We need to re-think the UX here, as canceling of subscription is required. cc: @danielmarquespt

**Comment by chrsmith** [comment]
@vdavid , I think you already did this? We now show a confirmation dialog when you change a subscription's `cancelAtPeriodEnd` flag from `false` to `true`?

**Comment by thenamankumar** [comment]
This is done by @vdavid
