### ISSUE TITLE
bug: I am getting this error :" Error: Could not register service worker: "

### ISSUE THREAD

**Issue by ashdude1401** [sourcegraph/cody#2509]
### Version

1.0.4

### Describe the bug

Whenever I try use any feature of cody , it is opening a new blank window   and showing this error -"Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..".I have tried many things like loggin ,logout ,enabling &disabling extention and even unistalling&downloading extention ,but nothing working .

![image](https://github.com/sourcegraph/cody/assets/98846260/94cb9dcb-0c41-4fc6-8e7b-eb6a0ccec884)

### Expected behavior

It should open a new window and start chatting with me .

### Additional context

It is not even loading the previous histories

**Comment by DanTup** [comment]
This could be a VS Code issue - I've been seeing the same error in other extensions lately (quite intermittently) and there's quite a long open issue at https://github.com/microsoft/vscode/issues/125993

**Comment by simwai** [comment]
I also have this bug... :/

**Comment by nicoleepp** [comment]
I am running into this in my VSCode too
