### ISSUE TITLE
bug: Request failed: failed to decode event payload: unexpected end of JSON input - body

### ISSUE THREAD

**Issue by captivus** [sourcegraph/cody#2513]
### Version

v1.0.4

### Describe the bug

When using ChatGPT 4 Turbo Preview in Cody Pro chat, the response fails midstream and generates this error message:
`Request failed: failed to decode event payload: unexpected end of JSON input - body: {"id":"chatcmpl-8aQDj88iyldoeRqpKT41m27RRfMpr","object":"chat.completion.chunk","created":1703691291,"model":"gpt-4-1106-preview","system_fingerprint":"fp_3905aa4f79","choices":[{"index":0,"delta":`

The error message appears to be truncated.

### Expected behavior

Expected behavior is that the chat should successfully complete.

### Additional context

Screenshot below for reference.
![image](https://github.com/sourcegraph/cody/assets/366332/26b46f35-abb1-44e7-a20f-fbf25d298f9a)

**Comment by emapco** [comment]
I also have encountered this bug when using gpt3.5 turbo and gpt4 turbo in Cody Pro chat.

**Comment by monko9j1** [comment]
I am getting the same error, using gpt-4 turbo.

**Comment by abeatrix** [comment]
Users confirmed the issue has been resolved in the latest release (v1.0.5).

![Image](https://github.com/sourcegraph/cody/assets/68532117/ce16ee17-2167-432c-9f8b-6f460c330c46)

![Image](https://github.com/sourcegraph/cody/assets/68532117/02b8488d-a911-49d6-ba86-8f5fe63744be)
