### ISSUE TITLE
bug: "ommited for brevity"

### ISSUE THREAD

**Issue by kateisprettydamngreat** [sourcegraph/cody#2518]
### Version

1.0.4

### Describe the bug

![image](https://github.com/sourcegraph/cody/assets/82071373/cc6c1700-46f3-48a9-a8b5-b6af4ccdd99e)
[ItemScript.cs.txt](https://github.com/sourcegraph/cody/files/13781864/ItemScript.cs.txt)
[Custom command json](https://github.com/sourcegraph/cody/files/13781866/cody.json)

The excessive commenting on the code as seen in [https://github.com/sourcegraph/cody/issues/2516](Issue 2516) is present here too, as though it's trying to teach me how to do it myself. While comorbid with 2516, this issue also occurs on it's own without a broken codeblock.

### Expected behavior

A full, concise optimization of the code with minimal commenting.

### Additional context

.txt appended for compat.

**Comment by kateisprettydamngreat** [comment]
[overcommenting example.json](https://github.com/sourcegraph/cody/files/13781901/overcommenting.example.json)
Interesting example of the commenting without any comorbid unwanted behavior.

**Comment by kateisprettydamngreat** [comment]
> [overcommenting example.json](https://github.com/sourcegraph/cody/files/13781901/overcommenting.example.json) Interesting example of the commenting without any comorbid unwanted behavior.
> 
> EDIT, this demonstrates [issue 2516](https://github.com/sourcegraph/cody/issues/2516)

Additionally, this code is of poor quality and needed debugging, so something here is messing with the llm.

**Comment by abeatrix** [comment]
Thanks for filing the issue @kateisprettydamngreat ! 
As mentioned in the discord thread, we can try updating the prompt and ask Cody to provide the optimized code without excessive commenting. Here is the prompt I tried in [cody.json](https://github.com/sourcegraph/cody/files/13796569/cody.json). It should also help with the hallucination issue mentioned in https://github.com/sourcegraph/cody/issues/2519 🙏
