### ISSUE TITLE
As a Cody user or billing owner, I should get transactional email depending on certain triggers

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2525]
Transactional emails, their triggers, audiences, and copy: https://docs.google.com/document/d/1DD6Afb2z21G0v2vPRonuol0aikIjeRm1RjJBVeCLZy4/edit#heading=h.qksigfk2a2b2

**Comment by chrsmith** [comment]
Closing this out in favor of two other issues covering the same thing.


[#225](https://github.com/sourcegraph/accounts.sourcegraph.com/issues/225)
[#245](https://github.com/sourcegraph/accounts.sourcegraph.com/issues/245)
