### ISSUE TITLE
JetBrains: Cody: Overwrite the current line suffix when it's not included in multiline autocomplete

### ISSUE THREAD

**Issue by Gedochao** [sourcegraph/cody#253]
## Current Behaviour

https://github.com/sourcegraph/cody/assets/18601388/447a8729-4622-4722-b80c-545a5dee6fc2

The current line suffix is still visible when a multiline autocomplete suggestion is rendered.
Additionally, it is being added after the first line of the auto completion.

## Expected behaviour

If the current line suffix is not contained in the multiline completion, we should write over it.
It shouldn't be visible as the autocomplete suggestion is being rendered, and applying it should overwrite it on the spot.

**Comment by olafurpg** [comment]
Closing this as wontfix since the agent-powered completions already handle this scenario.
