### ISSUE TITLE
Update sidebar id from 'cody.chat' to 'cody.sidebar'

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#2533]
Follow up on https://github.com/sourcegraph/cody/pull/2528#discussion_r1438449073

The webview of SidebarViewController is currently registered under 'cody.chat'. It should be updated to 'cody.sidebar' for clarification.

Expected behavior after the change:

The Sidebar should remain open on VS Code restart.

**Comment by kalanchan** [comment]
closing as it's a small task, low priority

**Comment by kalanchan** [comment]
closing as it's a small task, low priority
