### ISSUE TITLE
bug: AI Code Generation Stalling and Unresponsive Stop Button

### ISSUE THREAD

**Issue by jim-steven** [sourcegraph/cody#2539]
### Version

v1.1.1704208019

### Describe the bug

![image](https://github.com/sourcegraph/cody/assets/141747724/8ad92264-58b9-4275-9396-d06dbc786ad5)

A Discord user encountered a problem with ChatGPT 4, where it couldn't decode an event payload due to an "unexpected end of JSON input." The error message indicated the system received less JSON data than expected, leading to an unprocessable JSON structure. After switching to pre-release, this issue was resolved. However, ChatGPT 4 then began stalling during code generation, and the 'Stop Generating' button stopped working, requiring a new chat to fix the problem.

[Discord link](https://discord.com/channels/969688426372825169/1191760945177968721)

### Expected behavior

The AI should generate code smoothly without stalling. The 'Stop Generating' button should function correctly, allowing users to halt the code generation process at any time without needing to restart the chat.

### Additional context
[Error Logs](https://github.com/sourcegraph/cody/files/13813228/message.txt)

**Comment by jim-steven** [comment]
Two more users ran into this [error](https://discord.com/channels/969688426372825169/1191834179982344284), one of them on pre-release.

**Comment by jim-steven** [comment]
related to #2464 and #2526. should have been fixed with the recent pre-release.

**Comment by jim-steven** [comment]
additional user that has the [same issue from GH](https://discord.com/channels/969688426372825169/1192077669639127163).
![image](https://github.com/sourcegraph/cody/assets/141747724/573c2ef8-5c91-420a-b268-b67b6735e5f2)

**Comment by jim-steven** [comment]
![image](https://github.com/sourcegraph/cody/assets/141747724/ebca0fb4-c937-44f3-9ba4-5d394eac1170)
![image](https://github.com/sourcegraph/cody/assets/141747724/ac79590c-fc03-41c2-9c46-3336c7e023c0)

**Comment by abeatrix** [comment]
dup of https://github.com/sourcegraph/cody/issues/2513

The main issue described in this issue is fixed in the latest release (v1.0.5).
