### ISSUE TITLE
As a Sourcegraph employee, I should be able to give a one-time refund to a user if they have a negative customer experience.

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2544]
**Requirements:**
- A Sourcegraph admin with the proper permissions in Stripe should be able to give a 1 time credit to a user who has a negative customer experience
- The type of refund we should give is N months of Cody Pro for free.

**Open questions we're determining via the [Cody Support Plan PRD](https://docs.google.com/document/d/1f4FPrDUpfquvGrmhqr1U53hS_Go3XfS9M_zePBiYEqE/edit#heading=h.7g5r2vmzz2jp)**:
- What is a proper amount to give?
  - Perhaps limit this to extra free months of Cody Pro
- Under what scenarios is it appropriate to give a refund?
- What permissions / safeguards can we / should we have in place in Stripe to prevent accidents + unintended negative activity (eg. accidentally refunding someone $1000)?

**Comment by chrsmith** [comment]
We have all the support we need for February, although the experience will be a little rough.

A Sourcegraph employee can go into the Stripe Console directly and add a credit balance for the customer. This won't show up anywhere in the UI, but the credit will be applied to the customer's next invoice. (And will show up as a separate line item.)

So for February we do have the capability to give a one-time or even multi-month refund/credit. But there are various ways we can improve or streamline the process. But all of those would be post-February. So closing this ticket out, and we can revisit this topic post launch. (And do the work to streamline the experience if we end up issuing refunds more than ~never.)



![Image](https://github.com/sourcegraph/cody/assets/4029847/aaf75151-de5e-4b2f-8941-95ac6a179cf3)
