### ISSUE TITLE
bug: currentDir context is not shown in UI

### ISSUE THREAD

**Issue by Bruno-DaSilva** [sourcegraph/cody#2548]
### Version

v1.0.4

### Describe the bug

When using the `currentDir` context option, eg. when running the generate-tests command (`/test`), the list of files used for context is incomplete. None of the files generated by the currentDir context are shown. Yet, if you examine the debug promptCompletion output, the context files are there..

<img width="1800" alt="bugged2" src="https://github.com/sourcegraph/cody/assets/8520801/f587bc34-3edd-4fbe-9075-4d366c619655">
<img width="1800" alt="bugged1" src="https://github.com/sourcegraph/cody/assets/8520801/65f3fc75-74e5-4503-ae43-6d9aced7f701">

### Expected behavior

The UI that shows the list of files sent as context should contain the files from the currentDir context option. 
Here's what it looks like with one of the below fixes applied:
<img width="1799" alt="fixed2" src="https://github.com/sourcegraph/cody/assets/8520801/3bb8da6c-fddc-4924-982b-72b3726bd527">
<img width="1798" alt="fixed1" src="https://github.com/sourcegraph/cody/assets/8520801/7aec720e-3fb6-463d-8931-a123b75d0f65">

### Additional context

To be clear, I'm talking about this UI Component:
<img width="414" alt="Screen Shot 2024-01-03 at 6 01 37 AM" src="https://github.com/sourcegraph/cody/assets/8520801/f5034237-a978-4ec6-baca-eb7fc709e34a">

## Why this happens:
After some debugging within the extension, I found the prompt message generated for currentDir context files is hardcoded in here: https://github.com/sourcegraph/cody/blob/52a3187ed80439a5e9f45bb6c753d8c35ae6f978/lib/shared/src/chat/prompts/vscode-context/helpers.ts#L358
EDIT: also in getCurrentDirFilteredContext().

Yet, the SimpleChatRecipeAdapter calls `contextMessageToContextItem(message)`:
https://github.com/sourcegraph/cody/blob/52a3187ed80439a5e9f45bb6c753d8c35ae6f978/vscode/src/chat/chat-view/SimpleChatRecipeAdapter.ts#L96-L101
which strips the prompt messages down to the file information so long as they match these strings:
https://github.com/sourcegraph/cody/blob/52a3187ed80439a5e9f45bb6c753d8c35ae6f978/vscode/src/chat/chat-view/chat-helpers.ts#L172
https://github.com/sourcegraph/cody/blob/52a3187ed80439a5e9f45bb6c753d8c35ae6f978/vscode/src/chat/chat-view/chat-helpers.ts#L180
https://github.com/sourcegraph/cody/blob/52a3187ed80439a5e9f45bb6c753d8c35ae6f978/vscode/src/chat/chat-view/chat-helpers.ts#L188

And otherwise returns `undefined`.

Well, as you can see, the currentDir prompt string doesn't match any of these. Thus all files from this context are filtered out and don't appear in the UI.

### Proposed Fixes:
1. add the hardcoded `Codebase context from file path ` to the [prompt templates file](https://github.com/sourcegraph/cody/blob/52a3187ed80439a5e9f45bb6c753d8c35ae6f978/lib/shared/src/prompt/templates.ts) and then add it to the `stripContextWrapper()` function in chat-helpers.ts, OR
2. change the hardcoded prompt prefix to use one of the already existing file context templates, which will match what's used in chat-helpers.ts.

**Comment by Bruno-DaSilva** [comment]
I've updated the original with root cause and proposed fixes. Hoping that can mean a swift fix from someone :)

**Comment by Bruno-DaSilva** [comment]
quick ping to @abeatrix as you're the implementer of vscode-context and @beyang as you're the implementer of the simplify-chat-prompts refactor - I assume one of you should know which fix is preferred here.

**Comment by Bruno-DaSilva** [comment]
Note this hardcoding-not-matching seems to happen in at least one other place: getCurrentDirFilteredContext(). So that will have to change as well.

**Comment by abeatrix** [comment]
@Bruno-DaSilva hey there, thank you so much for the detailed report! I am working on a PR that would address this issue, will keep you posted here!

**Comment by Bruno-DaSilva** [comment]
hahaha you were already working on it before I reported, I see. Wonderful. Thanks for picking this up, @abeatrix!

**Comment by abeatrix** [comment]
@Bruno-DaSilva This should be fixed on the latest pre-release version. Can you give that a try and let us know if that doesn't work, please? 🙇‍♀️

**Comment by Bruno-DaSilva** [comment]
This looks like it's working on the pre-release version! Thanks for the quick fix 🙌
