### ISSUE TITLE
As a Cody Pro *Limbo* user on a Cody Pro trial plan, I should be notified that I'll need to start paying for Cody Pro on February 21

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2553]
Requirements here: https://docs.google.com/document/d/11gVz0IdKDIpdh05rCfmrAJxiIUycKJqJoEBDE7kVbL4/edit#bookmark=id.94ddbyq4mnu2

**Comment by chrsmith** [comment]
@chenkc805 , On the eng side we need to make sure that the SSC frontend is live in production and can support the traffic. But is there any other work you need from eng to support this?

**Comment by vdavid** [comment]
Progress update:
Naman and I think all the dev work is done here and we just need:
- testing in the clients (AFAIK, it's ongoing in both JetBrains and VS Code)
- make sure someone has a trigger in their calendar to send out the emails on the 8th

@chenkc805, do you see anything else to be done here, or any corrections to the above?

**Comment by chrsmith** [comment]
This has been fixed. The `cody-pro-trial-ending` email will be sent 3x days before a free trial is slated to end. https://github.com/sourcegraph/accounts.sourcegraph.com/pull/462
