### ISSUE TITLE
As a user, if I have a 3rd party extension that blocks things like HubSpot from showing up, I should still be able to move through the signup flow

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2557]
**Problem:**
- Users with 3rd party applications like Tailscale or related products may automatically block our Hubspot form. 
- If the form is blocked, there's no way for the user to progress to the next page (see screenshot below)

**Solution:**
- If the form doesn't render, automatically progress them to the next step of the onboarding flow

More context: https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1703973231087469
![Image](https://github.com/sourcegraph/cody/assets/3654603/29ed0094-86ef-4885-bff7-4b769d5c19f9)

**Comment by chenkc805** [comment]
@arafatkatze I think this (https://github.com/sourcegraph/sourcegraph/issues/59353) is a similar and related bug to the one outlined here. Could you see if you can tackle this bug as part of this issue?

**Comment by arafatkatze** [comment]
@chenkc805 Thanks for the reminder and I will take a look at both of them.

**Comment by thenamankumar** [comment]
@arafatkatze Hey this is a blocker and affecting a few users. Will you be working on this soon or should the @sourcegraph/cody-plg team take this over?

**Comment by arafatkatze** [comment]
@thenamankumar Sorry this accidentally fell off my plate I will get to this within 48 hours

**Comment by arafatkatze** [comment]
Still investigating this and would want to come up with something hopefully by tomorrow.

**Comment by chenkc805** [comment]
I think we can close this since https://github.com/sourcegraph/sourcegraph/pull/60128 is complete. Closing, but anyone can feel free to re-open if I'm mistaken.

**Comment by chenkc805** [comment]
Hm @arafatkatze @thenamankumar it looks like users are still running into this issue: https://discord.com/channels/969688426372825169/1211659921494380595/1211689984214564954

Will ask our QA team to see if they can reproduce.
