### ISSUE TITLE
Add link handler with confirmation dialog for links generated by Cody 

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2563]
See [thread](https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1701802923795349) and related [issue](https://github.com/sourcegraph/security-issues/issues/369). SLA for early March.

**Comment by kalanchan** [comment]
Context: This is to help the Security test publish their pentest report, as they have an SLA to meet by March. 

Scope of work: Display navigation popup when a user clicks on a link generated by Cody.
