### ISSUE TITLE
PRD: [VSC] *On Feb 1* Notify users that Cody Pro trial is coming to an end

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2564]
### Description:

Notify Cody Pro users that their free trial is coming to an end, and redirect them to /cody/subscription page if they'd like to continue using Cody Pro. This should go live on February 1.

### Objectives:

Notify Cody Pro free trial users that their free trial is ending, and provide them with a way to continue using Cody Pro.

### Acceptance Criteria:

- Starting February 1, all Cody Pro users see a dismissible notification that their free trial of Cody Pro will end on February 15
- The notification directs users to sourcegraph.com/cody/subscription
- See work plan for copy details

### Design Tasks:

```[tasklist]
### Design Tasks
```
@toolmantim Could you please put together a design for this? 

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### Related Docs:

- [Cody Pro Trial --> Paid Transition](https://docs.google.com/document/d/11gVz0IdKDIpdh05rCfmrAJxiIUycKJqJoEBDE7kVbL4/edit)
- [Cody Clients notification work plan](https://docs.google.com/document/d/1p8V_c5wkmNgnCshRdlnjbHqxgkYLVlvpTyDdbHu4VSY/edit)

**Comment by taylorsperry** [comment]
@chenkc805 please review to make sure this meets requirements, and feel free to suggest any copy changes

**Comment by chenkc805** [comment]
"**Your Cody Pro trial is ending soon on February 15**
Input your credit card here (link TBD) to continue using Cody Pro. 
You won't be charged until February 15."

@chrsmith @thenamankumar do we have a front end link of the credit card page yet? We want to deeplink there for users to start inputting their credit cards early

**Comment by taylorsperry** [comment]
@kalanchan to work with eng to scope. Depending on the level of effort, we may just email users to let them know that their trial is coming to an end (instead of adding an in-app notification). See [Cody Pro Trial --> Paid Transition](https://docs.google.com/document/d/11gVz0IdKDIpdh05rCfmrAJxiIUycKJqJoEBDE7kVbL4/edit).

**Comment by kalanchan** [comment]
@toolmantim @sourcegraph/cody-clients is there a way to gate this notification only for PLG users? Enterprise should be excluded

**Comment by taylorsperry** [comment]
This notification should *only* go to Pro users (whose trials are coming to an end). What we aligned on earlier this week is that if we don't have the bandwidth to add this notification, we'll rely on the email campaign instead (ie, we'll email Cody Pro users to tell them their trial is coming to an end and link them to the page where they can add their credit card).

**Comment by chenkc805** [comment]
@taylorsperry if we don't have the bandwidth for this should we close this issue?

**Comment by kalanchan** [comment]
> @taylorsperry if we don't have the bandwidth for this should we close this issue?

@chenkc805 I think we'll be good to implement this, just waiting for Naman to expose the field for the clients 

https://sourcegraph.slack.com/archives/C05SZB829D0/p1705478040166359?thread_ts=1705085764.652129&cid=C05SZB829D0

**Comment by DanTup** [comment]
@kalan is this done (via https://github.com/sourcegraph/cody/pull/2910) or is there anything outstanding?
