### ISSUE TITLE
PRD: [VSC] *On Feb 15* Notify users that Cody Pro trial has ended

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2565]
### Description:

Notify Cody Pro users that their free trial has ended, and redirect them to /cody/subscription page if they'd like to continue using Cody Pro. This should go live on February 15.

### Objectives:

Notify Cody Pro free trial users that their free trial is ending, and provide them with a way to continue using Cody Pro.

### Acceptance Criteria:

- On February 15, all Cody Pro users see a dismissible notification that their free trial of Cody Pro has ended
- The notification directs users to sourcegraph.com/cody/subscription
- See work plan for copy details

### Design Tasks:

```[tasklist]
### Design Tasks
```
@toolmantim Could you please add a design for this notification? 

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### Related Docs:

- [Cody Pro Trial --> Paid Transition](https://docs.google.com/document/d/11gVz0IdKDIpdh05rCfmrAJxiIUycKJqJoEBDE7kVbL4/edit)
- [Cody Clients notifications work plan](https://docs.google.com/document/d/1p8V_c5wkmNgnCshRdlnjbHqxgkYLVlvpTyDdbHu4VSY/edit)

**Comment by taylorsperry** [comment]
@chenkc805 please review to make sure this meets requirements, and feel free to suggest any copy changes

**Comment by toolmantim** [comment]
Does the account type change to Free on that date, or is it still Pro but with some new flag that we can use to encourage payment (and a grace period)?

**Comment by toolmantim** [comment]
A heads up that they need to enter a credit card by x date to continue using Cody Pro uninterrupted would be good for the user. That means the credit card stuff would need to go live before the hard auto-downgrade date.

**Comment by chenkc805** [comment]
"**Your Cody Pro trial is ending soon on February 15**
Input your credit card here (link TBD) to continue using Cody Pro. 
You won't be charged until February 15."

> A heads up that they need to enter a credit card by x date to continue using Cody Pro uninterrupted would be good for the user. That means the credit card stuff would need to go live before the hard auto-downgrade date.

Yes we're targeting a URL to collect CCs (but not process them) starting Feb 1. CC: @chrsmith @thenamankumar

**Comment by kalanchan** [comment]
> A heads up that they need to enter a credit card by x date to continue using Cody Pro uninterrupted would be good for the user. That means the credit card stuff would need to go live before the hard auto-downgrade date.

Yeah, this is addressed in #2564

**Comment by DanTup** [comment]
@kalanchan is this done (via https://github.com/sourcegraph/cody/pull/2910) or is there anything outstanding?

(I guess it still relies on the flags being flipped, not sure if that's tracked somewhere).

**Comment by kalanchan** [comment]
@DanTup yeah this is done, thanks for catching that. I'll close the ticket :) 

The flag flip is being tracked [#368](https://github.com/sourcegraph/accounts.sourcegraph.com/issues/368). Do you have access to the repo? 

Regardless, it'll be flipped on Feb 12 :)
