### ISSUE TITLE
feedback: Temporary skip context for a chat session/question

### ISSUE THREAD

**Issue by kukicado** [sourcegraph/cody#2568]
### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [X] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

Allow Cody chat to be used without current codebase context taken into account.

### Why is this feedback important? Please describe the rationale.

Sometimes i just ask questions about math/std/other stuff which is not related to a current context at all. I think it would be nice to have a way to skip it, for you guys due to llm api pricing, and for the user to have a larger current context window available. Something like /ctx command that can switch it on and off?

### Describe the solution you'd like to see

Add ability to add either a / command or @ command to specify that you do not want current codebase context taken into account for the question being asked.

### Additional context

Discord user "eci" suggested this feature.

**Comment by abeatrix** [comment]
Codebase context is excluded when `Enhanced Context` is disabled:
<img width="771" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/49217894-0994-4cc1-a6cc-2471e8c25c8a">

@toolmantim should we update the tooltip/description to mention enhanced context = codebase context?  🤔

**Comment by kalanchan** [comment]
closed as this is completed
