### ISSUE TITLE
bug: editing non-file documents with ignore file enabled causes errors

### ISSUE THREAD

**Issue by DanTup** [sourcegraph/cody#2585]
### Version

main f2e64874

### Describe the bug

When editing a file that doesn't have a file URI (such as my workspace settings - although it's not clear to me why that's not a file URI), I see errors like this in the console:

![image](https://github.com/sourcegraph/cody/assets/1078012/a6f68219-c619-449a-88de-af17e12a1bc3)

### Expected behavior

No errors

**Comment by DanTup** [comment]
@abeatrix I'm not sure whether we intend to ignore or not-ignore any no-file URIs, but it actually seems like there's code here that almost handles this, but specifically lets the user-data scheme through (but ignore helper then fails on it because we expected only file URIs):

https://github.com/sourcegraph/cody/blob/cfa212c03ad33ffb99c4605cf0eebae4b6b0eaca/vscode/src/completions/context/retrievers/jaccard-similarity/jaccard-similarity-retriever.ts#L101-L109

**Comment by abeatrix** [comment]
> @abeatrix I'm not sure whether we intend to ignore or not-ignore any no-file URIs, but it actually seems like there's code here that almost handles this, but specifically lets the user-data scheme through (but ignore helper then fails on it because we expected only file URIs):
> 
> https://github.com/sourcegraph/cody/blob/cfa212c03ad33ffb99c4605cf0eebae4b6b0eaca/vscode/src/completions/context/retrievers/jaccard-similarity/jaccard-similarity-retriever.ts#L101-L109

Interesting! I wasn't aware of the 'vscode-userdata' file but I'd assume we would want that to be ignored by default? wdyt 🤔 ?

**Comment by DanTup** [comment]
Probably - but I wonder if there's other code that might be passing other URIs like this. Should we update `IgnoreHelper` to just reutrn true (always ignore) for non-file URIs instead of throwing? 🤔

**Comment by DanTup** [comment]
I'm failing to reproduce this now.. if you have any ideas what I might've done to go through this code path, let me know! I've tried opening the settings files both as JSON and the UI, having it active, in the background, opened and closed... Unfortunately I didn't keep the full stack trace to know why it was going in jaccard-similarity-retriever.

**Comment by abeatrix** [comment]
> Probably - but I wonder if there's other code that might be passing other URIs like this. Should we update `IgnoreHelper` to just reutrn true (always ignore) for non-file URIs instead of throwing? 🤔
> 
> 
> 
> When I wrote it, passing a non-file URI seemed like a bug, but perhaps it's very easy for documents to be non-files and it's a pain for every caller to have to handle this.
> 
> 
> 
> (this won't fly if we need to support virtual workspaces or similar now or in future though)

For this stage, imo we should just focus on supporting files and return true for all non-files like you suggested, since non-files cannot be indexed and are not supported by Sourcegraph anyway. Wdyt?

jaccard-similarity-retrieve is used by auto completion so we can probably reproduce by trying to trigger an autocomplete iirc.

**Comment by philipp-spiess** [comment]
This error will also completely break autocomplete if a non-code file is open (e.g. vs code settings) as the error bubbles through.

Not sure about what would be a good use case. Maybe we make the the `isIgnored` function nullable and let the caller decide what it should do with this?
