### ISSUE TITLE
bug: Unexpected end of JSON input {Suggested resolution within}

### ISSUE THREAD

**Issue by Kynlos** [sourcegraph/cody#2589]
### Version

1.0.5

### Describe the bug

Unexpected end of JSON input when (suspected) reaching output token limits causes code generation to stop mid-stream and occasionally causes the "stop generating" button to stop working so the chat window is no longer usable.

### Expected behavior

When encountering the "unexpected end of JSON input" error, Cody will suppress the error display in the chat webView. Instead, an automated prompt will be initiated, requiring engineering for consistent outcomes. The prompt will instruct, "Continue generating from where you left off. Do not provide any additional commentary." The model will then resume code generation from the interrupted point until completion. This approach may lead to partially unfinished lines from the prior output being restarted from the beginning of that line. Users can typically identify this, but to enhance clarity, the option of disabling "streaming responses" for additional code replies is considered. Programmatic comparison of the last line from the initial output with the first line of the subsequent response can help mitigate issues. Once the entire code is generated, Cody will concatenate all the responses into a unified code-block using internal methods, not relying on model generation output. This implementation aims to provide extended response possibilities, particularly useful when refactoring substantial code segments.

### Additional context

Issue was caused with:

**Model:** GPT4
**Total Input Tokens:** 2048 (Tiktoken) - **Characters** 9090
**Total Output [First reply before fail]:** 827 - **Characters**: 3413
**Total Output [After 2nd prompt to continue generating]:** 179 - **Characters** 775
**Combined Total Output:** 1005 - **Characters** 4182
**Method Used:** Cody Chat webView

------------
**Log output from trying the method suggested in "Expected Behaviour":**

### Initial Prompt:
 **logEvent: CodyVSCodeExtension:chat-question:recipe-used VSCode {"properties":{"requestID":"ea8aea5a-2706-484a-86dd-9b3804b00415","chatModel":"openai/gpt-4-1106-preview","promptText":"Refactor this code without providing commentary","contextSummary":{}},"opts":{"hasV2Event":true}}**

█ telemetry-v2: recordEvent: cody.recipe.chat-question/recipe-used: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":10},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]},"timestamp":"2024-01-05T16:07:11.146Z"}

### Where Cody Errors:
█ CompletionLogger:onError: {"type":"completion","endpoint":"https://sourcegraph.com/.api/completions/stream","status":"error","duration":60179,"err":"failed to decode event payload: unexpected end of JSON input - body: {\"id\":\"chatcmpl-8dh11MkjVp5nVzMXHSFnqQhITUE3V\",\"object\":\"chat.completion.chunk\",\"created\":1704470835,\"model\":\"gpt-4-1106-preview\",\"system_fingerprint\":\"fp_3905aa4f79\",\"choices\":[{\"index\":0,\"delta\":{\"content\":\"       \"},\"logprobs\":null,\"finish_rea"} 

█ SimpleChatPanelProvider: getEnhancedContext > embeddings (start)
█ SimpleChatPanelProvider: getEnhancedContext > searching local embeddings
█ LocalEmbeddingsController: query returning 0 results
█ SimpleChatPanelProvider: getEnhancedContext > embeddings (end)

### Request for the model to continue generating
█ logEvent: CodyVSCodeExtension:chat-question:recipe-used VSCode {"properties":{"requestID":"c1913e60-7fa3-484d-829c-6a1d680ca32e","chatModel":"openai/gpt-4-1106-preview","promptText":"continue generating from where you left off. Don't provide additional commentary","contextSummary":{}},"opts":{"hasV2Event":true}}

### Continuation success:
█ telemetry-v2: recordEvent: cody.recipe.chat-question/recipe-used: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":10},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]},"timestamp":"2024-01-05T16:08:35.896Z"}
█ CompletionLogger:onComplete: {"type":"completion","endpoint":"https://sourcegraph.com/.api/completions/stream","status":"success","duration":13694} 
█ logEvent: CodyVSCodeExtension:chatResponse:hasCode VSCode {"properties":{"lineCount":23,"charCount":775,"requestID":"c1913e60-7fa3-484d-829c-6a1d680ca32e"},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent: cody.chatResponse.new/hasCode: {"parameters":{"version":0,"metadata":[{"key":"lineCount","value":23},{"key":"charCount","value":775},{"key":"contextSelection","value":10},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]},"timestamp":"2024-01-05T16:08:49.595Z"}

**Comment by jdorfman** [comment]
cc @abeatrix

**Comment by abeatrix** [comment]
> cc @abeatrix 

I think this is a feature request and not a bug as this is the default behavior for all LLM providers. Wdyt?

**Comment by Kynlos** [comment]
> > cc @abeatrix
> 
> I think this is a feature request and not a bug as this is the default behavior for all LLM providers. Wdyt?

Yeah I wasn't quite sure where it should have been tbf.  Want me to re-submit as a FR?

**Comment by abeatrix** [comment]
I think we can just rename the title from bug to feature request, is that right @jdorfman ?
