### ISSUE TITLE
If a Pro user downgrades to Free, old chats with a non-default LLM should be "read only"

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2591]
LLM selection is only available to Pro users. If a Pro user downgrades to free, a chat with a non-default LLM will still be available in their chat history, but the non-default LLM is not supported for any follow-up questions the user might ask. Those historical chats should become "read only." The message should be "[non-default LLM] is only available to Cody Pro users. [Upgrade](sourcegraph.com/subscriptions)"

**Comment by kalanchan** [comment]
To confirm:
- is this gated on the backend?
- add additional gating on the frontend if needed

**Comment by kalanchan** [comment]
@kalanchan to test this behaviour before moving forward

**Comment by kalanchan** [comment]
Paired with @chrsmith to test this scenario, discovered the following:
- When a pro user downgrades to free and uses a historical chat, the "pro only LLM" chat only works for ~15 mins until the rate limits get refreshed on Cody Gateway and the user is gated from the backend (see video)
- Once rate limits are refreshed, we do have gating but we don't display a nice error in the UI to indicate that the user needs to upgrade to use pro only features. Instead we just throw the error from the client (see picture)


For next steps, I suggest we first determine how big of a priority this is. As of right now to test this, we require partnership with Chris Smith to do the upgrade/downgrade flow. 


https://github.com/sourcegraph/cody/assets/51868853/1b7f9e8e-2d7f-4b34-bcb9-0417d6ae231c




![Image](https://github.com/sourcegraph/cody/assets/51868853/790ed3ef-aa09-4c69-85b2-4af7ff7d3271)
