### ISSUE TITLE
bug: cannot select first item on chat model dropdown

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#2592]
### Version

v1.0.1 - v1.0.5

### Describe the bug

After switching to a different model, i can't switch back to the first model on the menu again until I select another one:

![stuckmenu](https://github.com/sourcegraph/cody/assets/68532117/440bb2a2-c111-4eb8-b550-f6bdfe4cdac7)

### Expected behavior

you can switch between any available items on the menu on click

**Comment by deepak2431** [comment]
@abeatrix I was looking into this today. I think the issue is when the model is selected, and onLoad of a new chat window, the previously chosen model is selected by default it doesn't highlight the selected one just it highlights the first one as of default selection order.

**Comment by abeatrix** [comment]
@deepak2431 would you like me to assign the issue to you?

**Comment by deepak2431** [comment]
@abeatrix Sure, you can I will make a PR for this soon.
