### ISSUE TITLE
bug: Cannot use cody since the introduction of the Pro Plan

### ISSUE THREAD

**Issue by melMass** [sourcegraph/cody#2594]
### Version

v1.1.1704553609

### Describe the bug

Ever since the introduction to the Pro plan, I subscribed to the trial until feburary and doing this effectively locked me out (reseting on the 16th of january now).

### Expected behavior

Subscribing to Pro and the trial should not have locked me out. IIRC it used to reset daily before that

**Comment by sqs** [comment]
@melMass Can you please post the error message you are seeing? A screenshot would be very helpful. Thank you.

**Comment by k1287988804** [comment]
@sqs After I upgraded my subscription to Pro and used the chat function, there was still a limit on the number of messages, an error code of 429 was reported, and it cannot be used after that.

**Comment by melMass** [comment]
@sqs I saw the other answer in #2488 and https://github.com/sourcegraph/sourcegraph/pull/59330#issuecomment-1878658295 did seem to solve it for me! 

Feel free to close this issue if needed

Thanks
