### ISSUE TITLE
Ask Cody to Fix not always provides easy to see user feedback

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#2601]
It seems like "Ask Cody to Fix" no longer does anything when clicked (got this bug report from a friend but can repro).

<img width="873" alt="Screenshot 2024-01-08 at 12 16 02" src="https://github.com/sourcegraph/cody/assets/458591/2c0df733-b5c8-42d9-ab80-3f625b3e5ca6">

**Comment by umpox** [comment]
I think this is in cases where Cody attempts to expand the selection, but the expanded selection is too large.

There is likely a codelens error further up

![image](https://github.com/sourcegraph/cody/assets/9516420/332312c2-972f-49b4-ae05-331fe094361f)

I think we should update the smart selection to validate the expanded selection size before using it

**Comment by philipp-spiess** [comment]
Ohh yes that _is_ the case for me. @luastoned is this the case for you, too?

**Comment by philipp-spiess** [comment]
Perhaps we can check if the beginning of the selection is inside the viewport and if not also show an error message so there's feedback to the user?
