### ISSUE TITLE
bug: Log enhanced context toggle on click

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#2609]
RE: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1704497445571159?thread_ts=1704483248.015969&cid=C04MSD3DP5L

Requested by @taylorsperry :
> Do you know if we have an event that fires when a user clicks on the Enhanced Context toggle? Could we add one?

**Comment by taylorsperry** [comment]
Thank you, @abeatrix !
