### ISSUE TITLE
bug: cody.useContext config option does not work

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#2615]
### Version

v1.0.1 - v1.0.5

### Describe the bug

Reported by Corey Hill on slack: https://sourcegraph.slack.com/archives/C05AGQYD528/p1704736089086349

> I need a way to reliably force Cody chat to exclusively use Symf or local embeddings.  I know in the settings there is a way to select context source, but I am not convinced that is doing anything. 

### Expected behavior

Users should be able to config the type of enhanced context used via the `cody.useContext` config option

**Comment by marcodiiga** [comment]
Sorry to recomment on this but it seems the problem might still be present, 1.23.1718772677, I'm experiencing embeddings indexing on any codebase even if in settings.json `"cody.useContext": "none"` is present.
Can anyone confirm this is still happening or that it's just my local install please?
