### ISSUE TITLE
Enhanced context selector should be a toggle button with pop-up arrow

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#2618]
[Figma](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1171-37674&mode=design&t=pKiZKQ8zL0qfdu1G-0)

**Comment by beyang** [comment]
I think this is done now?
