### ISSUE TITLE
Move local embeddings as a back-fill for symf

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#2623]
[Internal Slack thread](https://sourcegraph.slack.com/archives/C0C324C91/p1704479315299139) to monitor for decision on removing local embeddings.

[PRD draft](https://docs.google.com/document/d/1DW94fQV_3G3UAAFpMzSvTqaYExtBs29huogarXRxSFE/edit#heading=h.nzmhwecrkypz) indicating local embeddings are not to be removed. If that is the case, @beyang wants local embeddings as a backfill for symf, however that is probably very few cases in practice.

After 1:1 sync with @beyang 2024-05-11, the plan is: symf to be the primary source. When local embeddings are available, query them and blend the results—either with a 70/30 60/40 etc. split or with RRF.

**Comment by kalanchan** [comment]
completed
