### ISSUE TITLE
bug: request sent to LLM without context due to large context size

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#2636]
### Version

v1.0.5

### Describe the bug

If the shared context is too large, the chat question will still be submitted to the LLM without context, leading to the LLM response that it doesn't have any context:

![image](https://github.com/sourcegraph/cody/assets/68532117/7e9bf28d-43c1-4b17-9de5-709e5c410278)

However, we wouldn't know that no context was shared due to the context's size until we open the output channel and look for logs:

![image](https://github.com/sourcegraph/cody/assets/68532117/93780fe2-ecbb-4df5-aab7-4edcb2a42402)

### Expected behavior

- let user know in the UI that the context was not shared due to context limit
- context should be truncated and share with LLM to provide a response

**Comment by deepak2431** [comment]
@abeatrix Looking into this issue!

**Comment by abeatrix** [comment]
> let user know in the UI that the context was not shared due to context limit

Fixed in https://github.com/sourcegraph/cody/pull/3528
We now display the excluded @-mention files in UI to avoid confusion:
![image](https://github.com/sourcegraph/cody/assets/68532117/2f118331-5c32-4b21-8b48-200352f0ce96)
