### ISSUE TITLE
Autocomplete: Bad multiline completion that repeats next line

### ISSUE THREAD

**Issue by sqs** [sourcegraph/cody#264]
@valerybugakov I saw the problem from #108 reoccur.

![image](https://github.com/sourcegraph/cody/assets/1976/ca11f9c1-d644-43b1-a5e1-8113e6a9a499)

I am on `v0.7.1689397232` (nightly/insiders build).

**Comment by sqs** [comment]
Saw this occur again: 
<img width="601" alt="image" src="https://github.com/sourcegraph/cody/assets/1976/5acefc07-6384-4633-9b79-f53c32af3af4">

Cody v0.7.1689706133

**Comment by philipp-spiess** [comment]
Here's another case that is super awkward:
<img width="922" alt="Screenshot 2023-07-19 at 13 49 53" src="https://github.com/sourcegraph/cody/assets/458591/2e1d1ae6-d82d-4dfd-8dab-01a9943a17b2">

Cody v0.7.1689737285
