### ISSUE TITLE
bug: NLS Search in VSC spins and fails to load

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#2645]
### Version

1.0.5

### Describe the bug

The NLS panel fails to load and just shows the "loading / spinning" animation.  

<img width="371" alt="image" src="https://github.com/sourcegraph/cody/assets/8737510/d22cbc7f-a9d4-40fc-994b-8bb90daf53bb">

I experienced the issue when switching from the pre-release version to the stable release.  

When I switch to pre-release v1.1.1704822233 it loads correctly.  

### Expected behavior

The NLS panel loads and shows a box to execute a search.

**Comment by kalanchan** [comment]
@chillatom i'm going to close this, if it's still an issue please open

**Comment by chwarwick** [comment]
@kalanchan still an issue on v1.8.3 for me.  I've never seen this work. 
<img width="393" alt="image" src="https://github.com/sourcegraph/cody/assets/6098507/c6598061-66cc-4d95-bf23-6d27a535b99c">
