### ISSUE TITLE
bug: no environment info for displayPath function (call setDisplayPathEnvInfo; see displayPath docstring for more info)

### ISSUE THREAD

**Issue by tomo-dev-2018** [sourcegraph/cody#2734]
### Version

vscode-v1.2.1705244830

### Describe the bug

Doesn't work at all. Displays the following:
__________
no environment info for displayPath function (call setDisplayPathEnvInfo; see displayPath docstring for more info)
__________

### Expected behavior

Should work.

**Comment by kalanchan** [comment]
hey all, if this is still an issue please create a new ticket, thanks!
