### ISSUE TITLE
bug: Request Failed: http2: server sent GOAWAY and closed the connection;

### ISSUE THREAD

**Issue by akagami-harsh** [sourcegraph/cody#2735]
### Version

v1.1.3

### Describe the bug

![image](https://github.com/sourcegraph/cody/assets/122517264/d70c3a9b-fa53-4d93-aa40-924e93271bdf)

### Expected behavior

this was working till today

**Comment by philipp-spiess** [comment]
@akagami-harsh Thanks for posting this. We're aware of some issues right now in the Cody backend and are investigating. Hopefully I can provide an update soon!

**Comment by philipp-spiess** [comment]
We pushed a hotfix to fix this particular error. We're still having some issues with latencies, especially for Autocomplete, that we're working on, however the chat issue should be resolved. Please let us know if you still have issues!

**Comment by akagami-harsh** [comment]
now getting this error occasionally 
![image](https://github.com/sourcegraph/cody/assets/122517264/2dab33ff-9301-4a48-8ea2-e46f4e86ee30)
