### ISSUE TITLE
Chat: Better context summarization and truncation

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#2769]
### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

Cody context is truncated, causing unquantified forgetting and poor performance. We tried simply showing the user an error message when this happened, but that was confusing.

### Why is this feedback important? Please describe the rationale.

Chat and inline edits are a core part of the Cody experience and we want it to be as good as possible. But LLM context sizes are limited or large context windows are slow, so we have to manage the limited context window size that we have.

### Describe the solution you'd like to see

Here's the chat context truncation behavior we have today. Include the following until the limit is reached, then truncate:
- Preamble
- Existing transcript up to current message, prioritizing recent messages (that is, current message is the most important)
- Explicit tagged context up to current message, prioritizing recent messages (that is, current tagged context is the most important)
- Current enhanced context

We should do some hand inspection of this truncation, but I think we will do better with something like:
- Preamble
- Current message
- Current explicit tagged context
- Current enhanced context (note, to this point, we are basically like "new chat" context.)
- Existing transcript *and* tagged context, prioritizing recent messages (that is, previous bot response is the most important, and tagged context is likely to be included.)

### Describe any alternatives that could be considered

Some other casual ideas:
- Have the LLM giving feedback along with its response about which context sources it found useful, and boost the priorities of those in the replayed transcript (@rishabhmehrotra has mentioned wanting one-shot learning in the transcript, this is a little bit like that...)
- Summarize the existing transcript instead of truncating it, at the cost of an extra turn.

**Comment by blarvin** [comment]
Will it be possible in future to DELETE irrelevent chat messages from a conversation, and have the context updated accordingly? Is that a thing? (I created a feedback issue #2579  suggesting a delete chat message feature - mostly its a UX thing, but context would be major bonus )

**Comment by kalanchan** [comment]
@dominiccooney @chillatom to discuss what we need to do here to preserve context in each multi turn chat
