### ISSUE TITLE
Telemetry (CodyUseCaseSelected) on Hubspot personal/work form not firing correctly

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2771]
Bug: currently this event is not firing: https://app.amplitude.com/analytics/sourcegraph/chart/new/8el7i73s

Requirements in this row: https://docs.google.com/spreadsheets/d/1QXnrHkgGLXdbfHEhI_VjtDTy-mCtnK1qri3IMQu7rNk/edit#gid=1704312181&range=20:20

**Comment by chrsmith** [comment]
Moving to the "Backlog". This seems like a bug and something the SSC/PLG team should drive, but where exactly that CodyUseCaseSelected form shows up and how it pushes data to HubSpot, etc. needs some investigation.

**Comment by chenkc805** [comment]
This is working now, thanks to Gitstart. https://github.com/sourcegraph/sourcegraph/pull/59856
