### ISSUE TITLE
feedback: Will be useful to define the language to /doc that piece of file

### ISSUE THREAD

**Issue by arthurduarte1** [sourcegraph/cody#2787]
### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [X] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

Select or set on "project config file" the language to be used to generate the documentation on code.

### Why is this feedback important? Please describe the rationale.

Some projects I'm involved in need to have doc files in different languages, such as English.

### Describe the solution you'd like to see

Maybe something like /doc-language or even the possibility to set up a project config file and define it there.

### Describe any alternatives that could be considered

Today I'm using the /doc command and after that, I select the text and use the /edit command asking to translate to my language.

### Additional context

I'm using this functionality on PHP code.

**Comment by umpox** [comment]
Hi @arthurduarte1

You should be able to do this in the next Cody release with the `cody.edit.preInstruction` setting in VS Code.

For example:
```
"cody.edit.preInstruction": "If writing documentation, always produce your output in English"
```
