### ISSUE TITLE
bug: Autocomplete does not display an warning/error status when the users access token is no longer valid

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/cody#2788]
### Version

v1.1.3

### Describe the bug

When an access token is invalidated the following happens:

- The user attempts to chat or uses a chat based command, an error message is displayed "Invalid access token"
- The user attempts an inline edit command like "Document Code" and error message is present "Applying edits failed" which shows the invalid access token error
- Autocomplete - there is no indicator that it is now disabled.  The icon does not spin but also doesn't show the warning color that would be present if the token was invalid when the ide was opened.

### Expected behavior

The cody icon should update to the warning color when the access token is no longer valid.

**Comment by aramaraju** [comment]
@kalanchan Can you check if this bug is either resolved or handled already on the Clients team?
