### ISSUE TITLE
bug: improper escaping in inline edit

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2790]
### Version

reported by community user, not sure of the version

### Describe the bug

Reported by a user on 12/19, so might be fixed. 
<img width="695" alt="Screenshot 2024-01-17 at 3 41 36 PM" src="https://github.com/sourcegraph/cody/assets/43555476/6abc2d97-1e4b-40bc-9e61-0f4ab030f408">

### Expected behavior

Should escape properly. I'm not seeing this behavior in .ts files, but can we double-check for c#?

**Comment by umpox** [comment]
closed by https://github.com/sourcegraph/cody/pull/4085
