### ISSUE TITLE
bug: Cody rate limit does not reset for pro plan

### ISSUE THREAD

**Issue by briskteq-faiz** [sourcegraph/cody#2793]
### Version

1.1.3

### Describe the bug

The rate limit in vs code does not reset as per the described message and i'm not able to access any features of cody at all.

### Expected behavior

The cody chat, edit and autocomplete should behave correctly and the limit should be reset daily

**Comment by kalanchan** [comment]
should be fixed now, please create a new ticket if it's an issue or contact our support team
