### ISSUE TITLE
bug: Cody Does Not Properly Communicate When Secure HTTP protocol is needed for connection to Sourcegraph

### ISSUE THREAD

**Issue by alexAtSourcegraph** [sourcegraph/cody#2802]
### Version

as of v 1.1.2

### Describe the bug

When using the Sourcegraph Instance URL without https and instead using HTTP Cody will generate an authentication error regardless of which auth method is used. (URL or access token) http://domain.sourcegraph.com

<img width="467" alt="Cody_Authentication" src="https://github.com/sourcegraph/cody/assets/86978415/3bdb81f3-6e57-41ba-ac29-d89252e50402">

### Expected behavior

I would expect Cody to receive a 400 or 403 request from the Sourcegraph instance handle that case and suggest that the user add https to the Sourcegraph instance URL or automagically add it to the URL when parsing to avoid the error all together.

If 403/400 and http protocol used retry with https.
If retry fails with a refused connection then show authentication error.
If 403/400 and https protocol used then show authentication error.

**Comment by kalanchan** [comment]
hey all, if this is still an issue please create a new ticket, thanks!
