### ISSUE TITLE
bug: Chat submit button hides on large input

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#2824]
### Version

1.1.3

### Describe the bug

The chat button gets hidden when large text is used in the input:

https://github.com/sourcegraph/cody/assets/44617923/3e79de04-f5bd-46c7-bb94-12791d2c6775

### Expected behavior

The input button should not be hidden.

**Comment by deepak2431** [comment]
CC: @abeatrix

**Comment by DanTup** [comment]
https://github.com/sourcegraph/cody/pull/2837 should make this better by restricting the chat input to 80% of the viewport. You could still resize the window very small and cause parts to not be visible, but it should handle the normal cases with reasonable sized windows and just large inputs.

**Comment by deepak2431** [comment]
@DanTup I think yeah that should fix it.
