### ISSUE TITLE
Cody Chat in VS Code Secondary Side Bar

### ISSUE THREAD

**Issue by rickdroneflytecom** [sourcegraph/cody#2828]
### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

Instead of Cody's chat taking up coding space by using a coding tab, I would really like for Cody to converse in the secondary side bar, as Copilot does.

### Why is this feedback important? Please describe the rationale.

Coding space is crowded enough with just code. Having to fit Cody chat into a tab in the coding area isn't optimal.

### Describe the solution you'd like to see

See how Copilot can function completely within the Secondary Side Bar. That is far superior than having to chat in a coding tab, as Cody currently does.

**Comment by claidler** [comment]
This is a major blocker for me. 

If I have 2 files open side-by-side and I go to open a new Cody chat, one of my files in the split gets replaced with the Cody chat.

No other option I'm aware of works like this (Cursor, Copilot Chat, Phind, Codeium) and I can't understand the design decision here?

**Comment by jdorfman** [comment]
@rickdroneflytecom @claidler thanks for sharing this. Our product team will take a look

**Comment by claidler** [comment]
Thanks @jdorfman  !

**Comment by claidler** [comment]
@jdorfman fyi I'm not sure how I feel about this now. I just had a really enjoyable experience with it. Possibly because I was on a laptop and it was nice that it took over the split pane because I only have so much screen space. Also kind of like having chat history available via ctrl+p. Maybe it felt unusual to begin with but it may be growing on me.

**Comment by jdorfman** [comment]
@claidler I'm in the same boat. At first, I was like "Why did we change this!?" then as time went on I actually found it more convenient. They are disposable.

**Comment by claidler** [comment]
@jdorfman ah, I didn't realise you changed it. It kind of makes sense from the perspective that for the most part we're looking at suggested code along with the text, so why shouldn't it be in a split like this with the rest of your code. I think I'm converted from 'this is a major blocker for me'.

**Comment by jdorfman** [comment]
@claidler can you shoot me an email about https://github.com/claidler/htmx_go_tailwind_starter
 
 We have a paid guest blog post program and I think it would be a great fit. community@sourcegraph.com
