### ISSUE TITLE
Make Enhanced Context more discoverable - Add CTA to chat transcript for Free/Pro users

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2838]
We know that the "Enhanced Context" button isn't easily discoverable for users. This is a problem for our Free/Pro SKU because we need users to enable embeddings so that we can continue learning about the value that embeddings context brings to chats. 

This issue partially addresses the effort to make Enhanced Context more discoverable by adding a CTA to the top of the chat transcript that opens the Enhanced Context popup. (Follow-up issue https://github.com/sourcegraph/cody/issues/2839) See design below. 

**Only Free/Pro users should see this notification**. We'll add a different one for enterprise users once multi-repo context is enabled. 

The CTA should only be displayed once/chat (if a user asks follow-up questions in the same chat, they don't see the CTA in Cody's subsequent responses). 

To measure the effectiveness of this CTA, we should add an event that we can log. The simplest solution is probably to adapt the existing event [added here](https://github.com/sourcegraph/cody/issues/2609#event-11420138487).

![image](https://github.com/sourcegraph/cody/assets/43555476/0e976948-5bf4-4c7e-8ef0-141bebfe1de6)

**Comment by abeatrix** [comment]
@taylorsperry is the engineering task is to add the "Enable Embeddings" if the users do not have it enabled? 

Is Enable Embeddings the correct wording if we only support local Embeddings now? @toolmantim

**Comment by abeatrix** [comment]
We have updated to open the enhance context settings modal on first chats to increase discoverability in https://github.com/sourcegraph/cody/pull/3547:

![image](https://github.com/sourcegraph/cody/assets/68532117/052c6d4a-7064-4a1b-80dc-abbbf8726e03)
