### ISSUE TITLE
Improve discoverability/understanding/onboarding for context sources (embeddings/symf for PLG, repo & multi-repo for Enterprise)

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2839]
We know that the "Enhanced Context" button isn't easily discoverable for users. This is a problem for our Free/Pro SKU because we need users to enable embeddings so that we can continue learning about the value that embeddings context brings to chats.

This issue is a follow-up to https://github.com/sourcegraph/cody/issues/2838. The goal is to make Enhanced Context more discoverable by adding a description to the Enhanced Context button prompting users to "Complete Setup: Enable Embeddings." See design below. 

**Only Free/Pro users should see this notification.** We'll add a different one for enterprise users once multi-repo context is enabled.

The description should only be displayed under the following conditions: 
- The user is a free/pro user
- The user has opened a new folder that doesn't have embeddings. (The description should only appear once. Whether or not the user enabled embeddings for the folder, they won't see the description again the next time they open the folder.) 

To measure the effectiveness of this CTA, we should add an event that we can log. The simplest solution is probably to adapt the existing event https://github.com/sourcegraph/cody/issues/2609#event-11420138487.

https://github.com/sourcegraph/cody/assets/43555476/3145af38-181f-4039-9975-820e419fb081

**Comment by kalanchan** [comment]
@chillatom needs follow up

**Comment by toolmantim** [comment]
I've an updated design here that covers both PLG and Enterprise users:
https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1447-39182&mode=design&t=cB0ygKAkoURvrspK-4

Let's get this in, we can't have people missing these features.

### PLG

<img src="https://github.com/sourcegraph/cody/assets/153/df228468-9416-4905-a1ac-cd1563e55f16" width="290">

<img src="https://github.com/sourcegraph/cody/assets/153/c464ea9b-ebd6-475f-a5c3-09493110a1dd" width="290">

### Enterprise

<img src="https://github.com/sourcegraph/cody/assets/153/6861fb99-f07e-445a-b096-e1fe587a8c6f" width="290">

<img src="https://github.com/sourcegraph/cody/assets/153/0a7f8e60-78ef-41ba-bf04-244ef17acb9d" width="290">

**Comment by sqs** [comment]
added figma comment at https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm?node-id=1447:38603&mode=design#739536448

**Comment by kalanchan** [comment]
related to #2838

**Comment by abeatrix** [comment]
@taylorsperry @toolmantim is there other things we will need to do on the eng side for this issue?
So far we have:
- https://github.com/sourcegraph/cody/pull/3547 merged
 - https://github.com/sourcegraph/cody/pull/3566 review

**Comment by kalanchan** [comment]
closing unless we have more tasks to do
