### ISSUE TITLE
Update Enhanced Context copy and link to docs

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2840]
This is what the Enhanced Context popup looks like today. 

<img width="322" alt="Screenshot 2024-01-21 at 12 03 30 PM" src="https://github.com/sourcegraph/cody/assets/43555476/3fb6d2eb-0df1-499c-ba65-9602a7fa7ef6">

We should add a Learn More link that directs users to docs.sourcegraph.com/cody, unless, @MaedahBatool, there's a more specific link we can use (see https://github.com/sourcegraph/sourcegraph/issues/59730). 

![image (1)](https://github.com/sourcegraph/cody/assets/43555476/eb760f72-b2fe-4a2e-b5d6-4761beeca3cc)

@chillatom Do you have any suggestions for how we might improve the copy and still keep it to ~1 sentence? I suspect they should be slightly different for Free/Pro vs Enterprise users. Free/Pro should explain that we use symf automatically (true?) and encourage the user to enable embeddings; for Enterprise, the copy should explain that we use keyword search and encourage the user to add more repos to their context.

**Comment by kalanchan** [comment]
I believe this is done!

![CleanShot 2024-01-30 at 17 32 10@2x](https://github.com/sourcegraph/cody/assets/51868853/21a017de-d381-4812-9f21-61cd1dc116f7)
