### ISSUE TITLE
bug: Can't sign in to use Cody, SimpleChatPanelProvider: postError

### ISSUE THREAD

**Issue by canadaduane** [sourcegraph/cody#2852]
### Version

v1.1.3

### Describe the bug

When using VSCodium, I try to log in to Cody by pressing the "Sign in with Github" button (or any other button) and nothing happens.

In the console, the log for Cody has the following output each time I press a button:

```
logEvent: CodyVSCodeExtension:auth:simplifiedSignInGitHubClick VSCode {}
SimpleChatPanelProvider: postError: Invalid request type from Webview Panel: auth
```

### Expected behavior

I should be able to sign in and use Cody

### Additional context

![image](https://github.com/sourcegraph/cody/assets/129/93af0eb6-c5a3-4bae-845b-01edd4184a25)

**Comment by abeatrix** [comment]
Resolved by https://github.com/sourcegraph/cody/pull/2904

Please feel free to reopen if the issue persists in the latest release for you 🙇🏻‍♀️
