### ISSUE TITLE
Expand query format to multiple LLM generated candidates

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#2856]
Just a quick thought when scanning the Squirrel dataset.  All the questions are of the form 

`what do we mean by {reference}?`

Can we add manipulations of a given query for a fixed answer to get a better sense of how Cody handles different formed responses with the same intent?

e.g. "what do we mean by Alluxio Assembly?" becomes

1. "Can you explain what Alluxio Assembly refers to?"
2. "I'm curious about what is meant by the term 'Alluxio Assembly'."
3. "What is the definition of Alluxio Assembly?"
4. "Could you clarify what Alluxio Assembly is?"
5. "I'm trying to understand, what does Alluxio Assembly mean?"
6. "What does the term 'Alluxio Assembly' signify?"
7. "Can you tell me about what Alluxio Assembly stands for?"
8. "I'd like to know the meaning of Alluxio Assembly."
9. "What's the concept behind Alluxio Assembly?"
10. "Could you elaborate on the meaning of Alluxio Assembly?"

**Comment by rishabhmehrotra** [comment]
i've added a step to query gpt-4 with the base question, answer pair and generate 5 variations of the questions.
the enriched dataset has 19K rows now ([gcs link](https://console.cloud.google.com/storage/browser/_details/ai-exp-storage/squirrel_questions_v5.csv;tab=live_object?project=rishabh-experiments))
i've also added a new field questionID, so we can keep track of metrics at the question-group level
