### ISSUE TITLE
Soften the error message when a chat reaches its context limit

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2857]
Related to https://github.com/sourcegraph/cody/issues/2600

Today, users see a very scary-looking notification when a chat reaches its context limit. See below: 

![Screenshot 2024-01-18 at 15 37 35](https://github.com/sourcegraph/cody/assets/43555476/e6c89114-6877-49d5-9006-d991a6ce6508)

We should soften this message so that users know that they can continue chatting, Cody just might "forget" some of its previous context. 

Suggested copy: 

"This chat has exceeded its token limit, which means Cody might forget its previous context. You can still keep chatting here, but you may want to [start a new conversation](link to open new chat). Learn more in the [Cody docs](docs.sourcegraph.com/cody)."

**Comment by chillatom** [comment]
A few general questions. 

1. Terms like "token" and "context" are very familiar to those who work with LLMs, but may not be familiar to all users.  Should we avoid them?
2. Expanding on (1) should we focus here on highlighting the experience (e.g. Cody forgets things from prior messages) or do we want to get into the technical weeds for our users (e.g. why Cody forgets)?

**Comment by taylorsperry** [comment]
Great feedback, thank you! I like the less technical route (save the technical explanations to the docs, which are easier to keep up to date ;). I've added a note about that [here](https://github.com/sourcegraph/sourcegraph/issues/59730))

WDYT about this? If we're going less technical, I want to make the details available to those who want to get in the weeds. 

"[Notice icon] Cody may start to forget previous information the longer your conversation is. Consider [starting a new chat](new chat link) or [learn more](docs link)"

**Comment by toolmantim** [comment]
Can we remove the notice altogether once the edit changes are merged?

**Comment by taylorsperry** [comment]
I feel like we've gotten feedback that it's confusing when Cody "forgets" something that it knew previously. I like that this option favors transparency, but are you worried about it being annoying, @toolmantim ?

**Comment by chillatom** [comment]
> "[Notice icon] Cody may start to forget previous information the longer your conversation is. Consider [starting a new chat](new chat link) or [learn more](docs link)"

I really like this.  

Also +1 to removing the notice icon or swapping it for something a little less associated with a failure / error etc. Perhaps a lightbulb 💡 since this is more like a tip?

**Comment by chillatom** [comment]
Slight aside, I notice that the error banner is rendered as part of the output text and therefore "scrolls" out of view if the LLM is generating a lot of text.  Is this the intended behavior?

**Comment by taylorsperry** [comment]
I just chatted with @toolmantim about this and he reminded me that we had an action item to get to the bottom of why we added this notice in the first place. We agreed that we can just remove the notice for now, and once we have a better understanding of why we added it to begin with, we can align on a solution. I'll close this issue and create a separate one for that.
