### ISSUE TITLE
Test query term expansion ahead of call to get context query

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#2859]
Test the quality impact of query term expansion

Per discussion in [Enterprise Cody Context RFC](https://docs.google.com/document/d/1t3-NrlgYd1tdgbabN3YoPpumuP0WpFeOTp_B1C14Rnw/edit?disco=AAABD4LuX28)

@chwarwick says that query term expansion by LLM is not necessarily required since CodyContext search can handle the full search term.

**Comment by dominiccooney** [comment]
Adding some more details here:

The user types messages in a chat box.

Other context sources don't handle that input "as is." symf does an LLM turn to expand it to a set of keywords which it stems before doing a keyword search. cody-engine/local embeddings does an embedding.

Question is, how well does `getCodyContext` perform, given the user message as-is? And how well does 5.2 perform with embeddings disabled? If it is not good enough then we need to do something before Feb GA. (For example, we could crib from the symf design and do the LLM turn to expand queries to keywords.)

**Comment by kalanchan** [comment]
Closing this off to evaluate and benchmark the default behaviour of the Search API vs embeddings first. 

term expansion can come after we get a sense of how it currently performs
