### ISSUE TITLE
Remove the scary-looking notification when a chat reaches its context limit

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2860]
Today, users see a very scary-looking notification when a chat reaches its context limit. We added this just before the Dec release and we know that it's created a lot of confusion for users. We're taking other steps https://github.com/sourcegraph/cody/issues/2600 to discourage users from long, ongoing chats which we expect to help mitigate Cody's forgetfulness. 

Once we have a better understanding of the impact on users when Cody's context window is full, we can make a decision about what else we need to do to address it. 

![Screenshot 2024-01-18 at 15 37 35](https://github.com/sourcegraph/cody/assets/43555476/e6c89114-6877-49d5-9006-d991a6ce6508)

Opened in favor of https://github.com/sourcegraph/cody/issues/2857.

**Comment by kalanchan** [comment]
fixed in #2891
