### ISSUE TITLE
bug: Search Local Index

### ISSUE THREAD

**Issue by XdTyatMochi** [sourcegraph/cody#2863]
### Version

Version: 1.86.0-insider

### Describe the bug

The primary issue we're encountering is centered around the Search Index, which is currently experiencing a critical bug that prevents it from indexing the repository as intended. This bug has created a significant barrier for Cody, who is unable to gain access to my repository due to this malfunction. At this juncture, the only functionality Cody seems capable of is producing simple, 20-line codes, a task reminiscent of the capabilities of ChatGPT-4. However, this level of performance is not particularly beneficial for our needs. If Cody remains unable to access my repository, its utility is severely compromised, reducing it to a tool with limited functionality that doesn't extend beyond basic conversational interactions similar to those of ChatGPT-4. This limitation significantly undermines the potential applications and benefits we could derive from Cody, rendering it nearly useless in our current context.

![Code_-_Insiders_reGLTlDfUS](https://github.com/sourcegraph/cody/assets/95565671/88b49994-23ae-4b80-9c9c-0b080a911334)

### Expected behavior

Every time I click on Retry Local Index nothing happens. Here is the log for that
![Code_-_Insiders_iKs3D6TekS](https://github.com/sourcegraph/cody/assets/95565671/a64a7904-bbf7-4fa6-8262-dbabf944b795)
![Code_-_Insiders_a1QVmjYONr](https://github.com/sourcegraph/cody/assets/95565671/50f76f81-523d-446d-bf04-c0ffa0ff019f)

**Comment by kalanchan** [comment]
@XdTyatMochi Is this issue still happening? We've tested this on the latest version and it seems to be working now
