### ISSUE TITLE
Add events for users including `@-file` or `@#-symbol` tagging in chat inputs

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#2867]
Today, Cody Chat in VSC supports tagging files (with `@`) and symbols (with `@#`) to include in Cody's context, but we don't have a way of knowing how valuable this functionality is to users. 

Can we add telemetry to log these events (without capturing the actual file or symbol that was tagged) so that we can measure this?

**Comment by kalanchan** [comment]
@kelsey-brown how should we get started on this? I assume you will have to enable the data collection fields first?

**Comment by abeatrix** [comment]
@taylorsperry @kalanchan the telemetry should be available in looker 🫡  https://sourcegraph.slack.com/archives/C05AGQYD528/p1707962756304409?thread_ts=1707959968.144029&channel=C05AGQYD528&message_ts=1707962756.304409

**Comment by abeatrix** [comment]
Looker: https://sourcegraph.looker.com/looks/1883
Doc: https://docs.google.com/document/d/17Ia6LEcwnPu6pOBv6UZlP0aJGEZbIjxDjPiYdbnliWI/edit
