### ISSUE TITLE
Autocomplete: Add telemetry for how long accepted completions stay in the codebase

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/cody#287]
Log whether or not the code within an accepted completion remains in the codebase, vs. getting edited or deleted relatively quickly.
It would be very impactful as a measurement of value for our potential customers.

Open question: how long do we want to wait before we do this check? Something like 15 min? What interval do other AI autocompletion tools use?

**Comment by philipp-spiess** [comment]
> Open question: how long do we want to wait before we do this check? Something like 15 min? What interval do other AI autocompletion tools use?

Copilot does 15s, 30s, 2min, 5min, 10min: https://thakkarparth007.github.io/copilot-explorer/posts/copilot-internals.html#question-1-how-is-the-40-number-measured :)
