### ISSUE TITLE
bug: incorrect context in Flutter

### ISSUE THREAD

**Issue by zipos** [sourcegraph/cody#2878]
### Version

v1.2.1706022447 pre-release

### Describe the bug

![image](https://github.com/sourcegraph/cody/assets/74840471/71ecf4e3-6b68-4671-8f38-84e5bae3990c)

As above; totally irrelevant context from platform specific folders gets processed and only the currently open file from the lib folder which it probably should read the entirety of.

### Expected behavior

I expected it to include most of the lib folder and not untouched platform specific folders and to give me a response aware of multiple files that I actually changed and created.

**Comment by Zipos** [comment]
Follow up: It doesn't work correctly in Android Studio either.
![image](https://github.com/sourcegraph/cody/assets/74840471/9916875f-e7e8-4c8f-8b7b-c879ad77fb86)
![image](https://github.com/sourcegraph/cody/assets/74840471/d6b24d9c-4647-4b7e-bb2c-34ddf75d332d)
