### ISSUE TITLE
Option for double quotes

### ISSUE THREAD

**Issue by Creative-Difficulty** [sourcegraph/cody#2894]
### Description:

I like to use "" (double quotes) in my code, but cody autocomplete only uses single-quotes, which is very annoying.

### Objectives:

Add a setting in VSCode to switch between " and '

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### Related Docs:

- [PRD: Your-Title]()

**Comment by kalanchan** [comment]
hey @Creative-Difficulty, could you re-submit this as a [feedback issue](https://github.com/sourcegraph/cody/issues/new?assignees=&labels=clients/vscode,feedback&projects=sourcegraph/387&template=feedback.yml&title=feedback:+)? We are only using PRD issues for internal use.

Thanks!
