### ISSUE TITLE
Autocomplete: use the next line indentation for the hot-streak document context updates

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/cody#2903]
Based on @philipp-spiess's idea, [discussed](https://github.com/sourcegraph/cody/pull/2881#discussion_r1466389600) in [this PR](https://github.com/sourcegraph/cody/pull/2881):

We have all this fancy logic here to find out what the indentation is that the next completion is going to be inserted at, but we do already have the exact indentation from the LLM response.

E.g. imagine we have these two lines, the first one is the "regular" completion and the next one the hot-streak:

```
const foo = fetch(
  'https://example.com',
```
When we parse the hot-streak, we actually trim the start of the completion so it'll have the content of 'https://example.com', and then we reverse-engineer the whitespace based on the line above.

I’m suggesting we just use the same whitespace as returned from the LLM! That would work for:

When the hot-streak is on the same indentation (since the indentation the LLM generates will match the one VS Code uses when you press enter)
When the hot-streak is indented - The use case you just adde in this PR
When the hot-streak is unindented - Which is not handled at all right now

**Comment by beyang** [comment]
@valerybugakov is this still relevant?

**Comment by valerybugakov** [comment]
@beyang, this is a low-priority idea improvement for hot-streak completions extracted from the PR discussion. 
We can close this or keep it around since it's marked as P2. cc @philipp-spiess
