### ISSUE TITLE
bug: Biome Errors happen when you open Cody with no folder opened

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#2915]
### Version

1.1

### Describe the bug

<img width="341" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/1f06b9be-00cb-4bdd-87f4-c89ea94bdb9c">
See this

### Expected behavior

No extension issue should happen when you open just a new window

**Comment by DanTup** [comment]
Seems like a Biome extension bug - I opened https://github.com/biomejs/biome-vscode/issues/95

**Comment by arafatkatze** [comment]
@DanTup You are right. I am closing this in favour of the issue you opened.

Thank you!!
