### ISSUE TITLE
bug: chat-question:submitted event not firing correctly

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2916]
### Version

1.1.3

### Describe the bug

When using Cody in VS Code and initiating a chat, I'm not seeing the `chat-question:submitted` event firing. 

When looking in [Amplitude](https://app.amplitude.com/analytics/sourcegraph/chart/new/hlqjvycb?source=copy+url), it doesn't look like this event is firing correctly because it's only logging ~20-40 events per day, when there are thousands of `chat-question:executed` events firing instead. 

### Expected behavior

`CodyVSCodeExtension:chat-question:submitted` should be logged when a user submit a chat question from anywhere in the app (it should tell us where the request originally comes from, like code-action or command for example)
this tells us if a user has submitted a question, but it doesn’t mean their submitted question has actually get to the execution step. 

Context: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1705688851522529?thread_ts=1705688145.992259&cid=C04MSD3DP5L

**Comment by chenkc805** [comment]
CC: @kelsey-brown  for visibility

**Comment by beyang** [comment]
Still an issue?

**Comment by kelsey-brown** [comment]
Yes this is still an issue
