### ISSUE TITLE
GPT 4 version upgrade

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#2919]
<img width="750" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/bd27609d-0e05-497f-8afe-59367b2d16b0">

Pretty easy to add a PR to upgrade the GPT 4 model version. Will do it when I have a few spare cycles.

**Comment by kalanchan** [comment]
let's hold off on this for now - we should give PLG a heads up to make sure they can support this on the pro plan

**Comment by arafatkatze** [comment]
Okay I understand but lets definitely keep it in mind because the eval quality could be a lot better

**Comment by chillatom** [comment]
We already point to GPT-4 turbo for PLG Pro customers.  Can we close this?

**Comment by kalanchan** [comment]
@chillatom we're using `gpt-4-1106-preview`, I believe the ask here is to upgrade to `gpt-4-0125-preview` which is the _new_ _new_ one 😅 

regardless, we should give PLG and PMM a heads up whenever we make model updates 

see [gpt docs](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo) for reference

**Comment by philipp-spiess** [comment]
This new model seems like it could be big for Cody:

> This model completes tasks like code generation more thoroughly than the previous preview model and is intended to reduce cases of “laziness” where the model doesn’t complete a task. The new model also includes the fix for the bug impacting non-English UTF-8 generations.

It's been out for quite some time now and there's no negative backslash that I’m aware of. We should for sure update and not hold back here, seems like a quick w for our customers. PR here: https://github.com/sourcegraph/sourcegraph/pull/61272

**Comment by philipp-spiess** [comment]
@lalithorcruxer Yep. Or try out the pre-release version right now 😎 

<img width="831" alt="Screenshot 2024-03-21 at 13 59 47" src="https://github.com/sourcegraph/cody/assets/458591/60231d43-8d7c-4736-a576-1103807a1c68">
