### ISSUE TITLE
feedback: 

### ISSUE THREAD

**Issue by KernelBypass** [sourcegraph/cody#2922]
### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [X] Other

### What needs to be improved? Please describe how this affects the user experience.

Cody chat launches in a split screen - in its right half. If you launch a chat and then open any source files (doesn't matter how - via explorer tab or an outside file manager), they open in the same right half of the split screen where the chats are, which is suboptimal.

### Why is this feedback important? Please describe the rationale.

Usability is greatly reduced. End up with a messy mixture of chats and source files.
Have to constantly toss tabs with files back into the left split.

Especially bad because chat window is smaller (as it should be).

Right chat window should be for chats only.
Source files should open strictly in the left split.

### Describe the solution you'd like to see

Make the chat split window for chats only - no source files should open there.

**Comment by beyang** [comment]
Related: https://github.com/sourcegraph/cody/issues/2450

**Comment by beyang** [comment]
We're bringing chat back to the sidebar. It will be available in the next stable release (due out within the next two weeks). I believe that should resolve this issue. If not, please re-open!
