### ISSUE TITLE
Cody web uses the previous file context if the current file is exluded from the scope

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/cody#2925]
### Steps to reproduce
- open any file in a repo
- open the Cody sidebar
  - ask Cody a question
  - check the current file is included in the chat transcript
- open another file
  - exclude the current file from the scope in the scope selector
  - ask Cody a question
  - check the current file is not present in the chat transcript
  - check Cody answer

### Actual behavior
- Cody refers to the previous file 

### Expected behavior
- Cody ignores the previously referenced file and refers to the current one. As the current file is excluded from the scope, if the question is file-related, Cody should respond with some kind of "can't access the file content" message. 

[Loom](https://www.loom.com/share/e2beaed8551546b1b5d8fc4fb1374691?sid=db14226f-25d3-48ed-befb-b1b44c3ae8a3)

**Comment by kalanchan** [comment]
currently not prioritizing cody web, we'll revisit this if cody web becomes a focus area next year
