### ISSUE TITLE
follow-up: check paths that could be case-insensitive

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#2929]
context: https://github.com/sourcegraph/cody/pull/2913#issuecomment-1913674458

Currently, we are applying a workaround for instances where the relative path is being computed wrong on Windows.

Instead of applying a workaround, @DanTup: 
> we might need to think about how we check paths that could be case-insensitive)

**Comment by DanTup** [comment]
(from https://github.com/sourcegraph/cody/pull/2913#issuecomment-1915263484):

> Do you think this is an issue specified to cody/ignore? or does it affect other features as well? Trying to determine if this should be a follow-up issue for general or cody/ignore issue

I don't know if there are any other places computing relative paths in the way the ignore helper does so it _might_ not affect anything else, but it'd probably require some careful reviewing or testing to confirm.

Probably a good place to start would be to expand the tests for @sqs's new path functions to include mixed casing and make them all pass. Unfortunately I don't know if we can easily tell whether the URIs _should_ be case-sensitive though... so the easiest solution might be to make them all case-insensitive (or do what VS Code does and "guess" based on the platform, which is unfortunately not sound, but I think users of non-default case-sensitivity in VS Code are going to have issues anyway).
