### ISSUE TITLE
Autocomplete: Audit the cancellation pipeline

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#293]
Can we be 100% certain that if a request is canceled, the LLM proxy relays the cancellation? What exactly happens when a HTTP post request is closed after the request is sent and once it's pending a response? Could it be that the response is still being sent but the client computer just discards the response? 

AFAIK the server only knows that the connection is closed once it tries to send the first bytes. Is this true? 🤔  For a non-streaming request this means that we already buffered the full response payload before we find out, thus defeating the main need for cancellation to reduce LLM hits.

If that's the case, should we move to a streaming response for code completions?

cc @eseliger who knows much more about this than I do 🙈

**Comment by eseliger** [comment]
Go servers will handle request cancellation generally well, at least the context is canceled - from then on it's up to the implementer. 

Here's a simple client/server model to showcase that:

server.go
```go
package main

import (
	"fmt"
	"net/http"
	"time"
)

func handler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Sleep for 10 seconds
	select {
	case <-time.After(10 * time.Second):
		// Done sleeping
	case <-ctx.Done():
		println("request canceled")
		return
	}

	// Write response
	println("hello world")
	fmt.Fprint(w, "hello world")
}

func main() {
	http.HandleFunc("/", handler)
	http.ListenAndServe(":8080", nil)
}
```

client.go
```go
package main

import (
	"context"
	"io"
	"net/http"
	"time"
)

func main() {
	// Create a request context that we can cancel
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	// Make the request with our context
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, "http://localhost:8080", nil)

	// Do the request
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		if err == ctx.Err() {
			println("context canceled")
			return
		}
		panic(err)
	}
	defer resp.Body.Close()

	// Read the response
	_, err = io.Copy(io.Discard, resp.Body)
	if err != nil {
		if err == ctx.Err() {
			println("context canceled")
			return
		}
		panic(err)
		// Handle error which may be due to canceled context
	}
}
```

We do use the request context in the upstream client to Cody Gateway (or other providers), so the upstream request should consequently also be cancelled, which in return should cause Cody Gateway to cancel the request that is made to Anthropic/OpenAI. 
HOWEVER, it is an implementation detail whether OpenAI and Anthropic will actually handle cancellations at all, and thus not bill for what's not been done yet. I have no insight into whether they're doing that.

**Comment by philipp-spiess** [comment]
@eseliger the example is AWESOME. I ran it as well. I think I might have had a mental model issue here and thought that network requests can't detect interruptions when there is no packets being sent but maybe there's a special abort message that I wasn't aware of.

In any way this seems to be working fine. Thanks again!!

**Comment by eseliger** [comment]
Happy that helped! 

And yes, that's definitely true for involuntary disconnects like cutting the internet connection or so where the client cannot say goodbye anymore, but for our use-case here where we do controlled cancellation, the TCP FIN message should properly indicate that the connection should be terminated gracefully.
