### ISSUE TITLE
Enhanced Context Selector should not dismiss when choosing repositories

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#2938]
### Version

Main f32232e6aae6025ea2dc53af9288988c5b6a42eb

### Describe the bug

1. Sign into an Enterprise account.
2. Start a chat
3. Open the Enhanced Context Selector
4. Click the Choose Repositories button
5. Choose a repository, OK

### Expected behavior

The Enhanced Context Selector should not auto-dismiss when the Repo Picker is closed.

**Comment by dominiccooney** [comment]
Not directly related but while we are here, @toolmantim pointed out we could use `popover` instead of `dialog` for toplayer. In theory this gives us `::backdrop` *and* the relative positioning we need.

**Comment by sqs** [comment]
This appears to be (unintentionally) fixed in my WIP PR https://github.com/sourcegraph/cody/pull/3287.

**Comment by dominiccooney** [comment]
@sqs Cool! The existing focus management code that forwards document focus into the text box that caused the enhanced context selector to disappear. Thus you should check that autofocusing the text box on new chat creation is not broken.
