### ISSUE TITLE
cody isnt reading all of the code

### ISSUE THREAD

**Issue by wisdomcrafting** [sourcegraph/cody#2958]
and for some reason the code gets cut off it was reading lots of code and now it only reads 60-90 lines
 Please assist

**Comment by kalanchan** [comment]
hey @wisdomcrafting, could you file a bug [here](https://github.com/sourcegraph/cody/issues/new?assignees=&labels=bug,clients/vscode&projects=sourcegraph/387&template=bug_report.yml&title=bug:+) describing your issue? We'll look into this afterwards.

thank you!
