### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by wisdomcrafting** [sourcegraph/cody#2960]
### Version

1.2.1

### Describe the bug

cody was reading the entirety of the scripts and it stopped reading it and it defines it as this appears to be a part of a larger code structure and only reads 60-90 lines of code, i believe this started happening after the update

### Expected behavior

should read the entire code when you try to have the program explain the code or chat with you

**Comment by kalanchan** [comment]
hello, if this is still an issue please create a new ticket, thanks!
