### ISSUE TITLE
Display warning for @-mentioning massive files

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#2965]
Display warning/error message when file is too large to @ in chat

see design and input: https://sourcegraph.slack.com/archives/C05AGQYD528/p1704800906759909

**Comment by abeatrix** [comment]
@kalanchan can I get more information for the task please? 
What's the definition of a large file here? What's the expected behavior?

**Comment by toolmantim** [comment]
The Figma for this is here: https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=331-103646&mode=design&t=jidOC06CYg9nSWOI-4

I guess the bug is that if a file is too large to include in context, we just exclude it, and users are wondering why.

Ideally we detect that it will be too big at file-selection time, and ask them to provide a symbol.

**Comment by kalanchan** [comment]
what is considered too large? 🤔


Ideally we have a mechanism that detects how many tokens it's going to eat up, and make a decision there. But without it we are kinda just guess right? 

@dominiccooney any thoughts on how we can programatically calculate this

**Comment by toolmantim** [comment]
An alternative to my design, which we should consider/test, is to include a summary of the file in the context vs forcing them to select a symbol. A symbol may be too large for the context too 🤔

**Comment by abeatrix** [comment]
> Ideally we detect that it will be too big at file-selection time, and ask them to provide a symbol.

What if they select a file that's within the "limit" but then they added a question that's over the overall limit? 

Should we set a maximum token limit allowed per file (not ideal) and per chat input?

Or maybe add a token counter in the chat ui to make the limit visible instead (like a tweet limit in Twitter)?

**Comment by umpox** [comment]
@toolmantim @abeatrix We should ensure we do this for the Edit logic too. I'm happy to take a look at this post-release.

I think we can use the `detail` option in the QuickPick to show a similar UI

**Comment by abeatrix** [comment]
Adding @umpox for Edit logic

**Comment by chillatom** [comment]
Is this at the complexity level that we should write an RFC?  Sounds like we have a few options

1. Warning for too large
2. Push users towards symbols
3. Gracefully handle too large files
    - summarize
    - expand context window
    - other?

There are some other edge cases to consider (some of which listed above) 

1. What if mentioning N files and the Nth pushes over the context limit
2. What if symbols are too large

**Comment by virgildotcodes** [comment]
I'm getting the warning that an ~800 line file is too large when using Claude 3 Opus. This should comfortably fit within its context window. Is this a bug, or is the context size that Cody provides intentionally smaller than the models allow?
