### ISSUE TITLE
bug: errors when using "ask cody to explain" an error

### ISSUE THREAD

**Issue by vadi2** [sourcegraph/cody#2970]
### Version

1.2

### Describe the bug

Using the "ask cody to explain" an error always gives this message:

> Cannot read properties of undefined (reading 'match')

### Expected behavior

An explanation of the error.

**Comment by cbjerg** [comment]
Same error here. Also "Ask Cody to fix" gives me "retrieved codebase context before initialization"

**Comment by umpox** [comment]
Thanks for reporting!

PR to fix: https://github.com/sourcegraph/cody/pull/3015

@cbjerg That error should be fixed in the latest release, if not please LMK and I'll take another look
