### ISSUE TITLE
feedback: Project-Specific Chat Option

### ISSUE THREAD

**Issue by chrislucca** [sourcegraph/cody#2975]
### Version

1.2.1

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

Currently, it seems that the chats are global. When I open any project, I see all the chats, even from other projects.

### Describe the solution you'd like to see

It would be useful for the chats to be specific to the open project or at least to have an option to determine whether a new chat should be considered global or project-specific.

**Comment by blarvin** [comment]
Yes! This should be obvious. At first I thought this is how it worked. I mean, it is aaaaaallll about context. The whole point of Cody is (should be) to really always be in the context of the current project, no matter what, no distractions, no side-quests, no hallucinations, no other "ideas".
