### ISSUE TITLE
Autocomplete: Rewrite and normalize indentation

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#299]
Claude Instant sometimes has incorrect indentation. Can we fix this by rewriting the response and use the indentation information from the IDE to make it fit?

**Comment by sqs** [comment]
Here's an example of bad indentation that I just saw:

<img width="901" alt="image" src="https://github.com/sourcegraph/cody/assets/1976/86a81889-2f24-42fe-9e3f-5b8a32f5ebdc">

**Comment by abeatrix** [comment]
Another example provided by @deepak2431 
![image](https://github.com/sourcegraph/cody/assets/68532117/e5ce9f4a-84bc-4e01-b959-4b3092ba344a)
