### ISSUE TITLE
feedback: Didnt complete the request

### ISSUE THREAD

**Issue by silverfin-liamwills** [sourcegraph/cody#2997]
### Version

v1.2.2

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [X] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

It was 50% right on the answer it gave, but it seemed to give up halfway through the code it was creating. 

### Describe the solution you'd like to see

Id like it to do the whole request

### Describe any alternatives that could be considered

It may have to do with the size of the file, it wasn't an insane amount of code so I would have expected it to be able to do it.

**Comment by kalanchan** [comment]
thanks for the feedback! we're aware of this issue and is working on expanding the context token output, going to close this for now
