### ISSUE TITLE
TODOs after migrating to the new cody repo

### ISSUE THREAD

**Issue by sqs** [sourcegraph/cody#3]
Now that Cody is in this new separate repo ([Slack thread](https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1688992759973489?thread_ts=1688535501.677599&cid=C04NPH6SZMW)), some remaining TODOs:

- [ ] use simpler/faster import-order from sourcebox repo?
- [x] #63
- [ ] convert vscode integ/e2e tests to vitest as runner
- [ ] slow eslint
- [ ] move relevant docs from the https://github.com/sourcegraph/sourcegraph repo `doc/cody/` dir into here; update other docs as needed to refer to this new repo
- [ ] separate tsconfig for vscode/webviews?
- [ ] lib/shared imports `vscode` in the recipe impls - lib/shared should not be vscode-specific
- [ ] dedupe lib/shared/src/common stuff
- [x] #5
- [x] #6
- [x] set up renovate?
- [x] check links in VS Code marketplace listing
- [x] set required checks

**Comment by jdorfman** [comment]
@sqs 

#6 is waiting on a JetBrains marketplace update (in progress)
#110 is waiting for your sign off
