### ISSUE TITLE
does not work using a VPN and error message is encoded as HTML as does not show well in VSCode

### ISSUE THREAD

**Issue by mikel963** [sourcegraph/cody#3009]
### Version

1.2

### Describe the bug

I get this message - but was hard to read int vscode

Please enable cookies.
Sorry, you have been blocked
You are unable to access sourcegraph.com
Why have I been blocked?
This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

What can I do to resolve this?
You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.

Cloudflare Ray ID: 84f14bb36a2c024d • Your IP: Click to reveal 91.90.124.21 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

### Expected behavior

error message should be readable

**Comment by ibro45** [comment]
This appears to still be an issue. Realized that it was due to VPN by accident.
