### ISSUE TITLE
bug: Document code command bad diff when using Azure OpenAI

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/cody#3016]
### Version

v1.2.3

### Describe the bug

When using the document code command when connected to Azure OpenAI the entire function is being duplicated in addition to the code getting added

### Expected behavior

The only diff should be the new documentation added

### Additional context

Below is a screenshot of the diff, this occurred both when highlighting the entire function or placing the cursor on the command name and triggering the document command.
<img width="1318" alt="Screenshot 2024-02-02 at 9 55 28 AM" src="https://github.com/sourcegraph/cody/assets/6098507/c07d0995-7a40-4d9c-874b-96130eff5477">

**Comment by chwarwick** [comment]
@taylorsperry it would be good if we could prioritize this for Feb release as Azure is a common choice for enterprise customers.

**Comment by umpox** [comment]
@chwarwick Enterprise customers have to opt in to use Azure OpenAI right? Is the default Claude?

I think this is happening because Edit currently defaults the custom model to use `chatModel`. I can add an `editModel` option that they would need to set instead

**Comment by umpox** [comment]
@chwarwick Can you provide some reproduction sets as to what I need to add to site configuration to replicate this?

We should only ever use `anthropic/claude-2.0` for doc/fix/test commands, so I wouldn't expect to see OpenAI being used for this

**Comment by chwarwick** [comment]
> @chwarwick Can you provide some reproduction sets as to what I need to add to site configuration to replicate this?
> 
> We should only ever use `anthropic/claude-2.0` for doc/fix/test commands, so I wouldn't expect to see OpenAI being used for this

@umpox  I can help configure an Azure OpenAI env for you.  Not all enterprise customers use or allow anthropic models, Azure OpenAI has been a common choice for several enterprises due wanting to run everything within their own environment.

**Comment by chwarwick** [comment]
@umpox  I think the difference is that not all enterprise customers use the Cody Gateway, and are commonly using things like AWS Bedrock (anthropic models) or Azure OpenAI (openai models).  We can no longer have commands that only work with specific models.
