### ISSUE TITLE
bug: Authorzing Cody for Cursor when VSC is installed

### ISSUE THREAD

**Issue by fb-rmetzker** [sourcegraph/cody#3026]
### Version

Cursor: 0.24.4,  VSC: 1.85.1

### Describe the bug

When trying to Authorize Cody for Cursor, it provides the authorization and opens the "requesting app", opening VSC if it is installed.

### Expected behavior

I would expect this to open the requesting application.

### Additional context

Cursor is built from VSC code base: 1.85.1

Commit: 1174f14681896d40a3d4e622344bddb40c086230
Date: 2024-01-29T20:09:58.730Z (4 days ago)
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by blqke** [comment]
Don't open with VSCode, take the access token in red here 
![image](https://github.com/sourcegraph/cody/assets/1248148/97cc6b98-ce1b-4582-b7ee-cdb276f0b216)

replace this with your access token and access this URI via your browser
```
cursor://sourcegraph.cody-ai?code%3Dsgp_your_access_token
```

**Comment by dannycoin** [comment]
> Don't open with VSCode, take the access token in red here ![image](https://private-user-images.githubusercontent.com/1248148/305037785-97cc6b98-ce1b-4582-b7ee-cdb276f0b216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzQ5NjIsIm5iZiI6MTcwODQzNDY2MiwicGF0aCI6Ii8xMjQ4MTQ4LzMwNTAzNzc4NS05N2NjNmI5OC1jZTFiLTQ1ODItYjdlZS1jZGIyNzZmMGIyMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMTMxMTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njc0OTllOGRhNGE4N2U2Y2YwOWIwZTE4OWFiNGRlOTI1MmRhNmM3MzI2NGY2ZWRmZWZmY2Q1Y2M0YTZlMTBlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zk140-Rd3bQtQpbG88-fDb1NbezsGDSp1Bdetchm-aM)
> 
> replace this with your access token and access this URI via your browser
> 
> ```
> cursor://sourcegraph.cody-ai?code%3Dsgp_your_access_token
> ```

this does not work..
