### ISSUE TITLE
Holistic Embedding update function 

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#3028]
A recurring issue faced by many users involves the inability to re-index embeddings within Cody. This issue aims to clarify the complexities surrounding this issue and provide a temporary workaround.

## Challenge in Re-Indexing Embeddings:

Currently, there are three primary methods used:

1. SYMf

2. Blazingly Fast Graph (BFG)

3. Remote Embeddings: might be removed potentially

Each of these methods contributes to the complexity of updating embeddings, leading to the current limitation where embeddings remain as they were at the initiation of Cody in the repo. Ideally it would be great to create like a single button that runs update index on all of the different indexing sources to bring them in sync with the current codebase. 

## Temporary Workaround:

To mitigate this issue temporarily, users can employ the following workaround:

Open multiple files or folders in your UI.
This approach allows users to circumvent the limitation of non-updatable embeddings to some extent.
Note: This is a temporary solution, and we are actively working on a more robust fix.

**Comment by blarvin** [comment]
Cool! Thanks for the amazing work!
