### ISSUE TITLE
feedback: Turn off autompletion for comments

### ISSUE THREAD

**Issue by canadaduane** [sourcegraph/cody#3038]
### Version

1.3.1707145731

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

It's rare that Cody can suss a useful and thoughtful comment from the code itself--the best code comments reveal new information such as a "why" or "historical context" that is not present. I'd like to keep autocomplete enabled for code, but disable it when in the context of creating a comment.

### Describe the solution you'd like to see

I'd like a config that allows me to disable autocompletion within the context of creating a new comment. So if I've typed `// (<- cursor is here)` it should not make any comment suggestions.

**Comment by philipp-spiess** [comment]
Hey @canadaduane. I think this is an excellent idea. We already throttle autocompletes inside comments somewhat but I agree that there are situations where I too would prefer disabling them completely. Let me just sync with the rest of the team but I think we can do that :)
