### ISSUE TITLE
P2 Enterprise users are prompted to request that their admin index the project or to switch to their personal sourcegraph.com account

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#3041]

**Comment by abeatrix** [comment]
Isn't remote embeddings no longer supported? @kalanchan

**Comment by kalanchan** [comment]
yeah good point, embeddings no longer supported on enterprise. I think we can close this out @taylorsperry @aramaraju

**Comment by aramaraju** [comment]
Correct me if I'm wrong here, but we don't have the prompt anymore. At least based on my VSCode testing. If we confirmed that, we can close this issue
