### ISSUE TITLE
feedback: 

### ISSUE THREAD

**Issue by mmfazrin-phcc-gov** [sourcegraph/cody#3046]
### Version

v1.2.3

### Areas for Improvement

- [x] UI/UX
- [ ] Onboarding
- [ ] Docs
- [x] Chat
- [ ] Commands
- [x] Context
- [X] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

Auto complete response not good and quick as GitHub Copilot

### Describe the solution you'd like to see

Should be match the response quality of GitHub Copilot's quality

**Comment by kalanchan** [comment]
thanks for the feedback! we're working on making Cody Autocomplete better with each iteration, feel free to try the latest version and see if it is better.
