### ISSUE TITLE
bug: accepting a suggestion removes first line of code

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#3050]
### Version

v1.3.1707145731 (pre-release)

### Describe the bug

accepting a suggestion removes first line of code:

https://github.com/sourcegraph/cody/assets/68532117/daa7377a-466f-4d1c-ba69-e2843a6b8ebe

https://github.com/sourcegraph/cody/assets/68532117/f6bed51f-a7df-4246-8074-3cde03b0fcfa

Log from output channel: [auto.log](https://github.com/sourcegraph/cody/files/14181079/auto.log)

### Expected behavior

Suggestion includes the first line of code

### Additional context

Happened in this function: https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/ui/src/Chat.tsx?L405-411
- Start a new if statement: `if (` without closing bracket
- wait for suggestion to pop up
- accept suggestion
- the first line often gets removed

**Comment by valerybugakov** [comment]
@philipp-spiess, autoformatting logic should be turned off by default, right? 🤔 I'll check it locally too.
