### ISSUE TITLE
clients/vscode: how to exclude files/folders from indexing/embeddings ?

### ISSUE THREAD

**Issue by gpertea** [sourcegraph/cody#3059]
In a C++ project I have a directory that has a lot of source code files I want to be excluded from indexing by Cody. I also want to exclude some .c/.cpp files from indexing in other directories, and only index the headers. 

I cannot put all those in `.gitignore` because they are part of the project code distribution, but they are just too big and do not want them indexed by the Cody engine 

I could not find a good documentation on how to do this (using the pre-release v1.3.1707232140). I found some hints about `.sourcegraph/ignore` and/or `.cody/ignore`, I have these at the root of the workspace/project root, as I assumed they would be (due to lack of documentation..), but none of that worked - Cody keeps indexing 10855 files, no matter what I tried, which takes a long time of course..  

How can I set these exclusions for a project in vscode?

**Comment by dominiccooney** [comment]
Embeddings does not support .cody/ignore yet, but I am working on it.

**Comment by Overload119** [comment]
Still?
