### ISSUE TITLE
bug: cannot configure `unstable-ollama` provider, ignores model and Server Endpoint settings

### ISSUE THREAD

**Issue by lukeab** [sourcegraph/cody#3074]
### Version

v1.2.3

### Describe the bug

When selecting to use a self hosted ollama instance, there is no way to do 2 things: 
1. Set the server endpoint for the ollama instance. in my case I have a desktop machine with a good GPU and run ollama there, when coding on my laptop i want to use the ollama instance on my desktop, no matter what value is set for  `cody.autocomplete.advanced.serverEndpoint`, cody will always attempt to use http://localhost:11434, so i cannot sepcify the ip of my desktop machine hosting ollama.
2. Use a different model on ollama - no matter what value is set for `cody.autocomplete.advanced.model`, for example when llama-code-13b is selected, the vscode output tab for cody always says: `█ CodyCompletionProvider:initialized: unstable-ollama/codellama:7b-code
`

### Expected behavior

When a esrver endpoint is specified, the ollama configuration should use that value instead of the default http://localhost:11434
when a model is selected it should use that model in the config and request paramteres, instead of always using `codellama:7b-code`

### Additional context

![image](https://github.com/sourcegraph/cody/assets/265588/0fc9c462-efa6-456f-90c3-c1286ea5153c)
image shows output for unstable-ollama/codellama:7b-code being used despite 13b being selected.

**Comment by lukeab** [comment]
Updated the description to correct the `cody.autocomplete.advanced.model` setting name.

**Comment by jdorfman** [comment]
Thanks @lukeab for reporting this. We will follow up ASAP.

**Comment by lakarpusky** [comment]
`VSCode v1.85.2` `Cody AI v1.4.4`

![CleanShot 2024-02-18 at 22 45 03](https://github.com/sourcegraph/cody/assets/25494196/ce4c5479-6fae-420d-a84e-3bea85cdaf17)

missing `unstable-ollama` provider?

![CleanShot 2024-02-18 at 22 39 02](https://github.com/sourcegraph/cody/assets/25494196/12d0d63e-b99c-4b69-9e0c-0163675e45e2)

**Comment by philipp-spiess** [comment]
@lukeab `cody.autocomplete.advanced.serverEndpoint` is actually not used when the Ollama provider is configured. Sorry for that (I know it's super confusing and we have to make this easier, sorry!). You want to use the `cody.autocomplete.experimental.ollamaOptions` option like this:

```
  "cody.autocomplete.advanced.provider": "experimental-ollama",
  "cody.autocomplete.experimental.ollamaOptions": {
    "url": "http://localhost:11434",
    "model": "deepseek-coder:6.7b-base-q4_K_M"
  },
```

@lakarpusky Which doc do you refer to? We have renamed the option from `unstable-ollama` to `experimental-ollama`, so that doc will need updating I’m afraid.

**Comment by lakarpusky** [comment]
Thanks @philipp-spiess it worked with that configuration. It was my mistake I meant to say `log` changelog, but it seems I checked the wrong file.

Does Cody allow to change the chat model? Because I already have the `codellama:7b-instruct` model downloaded and being able to use the chat offline would be great.

**Comment by philipp-spiess** [comment]
@lakarpusky Unfortunlaty we don't have support for Ollama in Chat yet. :/

**Comment by klimchuk** [comment]
What's local Ollama used for when?

**Comment by philipp-spiess** [comment]
@mejoe 

> Is there a plan to enable Ollama for chat?

Yep, but I can't promise a timeline yet. I have created a separate issue to track demand for this though: https://github.com/sourcegraph/cody/issues/3252


@klimchuk 

> What's local Ollama used for when?

Currently Ollama support is experimental and only available for the autocomplete feature (so for inline code suggestions). A quick guide on how to enable it can be found here: https://github.com/sourcegraph/cody/blob/main/vscode/doc/ollama.md

**Comment by ByerRA** [comment]
One of the main reasons I was drawn to Cody was the fact that one could use Ollama with it.  It's disappointing to see that only "autocomplete" is used with local Ollama models (and this needs to be documented better) and not any of the other features.

**Comment by jdorfman** [comment]
@ByerRA coming soon =)

![image](https://github.com/sourcegraph/cody/assets/398230/605968cd-b369-44af-a348-8ba84419ee69)


https://github.com/sourcegraph/cody/pull/3282

**Comment by janvda** [comment]
> @lukeab `cody.autocomplete.advanced.serverEndpoint` is actually not used when the Ollama provider is configured. Sorry for that (I know it's super confusing and we have to make this easier, sorry!). You want to use the `cody.autocomplete.experimental.ollamaOptions` option like this:
> 
> ```
>   "cody.autocomplete.advanced.provider": "experimental-ollama",
>   "cody.autocomplete.experimental.ollamaOptions": {
>     "url": "http://localhost:11434",
>     "model": "deepseek-coder:6.7b-base-q4_K_M"
>   },
> ```
> 
> @lakarpusky Which doc do you refer to? We have renamed the option from `unstable-ollama` to `experimental-ollama`, so that doc will need updating I’m afraid.

It is not clear to me how I can add the following to my visual code settings file
```
"cody.autocomplete.experimental.ollamaOptions": {
  "url": "http://localhost:11434",
  "model": "deepseek-coder:6.7b-base-q4_K_M"
},
```

**Comment by lukeab** [comment]
it's great, the `cody.autocomplete.experimental.ollamaOptions`: {} url and model works now.
It would be ideal to have a sense of when experiemental may be merged into advanced? Or what the plan is to include the experimental features into the settings dialogs in vscode? Happy this works and now with PR #3282 answering the need in ticket #3252 things are looking better, would just love them all incorporated into the settings form fields.

**Comment by jdorfman** [comment]
@lukeab glad you are enjoying it! We don't have any plans on next steps. Right now we are gathering feedback (like this) and creating content to see what's next.

* https://sourcegraph.com/blog/local-chat-with-ollama-and-cody
* https://www.youtube.com/watch?v=Q9yYr5XUz88

**Comment by levicki** [comment]
@jdorfman @philipp-spiess For me these options in VS Code 1.90.0 with Cody 1.20.3 no longer seem to work:
```
    "cody.autocomplete.advanced.provider": "experimental-ollama",
    "cody.autocomplete.experimental.ollamaOptions": {
        "url": "http://localhost:11434",
        "model": "granite-code:34b"
    },
    "cody.autocomplete.languages": {
        "*": true
    },
    "cody.experimental.ollamaChat": true,
```
Namely, the `cody.autocomplete.experimental.ollamaOptions` and `cody.experimental.ollamaChat` show the Unknown Configuration Setting tooltip.

If I click Cody: Generate Code option from lightbulb icon I get `No chat model found in server-provided config` and output window is showing:
```
ConfigFeaturesSingleton: refreshConfigFeatures accessing Sourcegraph GraphQL API: Error: HTTP status code 401: Invalid access token.
```
Note that I am not logged into sourcegraph account, but I am also not getting any auto-completion offers.

Another error I am seeing in earlier output is:
```
LocalEmbeddingsController: load 5f1385928dff462ab5e748800ac37144 {"code":-32099}
```

Could you please point me to some updated docs which say what exactly is supported in current version and what are the correct configuration keys now?

**Comment by hitzhangjie** [comment]
+1 

The document is old.

**Comment by hyharry** [comment]
is there any solution existing right now. it does not work when sign out for VS Code 1.92.0 and Cody  1.28.1

**Comment by levicki** [comment]
> is there any solution existing right now. it does not work when sign out for VS Code 1.92.0 and Cody 1.28.1

Yes, the solution is not to use Cody.

Switch to https://www.continue.dev/ -- it's much better and fully open-source anyway.

**Comment by hyharry** [comment]
> > is there any solution existing right now. it does not work when sign out for VS Code 1.92.0 and Cody 1.28.1
> 
> Yes, the solution is not to use Cody.
> 
> Switch to https://www.continue.dev/ -- it's much better and fully open-source anyway.

Thanks for mentioning! will give a try

**Comment by icemagno** [comment]
> > is there any solution existing right now. it does not work when sign out for VS Code 1.92.0 and Cody 1.28.1
> 
> Yes, the solution is not to use Cody.
> 
> Switch to https://www.continue.dev/ -- it's much better and fully open-source anyway.

DO NOT DO THIS!
