### ISSUE TITLE
Document Code is not adding new line for commented code and causing the code looks erroneous

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3078]
### Version

v1.3.1707318553

### Describe the bug

**Steps to reproduce:**

1. Have Cody extension installed in your VS Code
2. User is already logged in to Cody
3. Open any file and select code snippet
4. Select "Document" from "Commands" and wait for Cody to finish writing documentation for your code.

**Observed behavior:**
New line is not added correctly and causing the code looks erroneous

### Expected behavior

New line should be added correctly for the documentation done by Cody.

**Note:**
This issue is intermittent and does not reproduce every time.

Video link:
https://drive.google.com/file/d/1TFixcCDUSOcWqrhzXHEWNC4yvGHtvzVM/view?usp=drive_link

**Comment by chenkc805** [comment]
Adding @abeatrix @umpox for viz

**Comment by abeatrix** [comment]
@jay-fibi can you try running the command using the latest stable release v1.4.0 and let us know if the issue persists?

**Comment by jay-fibi** [comment]
@abeatrix Checked with v1.4.0 and the issue is still there.

**Comment by abeatrix** [comment]
hmmm it's working correctly for me. @umpox any idea?

**Comment by abeatrix** [comment]
Fixed by https://github.com/sourcegraph/cody/pull/4362
Feel free to reopen if this is not fixed in the latest release.
