### ISSUE TITLE
bug: autocomplete not working

### ISSUE THREAD

**Issue by signorettif** [sourcegraph/cody#3082]
### Version

1.4

### Describe the bug

Hello team 👋🏼,

I am experiencing issues with the autocomplete feature, which is essentially not working for me. For context, I am logging into Sourcegraph via an Enterprise account, though I'm unsure if this has anything to do with the problem at hand.

I tried to play around with various settings, but I have not been successful. I have included the error messages I am encountering below.

While using the default settings (specifically, `"cody.autocomplete.advanced.provider": null`), I receive this error:

```
ERR error parsing CodeCompletionResponse: Error: {"error":"OpenAI: unexpected status code 404: {\n    \"error\": {\n        \"message\": \"The model `gpt-35-turbo` does not exist\",\n        \"type\": \"invalid_request_error\",\n        \"param\": null,\n        \"code\": \"model_not_found\"\n    }\n}\n"}: Error: error parsing CodeCompletionResponse: Error: {"error":"OpenAI: unexpected status code 404: {\n    \"error\": {\n        \"message\": \"The model `gpt-35-turbo` does not exist\",\n        \"type\": \"invalid_request_error\",\n        \"param\": null,\n        \"code\": \"model_not_found\"\n    }\n}\n"}
```

When I select anthropic as the provider (namely, `"cody.autocomplete.advanced.provider": "anthropic"`), the following error message appears:

```
ERR error parsing CodeCompletionResponse: Error: {"error":"expected to receive exactly one message with the prompt (got 4)"}: Error: error parsing CodeCompletionResponse: Error: {"error":"expected to receive exactly one message with the prompt (got 4)"}
```

### Expected behavior

Working autocomplete suggestions with either default setting or Anthropic.

**Comment by signorettif** [comment]
This is related to an error the enterprise configuration, which can be found [here](https://docs.sourcegraph.com/cody/overview/enable-cody-enterprise#openai).

There is a mistake in the configuration parameters, which should use the value `gpt-3.5-turbo` instead of `gpt-35-turbo`:

```
{
  // [...]
  "cody.enabled": true,
  "completions": {
    "provider": "openai",
    "chatModel": "gpt-4", // Or any other model you would like to use
    "fastChatModel": "gpt-35-turbo", // Or any other model you would like to use
    "completionModel": "gpt-35-turbo", // Or any other model you would like to use
    "accessToken": "<key>"
  }
}
```

**Comment by philipp-spiess** [comment]
Hey @signorettif. Great find, I've gotten this fixed ASAP: https://github.com/sourcegraph/docs/pull/86. 

Really sorry for the confusion in the docs!
