### ISSUE TITLE
bug: Unable to remove current repo from enhanced remote context

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/cody#3092]
### Version

v1.3.1707318553 (pre-release)

### Describe the bug

I opened the enhanced context selection and unchecked the current repo and added a different repo.  Then started a chat and inspected the context.  Context files from the local repo were present and were remote links. 

### Expected behavior

That no context would be present from the repo that was removed from the context.

**Comment by dominiccooney** [comment]
@chwarwick including the repo is by design, we pick up a "default" repo and stick you to it. We found it was worse to not have context.

But it is confusing that you can uncheck the repo and it doesn't go away.

**Comment by sqs** [comment]
You can now delete the `@<current-repo>` mention from chat
