### ISSUE TITLE
bug: chat input doesn't allow standard text motions

### ISSUE THREAD

**Issue by zephyrtronium** [sourcegraph/cody#3101]
### Version

1.4

### Describe the bug

Entering a line of text in the Cody AI chat input and then using ctrl+left and ctrl+right to navigate by word does nothing. Same for ctrl+shift+left and ctrl+shift+right to select by word as reported in #2512.

### Expected behavior

Motion by words when using ctrl+left and ctrl+right, as every other text input on every major OS/DE provides.

### Additional context

Other by-word motions (ctrl+backspace and ctrl+delete) work as normal.

**Comment by jdorfman** [comment]
Thanks for reporting @zephyrtronium and thanks @DanTup for fixing!
