### ISSUE TITLE
VS Code: 2 less number of lines are being selected in Context when user click on "Explain" for any code selection

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3110]
### Version

v1.4.1

### Describe the bug

**Steps to reproduce:**

1. Have Cody extension installed in your VS Code
2. User is already logged in to Cody
3. Open any file and select a code snippet or whole file
4. Click on "Explain" from "Commands"
5. Select drop arrow from chat transcript and check the @filename: lines

**Observed behavior:**
Count is showing wrong here and it is showing 2 less number of lines than actual lines of code.

### Expected behavior

It should display correct lines count for the context.

### Additional context

**Screenshot:**

![Screenshot 2024-02-09 at 10 39 08 PM](https://github.com/sourcegraph/cody/assets/158482423/33ea359b-86ef-42fb-ac62-c13d7cae3610)

**Comment by jdorfman** [comment]
Another great bug report.  Thanks @jay-fibi.
