### ISSUE TITLE
VS Code: Getting errors while using "Natural Language Search" on VS Code.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3112]
### Version

v1.4.1 & v1.5.1707404958 pre released

### Describe the bug

**Steps to reproduce:**

1. Have Cody extension installed in your VS Code
2. User is already logged in to Cody
3. Go to "Natural Language Search" and search for keyword i.e. alert, enhanced context logic and hit enter

**Observed behavior:**
We are getting random error messages are shown in the attached screenshots

### Expected behavior

Errors should not appear and "Natural Language Search" should work correctly.

### Additional context

**Screenshots:**

![Screenshot 2024-02-10 at 2 14 08 AM](https://github.com/sourcegraph/cody/assets/158482423/e17a7c9d-daad-4e5b-b624-dc7d50e486b9)
<img width="1460" alt="Screenshot 2024-02-10 at 1 54 00 AM" src="https://github.com/sourcegraph/cody/assets/158482423/4e99b315-b04a-4877-b91a-bcc197216a78">

**Comment by jdorfman** [comment]
Thanks for reporting this @jay-fibi. We will investigate and follow up ASAP.

**Comment by iswarmondal** [comment]
Hey @jdorfman, I have managed to reproduce the error shown in the second screenshot. I'm taking a look at that.

**Comment by jdorfman** [comment]
@iswarmondal can you enable logs and paste them here?

How to enable:
https://www.loom.com/share/b5b2d8e7e0ac43308579734e0584f6ca?sid=0c8df13c-2ef0-42d3-85c5-de58bf907467

**Comment by kalanchan** [comment]
going to close this as we aren't focusing on NLS atm
