### ISSUE TITLE
It doesn't run on VSCODIUM

### ISSUE THREAD

**Issue by manueleforero** [sourcegraph/cody#3119]
Hi, please i can't install on my EXCELENT VSCODIUM (because your only dispath vscode).

Please fix that editor.
Thanks you.

**Comment by baristaGeek** [comment]
I haven't looked at the platform's repo. But based on the fact that when you log in via OAuth to any service (GitHub, Google, etc.) on VS Codium you get redirected to VS Code, I'm guessing the solution is making the platform pass a parameter to modify the URI that will open either VS Code or VS Codium

**Comment by dominiccooney** [comment]
Looks like we need to use `vscodium://` as the scheme instead of `vscode://` or `vscode-insiders://`. We'll need to change the Sourcegraph frontend to allow redirects to this scheme, or use `http://` like JetBrains.
