### ISSUE TITLE
The Code snippet links provided by the Cody Chat are opening the wrong link on local Sourcegraph instance

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#3125]
Example of a wrong link
<img width="1168" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/6b5c0dda-f63d-4c10-8bcb-a0ae88b2c83b">

Correct Link 
<img width="1175" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/b62768d5-53cf-4a45-8697-52b7d235058c">

This always happens and I suspect its because I setup a new connection to Cody in my Sourcegraph Instance locally.

<img width="948" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/abfe07e8-c9c7-492f-94bc-f34f0a13c56f">

**Comment by arafatkatze** [comment]
@chwarwick We have other priorities so I am just gonna leave this as an issue for now but I wanted to ask if I am not making some sort of classic new connection mistake that leads to this.

**Comment by dominiccooney** [comment]
@arafatkatze what are the raw links like?

Here's what the client is doing, breaking around here we can narrow down whether this is a client or backend issue:

This GraphQL: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/sourcegraph-api/graphql/queries.ts?L133:14-133:34
Munged this way: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/sourcegraph-api/graphql/client.ts?L505-509

**Comment by chwarwick** [comment]
@arafatkatze New connections for local development would go into the external-services-config.json in your local dev-private.  By default running locally doesn't allow config changes although you can override that with an environment variable `EXTSVC_CONFIG_ALLOW_EDITS=true`

I assume in this case the Cody repo just isn't on your local instance.

**Comment by arafatkatze** [comment]
>I assume in this case the Cody repo just isn't on your local instance. 

@chwarwick the Cody repo is on my local instance and I tried it again so I was getting the chat working perfectly with references but the links had this issue. 


@dominiccooney 
> what are the raw links like?

Example raw link is [this](https://sourcegraph.test:3443//github.com/sourcegraph/cody%403972bf8b726d5008f3167cf6fabf9546bb9dcd0a/-/blob/vscode/src/chat/chat-view/SidebarViewController.ts?L9-16)


Apologies but this seems like not a SUPER important issue and I have some commitments so Imma leave this for now. However if any of you feel this is important to be solve then you can assign it to me and I will solve it. I am sure its trivial anyway.
