### ISSUE TITLE
VS Code: One LLM is missing for "Edit" but available for "New Chat"

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3144]
### Version

v1.4.3

### Describe the bug

Steps to reproduce:

1. Have Cody extension installed in your VS Code
2. User is already logged in to Cody
3. Click on Cody and click "Edit" from "Commands"
4. Click on "Model" and verify list of available LLM
5. Open "New Chat" and click on "LLM selection" dropdown

Observed behavior:
"Mixtral 8x7B bt Mistral" LLM is missing for "Edit" but available for "New Chat"

### Expected behavior

Number of LLM should be same for both the places.

### Additional context

Screenshot:

<img width="928" alt="Screenshot 2024-02-13 at 12 20 04 AM" src="https://github.com/sourcegraph/cody/assets/158482423/556abe91-8293-448b-80cf-006930165385">
<img width="599" alt="Screenshot 2024-02-13 at 12 20 23 AM" src="https://github.com/sourcegraph/cody/assets/158482423/6f0b8fd0-7a12-442d-80ef-47f160096056">

**Comment by deepak2431** [comment]
@jay-fibi Thanks for reporting this. I think this might be intended not to include Mixtral in the Edit options.
CC: @umpox @abeatrix Was this the case?

**Comment by abeatrix** [comment]
Yea i tihnk you're right @deepak2431. i believe that's because of Mixtral's performance for Edit is not on par with other models, but I can see how it's causing confusion. @umpox @toolmantim should we still show the model but mark it as experimental? 🤔

**Comment by toolmantim** [comment]
I’ll wait to hear from @umpox why it was excluded.  If there are problems with reliability etc then we don’t want a buggy model in there. If it was just quality of code gen, we should probably err on adding it.

**Comment by umpox** [comment]
It's a weaker model and it struggles with reliability. It's not included right now.

I'm going to close this, but hopefully in the future we'll be able to access an improved model or improve our handling of the response.
