### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by sharp231** [sourcegraph/cody#3148]
### Version

バージョン: 1.86.1 

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [X] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [X] Other

### What needs to be improved? Please describe how this affects the user experience.

Can you make it available in Japanese?

### Describe the solution you'd like to see

Can you make it available in Japanese?

**Comment by deepak2431** [comment]
@sharp231 I think this will be supported soon to change the default language, but for now, there's a way in which you can use Cody to answer all of your questions in Japanese. 

You can open the Cody chat settings and add this as the pre-instruction. Cody will answer all of your questions in Japanese. Hope this helps!
![iScreen Shoter - Code - 240214103252](https://github.com/sourcegraph/cody/assets/44617923/35fc8a3c-2bfb-4f79-ba4a-b1b5907cc816)

**Comment by sharp231** [comment]
If the basic language is Japanese, will the programming code also be Japanese?
In that case, how should I give instructions in English?
