### ISSUE TITLE
bug: Fix "Cody updated…" incorrect appearing on new installs

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#3171]
### Version

1.4

### Describe the bug

Steps to repro:
- Install Cody
- Login with Cody
- 🐛  See "Cody updated..." banner, which blocks the chat text
![CleanShot 2024-02-14 at 21 53 07@2x](https://github.com/sourcegraph/cody/assets/3654603/cbc35a15-1ced-44b1-b4d6-743e801f55db)

### Expected behavior

Expected behavior
- Install Cody
- Login with Cody
- Don't see "Cody updated..." banner, which blocks the chat text
- Only show "Cody updated..." banner when Cody is already installed but it simply got updated to the newest version. 

### Additional context

CC: @toolmantim

**Comment by dominiccooney** [comment]
I can reproduce this.

**Comment by dominiccooney** [comment]
This was caused by the triggering logic for showing the notification not keeping up with changes to the chat transcript management.
