### ISSUE TITLE
feedback: This thing sucks

### ISSUE THREAD

**Issue by mmiller111** [sourcegraph/cody#3182]
### Version

1.4.3

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [X] Context
- [X] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

It can't actually look throught he code and answer my questions. It keeps making code up and when I ask it where it got the snippet it showed me, it says that it made a mistake and actually it doesn't exist in the code. Very frustrating!!

### Describe the solution you'd like to see

It should use actual context and if it doesnt know, just say so instead of making answers up

**Comment by blarvin** [comment]
I dont want to be negative, but this is legit. Cody is meant to be the solution to these problems, and it does the job a little better than naked ChatGPT. But still these CONTEXT issues are here! When we ask questions or ask for suggestions, we always and only want the answers to be in the context of the CURRENT PROJECT.

**Comment by FoxMcWeezer** [comment]
The RAG is incredibly bad. Cody has access to the entire codebase. There should never be an instance where it tells you it doesn't have context or the requested file wasn't included in its context. At that point, you are worse than me typing the same query into ChatGPT, as that would equally have zero context of my codebase. My favorite is when you see the files it pulls in for context, and it's completely unrelated files from a distant section of the codebase.
