### ISSUE TITLE
bug: mentioning files in chat sometimes does not filter (e2e test flake)

### ISSUE THREAD

**Issue by DanTup** [sourcegraph/cody#3195]
### Version

main d19cbb4f

### Describe the bug

The chat-atFile tests seem pretty flaky when they run on the bots. An example failure looks like this, where we expect "no files found":

![image](https://github.com/sourcegraph/cody/assets/1078012/a9f91946-fa18-4fd1-a67d-83dca11e85f1)

~~My suspicion is that this is because of the way this search is throttled and cancelled. It's throttled [here](https://github.com/sourcegraph/cody/blob/0451782d2995986f7c911b927763e53aa8b6f594/vscode/src/editor/utils/editor-context.ts#L43)~~

~~And we cancel previous requests via a cancellation token [here](https://github.com/sourcegraph/cody/blob/0451782d2995986f7c911b927763e53aa8b6f594/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts#L598-L601)~~

~~My feeling is that because the code above doesn't cancel the previous search until after the new one is sent, that we will sometimes end up not running the "last" search (it is throttled) and therefore we end up with stale results. In the screenshot above, I think the search fired for "fi" but then searches triggered by "xtures" may have been throttled (eg. made to return the same as the previous results for "fi").~~

(I no longer think this is throttle-related, see below).

### Expected behavior

When you stop typing (at least for some period), the the last character typed should always result in a complete unthrottled search.

**Comment by DanTup** [comment]
Actually, [`[options.trailing=true]` defaults to true](https://docs-lodash.com/v4/throttle/) so I feel like the last invocation should still return the correct results here. Needs more investigation (but I haven't been able to repro locally yet).

**Comment by DanTup** [comment]
After more testing, I don't think this is throttle-related at all. The find has no query and returns all files which are then filtered with fuzzysort. So even when the request is throttled, it'll return all files and they should be filtered by us.

**Comment by kalanchan** [comment]
this should be closed with Beatrix's fixes to e2e testing 
- https://github.com/sourcegraph/cody/pull/3558
- https://github.com/sourcegraph/cody/pull/3580
