### ISSUE TITLE
bug: Cody generated a javadoc comment for a Python function

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/cody#3206]
### Version

1.5.1708096199

### Describe the bug

- git clone https://github.com/tornadoweb/tornado
- open the folder in VS Code
- navigate to the file <folder>/tornado/httpserver.py
- find the start_request method of the HTTPServer class around line 250
- place cursor/caret inside the start_request method
- Cody->Document Code

Cody inserts a javadoc comment above the method, which doesn't parse.

### Expected behavior

It should insert either a Python comment or a Python docstring, not a Java/Javadoc comment.

### Additional context

![image](https://github.com/sourcegraph/cody/assets/613744/eb2247d2-f455-44b5-ad17-c00e7ce78aac)

I reproduced it with a fresh clone of the repo and a fresh vscode Cody from nightly.

**Comment by abeatrix** [comment]
Closing this issue as I think the changes we made to the doc command have fixed the issue as I can no longer reproduce it on 1.8.3, but feel free to open it again if this is incorrect. 

I did notice some formatting issues though which are being tracked in https://github.com/sourcegraph/cody/issues/3247:

![image](https://github.com/sourcegraph/cody/assets/68532117/618d6b33-15f0-4e66-9f62-b64d5836bef5)

![image](https://github.com/sourcegraph/cody/assets/68532117/4e0ebcda-8078-489c-9061-91dc9ee6d483)
