### ISSUE TITLE
Remove authentication steps in VS Code

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#3216]
Test removing unnecessary dialogues that stand between a user installing Cody and signing up for Cody. 

Context: 

- [Remove authentication steps PRD](https://docs.google.com/document/d/1AubJ226dUhaV0zC8WpA_19vzoXXtQ8AUmNqSHPaWKWQ/edit#heading=h.ftqde5tlfi9g)
- [Asana task](https://app.asana.com/0/1206519077296236/1206570325064763/f) 
- [Figma](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=5595-162671&mode=design&t=RaJNJM7wBkyxtw55-0)

**Comment by philipp-spiess** [comment]
This change will need a mechanism for the clients to _poll_ the authentication server so they are notified on a successful authentication event. This requires a different auth flow from the one I have right now (_I think_, confirming as we speak), something like OAuth 2.0 Device Authorization Grant. I'll follow up with more info
