### ISSUE TITLE
feedback: make commands accessible by right-clicking files in the IDE directory

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#3217]
### Version

v1.4.4

### Areas for Improvement

- [x] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

User wants a way to right click on the file from the IDE file list viewer and access Cody commands (Example: Right click on a file and select “edit” and then “add a function that does …“)]

### Describe the solution you'd like to see

See above 

### Additional context

[Slack thread](https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1708119138943819)

**Comment by mike-r-mclaughlin** [comment]
Requested by https://github.com/sourcegraph/accounts/issues/8765
