### ISSUE TITLE
The whole thing just pinwheels endlessly. 

### ISSUE THREAD

**Issue by scyppan** [sourcegraph/cody#3234]
### Version

v1.4.4 

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

I couldn't even get it to respond to basic requests. After a few chats, it just hung endlessly and never came back to life. The code itself also wasn't terribly helpful. Rather than helping to spot potential areas for review, it just tried to refactor the code but did so in also unhelpful and broken ways. 

### Describe the solution you'd like to see

.

**Comment by simwai** [comment]
+1
