### ISSUE TITLE
Implement utm_source into VSCode IDEs to understand where users come from when they upgrade

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#3239]
Context:
- To better understand how users are upgrading, we want to be able to track pass UTMs to the web for when users go to the web to upgrade via the IDEs. 

Requirements:
- When users click an upsell, append the URL with:
  - utm_source = vscode
  - utm_medium = chat_command_upsell | autocomplete_upsell
- When users click "Upgrade" in the bottom right of the IDE, append the URL with:
  - utm_source = vscode
  - utm_medium = upgrade_settings_panel

**Comment by kalanchan** [comment]
@chillatom needs follow up
