### ISSUE TITLE
bug: Cody inserting Python docstrings at wrong place

### ISSUE THREAD

**Issue by maxi07** [sourcegraph/cody#3249]
### Version

v1.6.0

### Describe the bug

When using the `Document code` Cody option above a python function, it does indeed generate correct docstrings but puts them above the function. A python docstring must be directly below the function name, not above (see [Python Docstring Convention](https://peps.python.org/pep-0257/)

![image](https://github.com/sourcegraph/cody/assets/7480270/8c714370-026b-41ec-af6c-bea5ccccc76c)

### Expected behavior

```python
def extract_text(pdf_path: str) -> str:
    """Extracts text from a PDF file.

    Args:
        pdf_path (str): The path to the PDF file.

    Returns:
        str: The extracted text from the PDF. An empty string is returned if the extraction fails.
    """
    try:
        reader = PdfReader(pdf_path)
        page = reader.pages[0]
        text = page.extract_text()
        return text
    except Exception as ex:
        logger.exception(f"Failed extracting text: {ex}")
        return ""

```

**Comment by jdorfman** [comment]
This is a great bug report, thanks @maxi07. Our team has been notified.

cc @kalanchan for visibility

**Comment by deepak2431** [comment]
I can reproduce this too:
![iScreen Shoter - Code - 240305183913](https://github.com/sourcegraph/cody/assets/44617923/f3446281-3efc-4902-ae5c-ac0ed5b4da8e)


Looking for a fix to this!
