### ISSUE TITLE
Ollama: Experimental support for chat

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#3252]
Creating an issue to track the demand for ollama support for chat models.

**Comment by cam-s-hunt** [comment]
+1. I'd like to be able to use a local Ollama API.

**Comment by ByerRA** [comment]
+1 YES!!!!

I think having the ability to have ALL of Cody's functions able to be run from Ollama would be of great benefit and would also draw more people to use Cody as I believe more and more people are going to want to run local models.

**Comment by mrdjohnson** [comment]
+1 big ollama user here, I'd love cody + ollama for use on flights / bad internet connections / code security

**Comment by PieBru** [comment]
Following this guide: https://github.com/sourcegraph/cody/blob/main/vscode/doc/ollama.md
![image](https://github.com/sourcegraph/cody/assets/6537434/6beec38f-d387-4d26-b73d-fb6206519d5d)

**Comment by mrdjohnson** [comment]
I just tried using Cody offline with the ollama flag on and it was still trying to hit Cody's servers it looks like? 

`"cody.experimental.ollamaChat": true`

`Request Failed: getaddrinfo ENOTFOUND sourcegraph.com`

Is the ollama integration meant for Cody to work completely offline?

**Comment by mrdjohnson** [comment]
I think I figured out how to use ollama! (I needed to create a new chat and set the bot to be ollama ) Thank you so much for the work you put into this! 🥳 🥳

**Comment by abeatrix** [comment]
Thank you for trying it out 🤗 

We have a blog post with instructions on how to set up Ollama for chat if anyone else is interested in giving it a try 😃  https://sourcegraph.com/blog/cody-vscode-1-8-0-release
