### ISSUE TITLE
feedback: Specify unit test method.

### ISSUE THREAD

**Issue by James-Morrell** [sourcegraph/cody#3254]
### Version

1.86.2

### Areas for Improvement

- [ ] UI/UX
- [X] Onboarding
- [ ] Docs
- [ ] Chat
- [X] Commands
- [X] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

Using the Generate Unit Tests function with C# doesn't always give the correct framework response.

Example:
Project is using Xunit, but sometimes the generated code would be Nunit

### Describe the solution you'd like to see

When using the Generate Unit Tests function for the first time, ask for input of which test framework to use.

**Comment by abeatrix** [comment]
@James-Morrell Thank you so much for your feedback!  Do you mind sharing some information with us so we can look into this further?
1. What's the naming convention of the Xunit test files in your project? For example, `example.Tests.cs` or `exampleTest.cs` 
2. What's your Cody version? (1.86.2 is the version of your VS Code. You can find your Cody version next to the Release Note icon in your Cody's SETTING & SUPPORT sidebar:
![image](https://github.com/sourcegraph/cody/assets/68532117/eff387ee-11f3-46a6-a502-1718faf7e152)

**Comment by James-Morrell** [comment]
@abeatrix I'm running v 1.6.0 of Cody.

My usual naming convention for tests is `ExampleTests.cs`, where Example would be the class name being tested.
On occasion when a set of tests for a single method gets very large I'll split the test class like so:
`ExampleTests_FuncOne.cs`
