### ISSUE TITLE
Web: Getting a random 404 error when login to Cody.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3284]
### Version

Web

### Describe the bug

**Steps to reproduce:**

1. Open Cody and click on "Sign in with Google"
2. User will be redirected to authorization page on browser.
3. Hit "Authorize" button and wait for a moment

**Observed behavior:**
"404 Not Found" error page is displayed and user will not be able to sign in to Cody.

### Expected behavior

"404 Not Found" error page should not be displayed and user should be able to login to Cody.

### Additional context

**Video link:**

https://drive.google.com/file/d/1zvRoajdZtjSqLmrccj_xO_oNvNwFfmay/view?usp=drive_link

**Comment by dominiccooney** [comment]
@jay-fibi could you make that Drive link viewable?

@chenkc805 could you triage this, I believe your team is changing this flow?
