### ISSUE TITLE
bug: Linux + Chromium/Firefox - Can't get after the authorization request

### ISSUE THREAD

**Issue by PieBru** [sourcegraph/cody#3288]
### Version

VSCodium 1.87.0 r24060

### Describe the bug

I'm on Arch Linux. As there are much more Linux setups than MAC or Win, I Don't ask to debug this problem.
IMO it makes more sense to allow registration via email or as a backup via the direct input of the authorization code `sgp_*`.

BTW, here are some visual details of the problem, it occurs with both the release and the pre-release of Cody:
![image](https://github.com/sourcegraph/cody/assets/6537434/72331f88-54d8-445f-ad52-7dadf2fff61d)
![image](https://github.com/sourcegraph/cody/assets/6537434/f7301009-555b-49c3-a380-eb90b908a021)
![image](https://github.com/sourcegraph/cody/assets/6537434/0aac6779-159c-4dbe-8824-50b1113a3edd)

Thank you,
Piero

### Expected behavior

To be able to give Cody a try.

**Comment by dominiccooney** [comment]
@PieBru , this is related to your browser/VSCodium setup. You need to configure LibreWolf to open vscodium:// links in VSCodium. On Linux this is sometimes handled by the desktop (eg GNOME), sometimes by the browser (eg about:config in Firefox... unfortunately I'm not too familiar with LibreWolf.)

At the moment, there is a workaround in the Cody extension:

1. Copy the access token out of the box in the first screenshot.
2. Open VSCodium, click on Cody
3. Sign in to an Enterprise instance
4. Type in https://sourcegraph.com
5. Paste in the access token

Hope this helps!
