### ISSUE TITLE
bug: Can not Get started with vscode

### ISSUE THREAD

**Issue by albilu** [sourcegraph/cody#3297]
### Version

1.6.0

### Describe the bug

When Clicking on Get Started after signin process with github account from vscode nothing happen and i am stuck in the page below
![image](https://github.com/sourcegraph/cody/assets/35330562/3f8bcdcc-5aa3-4f92-8162-2f42c31bccdb)

### Expected behavior

Sign in process complete and extension is usable in vscode

**Comment by creamcast** [comment]
Same happening here, tried several different browsers and devices but nothing worked. It must be a joke.

**Comment by dominiccooney** [comment]
@chenkc805 could you help us triage and fix this? IIRC your team is simplifying this process, but it looks like it is not working, or people aren't noticing the VS Code window has signed in, etc.
