### ISSUE TITLE
Add Kotlin support to Autocomplete 

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#3303]
Right now, Kotlin has no support for multi-line completions and is not considered in TreeSitter.

- [ ] Add Kotlin to the supported TreeSitter grammers and ensure it works c.f. https://github.com/sourcegraph/cody/blob/main/vscode/src/tree-sitter/grammars.ts#L9-L21
- [ ] Add Kotlin to the list of supported multi-line completion languages c.f. 
   - https://github.com/sourcegraph/cody/blob/main/vscode/src/tree-sitter/language.ts#L8
   - https://github.com/sourcegraph/cody/blob/main/vscode/src/completions/detect-multiline.ts#L35-L55

**Comment by kalanchan** [comment]
from EPD grooming:
- add rust

**Comment by beyang** [comment]
@valerybugakov does this mean Kotlin and Rust currently don't take advantage of dynamic multiline completions (given the latter relies on tree-sitter information)?

**Comment by kalanchan** [comment]
@philipp-spiess we're going to add this to your plate next sprint, if you have capacity please feel free to add this

**Comment by valerybugakov** [comment]
> does this mean Kotlin and Rust currently don't take advantage of dynamic multiline completions (given the latter relies on tree-sitter information)?

- We fall back to the indentation-based truncation. Dynamic multiline completions should still work as long as we have the language support configured in [this list](https://github.com/sourcegraph/cody/blob/main/vscode/src/tree-sitter/language.ts#L8). I can add Kotlin support today.
- With https://github.com/sourcegraph/cody/pull/3373, we have Kotlin and Rust grammars, so they will leverage tree-sitter for multiline truncation.

**Comment by valerybugakov** [comment]
Here's the implementation: https://github.com/sourcegraph/cody/pull/3404

**Comment by dominiccooney** [comment]
Predicting some questions after EPD triage, @csells: *Suggestion* counts by language are in [the Looker Cody (events) dashboard.](https://sourcegraph.looker.com/dashboards/476?Server%20Endpoint=&IDE=) (Acceptance Rate by Language) and we could use that as a crude proxy for language usage.

Language use varies depending on the editor.

In VSCode:

- Rust is our 19th top language
- Kotlin, our 117th (this is a surprise to me that it is so low)

In JetBrains:

- Kotlin is our 4th top language (guess we found all the Kotlin hackers)
- Rust is our 15th top language

# What next?

Some candidates to focus on next, based on this idea: Ruby, Scala, SQL (embedded SQL could be tricky/interesting), CSS

I also took a bit of a different approach... One problem with Looker is some languages have very few suggestions. But assuming CAR of ~0.3 and using the Binomial theorem we can find lists of "definitely under performing" languages. If we want to improve CAR, we should work on `javascriptreact` and `typescriptreact`. They are super popular and definitely underperforming:

(with VSCode data:)

```
number of suggestions, language, 95% confidence interval on CAR
(69695, 'typescriptreact', ConfidenceInterval(low=0.2537500018415423, high=0.2602525920100153))
(20089, 'javascriptreact', ConfidenceInterval(low=0.2658447206982429, high=0.2782006194722877))
(11282, 'html', ConfidenceInterval(low=0.1847553428288961, high=0.19937842063777586))
(9299, 'vue', ConfidenceInterval(low=0.21545626198001067, high=0.23250711373953362))
...
```

(with JetBrains data:)

```
(4439, 'typescriptreact', ConfidenceInterval(low=0.2440134997770568, high=0.2699363853658348))
(1421, 'dart', ConfidenceInterval(low=0.17058846569465186, high=0.21212020659893344))
(1019, 'vue', ConfidenceInterval(low=0.14906424825357784, high=0.19632357711590956))
(772, 'markdown', ConfidenceInterval(low=0.16085996487384843, high=0.21719596343385086))
```

**Comment by dominiccooney** [comment]
Reopening, retitling this to track the Rust ask.

**Comment by kalanchan** [comment]
cc @chillatom @csells @taylorsperry  kotlin and rust is supported now
