### ISSUE TITLE
Test command should generate file name with correct file path

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#3311]
Reported by Dan Diemer on [Slack](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1709594478210299):

> Cody is creating a new test file in the src path with the same name as the actual test file for the code. The file should be lived in the /test path instead

From beyang: 

> we probably need to add something to the test generation command to search for existing test files in parallel directory hierarchies. It's not uncommon to have parallel directory hierarchies under top-level src/ and test/ directories in many codebases (this is in contrast to the pattern in most Sourcegraph codebases, where unit test files are often colocated with the files they test).

**Comment by csells** [comment]
We've heard VIP customer feedback that they'd like their unit tests to be generated to match not just their testing framework but also the coding style, i.e. single quotes instead of double quotes and not generating semi-colons at the end of lines.
