### ISSUE TITLE
bug: @-mentioned file not included in one hour old chat

### ISSUE THREAD

**Issue by itsklimov** [sourcegraph/cody#3320]
### Version

1.6.1

### Describe the bug

in 1 hour old chat, it did not look at the files and wrote generic recommendation

### Expected behavior

after restart it answered as expected

### Additional context

        "text": "@front/admin/routers/login.py what is in this file?",
        "speaker": "human"
      },
      {
        "speaker": "assistant"
      }
    ]
  }
}
█ logEvent: CodyVSCodeExtension:chatResponse:hasCode VSCode {"properties":{"lineCount":34,"charCount":1364,"requestID":"816f8542-62ee-48d2-8e5e-a272e8713c4e"},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent: cody.chatResponse.new/hasCode: {"parameters":{"version":0,"metadata":[{"key":"lineCount","value":34},{"key":"charCount","value":1364},{"key":"recordsPrivateMetadataTranscript","value":1},{"key":"contextSelection","value":10},{"key":"guardrails","value":0}],"privateMetadata":{"requestID":"816f8542-62ee-48d2-8e5e-a272e8713c4e","responseText":"As an AI developed by OpenAI, I don't have direct access to your files or any specific implementation details that are not provided in the conversation. However, I can give you an example of what might typically be found in a `login.py` file within the `routers` directory of a FastAPI application.\n\nThe `login.py` file would generally contain route definitions related to user authentication, such as displaying a login form, handling login submissions, and possibly handling logout actions. Here's a basic example of what such a file might look like:\n\n```python\nfrom fastapi import APIRouter, Depends, HTTPException, status\nfrom fastapi.security import OAuth2PasswordRequestForm\nfrom fastapi.responses import RedirectResponse\nfrom fastapi.templating import Jinja2Templates\nfrom starlette.requests import Request\n\nfrom . import auth  # This would be a module with your authentication logic\n\nrouter = APIRouter()\ntemplates = Jinja2Templates(directory=\"path/to/your/templates\")\n\n@router.get(\"/login\")\nasync def login_form(request: Request):\n    return templates.TemplateResponse(\"login.html\", {\"request\": request})\n\n@router.post(\"/login\")\nasync def login(request: Request, form_data: OAuth2PasswordRequestForm = Depends()):\n    user = auth.authenticate_user(form_data.username, form_data.password)\n    if not user:\n        raise HTTPException(\n            status_code=status.HTTP_401_UNAUTHORIZED,\n            detail=\"Incorrect username or password\",\n            headers={\"WWW-Authenticate\": \"Bearer\"},\n        )\n    access_token = auth.create_access_token(data={\"sub\": user.username})\n    response = RedirectResponse(url=\"/\", status_code=status.HTTP_302_FOUND)\n    auth.set_access_token_cookie(response, access_token)\n    return response\n\n@router.get(\"/logout\")\nasync def logout():\n    response = RedirectResponse(url=\"/login\", status_code=status.HTTP_302_FOUND)\n    auth.remove_access_token_cookie(response)\n    return response\n```\n\nIn this example, the `login_form` route returns a template for the login page, the `login` route handles the login logic (authenticating the user and setting a cookie with an access token), and the `logout` route handles logging the user out (removing the access token cookie).\n\nThe `auth` module would contain the actual authentication logic, such as verifying user credentials and generating access tokens. The `OAuth2PasswordRequestForm` dependency is a utility that provides an easy way to handle login forms that submit `username` and `password` fields.\n\nPlease note that this is just an example, and the actual contents of your `login.py` file could be different based on your specific application's requirements and your authentication implementation."}},"timestamp":"2024-03-06T16:35:31.579Z"}

**Comment by dominiccooney** [comment]
@itsklimov when you @-mentioned the login.py file, I get the impression it did not appear in context. It would be great if we could see a little bit earlier in the log to help determine why.

I'm trying to reproduce this. You mentioned the chat was an hour old. Did you restart VSCode in that time, close and reopen the chat, anything like that?
