### ISSUE TITLE
PRD: Context Error Reports

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3321]
### Description:

Epic for collecting user bug reports related to context retrieval, ranking, use etc.  

### Objectives:

Purpose is to create a centralized view of the issues to identify trends and propose general fixes. 

### Acceptance Criteria:

N/A

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/sourcegraph/cody/issues/3322
- [ ] https://github.com/sourcegraph/cody/issues/3331
```

### Related Docs:

N/A

**Comment by spirelab** [comment]
still the same or what? it says its an ai assitant and cant access my code? whats the point? i am a pro user
