### ISSUE TITLE
Chat context suggestions

### ISSUE THREAD

**Issue by st0nebraker** [sourcegraph/cody#335]
When Cody Web chat context is empty, add suggested repositories to aid user to more quickly add context for a better interaction. The suggested repositories could be based on their chat history, most used, or just alphabetically chosen.

![Image](https://user-images.githubusercontent.com/59381432/254965265-94d72442-4400-4dd9-86df-68488ef2fe3a.png)

**Comment by thenamankumar** [comment]
Closing this in favour of: https://github.com/sourcegraph/sourcegraph/issues/55363
