### ISSUE TITLE
feedback: Sentry related failure when chatting, getPropagationContext

### ISSUE THREAD

**Issue by ABISHEK-KU** [sourcegraph/cody#3356]
### Version

v1.8.1

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [X] Other

### What needs to be improved? Please describe how this affects the user experience.

when i chat this error is only coming. not able to chat. Request Failed: scope.getPropagationContext is not a function

### Describe the solution you'd like to see

![Uploading Screenshot 2024-03-08 at 4.23.20 PM.png…]()

**Comment by dominiccooney** [comment]
@ABISHEK-KU is this problem still happening? Could you try updating VSCode, the Cody extension and seeing if the problem still occurs? If the problem does occur, in the Cody sidebar under Settings & Support could you click ..., Export Logs and share those logs with us?

getPropagationContext indicates a problem related to Sentry.
