### ISSUE TITLE
Bug: Super large message in Cody is completely ignored silently with no context and an added fake preamble

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#3364]
### Version

1.8

### Describe the bug

Very large message sent to the cody chat completely borks the context addition of the chat and then the chat only has the preamble and nothing else. 

This happens in the codebase [here](https://sourcegraph.com/-/editor?remote_url=https%3A%2F%2Fgithub.com%2Fsourcegraph%2Fcody.git&branch=main&file=vscode%2Fsrc%2Fprompt-builder%2Findex.ts&editor=VSCode&version=2.2.16&start_row=49&start_col=18&end_row=49&end_col=18) basically if when adding messages in the reverse order if the context of the message itself is too large then the message has absolutely nothing but a template preamble and its gives a response like this

<img width="341" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/2c2a69f5-13fe-4ba9-9289-337de7787c03">

### Expected behavior

Theres two ways to solve this
1. Notification: We can raise some kind of notification or messaging but I would hate to go down that route @toolmantim and @abeatrix have already pontificated enough times on this so I don't want to bring this again. I think it would be pretty safe to say that the messaging for context exceeded through notification/ error handling is atrocious. So lets do something else
2. LLM context addition: Add a condition in [tryaddmessages](https://sourcegraph.com/-/editor?remote_url=https%3A%2F%2Fgithub.com%2Fsourcegraph%2Fcody.git&branch=main&file=vscode%2Fsrc%2Fprompt-builder%2Findex.ts&editor=VSCode&version=2.2.16&start_row=49&start_col=21&end_row=49&end_col=21) to add a template text as context to the LLM inscase the message is so so large that it can't be added to the context. That way the LLM would just tell the users. "hey you gave me a very large messsage or file and I can't handle it". They can natually figure out. what to do next. We can tweak that text too 

What do I need now? Just @abeatrix or @beyang if both of you give me a thumbs up I will immediately spin up a PR for this. IT should be very easy to implement this. Unless you have other suggestions this looks like a simple and the best course of action.

**Comment by abeatrix** [comment]
@arafatkatze hey ara thanks for filing the issue! There's an issue we created a while ago regarding to large context being removed here as well https://github.com/sourcegraph/cody/issues/2636 

In the screenshot you shared, I believe that's from jetbrains, is that correct? 

In VS Code, users can see a warning about the file being too large when they trying to @ it, and I believe @kalanchan is working with the JB team to add that.

> Add a condition in tryaddmessages to add a template text as context to the LLM inscase the message is so so large that it can't be added to the context. That way the LLM would just tell the users. "hey you gave me a very large messsage or file and I can't handle it". 

If we can already tell that the message is too large, I don't see the point of sending template text to LLM if we can just display it locally, where we can just display "hey you gave me a very large messsage or file and I can't handle it" without sending the request to LLM in the first place?

@toolmantim has a design iirc to show users the removed context in the chat ui to surface the issue to the users, which I think will help. Plus I believe the main issue here is that the JB users currently cannot tell if the file is too large before they add the file, where vs code users can now see the warning.

I will bring this up again in our next team meeting to see how we want to proceed though and will keep you posted!

**Comment by arafatkatze** [comment]
> In VS Code, users can see a warning about the file being too large when they trying to @ it, and I believe @kalanchan is working with the JB team to add that.

Yeah that stuff already exists and I saw it 
<img width="430" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/0c521116-43f7-46f3-bf5d-a5bf475a1655">


> In the screenshot you shared, I believe that's from jetbrains, is that correct?

Yes


> If we can already tell that the message is too large, I don't see the point of sending template text to LLM if we can just display it locally, where we can just display "hey you gave me a very large messsage or file and I can't handle it" without sending the request to LLM in the first place?

IF thats the route you folks want to pursue then its fine by me. MY only concern was the the UI around this kind of error raising hasn't been nice too often but if you and tim think that would be the right thing to do then its fine. 

I just wanted to let you know that this is an enteprize issue and I would really like to solve it sooner rather than later. Happy to help in any way to speed up the resolution of this. 

🙇

**Comment by abeatrix** [comment]
> IF thats the route you folks want to pursue then it's fine by me. MY only concern was the the UI around this kind of error raising hasn't been nice too often but if you and tim think that would be the right thing to do then its fine. 


I don't know if that's the right thing to do. I was just pointing out sending template text to the LLM and have the LLM display the warning message would be the same as displaying the warning message without sending the template text to the LLM 😅 

> I just wanted to let you know that this is an enteprize issue and I would really like to solve it sooner rather than later. Happy to help in any way to speed up the resolution of this. 

Yea that's fair! As you mentioned you can see the warning when trying to @ a large file in VS Code but not in JB, so I think the next best step is to the add the warning to JB, Wdyt?

**Comment by arafatkatze** [comment]
> Yea that's fair! As you mentioned you can see the warning when trying to @ a large file in VS Code but not in JB, so I think the next best step is to the add the warning to JB, Wdyt?

Okay if we add the warning to Jb then we atleast have a fallback by saying that the file selected was too large so that's why people are faced this issue of context ignored. Come to think of it, the file being too large thing NOT being present in Jetbrains is lack of feature parity and also lack of clarity and we(and in this I) should solve it regardless of this issue.

> I don't know if that's the right thing to do. I was just pointing out sending template text to the LLM and have the LLM display the warning message would be the same as displaying the warning message without sending the template text to the LLM 😅

Practically they seem to have the same intent and the only question is that which preference has a cleaner design and is better thing that must be present in our codebase. Since @toolmantim and you have a lot of experience with adding/removing things in this regard I am leaving this choice upto you. You tell me what to do and I will implement that or if you feel that its faster to implement it yourself thats fine too. Whatever reduces friction to get it out to the enterprize people really soon.

**Comment by kalanchan** [comment]
> If we can already tell that the message is too large, I don't see the point of sending template text to LLM if we can just display it locally, where we can just display "hey you gave me a very large messsage or file and I can't handle it" without sending the request to LLM in the first place?

+1 to @abeatrix's  logic here, why wait one whole turn before telling our users that the context is too large to handle if we can prevent it in the first place 

The whole thinking behind multi turn chat is that a user can continuously ask questions without having to start a new chat, I don't think it's unreasonable that the LLM starts forgetting things after a conversation has gotten really long. The main issue is if the LLM starts forgetting things after 1 or 2 turns, so maybe we need a better way to nudge the user to start a new chat OR just select the interested lines of code to use instead? 

We're going to be adding the "file too large warnings" in JetBrains next week, which should help as a stop gap for now.

**Comment by arafatkatze** [comment]
>  why wait one whole turn before telling our users that the context is too large to handle if we can prevent it in the first plac

Cool so we can just raise a notification and say that the message sent was too large. 

NOTE: This issue is about the fact that the message is "secretly" skipped in the first term itself when you send a really large message and thats what I was referring to (rather than waiting a turn thingy). 

>  I don't think it's unreasonable that the LLM starts forgetting things after a conversation has gotten really long. 

Yeah thats fine and I am personally okay with that behaviour and see not much of a reason to nudge users. We have done a ton of back and forth on this so doing the nudge thing again seems unwise. 

> We're going to be adding the "file too large warnings" in JetBrains next week, which should help as a stop gap for now.

Thats awesome sounds good


So effectively there are 2 action items
1. Jetbrains Warning -> Raise file too large warnings -> will be handeled by the right team next week
2. Raise notification/warning message about the "skipping" the first message thingy. Lets let @toolmantim decide what should be done for that one(I can do the implementation)

**Comment by aramaraju** [comment]
I'm happy with the problem definition here, and the suggested solutions. Let's hear from @toolmantim to make sure the user experience is accounted for. Thanks @arafatkatze

**Comment by toolmantim** [comment]
Has anyone been able to reproduce this in VS Code? I tried copy + pasting many lines, or @'ing large files, and I can't seem to reproduce the issue.

**Comment by arafatkatze** [comment]
Yes I did reproduce this on Vscode.

The prompt is "explain <Copy[ this entire file ](https://sourcegraph.com/-/editor?remote_url=https%3A%2F%2Fgithub.com%2Fsourcegraph%2Fcody.git&branch=main&file=vscode%2Fsrc%2Fchat%2Fchat-view%2FSimpleChatPanelProvider.ts&editor=VSCode&version=2.2.16&start_row=9&start_col=21&end_row=9&end_col=21)>"

**Comment by abeatrix** [comment]
Fixed in https://github.com/sourcegraph/cody/pull/3528
We now display the excluded @-mention files in UI to avoid confusion: 
![image](https://github.com/sourcegraph/cody/assets/68532117/fef4eb1b-0410-42aa-9196-8b8b1a7def1e)
