### ISSUE TITLE
bug: Often the Cody chat does not work and an error can be seen at the top of the chat tab

### ISSUE THREAD

**Issue by pitAlex** [sourcegraph/cody#3368]
### Version

1.8.2

### Describe the bug

Something is wrong with the chat feature in the VS Code extension of this AI. While at first it was working fine, now it frequently stops working, displaying this error at the top: "Cannot read properties of undefined (reading 'line')", forcing me to delete the current chat history and start a new one.

### Expected behavior

It should not display an error and should respond to my prompt.

**Comment by Caio-Sc** [comment]
this happens to me when I close the chat and open it again.
![image](https://github.com/sourcegraph/cody/assets/53196995/2a78128b-a137-4380-af7d-ffc124ebb534)
