### ISSUE TITLE
Cody plugin "Stop generating" button remains visible indefinitely

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/cody#337]
VSCode version: 1.80.1 (Universal)
Operating System: macOS 13.5
Cody version: 0.6.0

We received a report of an issue with Cody's "Stop generating" button. The issue is that the button remains visible indefinitely after any query. The user needs to reload the VSCode window to return to a state where they can query Cody again. This problem is reproducible for the user for any query they make.

https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1689810902501119

**Comment by abeatrix** [comment]
@gabtorre i think this is resolved in https://github.com/sourcegraph/cody/pull/598 

Feel free to reopen the case if you run into this again, thanks!
