### ISSUE TITLE
Onboarding experiment - interactive editor buffer walkthrough

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#3401]
Asana: https://app.asana.com/0/1206519077296236/1206770402820250

Figma: https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=2007-46416&mode=design&t=Y3nQFWe3AjCDNbBw-4

**Comment by kalanchan** [comment]
Landed in v1.16
