### ISSUE TITLE
Autocomplete: implement the "percentage of code written by Cody" metric

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/cody#3403]
- We want to log this as an aggregated value of chars users add. Every completion suggestion event we track will also include a cumulative number of all the new characters added since the last suggestion event.
- [Slack thread](https://sourcegraph.slack.com/archives/C01GJFE26BX/p1707405544177009)

**Comment by philipp-spiess** [comment]
@valerybugakov see https://github.com/sourcegraph/cody/pull/3070

**Comment by valerybugakov** [comment]
Noice! Linked the issue to the PR 🙌
