### ISSUE TITLE
bug: Inline Edit Mode Cannot Add Lines in Selection

### ISSUE THREAD

**Issue by vincentsch** [sourcegraph/cody#3408]
### Version

v1.8.2

### Describe the bug

When selecting a code block, such as `<script setup>...</script>` in a Vue component, and subsequently using inline edit mode for modifications, the resultant code may occasionally exceed the length of the original selection. In such cases, the insertion or editing process halts at the last selected line, resulting in truncated code.

### Expected behavior

The editor should automatically add new lines as needed when the modified code is longer than the original selection, ensuring no code gets cut off.

**Comment by vincentsch** [comment]
Another case: I created an empty docker-compose.yml file and used Alt+K to generate the contents with Claude Opus 3. The code is generated and ends abruptly at line 75, leaving me with a truncated file.

**Comment by dominiccooney** [comment]
@vincentsch could you share your prompt for the long dockerfile?

I can't reproduce a problem with adding to the end of a ~screenful of selected code. I think this is about lengthy output being truncated.

I created an empty Julia file and asked Claude/Opus 3 to write a Lua parser and interpreter. Claude/Opus 3 is not up to this task (although its attempt is interesting...) but for me the output is truncated after 127 lines ending with `function interpret(ast, scope=LuaScope(nothing`. This is almost certainly hitting a stop token but we are not giving any feedback about what's happening.

We should add metrics for stop reason in edit output to assess how often this happens. It appears we record the interaction as a success.

Assigning to @toolmantim for input on what the feedback should be.

CC @umpox for edit.
