### ISSUE TITLE
bug: Python symbol search with '@#' retrieves single line only, not the complete object

### ISSUE THREAD

**Issue by Remote-Radical** [sourcegraph/cody#3411]
### Version

1.8.3

### Describe the bug

Manually providing symbol using '@#' retrieves only a single line where symbol is defined. This makes the provided context useless in most cases. See attached screenshots.

![image](https://github.com/sourcegraph/cody/assets/49757637/1f24cb2d-2c92-42f3-bb00-65f88238c248)

![image](https://github.com/sourcegraph/cody/assets/49757637/05931310-19e0-4732-809d-4f8862f4fd44)

### Expected behavior

I expect the symbol search to retrieve all lines of object definition when working with object-oriented languages.

**Comment by dominiccooney** [comment]
I can reproduce this with VSCode 1.87.2, Cody 1.8.3, Python extension 2024.2.1.

The Python symbols are just the first line of the definition.
