### ISSUE TITLE
feedback: request: Generate the commit message for staged changes

### ISSUE THREAD

**Issue by sughodke** [sourcegraph/cody#3425]
### Version

v1.8.2

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [X] Other

### What needs to be improved? Please describe how this affects the user experience.

A new feature to create a commit message given the staged commits

### Describe the solution you'd like to see

In the revision control screen, when I select files or chunks to be staged I would love to see the agent generate a commit message

### Describe any alternatives that could be considered

`git diff | gpt -p "Write a brief commit message given these changes" | pbcopy`

Requires this tool https://github.com/kharvd/gpt-cli

### Additional context

Generated message would show up in this textbox.

<img width="395" alt="Screenshot 2024-03-15 at 10 31 40 AM" src="https://github.com/sourcegraph/cody/assets/31588/1f8d739c-3b1b-4989-b796-ed7427a457d6">

**Comment by vadi2** [comment]
What is the latest on this? It would be great to have this in.

**Comment by sirnails** [comment]
This would be a game changer! looking forward to seeing this...

**Comment by esafak** [comment]
I have the same request for IntelliJ.
