### ISSUE TITLE
bug: Visual Studio Code on Apple Silicon

### ISSUE THREAD

**Issue by KyvosUser** [sourcegraph/cody#3426]
### Version

1.87 (Apple Silicon)

### Describe the bug

The Cody extension installs perfectly. However the icon does not appear in the sidebar, so I cannot login to my account or use the chat / code features. The settings page for Cody is displayed in VSC, but there is nothing there to troubleshoot the issue. Same happens in VS Codium, and every other clean installation on Apple Silicon (deleted prefs, new user account etc.)

### Expected behavior

The Cody icon should appear in the sidebar of VS Code

**Comment by dominiccooney** [comment]
Hey @KyvosUser, many people on the Cody team use Cody in VSCode on Apple Silicon. There are a few extensions on the marketplace with Cody in the name, first let's confirm you have the right one.

Could you got to Extensions, ..., Views > uncheck everything except *Installed*, scroll down to Cody, click on the gear, Copy and then paste the result here?

You need this one: https://marketplace.visualstudio.com/items?itemName=sourcegraph.cody-ai
