### ISSUE TITLE
feedback: Edit Code Prompt Usability

### ISSUE THREAD

**Issue by smojef** [sourcegraph/cody#3427]
### Version

1.8.3

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

When I select code and press ALT-K, a small prompt box appears (to Edit Code).  
I have several issues:
1. If I start typing a long prompt for good AI behavior, then I will lose everything I typed if I press the ALT key (such as pressing ALT-TAB) or if I click on another application (like an OS popup notification).
2. If I type in the following prompt "Make this function compatible with @api", then a drop down list of files appears containing the word "api", and if I press TAB (expecting to continue with the selected file), then the prompt is lost.
3. There should be a way to quickly add the current file in the context for the prompt without typing its name

### Describe the solution you'd like to see

1. Preserve the partial prompt the next time we press ALT-K, fully selected, so that we can type to overwrite it or press right arrow to continue writing the prompt.
2. The user expects to press ENTER to submit the prompt, TAB should be a valid keyword to select suggestions while writing the prompt.
3. Maybe "@@" could be a simple expression to include the current editor context

### Describe any alternatives that could be considered

Alternatively, the prompt box could be improved to a multiline editor, with history and other features

**Comment by dominiccooney** [comment]
I'd like to second this feedback about alt-tabbing. I write very long edit prompts and the box is too small, and I often want to alt-tab to cut and paste something.

**Comment by toolmantim** [comment]
> 1. If I start typing a long prompt for good AI behavior, then I will lose everything I typed if I press the ALT key (such as pressing ALT-TAB) or if I click on another application (like an OS popup notification).
> 2. If I type in the following prompt "Make this function compatible with @api", then a drop down list of files appears containing the word "api", and if I press TAB (expecting to continue with the selected file), then the prompt is lost.

I think we should set `ignoreFocusOut: true` for the edit quickpick, which will allow copy+paste, not cause the tab to lose the prompt, etc. That should resolve both these issues.

@umpox any reason we set it to false? I think it's important in this case it's true (same for why we do that for the "Paste your API token" for login)

> 3. There should be a way to quickly add the current file in the context for the prompt without typing its name

Agreed, we should show a list of open files in the list by default, similar to what we do for chat:

![CleanShot 2024-03-19 at 18 19 21@2x](https://github.com/sourcegraph/cody/assets/153/2a7f6bbe-1103-47f7-8fca-0d70075b01a6)

**Comment by umpox** [comment]
@toolmantim If we set `ignoreFocusOut` should we add a "Close" (X) button so a user doesn't have to always know to use <kbd>Esc</kbd> to get rid of it. My concern is that most quick picks don't have this behaviour so it could be annoying to users.

We could also only enable `ignoreFocusOut` when the input is dirty

**Comment by toolmantim** [comment]
A close button is a good idea. I believe some quickpicks also put “Esc to cancel” text in the placeholder too, if we need it.

Only on dirty is interesting. You’d have to try it, but maybe that plus a close button would be the winning combo.
