### ISSUE TITLE
Support for custom providers

### ISSUE THREAD

**Issue by OlegTopalov** [sourcegraph/cody#3432]
Is it possible to use Ollama as a custom provider, like it's desribed in here? https://sourcegraph.com/blog/local-code-completion-with-ollama-and-cody

(using Cody with Rider)

**Comment by sqs** [comment]
Do you mean using Ollama for chat and commands? Ollama is supported for autocomplete as mentioned in the blog post, and there's even more experimental Ollama support for chat and commands as well; see #3252 for instructions on how to use it. See https://twitter.com/sqs/status/1750045006382162346 for a demo.

**Comment by OlegTopalov** [comment]
Well, I can use it with VSCode's extension, but can't find those settings in Jetbrains' plugin

**Comment by ThilinaTLM** [comment]
@sqs Is local model support available (ollama) for JetBrains products?

**Comment by jdorfman** [comment]
@ThilinaTLM it is now https://sourcegraph.com/blog/cody-jetbrains-6-0-14-release
