### ISSUE TITLE
bug: Output limit and stoppage during the rewrite of a 200 line class.

### ISSUE THREAD

**Issue by Xees** [sourcegraph/cody#3472]
### Version

1.8.3

### Describe the bug

Whenever i try to refactor a class of 200 lines or so. Cody sadly stops writing at about line 100. Which makes it hard to use for anything other than small modifications to functions. Or within large context windows.

![image](https://github.com/sourcegraph/cody/assets/174528/fb84c167-fc33-4982-832b-47b9c5ee843e)

And if asked to continue, it messes up the chat window frame, and context of its current work. like so:

![image](https://github.com/sourcegraph/cody/assets/174528/c1726af8-ca6f-45c9-8952-6696ca139d73)

### Expected behavior

It should continue the output for the full class, or give me a button to continue generating like chatGPT.

### Additional context

I'm using Claude 3 Opus which should have a massive context window and output window.

**Comment by vadi2** [comment]
While it's not ideal, you can type `continue` and it will continue generating output as a workaround.
