### ISSUE TITLE
bug: markdown is not rendered in transcript user message

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#3483]
### Version

main

### Describe the bug

Users can't encapsulate markdown with triple backticks (```) anymore in chat

see video 

https://github.com/sourcegraph/cody/assets/51868853/2f7c3eb4-1909-43a2-84c2-e917533a739a

 

### Expected behavior

in chat users should be able to encapsulate their code in markdown using triple backticks

**Comment by sqs** [comment]
The bug is that the markdown is not rendered when the user's message is displayed in the transcript.

Will look into it now

**Comment by kalanchan** [comment]
also filed in #3496

**Comment by kalanchan** [comment]
@sqs any updates to the fix?

**Comment by kalanchan** [comment]
Based on new design direction to make user transcript less rich, more notebook style
