### ISSUE TITLE
Add getEnclosingFunction logic for range expansion in edits + chats (and possibly other commands)

### ISSUE THREAD

**Issue by umpox** [sourcegraph/cody#3495]
What:
- Edits and Chats currently expand a cursor position to the nearest folding range. This is ok, but it isn’t ideal, there are many cases where this fails for us. For example, an “it” block inside a “describe” block in a JS test is not seen as a folding range, so we always expand the selection to the full “describe” block.
- Ideally we can always expand to the nearest enclosing function if available, before falling back to the folding range logic.

How:
- Add a tree-sitter query to find the nearest enclosing function
- Update our Smart Selection logic to look for this first.
- This should automatically add this behaviour to chat and edit.

**Comment by chillatom** [comment]
Adding an issues that I hope this might address.  Where the user cursor is within a massive class, we throw an error saying "selected text is too long", would be nice to gracefully handle that.  

https://sourcegraph.slack.com/archives/C05AGQYD528/p1711134734677989
