### ISSUE TITLE
bug: Code wrapped in ```  isn't getting formatted by Cody after the latest GPT-4 turbo upgrade

### ISSUE THREAD

**Issue by lalithorcruxer** [sourcegraph/cody#3496]
### Version

1.87.2

### Describe the bug

After the recent[ upgrade](https://github.com/sourcegraph/cody/issues/2919) to the latest GPT-4 Turbo version, cody editor is no longer recognizing the code formatted with ``code```. This is inhibiting the UX in editor.

### Expected behavior

Input should be shown with the formatting applied after pressing enter in the Cody editor

**Comment by kalanchan** [comment]
thanks for the feed back @lalithorcruxer we're aware of this and currently working on a fix

**Comment by kalanchan** [comment]
we're going to fix this in the latest release, thanks!
