### ISSUE TITLE
feedback: awful

### ISSUE THREAD

**Issue by MichalKurzewski** [sourcegraph/cody#3500]
### Version

1.8.3

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [X] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

no idea what needs to be improved, but using Claude3 opus gave me such terrible hallucinated answers i wouldn't even expect from chat gpt3.5. i provided few files as a context, it seems to understand the files, but gave totally idiotic answers twice.

### Describe the solution you'd like to see

any solution that would at least be possible. the question i had was maybe too complicated cause it involved 3 level depth child dependency, but it gave me straight wrong answer from the first glance misplaced the function in wrong context, instead trying to analyse it

### Describe any alternatives that could be considered

no idea i canceled the sub and will wait for Q* probably

**Comment by kalanchan** [comment]
hey @MichalKurzewski thanks for the feedback! 

Is this just happening on Claude 3 Opus? Were you able to get better responses from other LLM models? If you could post an example of your question to Cody we'd like to investigate further

**Comment by MichalKurzewski** [comment]
unfortunately its commercial product, cant send anything out.
to add to that, the chat Opus handled it somehow, with somewhat better
handling of failed trials (they made sense, but didnt work)

i can describe what i wanted and what happened in cody vs code:
- first i had the file opened and asked cody chat to explain the file,
which it gave me an incorrect answer. i drilled down to the fact that it
had incorrect scope analysing (file had 100 ish lines, but when I asked how
many lines there it replied 48 or something similar, which was in the
middle of function scope so totally wrong) after selecting everything in
that file it worked ok on it.
- then I provided the context using @for file paths and asked the question
again. It started to explain instead of attaching the previous prompt
context.
- i made 3 attempts of providing full context and @ files in one prompt and
it hallucinated so heavily i just couldnt look at it. the issue i had was
in a buttonClickHandler in one of the component. cody suggested to move it
into separate scope, which on the first glance would break everything.

thats it. i think ill just stick to web opus chat, and wait for q* doomsday
