### ISSUE TITLE
VS Code: "Show Diff" ghost text is not clickable.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3509]
### Version

v1.10.0

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Pro user
3. Open any source code file, select a code snippet
4. Right click and select "Cody > Document Code"
5. Wait for Cody to generate document for the selected code snippet
6. Try to click on "Show Diff" ghost text

### Observed behavior:

"Show Diff" text is not clickable

### Expected behavior

"Show Diff" ghost text should be clickable and display the diff.

### Additional context

**Screenshot:**

![Screenshot 2024-03-22 at 8 12 34 PM](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/ffc7e9e6-5cff-4210-a6c2-f16260301967/abdd4dc2-5bfd-495b-b0ab-52462a1bbba4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9mZmM3ZTllNi01Y2ZmLTQyMTAtYTZjMi1mMTYyNjAzMDE5NjcvYWJkZDRkYzItNWJmZC00OTViLWIwYWItNTI0NjJhMWJiYmE0IiwiaWF0IjoxNzExMTIwNjM0LCJleHAiOjMzMjgxNjgwNjM0fQ.wEhJdv_e0C4sz7V0_s5YbQvH851Vt9tsiYfirtDDRfY "=815x")

**Comment by umpox** [comment]
We no longer calculate diffs for outputs where we're only _inserting_ new code.

We should hide this CTA and instead show the diff directly in the document (add the git diff added background)

**Comment by umpox** [comment]
PR for quick fix: https://github.com/sourcegraph/cody/pull/3537

> instead show the diff directly in the document (add the git diff added background)

Will do this in a follow up PR
