### ISSUE TITLE
Edit: Track persistence rate for variants of edit over X seconds/minutes

### ISSUE THREAD

**Issue by umpox** [sourcegraph/cody#3513]
What:
- We don’t have a similar concept of “completion acceptance rate” for Edits. Edits are applied by default, so there is no actual acceptance action.
- We should instead, try to track the persistence of an edit over X seconds/minutes.

How:
- We already have a persistence tracker for completions, we can use this for Edits.
- We need to use chunks from the diff to track specific lines, rather than the whole edit. Tracking the entire selection range will be misleading, as the edit may only actually change a few characters or lines.
- We need to ensure that we correctly calculate a % of code left from the edit, combining both deletions and insertions. For deletions, we need to be tracking that code that Cody deleted, remains deleted.

**Comment by philipp-spiess** [comment]
There's some discussion about this in this thread: https://sourcegraph.slack.com/archives/CN4FC7XT4/p1710299380435099

One problem with persistence is that edits can also just delete code and if that happens we have no ranges that we can track after. We don't know if newly inserted characters are trying to _undo_ the completion or adding more text. Might need some thinking about how we can make this work well 🤔

**Comment by umpox** [comment]
Done
