### ISSUE TITLE
Formatting/copying issues in the chat window

### ISSUE THREAD

**Issue by JohnMcLaren** [sourcegraph/cody#352]
The problems described below were found by me in the `Cody` extension for `VSCode`.
1. The mouse context menu command "copy" does not work in the chat window.
But `<Ctrl + C>` works.
2. The problem with all `html documents` is that list item markers are **not selected** 
and cannot be copied along with the contents of the list:
```html
<ol>
    <li> action one </li>
    <li> action two </li>
    <li> action three </li>
</ol>
<ul>
    <li> firstly </li>
    <li> secondly </li>
    <li> thirdly </li>
</ul>
```
Cody also uses similar formatting in his replies and 
so all the lists in the reply are copied garbled (**no item markers**).

3. If a query string contains an expression with angle brackets, 
it will be cut out when displayed in chat, i.e.:
    - `What is <int>?`
it's turning into:
    - `What is ?`
Although, the content <...>, judging by the replies, Cody receives.

**Comment by jdorfman** [comment]
Hey @JohnMcLaren what OS are you using? I was unable to replicate it on macOS.

Just out of curiosity does "Insert at Cursor" also not work?

<img width="325" alt="Image 2023-07-21 at 2 29 30 PM png" src="https://github.com/sourcegraph/cody/assets/398230/72ce4c12-ea6e-46e1-8350-16ffe7ce1279">

**Comment by JohnMcLaren** [comment]
Hey @jdorfman !
I'm using Linux.
Initially, those problems were found in Kali Linux.
I then checked the behaviour of Cody in [Debian Live](https://www.debian.org/CD/live/) and [Kali Live](https://www.kali.org/get-kali/#kali-live).
VSCode was installed in them in the [same way](https://code.visualstudio.com/docs/setup/linux)  from the console:
```sh
# Get additional utilities
sudo apt install wget gpg apt-transport-https

# Add Microsoft key and repo
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg && \
sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg && \
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] \
https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list' && \
rm -f packages.microsoft.gpg

# Update repo sources
sudo apt update

# Install VSCode (~380 MB)
sudo apt install code
```
I noticed that the contents of the "About" window in VSCode in Live systems are different from what I saw in Kali Linux.
```
============================ Debian 12 XFCe Live
VSCode "About"
    Version: 1.80.1
    Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
    Date: 2023-07-12T17:22:25.257Z
    Electron: 22.3.14
    ElectronBuildId: 21893604
    Chromium: 108.0.5359.215
    Node.js: 16.17.1
    V8: 10.8.168.25-electron.0
    OS: Linux x64 6.1.0-9-amd64

============================ Kali Linux Live (XFCe v4.16 GTK v3.24.34)
VSCode "About"
    Version: 1.80.1
    Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
    Date: 2023-07-12T17:22:25.257Z
    Electron: 22.3.14
    ElectronBuildId: 21893604
    Chromium: 108.0.5359.215
    Node.js: 16.17.1
    V8: 10.8.168.25-electron.0
    OS: Linux x64 5.18.0-kali2-amd64

============================ Kali Linux (XFCe v4.18 GTK v3.24.37 NodeJS v17.4.0)
VSCode "About"
    Version: 1.80.1
    Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
    Date: 2023-07-12T17:22:25.257Z
    Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.80.1 Chrome/108.0.5359.215 Electron/22.3.14 Safari/537.36

```
Then I completely **re-installed VSCode** on the main Kali Linux system and that seems to have **solved the copying problem**.
```
============================ Kali Linux (XFCe v4.18 GTK v3.24.37 NodeJS v17.4.0)
VSCode "About" (after re-installing VSCode)
    Version: 1.80.1
    Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
    Date: 2023-07-12T17:22:25.257Z
    Electron: 22.3.14
    ElectronBuildId: 21893604
    Chromium: 108.0.5359.215
    Node.js: 16.17.1
    V8: 10.8.168.25-electron.0
    OS: Linux x64 5.18.0-kali2-amd64
```
* **Differences in behaviour between Debian and Kali Linux** 

**Behaviour of buttons on code in the chat window:**
1. "insert at Cursor" - inserts, regardless of the selection, all code at the specified position.
2. "Copy" - in Kali copies all code regardless of selection. In Debian it copies the selected code fragment.
3. Copying the selected code with the mouse - works.

**Behaviour on plain text in the chat window:**
Copying selected text with the mouse - works identically in both Kali and Debian.

_One more question, why are there **"Cut"** and **"Paste"** items in the mouse context menu 
if they don't even apply to the text of Cody's reply anyway?_

**The behaviour with angle brackets** in the request, in both systems is the same, they are not displayed:
![image](https://github.com/sourcegraph/cody/assets/10256841/82f2a44b-d935-4880-8de1-e24120e096da)

**The behaviour when copying lists** in the response text is also identical, 
only the text `without markers and indentation` is copied.
To test this, create a request to which Cody will respond with a list.
For example, _"Steps to calculate Pi."_
Then select the list and copy it. As you can see the list markers are not selected:
![image](https://github.com/sourcegraph/cody/assets/10256841/7eb6ac6a-1d2c-4ec3-bff6-03e229c1c622)
Once pasted into a plain text document, the list will turn into this:
![image](https://github.com/sourcegraph/cody/assets/10256841/8125ee69-7c79-4f55-a743-cc19ff932049)

_Is it a different behaviour on Macs and the lists are copied correctly?_

**Comment by jdorfman** [comment]
Thank you so much @JohnMcLaren, for this detailed report! I will share it with the team and follow up asap.

**Comment by JohnMcLaren** [comment]
@jdorfman , I was able to get **100% reproduction** of the mouse copy problem in the Cody panel.
The thing is, to get the` "Forward"` and `"Backward"` code navigation buttons
![bwd-fwd](https://github.com/sourcegraph/cody/assets/10256841/edaac5f9-667a-4774-a1e5-aa229ab1e3a7)
, we do the following:
1. Enable Command Center showing - enable the `"Window: Command Center"` option
![image](https://github.com/sourcegraph/cody/assets/10256841/047c657d-49a4-4f85-8708-667ffaeeaa5b)
2. Set the value of `"Window: Title Bar Style"` to `"custom"`
![image](https://github.com/sourcegraph/cody/assets/10256841/029d2093-931b-49f2-9bcb-7ccaa2c21528)

It is after doing the 2nd point that - copying with the mouse begins to work incorrectly.
Instead of copying a selected text/code fragment in the Cody panel, 
a **line from the code window with the cursor on it** is copied to the clipboard.
