### ISSUE TITLE
VS Code: Cody allows blank message to post and also respond.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3520]
### Version

v1.10.0

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Free/Pro user
3. Open New Chat 
4. Hit enter twice

### Observed behavior:
Blank message will be posted and Cody will also respond.

### Expected behavior

Blank message shouldn't be allowed.

### Additional context

**Video link:**

https://drive.google.com/file/d/1XtBcy_orLbS2Gjm4W-C7LPTmlhJoc7eZ/view?usp=drive_link

**Comment by sqs** [comment]
I can't repro this, but I can repro a similar issue: if you press Enter in the empty textarea, it types a newline and continues doing so. I believe we are not properly preventingDefault the event in this case. That would also lead to this bug, and it's possible the solution is the same.

**Comment by chillatom** [comment]
I can repro

https://www.loom.com/share/e1a0051027824d51b35cabeb977455ef?sid=d3bb489e-c1ca-4e71-8f31-44d12e0b6700
