### ISSUE TITLE
VS Code: LLM dropdown is missing for Enterprise user.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3525]
### Version

v1.10.0

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Enterprise user
3. Start a new chat and  check the LLM

### Observed behavior:
LLM dropdown is missing. 

### Expected behavior

It should be disabled but appear there so the user get aware of the LLM.

### Additional context

**<img width="539" alt="Screenshot 2024-03-22 at 11 52 56 PM" src="https://github.com/sourcegraph/cody/assets/158482423/8566b27b-28ae-4b95-a0e8-71c08a373510">**
Attaching screenshots for Free vs Enterprise accounts.

<img width="543" alt="Screenshot 2024-03-22 at 11 50 20 PM" src="https://github.com/sourcegraph/cody/assets/158482423/6ea53397-29b7-4200-b411-ebeb5126b006">

**Comment by chillatom** [comment]
CC @toolmantim thoughts? On one hand I agree.  On the other hand an enterprise user can't do anything with this information and it's on the admin to configure.

**Comment by toolmantim** [comment]
What's our Enterprise LLM upgrade process? Do we reach out to admins, or rely on them to know if they should update the model? Visibility (for both admin and non-admin Cody users) would help with the latter.

I'd suggest the UI would be a 80% opacity label (no drop down) with a tooltip.

**Comment by Robertwadelinger** [comment]
To add to this issue:
From an enterprise prospective, this would be a helpful item to have. Consider the following situations:
An Admin sets up LLM access to more than one provider, this can be done for 2 reasons, first - to allow for dev preferences, second, some LLM providers (like Azure) impose caps/rate limits on given model deployments, so with this option, devs can switch on the fly to avoid these caps.

Another example would be ollama installs, where available models can be numerous based on the ollama install.

Just some thoughts from another enterprise user.

**Comment by Robertwadelinger** [comment]
Bump
