### ISSUE TITLE
feedback: feature request - enable copying the response given by cody

### ISSUE THREAD

**Issue by dheerajbhaskar** [sourcegraph/cody#3533]
### Version

1.87.2

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

- Summary: I sometimes want to copy cody chat responses. For example to file an issue, like here.
- Here is the formatted response I see:
<img width="531" alt="image" src="https://github.com/sourcegraph/cody/assets/2944909/8e1bb821-8670-4cf6-b426-6e410d8d640d">
- When I copy paste the text shown in image, I get this:
```
General overview of options for IPC like DllCall, COM, FileMapping, Pipes, etc.

NamedPipes Example: [https://www.autohotkey.com/docs/objects/Pipe.htm#NamedPipes](command:_cody.vscode.open?%22https%3A%2F%2Fwww.autohotkey.com%2Fdocs%2Fobjects%2FPipe.htm%23NamedPipes%22)
Concrete example of creating a named pipe server/client.

Win32 API List: [https://www.autohotkey.com/docs/commands/DllCall.htm#Win32List](command:_cody.vscode.open?%22https%3A%2F%2Fwww.autohotkey.com%2Fdocs%2Fcommands%2FDllCall.htm%23Win32List%22)
List of common Win32 APIs that can be used with DllCall.

The key classes/functions are:

Pipe() - for creating pipe objects
Open() / Read() / Write() / Seek() / Close() - for working with pipe objects
DllCall() - for calling Win32 API pipe functions directly
Between Pipe() and DllCall(), you have full access to named pipes for IPC in AHKv2.
```
- There is no formatting like lists in the copied text. I'd want proper markdown

### Describe the solution you'd like to see

- markdown or worse case rich text I can copy to an email

### Describe any alternatives that could be considered

- screenshots
- manual recreation of formatting while filing an issue

**Comment by scho-to** [comment]
This would be a great improvement. Right now, in my custom commit Message Generation command, i added an instruction for Cody to use raw markdown Output.

This way, I can simply Copy the generated Text with correctly styled lists at least.
