### ISSUE TITLE
bug: The chat gets truncated halfway through response 

### ISSUE THREAD

**Issue by brunoderosa1** [sourcegraph/cody#3536]
### Version

v1.10

### Describe the bug

when the chat responds to a prompt, if the response is too long it gets truncated, i've tried many models its the same for each one, that leads me to understand that its an issue from cody itself on how it handles the text streams, a nice solution would be implementing something like chatgpt or gemini, that let the chat finish off the response, thanks in advance, overall cody rocks, you just need to know how to command it properly, great job!

### Expected behavior

when i make a prompt to the chat i expect it to give me the full answer or at least prompt me with a button or other mechanism to finish off the response that was being generated, it had happened to me that if the follow up prompt is not accurate, the follow up has nothing to do with what was previously being answered.

**Comment by umpox** [comment]
Thanks for reporting! We have increased Cody's output limit, it should now be much rarer to see Cody truncating the response like this. Let us know if you encounter any more issues!

This change will be available in this weeks Cody release, which is scheduled to go out either today or tomorrow.

**Comment by brunoderosa1** [comment]
thanks for addressing the issue!
