### ISSUE TITLE
bug: LLM dropdown has wrong Claude 3 titles

### ISSUE THREAD

**Issue by chris-sev** [sourcegraph/cody#3541]
### Version

1.10.0

### Describe the bug

The LLM dropdown has the wrong title when you hover over Claude 3 Haiku and Claude 3 Sonnet. They both say `This chat is using Claude 3 Opus...`

![cleanshot_2024-03-25_at_12 36 52_2x](https://github.com/sourcegraph/cody/assets/1857851/41a3920f-9493-4ea2-a887-d291360c95f9)

### Expected behavior

Both should say Claude 3 Haiku and Claude 3 Sonnet respectively

**Comment by keegancsmith** [comment]
This is working as expected. The hover text is telling you what you current chat is using not about the selection item. Maybe the copy could be improved to make it clearer? cc @abeatrix just to confirm if I am correct :)
