### ISSUE TITLE
Cody keeps suggesting attributes that don't exist in CDK API v2

### ISSUE THREAD

**Issue by bettlebrox** [sourcegraph/cody#3578]
### Version

v1.10.0

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [X] Context
- [X] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

![Screenshot 2024-03-27 at 13 27 19](https://github.com/sourcegraph/cody/assets/474346/e724443c-2122-417d-9745-88ec73bd7115)
the cluster attribute in the screenshot does not exist. Often the suggestions are from the v1 of the cdk api other times, like this, they are made up.

### Describe the solution you'd like to see

I'd like to see cody actually validate the code against the version of the api I'm using when making code suggestions

### Describe any alternatives that could be considered

Include a reference link so I can understand where the code suggested it coming from

**Comment by ggoonnzzaallo** [comment]
What was your initial prompt / input?
