### ISSUE TITLE
Support range for large @-mention files

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#3589]
Large files are disabled in @-mentions but that also removes the ability to choose range for the large files. 

We should update to support that.

Also noticed a regression (compared to the old @-mention) where the range doesn't show up until you have completed typing:

![image](https://github.com/sourcegraph/cody/assets/68532117/fd7d217e-a249-45bd-ab5d-7fb93d98066c)

![image](https://github.com/sourcegraph/cody/assets/68532117/c087b554-5ca7-452b-b579-5c202ab5860e)

**Comment by PriNova** [comment]
Thanks @abeatrix for raising this issue here. This is the best place for tracking it. My bad to append it on a closed PR.

**Comment by abeatrix** [comment]
@PriNova no problem at all! Thanks for flagging the issue!
