### ISSUE TITLE
Chat window not loading

### ISSUE THREAD

**Issue by yerbby** [sourcegraph/cody#360]
VSC on Windows 11.

Installed extension for VSC and signed in. 

The chat window  shows the 3 colored dots flashing and it stays loading indefinitely. The extension raises the following message: 

No output return from git config user.name. Please make sure the command works in your terminal before trying again.

Thanks in advance for any hints.

**Comment by RaySinner** [comment]
Yes, I have the same problem, I tried to install it on a clean virtual machine, but it does not start.Hope this can be fixed soon

![image](https://github.com/sourcegraph/cody/assets/118297374/68ef4012-93ff-4c8d-ba6b-c8b7eb5e1963)


![image](https://github.com/sourcegraph/cody/assets/118297374/8f3a9e92-01f6-4343-9f92-a865e5196e68)

**Comment by jdorfman** [comment]
Thanks @yerbby for the report and screenshots. I will let the team know!

**Comment by abeatrix** [comment]
@yerbby @RaySinner this issue should be fixed in latest stable release. Can you please try that and let us know if this is still an issue for you?

**Comment by TheWhiteWords** [comment]
I have the same problem. Tried to uninstall and reinstall the extension but now it does not even log in. 

Activating extension 'sourcegraph.cody-ai' failed: Cannot read properties of undefined (reading 'uri').

This error indicates that there was an issue activating the 'sourcegraph.cody-ai' extension in VS Code.

The specific error Cannot read properties of undefined (reading 'uri') suggests that some object is coming back as undefined when the extension activation code tries to read its 'uri' property.

**Comment by sqs** [comment]
@john3825  @ghost @RaySinner Can you please try the latest insiders build of the Cody VS Code extension (`v0.7.1690496766` or later)? See https://github.com/sourcegraph/cody/blob/main/vscode/doc/releases.md#insiders-releases for instructions on how to get it (it's the pre-release version on the VS Code Marketplace).

**Comment by RaySinner** [comment]
I tried the new version and it really solves the problem. I closed my ticket, I guess you can close this one too.

**Comment by sqs** [comment]
Thank you! @john3825 @ghost please let me know if this is NOT solved for you, and we will reopen it.

**Comment by john3825** [comment]
the @sqs It worked with **pre-release** version. It is a bug with the login function which pass **null**.

**Comment by deadcoder0904** [comment]
i'm wondering if this got to stable release?

bcz i'm having the same issue. been trying cody for 2 days now & it keeps on loading. the other day, i had to disable & enable the extension again to get working.

today, it gives this again:

![image](https://github.com/sourcegraph/cody/assets/16436270/ec431991-6bf4-44bd-9497-2623c0c30205)

it just keeps on loading.

im using cody on a secondary-sidebar to the right in vscode.
