### ISSUE TITLE
VS Code: User is not able to create custom command on VSC.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3602]
### Version

v1.10.1

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Free/Pro/Enterprise user
3. Click on "Custom Commands" and select "New Custom Command..."
4. Give any name and hit enter
5. Enter instructions for Cody to follow and answer and hit enter
6. Choose "Selected Code" and click on "OK" button
7. Choose where to save the command and select "User Settings"
8. Check the Custom Commands availability

### Observed behavior:
Custom command is not saved

### Expected behavior

Custom command should be saved successfully.

### Additional context

**Video link:**

https://drive.google.com/file/d/1CS4udrAHiyNCkZHeYny4mrzZQzk9JScl/view?usp=drive_link

**Comment by SphaeroX** [comment]
Same here...

I entered it manually into the json. What would be even better is if the entry also appeared when right-clicking on code.
