### ISSUE TITLE
Retention Experiment: Hover Commands

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#3605]
PR to implement the Hover Command feature: https://github.com/sourcegraph/cody/pull/3585
Retention Experiment Doc: https://docs.google.com/document/d/1G5koKO6MoZflObkkcsjcYfexfSY8fWC50BoT4k-BmZU/edit?usp=sharing

**Comment by abeatrix** [comment]
Feature implementation completed in https://github.com/sourcegraph/cody/pull/3585

## Status: Experiment in Progress

Feature is included in v1.12.0

The feature flag has been enabled for n% of dotCom users.

**Comment by abeatrix** [comment]
## Status: Test Ended

Context: https://sourcegraph.slack.com/archives/C05AGQYD528/p1713973441091799
