### ISSUE TITLE
feedback: feature request: Right click to mention line range in chat

### ISSUE THREAD

**Issue by hlhdaiaaii** [sourcegraph/cody#3612]
### Version

v1.10

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

I find mentioning with line range in chat very useful and I use it a lot to manually gather best context to feed to the model. However, imo it is not quite smooth due to having to type manually which lines and which files, which sometimes are many in my case.

### Describe the solution you'd like to see

I think I would be more productive if I could select pieces of code and then right click to select action like "Mention in chat" under Cody action menu. Doing this way would be fast in selecting many pieces of code from different files. Is something like this possible? Hope there will be similar feature like this soon.

**Comment by abeatrix** [comment]
Closed by https://github.com/sourcegraph/cody/pull/3619
