### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by GeekSheikh** [sourcegraph/cody#3618]
### Version

1.10.1

### Describe the bug

I followed the docs [here](https://sourcegraph.com/blog/power-users-guide-to-cody-ai-for-visual-studio-code) on the website and cannot figure out how to make the inline chat feature work. Are the docs wrong? Am I doing something wrong? Is it a bug?

Sidebar chat is working fine.

I also asked codyai to help me and followed its recommendations to no avail

```
Make sure you are using the latest version of the CodyAI extension. Inline chat is a relatively new feature so you may need to update.

Check if you have enabled the "CodyAI: Enable Inline Chat" setting. You can access extension settings by going to File > Preferences > Settings and searching for "CodyAI".

Try restarting VS Code after enabling the inline chat setting. The setting may not take effect immediately.

If you still don't see the inline chat option, there might be another extension conflicting with CodyAI. Try disabling other AI assistant extensions temporarily.

Ensure your VS Code workspace trust is set to "Trusted" for CodyAI to work properly. You can change this in the extensions panel.

Inline chat requires a valid CodyAI API key configured in settings. Make sure you have added the key and it is correct.

As a last resort, try uninstalling and reinstalling the CodyAI extension to see if that fixes any issues.
```

### Expected behavior

Either a setting to enable inline chat and/or the hotkey described in the docs to work

**Comment by abeatrix** [comment]
The inline chat feature has been deprecated and removed for quite some time now, but you can create a new chat from right click and then use @-mentions to specify the section of cody you want to add before entering your question. I hope this helps!

**Comment by varungandhi-src** [comment]
Closing this as it isn't a bug.
