### ISSUE TITLE
bug: incorrect large file warning when context window has reached

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#3620]
### Version

v1.10.2

### Describe the bug

CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1711660531417539

We are currently displaying "File Too Large" on @-mentions when Cody has run out of context window:

![image](https://github.com/sourcegraph/cody/assets/68532117/5c58f42b-2cfd-478b-9bbb-a198b77be186)
the 

### Expected behavior

The warning should be something about the context windows limit instead of File Too Large, which causes confusion for users on file with small number of text.a

**Comment by kalanchan** [comment]
fixed in v1.12
