### ISSUE TITLE
bug: Embedding will not update since 7 days

### ISSUE THREAD

**Issue by PriNova** [sourcegraph/cody#3636]
### Version

1.10.1 & latest pre-release

### Describe the bug

When entering chat mode with the 'enhanced context' feature enabled, the embeddings failed to update after 24 hours, despite the code being current with the upstream repository on the 'main' branch.

### Expected behavior

I anticipate receiving an update at least every 24 hours.

### Additional context

The screenshot provided includes the commit history on the right side, the log of the 'Cody' output, and hints related to the commit hash.

![Screenshot 2024-03-30 110826](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/9dea2fd3-4a42-4118-9fc5-385a65d7115d/3249c9d9-b489-4777-940c-f76fbea7e3de?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy85ZGVhMmZkMy00YTQyLTQxMTgtOWZjNS0zODVhNjVkNzExNWQvMzI0OWM5ZDktYjQ4OS00Nzc3LTk0MGMtZjc2ZmJlYTdlM2RlIiwiaWF0IjoxNzEyMDY4MDI5LCJleHAiOjMzMjgyNjI4MDI5fQ.Y40bLR8xIpJWSTbIrz6oDYe-jrCKTXYPlc6LPCVYNk8)

**Comment by PriNova** [comment]
The only workout which helps, was to delete the embedding file. Then it starts re-index new.

**Comment by FelipeMorandini** [comment]
> The only workaround which helped was to delete the embedding file. Then it starts indexing new.

Where do I find this file? I'm having the same issue.

**Comment by PriNova** [comment]
bump

**Comment by kurutah** [comment]
what's the point of embedding even a few days from now...

**Comment by PriNova** [comment]
> what's the point of embedding even a few days from now...

For the context fetching in Cody exists two mechanism. one is the keyword search based on the prompt input and the other are with embeddings. [1]

The keyword search is practical if you know the terms of the codebase.
The embeddings are more like a fuzzy search, but understands code structure, code semantics and so on.
Combined in Cody are a very high reliable fetching mechanism for context in my experience.

If code is changing, for example data structure, refactoring of functions etc, and the embeddings are outdated, then Cody will provide out-dated code.

I made experiments with keyword search only and blended (keyword + embeddings) and the latter brings much more reliable context to the point.

[1]: https://www.ibm.com/think/topics/vector-embedding

**Comment by PriNova** [comment]
Closed because of changing embedding strategy

**Comment by PriNova** [comment]
> Can I read somewhere what was changed? For now, in my project, it's all the same...

Hello @kurutah 
The changes are an iterative process and are not yet available as a stable version. As soon as the process is complete, this will certainly be announced in the blog at https://sourcegraph.com/blog
