### ISSUE TITLE
升级插件版本不会自动删除旧文件/文件夹

### ISSUE THREAD

**Issue by alminchen** [sourcegraph/cody#3643]
Type: **Bug**

升级插件版本不会自动删除旧文件/文件夹

Extension version: 1.11.1711946148
VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin x64 23.4.0
Modes:

System Info

| Item | Value |
| -- | -- |
| CPUs | Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000) |
| GPU Status | 2d_canvas: enabled |

canvas_oop_rasterization: disabled_off
direct_rendering_display_compositor: disabled_off_ok
gpu_compositing: enabled
multiple_raster_threads: enabled_on
opengl: enabled_on
rasterization: enabled
raw_draw: disabled_off_ok
skia_graphite: disabled_off
video_decode: enabled
video_encode: enabled
webgl: enabled
webgl2: enabled
webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.15GB free)|
|Process Argv|--crash-reporter-id 022407fe-3d30-42ee-89ad-9b9d1d230057|
|Screen Reader|no|
|VM|0%|

A/B Experiments

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
cppperfnew:31000557
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
7ghi1836:30988842
dsvsc021:30996838
gd77d436:30999572
```

**Comment by kalanchan** [comment]
hello! sorry, we're not able to understand the ticket here - please resubmit with more description.
