### ISSUE TITLE
Expand the output token limits

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3648]
Currently we limit the output tokens to 1,000.  In practice this isn't enough to accomplish much in the way of long form code generation.  1,000 tokens roughly equates to 133 LOC in typescript and functionally we get less than that due to token estimation, response pre-amble from the LLM that eats some tokens.  So if I am trying to translate a 200-400 LOC file, I hit the output limit.  

Most provider APIs cap the output at 4,096 tokens.  I'd like us to do two things

1. Explore increasing our output token limit to be much closer to the 4,096 token max, say 4,000 tokens.  We should validate that this won't have unintended consequences.  @philipp-spiess 
2. Create a button (or other UI element) that allows users to easily continue generation if we detect that we hit the token limit.  The button should show up if we hit the limit and stop streaming.  It should use a limited prompt structure that tells the LLM to continue where it left off and only uses the prior chat history and previously fetched context.  No additional context should be fetched. @toolmantim for designs.

**Comment by chillatom** [comment]
Tagging @chwarwick for enterprise considerations

**Comment by aramaraju** [comment]
> Previously this was done using the MaxChatTokens however that appears to have been repurposed by clients as a upper limit on included context.

@chwarwick Do we need to make a change to add another way to do token limits with these client changes?

**Comment by chillatom** [comment]
> Create a button (or other UI element) that allows users to easily continue generation if we detect that we hit the token limit

There was a comment on another ticket that had a nice suggestion.  If we can detect that we hit the output token limit, and I believe we may get that signal from the provider completion API, we could just automatically ask to continue.

**Comment by chillatom** [comment]
https://github.com/sourcegraph/cody/issues/3786 related

**Comment by umpox** [comment]
Closed through https://github.com/sourcegraph/cody/pull/3797

@chillatom Let's use https://github.com/sourcegraph/cody/issues/3583 to track the addition of the "Continue" button. I have a feeling that the need for this will be much less now we have a higher output limit. We can still add it if we feel a need, but let's reassess once this change it out to users.
