### ISSUE TITLE
@-mention menu requires tab or click 2x to select item

### ISSUE THREAD

**Issue by sqs** [sourcegraph/cody#3649]
On `main`, I am seeing that you need to type <kbd>Tab</kbd> twice or click in the menu twice to at-mention a file.

https://github.com/sourcegraph/cody/assets/1976/ecb0862b-c865-4ad1-acfe-643688060c0e

**Comment by elemental-mind** [comment]
It would actually be nice to have all @-mentions be interpreted as files.

I currently generate file lists for myself and paste them and it's a pain to tab every item to be recognized as a file input.
Alternatively, please allow including folders as context.
