### ISSUE TITLE
bug: Typing a lower case "i" in the chatbox renders the uppercase suggestion in the open text editor file

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3657]
### Version

v1.11.1712070706

### Describe the bug

Typing a lower case "i" in the chatbox renders the uppercase suggestion in the open text editor file

![image](https://github.com/sourcegraph/cody/assets/8737510/af18a1ad-024d-4a46-8e71-819657773f7c)

https://www.loom.com/share/d5efd47d936c43238860153c047f3c19

### Expected behavior

The upper case suggestion should render above the character I am typing

<img width="293" alt="image" src="https://github.com/sourcegraph/cody/assets/8737510/5f8d3f94-fcb8-463f-bfe5-29d349637d5d">

**Comment by chillatom** [comment]
I'm not entirely sure that this is a Sourcegraph Cody issue, a VS Code issue or a MacOS issue.

**Comment by abeatrix** [comment]
Is it still an issue for you @chillatom ? 

I can't reproduce it on the latest stable or insider build:
![image](https://github.com/sourcegraph/cody/assets/68532117/7ca05065-5486-40cd-b5fc-864ee1df6ec4)
