### ISSUE TITLE
bug: The 'Edit Code' feature triggers an error

### ISSUE THREAD

**Issue by PriNova** [sourcegraph/cody#3663]
### Version

Pre-release commit 518b74a

### Describe the bug

This issue happens with Cody build at commit 518b74a
Triggering the Code Edit action via ALT + K shortcut, nor via side panel or via action Cody icon fail. An error dialog notification appears "No chat model found in server-provided config".

![Screenshot 2024-04-02 233628](https://github.com/sourcegraph/cody/assets/31413214/f16a9b00-2a63-4c9f-bffa-92c1e2eb3735)

### Expected behavior

The context menu should pop up, where the Edit Code action will be triggered with a user prompt, the range selection and the model used when submitted.

**Comment by PriNova** [comment]
With the newest pre-release it works again. Will observe further if this was a server-side communication error.

**Comment by abeatrix** [comment]
it's fixed and will be included in today's release!
This should also be fixed on the latest pre-release version as well :D

**Comment by PriNova** [comment]
Thank you bea for the fix.

**Comment by sqs** [comment]
I also just experienced this on the nightly. Thanks for the fix!

**Comment by abeatrix** [comment]
Confirmed this is fixed by https://github.com/sourcegraph/cody/pull/3650 and included in the v1.12.0 release.

Thanks @PriNova @sqs for taking the time to file and report the issue 😄
