### ISSUE TITLE
Telemetry: Create a session ID for all chat messages within the same tab

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3688]
Currently our chat message telemetry lacks any notion of a "session" that groups user query + LLM response together into occurrences that happened within a tab.  

Proposal. 

- [ ] When a new chat window is opened, generate a unique chat session ID
- [ ] All chat telemetry metadata, including for message logging, contain the session ID.  Both for user query and LLM response. 
- [ ] Persist the chat session ID in the same way that we persist chat history, so that if a chat is brought back up in the future, any new message is tied to the previous session ID

The intended outcome is that we can query all events associated with a single chat window/tab and group them together.  This will disambiguate log data that is from a user with multiple chat tabs open at the same time for different intents/queries. 

CC @akalia25 @chenkc805

**Comment by abeatrix** [comment]
Each chat session has a unique ID so no additional work is needed for item 1&3 I believe.
