### ISSUE TITLE
bug: context references non-local files (opens browser instead)

### ISSUE THREAD

**Issue by kilyinov** [sourcegraph/cody#3696]
### Version

v1.12.0

### Describe the bug

When cody replies my question, the context links refer to the online version of the file, not within IDE. 
![Screenshot 2024-04-05 at 10 50 03 am](https://github.com/sourcegraph/cody/assets/866682/bccae501-3b93-4f7e-b22e-ff86064dc402)
![Screenshot 2024-04-05 at 10 49 32 am](https://github.com/sourcegraph/cody/assets/866682/a760f164-2300-45cc-98c9-9559daee9725)
![Screenshot 2024-04-05 at 10 48 02 am](https://github.com/sourcegraph/cody/assets/866682/185549b2-e002-44d1-82f6-3bd5c6011450)

### Expected behavior

I expect clicking a link in Context list would open file in IDE

**Comment by dominiccooney** [comment]
This is working as intended &rArr; assigning @chillatom and @toolmantim for the product/UX feedback.

**Comment by kilyinov** [comment]
@dominiccooney I might be missing something - local version of file is same as remote, as demonstrated by git log output
