### ISSUE TITLE
PRD: Update Settings and Support links

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/cody#3709]
### Description:

As a user, I want to access the VS Code for Cody "Support forum": https://community.sourcegraph.com/c/cody/vs-code/6
I also want the Discord link to have the Discord logo.

<img width="307" alt="Zight 2024-04-05 at 8 12 49 AM png" src="https://github.com/sourcegraph/cody/assets/398230/598c9a74-cf0f-4465-a0c1-5a8f68336ba7">
 

### Objectives:

* Promote the new community support forum since we shut down our Discord support forum
* Have users easily recognize that we have a Discord

### Acceptance Criteria:

- "Support" is renamed to "Support forum" and links to `https://community.sourcegraph.com/c/cody/vs-code/6` **not** `https://help.sourcegraph.com/hc/en-us/requests/new`
- The Discord icon should be replaced with the [Discord logomark](https://fontawesome.com/icons/discord?s=solid)

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### Related Docs:

- [PRD: Your-Title]()

**Comment by kalanchan** [comment]
@jdorfman is support forum going to replace the Cody Pro support form? Currently if a cody pro needs help, they submit a form to the TS team

**Comment by jdorfman** [comment]
Oh my bad. Didn’t realize that. Can we just add support forum to Cody free users?

**Comment by kalanchan** [comment]
I think Cody Pro users will benefit from the community support forum was well. 

how about we just add Community Forum as another row item?

**Comment by jdorfman** [comment]
I think that’s an excellent idea
