### ISSUE TITLE
Telemetry: Log model with LLM message response

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3712]
Currently the telemetry that logs the LLM response message does not associate a model name with the response.  This makes it hard to do downstream analysis on model specific qualities.  

Request - Log the chatModel with the `cody.chatResponse.new` event. 

[Logging for the chat response 
](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@f8c06e88a88303b51fd5ae610bf5d7dabb13c761/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts?L965-977)

```
telemetryRecorder.recordEvent('cody.chatResponse.new', 'hasCode', {
                metadata: {
                    ...codeCount,
                    recordsPrivateMetadataTranscript: authStatus.isDotCom ? 1 : 0,
                },
                privateMetadata: {
                    requestID,
                    responseText: authStatus.isDotCom && messageText.substring(0, MAX_BYTES_PER_FILE),
```

Only includes the requestID and the message string

Whereas the user s[ubmitted query logs more ](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@f8c06e88a88303b51fd5ae610bf5d7dabb13c761/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts?L410-424) via the `sharedProperties`

```
         telemetryService.log('CodyVSCodeExtension:chat-question:submitted', sharedProperties)
            telemetryRecorder.recordEvent('cody.chat-question', 'submitted', {
                metadata: {
                    recordsPrivateMetadataTranscript: authStatus.endpoint && authStatus.isDotCom ? 1 : 0,
                },
                privateMetadata: {
                    ...sharedProperties,
                    promptText: authStatus.isDotCom && inputText.substring(0, MAX_BYTES_PER_FILE),
                },
            })
```

[SharedProperties](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@f8c06e88a88303b51fd5ae610bf5d7dabb13c761/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts?L404-408)
```
  const sharedProperties = {
                requestID,
                chatModel: this.chatModel.modelID,
                source,
                traceId: span.spanContext().traceId,
            }
```

CC @akalia25 @chenkc805

**Comment by philipp-spiess** [comment]
@chillatom I see `chatModel` is already in the shared properties. Is this not what you want? :)
