### ISSUE TITLE
Make it clear what context was used, not just fetched

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3718]
Loose idea right now, but the current status is that on each follow up message we fetch new context and/or include specifically mentioned files.  Example below.  

However, we know that for the follow up message we used a mix of both prior fetched context and newly fetched or mentioned context.  We also know that not necessarily all of the prior or current files make it into the actual message to the LLM. 

**Question:** Should we make the context rendering not what we fetched, but what was actually included in the message to the LLM?  

So in the example below we would re-render any prior files that made it into the message? 

<img width="972" alt="image" src="https://github.com/sourcegraph/cody/assets/8737510/6a19dce9-2d3c-4c15-ae09-e4dc0c6b57ed">

**Comment by chillatom** [comment]
@toolmantim tagging you b/c this is a bit looser of an idea that I'd love to brainstorm with you

**Comment by toolmantim** [comment]
Yes I’d love to run you and @sqs through the thoughts I had in Noodle for just this.

**Comment by kalanchan** [comment]
@chillatom to update ticket with new screenshots, and we need an eng spike

**Comment by kalanchan** [comment]
closing for now as we have the new noodle UI that covers this
