### ISSUE TITLE
feedback: support for cody and jupyter notebooks inside vscode

### ISSUE THREAD

**Issue by faysou** [sourcegraph/cody#3725]
### Version

any

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

support for command completion in jupyter notebooks inside vscode, similarly to what is possible with Github Copilot

### Describe the solution you'd like to see

same as above

**Comment by olafurpg** [comment]
@faysou I'm sorry for the delayed reply. This issue should be resolved by the PR, which will become available in the next release https://github.com/sourcegraph/cody/pull/5473
