### ISSUE TITLE
Agent - use local linux certs

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/cody#3736]
Check the following locations for linux certs: 
`/etc/ssl/certs/ca-certificates.crt`
`/etc/ssl/certs/ca-bundle.crt`

If found split the contents into individual certs and attach them to the global agent.

**Comment by kalanchan** [comment]
nice, thanks @chwarwick looks like we can copy and paste some code from here

https://github.com/microsoft/vscode-proxy-agent/blob/main/src/index.ts#L628

**Comment by chwarwick** [comment]
draft pr https://github.com/sourcegraph/cody/pull/3752
