### ISSUE TITLE
Support @ mention of remote repos for enterprise

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3737]
Currently @ mention functionality only supports search over the local repo.  For enterprise users who are connected to multiple remote repositories, we should extend the search capability to include those repos as well.  

- [ ] @ mention file, line-range and symbol all work across any repos selected via the enhanced context selector
- [ ] search UX provides easy to understand syntax for pointing to a remote vs. local repo

**Comment by toolmantim** [comment]
I can see why a user would want to @ any file in their org, and especially from any additional repos that have already been added to the chat. I wonder if they'd also want branch support, or it always being `main`.

Mixing local and remote search sources for '@' file and symbol completions is interesting from a UX POV, as they have difference performance. Or we figure out a web-hosted endpoint that's fast enough, and not use VS Code for it 🤔 Slightly trickier I guess if you want to @ something that exists locally but doesn't exist remotely (a new file on a local branch).
