### ISSUE TITLE
Make LLM generated text clickable if it references real symbols. 

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3738]
Idea - We already render symbols as markdown code.  It would be great if these were clickable elements that took you to the symbol reference.

<img width="735" alt="image" src="https://github.com/sourcegraph/cody/assets/8737510/1680334b-33aa-4b47-9a2a-913c04eefd62">

**Comment by chillatom** [comment]
@toolmantim tagging you first for any design input.  I'm also not sure the LOE associated with this.  It's low priority, but a nice paper cut we could eliminate.

**Comment by toolmantim** [comment]
Yep, I think this would be great. Design wise, even just a link to start with be good.

I'm hesitant to design it up before we know if it's feasible, but if we had information about the symbol then I think a small chip-style link (like in the context dropdown) with an icon depending on the symbol type, would be good.
