### ISSUE TITLE
feedback: 

### ISSUE THREAD

**Issue by cnagytcorp** [sourcegraph/cody#3756]
### Version

1.87.2

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [X] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

I can't justify paying $9 a month when so far not a single suggestion worked.

### Describe the solution you'd like to see

When its uploading 100's of line of code than how does reference to something not even there, suggesting multiple solution but all based on assumption. Copilot at least saying solution work if this already implemented or so.
My expectation is to inspect various section of the code what works together and find the missing link or suggest solution with the exs=isting code and not something fundamentally different.. 

### Additional context

Good luck with your trials im renewing Copilot (even if i was hopping to find something better)

**Comment by ggoonnzzaallo** [comment]
Could you provide examples?
