### ISSUE TITLE
bug: Link to enterprise context files are broken

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#3766]
### Version

1.12

### Describe the bug
It seems like the encoded URL does not render a path properly on the sourcegraph instance after retrieving context

This was tested on S2 - if you click on any of the context files received from the enterprise instance, it brings you to a page not found

![CleanShot 2024-04-10 at 11 24 08@2x](https://github.com/sourcegraph/cody/assets/51868853/d97dfd15-1df0-41f9-8963-5384f6e15cc0)
![CleanShot 2024-04-10 at 11 24 45@2x](https://github.com/sourcegraph/cody/assets/51868853/e93569c5-5faa-4911-8df3-649f68002c46)

### Expected behavior

Context files should open correctly in the sourcegraph instance

**Comment by kalanchan** [comment]
I can confirm that we are encoding the "@" sign properly from VS Code, this is the href that gets added to the dropdown links - `https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody%40c69aaf7/-/blob/README.md`. 

Will raise this with the Code Search team that they are not decoding the URLs properly

**Comment by keegancsmith** [comment]
Reading the code here it hasn't changed in a long time and we explicitly do not decode when looking for the @ sign. I imagine we do this on purpose so we support repo names with @ in them (for example this happens with package repos).

I think cody needs to be updated so it doesn't encode the @ sign.

https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@d2a36127f9414f26b0ee1f4f44d37f92891e95d1/-/blob/client/shared/src/util/url.ts?L419-432
