### ISSUE TITLE
bug: code output is often truncated

### ISSUE THREAD

**Issue by hangrymuppet** [sourcegraph/cody#3779]
### Version

v1.12.0

### Describe the bug

Code is shown in a code box that is often truncated before it is done. This does not happen with text generated outside of code blocks.

Say I have a coversation like this,

Q) Explain concept and write code that does something

A) Concept explained

code block with truncated lines

Q) Document the above code and write comments

same code block with comments again truncated

The first code block can be truncated mid-line or mid-file.

Examples (last line of code block shown below)

mid-line example

```if (dog !=```

mid-file

```while (b < a) {```

### Expected behavior

no truncation or an option to regenerate the answer / continue

### Additional context

<img width="780" alt="Screenshot 2024-04-11 at 13 06 39" src="https://github.com/sourcegraph/cody/assets/7991855/a45ac125-b2d4-42ab-a8a3-9303202644da">
<img width="686" alt="Screenshot 2024-04-11 at 13 06 53" src="https://github.com/sourcegraph/cody/assets/7991855/0ead2085-267d-4b26-bf3c-d1970c3c3968">

**Comment by kalanchan** [comment]
related #3648

**Comment by umpox** [comment]
Thanks for reporting! We have increased Cody's output limit, it should now be much rarer to see Cody truncating the response like this. Let us know if you encounter any more issues!

This change will be available in this weeks Cody release, which is scheduled to go out either today or tomorrow.

**Comment by kalanchan** [comment]
> @umpox Thanks a ton!
> 
> Will this require an extension update (i use vscode) or is this a backend update?

it's available in v1.14! upgrade away :)
