### ISSUE TITLE
feedback: Make it easier to add a section of the code to the open chat

### ISSUE THREAD

**Issue by mcheviron** [sourcegraph/cody#3785]
### Version

Version: 1.88.1 

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

It would be nice to have a straightforward way to add current selected code to the chat without needing to do @fileName:5-10. For people that use relative line numbers for example, it's a chore

### Describe the solution you'd like to see

It'd be nice if the current selection can be automatically referenced in the open chat instead of needing a new chat on its own

**Comment by umpox** [comment]
@abeatrix Can we close this now? With your work to include the selection by default

**Comment by mcheviron** [comment]
pardon, does this mean that now, in an already opened chat, the current selection is automatically added as context? I didn't try this again so if you addressed it then yes of course we can close it

**Comment by abeatrix** [comment]
@mcheviron Thank you so much for the feedback! 
1. In today's Cody for VS Code release, there is a new feature that allows you to add code from your editor to open chat with the right-click menu: https://github.com/sourcegraph/cody/pull/3713
![image](https://github.com/sourcegraph/cody/assets/68532117/0e3be988-1064-4cc0-beaa-b9c3a91bbdcb)
2. We also have an existing feature where your current selection will be included automatically when you submit the question when enhanced context is enabled (the button next to your chat input box).
3. There is also an experimental feature that allows you to start a new chat or add current selection to chat on hover!
![image](https://github.com/sourcegraph/cody/assets/68532117/4d6309b0-b085-4106-b32c-3da761ef2289)

I hope this helps! 

(@umpox thanks for the ping!)
