### ISSUE TITLE
feedback: Claude3 Opus responses are often truncated...

### ISSUE THREAD

**Issue by tumma72** [sourcegraph/cody#3786]
### Version

v1.12.0

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

Often when the answer requires more than a couple of paragraphs of text, the Cody chat is truncated. I have experienced this primarily with the Claude 3 Opus model which tends to deliver longer and more articulated answers. Sometimes even after 2 or 3 repetitions it doesn't come to an end, so I have to ask to reply in smaller chunks.

### Describe the solution you'd like to see

I would like the window size for the reply to be longer so I won't have to ask to deliver in smaller chunks, with code snippets can be a bit of a puzzle work sometimes.

**Comment by umpox** [comment]
Thanks for reporting! We have increased Cody's output limit, it should now be much rarer to see Cody truncating the response like this. Let us know if you encounter any more issues!

This change will be available in this weeks Cody release, which is scheduled to go out either today or tomorrow.

**Comment by tumma72** [comment]
Thanks for fixing this, I am experiencing a lot less issues since the last few updates. For me we can consider this a closed issue.
