### ISSUE TITLE
Nudge Pro users on legacy models to Claude 3

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3793]
Pro users who use a legacy model (e.g. Claude 2.0, 2.1, Instant) should be nudged to select one of the Claude 3 models.  We should note that we will eventually deprecate the 2.0, 2.1, Instant models. 

Ideas
- In conjunction with #3792, use UX within dropdown to nudge users
- Banner within chat pre/post submission suggesting to try newer models

Goal 
- Move most users off of legacy models ahead of a deprecation

**Comment by toolmantim** [comment]
We've a design for this ready here @chillatom: https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=2144-46229&mode=design&t=o1hirLGSxXpKVGDI-4

**Comment by sqs** [comment]
Devil's advocate: can we just auto-switch self-serve users from Claude 2 to Claude 3 models, mark Claude 2 as deprecated, and then remove it in a couple weeks (with a mention in the blog post)? What would be the downside?

**Comment by toolmantim** [comment]
The notice made sense a long while back, but the quicker we can get people off the legacy models the better

**Comment by abeatrix** [comment]
reassigning to @philipp-spiess since he has a PR ready.
