### ISSUE TITLE
feedback: Context files with ollama

### ISSUE THREAD

**Issue by FlueschPluesch** [sourcegraph/cody#3796]
### Version

Cody 1.12.0

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

If I try to add @files in the chat it does not work with Ollama. Apparently the files are not send to the LLM as it does not know about the files.

### Describe the solution you'd like to see

The @files should be send to the LLM.

**Comment by dominiccooney** [comment]
#3881 may help with this.
