### ISSUE TITLE
VS Code: tree-sitter wasm bindings memory issue

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/cody#3799]
- Tree-sitter WASM bindings usage causes V8 external memory to grow linearly with the number of documents parsed with no clear way to free it.
- Unit test for reproduction https://github.com/sourcegraph/cody/pull/3788
- Related GitHub threads: [#1](https://github.com/WebAssembly/design/issues/1396), [#2](https://github.com/WebAssembly/design/issues/1397), [#3](https://github.com/emscripten-core/emscripten/issues/15591)
- I'm able to clean up the V8 external memory that grows in tests, but for that, I hacked a couple of changes into the pre-build tree-sitter WASM bindings. With them, I re-create a new parser instance after parsing 10k documents which allows GC to clean up the previously created WebAssembly.Memory instance
- [Slack thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1713163524283919?thread_ts=1712644535.812079&cid=C05AGQYD528).

**Comment by saoudrizwan** [comment]
@valerybugakov I've run into a similar issue with web-tree-sitter, is there something you recommend for freeing the memory from a vscode extension using the wasm vs altering the wasm itself?

**Comment by valerybugakov** [comment]
Hey @saoudrizwan! Check out this PR for the solution we came up with: https://github.com/sourcegraph/cody/issues/5460
