### ISSUE TITLE
VS Code: "Mixtral by 8x7B" LLM is missing for Edit Code

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3839]
### Version

v1.12.0

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Pro user
3. Open a source code file and click on "Edit Code"
4. Check the available LLMs

### Observed behavior:

"Mixtral by 8x7B" LLM is missing from the list.

### Expected behavior

"Mixtral by 8x7B" LLM should be available for Edit Code as it is available for Chat.

### Additional context

**Screenshot:**

![Screenshot 2024-04-17 at 8 38 36 PM](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/3c3b06f0-b8ca-4b74-a3de-cba2ff2a913e/e425339d-5880-4fd6-b8d6-2a98fe1f6774?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy8zYzNiMDZmMC1iOGNhLTRiNzQtYTNkZS1jYmEyZmYyYTkxM2UvZTQyNTMzOWQtNTg4MC00ZmQ2LWI4ZDYtMmE5OGZlMWY2Nzc0IiwiaWF0IjoxNzE1MTc0Mzc4LCJleHAiOjMzMjg1NzM0Mzc4fQ.j4QyLk_Jg9wbzoGjpYA1BJQC7StPSzIS3P0d5sJW-UU "=662x")

**Comment by abeatrix** [comment]
This is as intended as those models are currently not supported in Edits.
Should we include them but mark them as unavailable @umpox @toolmantim ?
