### ISSUE TITLE
VS Code: "Generate Unit Tests" is broken on MacOS but working fine for Windows.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3840]
### Version

v1.12.0

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Pro user
3. Open a source code file and open context menu
4. Select "Cody > Generate Unit Tests"

### Observed behavior:
Nothing is generated when user selects "Generate Unit Tests". It is working fine on Windows.

### Expected behavior

"Generate Unit Tests" should work and generate tests according to code snippet.

### Additional context

**Video link:**

https://drive.google.com/file/d/1az5tyXskEA5nAdSD4_fA7ey4hXpktUJs/view?usp=drive_link

**Comment by abeatrix** [comment]
@chillatom @umpox I think this is an issue with GPT-3.5 as I can reproduce it consistently: 
![image](https://github.com/sourcegraph/cody/assets/68532117/fbd90a02-58a9-4f03-8deb-d1dc761f55db)

We will need to update the prompt to get the Test command to work with all models, and run all Test commands with Claude 3 Sonnet by default in the meanwhile, wdyt?

**Comment by aramaraju** [comment]
Going to take a closer look here : a note for myself @aramaraju
