### ISSUE TITLE
bug: Blank parts of Cody Response in Chat

### ISSUE THREAD

**Issue by raznar** [sourcegraph/cody#3844]
### Version

1.12.0

### Describe the bug

[Customer 8857](https://github.com/sourcegraph/accounts/issues/8857) is reporting an issue where the response from Cody has noticeable blank portions in the response.
[Slack thread for reference](https://sourcegraph.slack.com/archives/C069NN7LTCN/p1713383241254189)
![](https://files.slack.com/files-pri/TTE6Q46VB-F06UU1T1V98/image.png)

### Expected behavior

The response from Cody should be able to render HTML elements as code blocks rather than leaving it blank.

**Comment by raznar** [comment]
![image](https://github.com/sourcegraph/cody/assets/7816316/32e64862-7c76-4a56-bd59-be2ad09d8c84)

**Comment by keegancsmith** [comment]
@abeatrix @philipp-spiess I took a quick look at this, I think this is quite tricky to implement. Do we massage the output from the LLM at all to insert `<div>` blocks into the markdown? If so it will be hard to tell the difference between the LLM output and ours. If not, what is the correct behaviour for us to do? Show `<div>` in code blocks, or to escape them? Right now `<div>` tags are explicitly allowed in our dompurify config.

In the meantime I created a test on the actual markdown renderer we use at https://github.com/sourcegraph/cody/pull/3908. The test case we could use is something like

``` typescript
it('escapes div tags', () => {
    // https://github.com/sourcegraph/cody/issues/3844
    const input = '- Browsers will interpret a self-closed <div /> the same as <div></div>.'
    expect(renderCodyMarkdown(input)).toBe('TODO')
})
```

FYI the output from the LLM I got from my chatlog looks like the following gist. Notice how the LLM is just straight up saying `<div />`. I also include it as a markdown file so you can see that github renders it in the same way we do. https://gist.github.com/keegancsmith/254d07bbde5b250ec8979b5033c9a0b5

**Comment by philipp-spiess** [comment]
@keegancsmith This is definitely a game of whack-a-mole (in the beginning we tried a lot of ways to defend against this but everything has downsides). 

I’m not sure why we would _not_ want to escape `<div />` BUT I do think we sometimes inject error messages into the chat widget using the same fields. That would require a cleanup if that's still the case so we have either a markdown (which we escape) or a message from us (which we know is safe).

The other issue we ran into previously (which might be related here?) is that if tags are _inside_ code blocks, we actually might not want to escape them (since otherwise it will render as `&gt;div&lt;`). I think [this code](https://github.com/sourcegraph/cody/blob/main/lib/shared/src/common/markdown/markdown.ts#L19-L43) is the spiritual success of trying to do this.

The other catch is that ideally all of this would work _while streaming_ which creates another layer of complexity. 

I wonder if there are open-source solutions to this whole "stream markdown from LLM" by now 🤔

**Comment by abeatrix** [comment]
@keegancsmith thanks for the gist example!

> If so it will be hard to tell the difference between the LLM output and ours. If not, what is the correct behaviour for us to do?

Not sure if this is what you're referring to but we render human messages and bot messages differently, where right now we don't render markdown for human messages.

> Show <div> in code blocks, or to escape them? Right now <div> tags are explicitly allowed in our dompurify config.

Can we disallow `<div>` or other tags inside `<code>` tags, except <span>?

**Comment by keegancsmith** [comment]
> > If so it will be hard to tell the difference between the LLM output and ours. If not, what is the correct behaviour for us to do?
> 
> Not sure if this is what you're referring to but we render human messages and bot messages differently, where right now we don't render markdown for human messages.

The ours I am refering to is if we mutate the LLM output at all. An example from the past was I remember hacking in something for guardrails attribution. Not sure if we have anything else like that.

> > Show <div> in code blocks, or to escape them? Right now <\div> tags are explicitly allowed in our dompurify config.
> 
> Is it possible to disallow `<div>` or other tags inside `<code>` tags (except `<span>`) via the config? or enclose all `<Tags>` with backticks inside codeblocks ? 🤔 (if possible)

I did explore that briefly. It didn't look like dompurify had a nice way to do that. It has some sort of custom hooks for tags, which is maybe the way we can do it?

Basically is there any good reason for us to have a `<div>` inside of markdown that needs to be preserved? If not I'm sure we can think up something which quotes it.

**Comment by abeatrix** [comment]
> Basically is there any good reason for us to have a <div> inside of markdown that needs to be preserved? 

Not that i can think of! The only thing inside the LLM response view that contains a `<div>` is the "action menu bar" we inject during stream, but through HTML and not markdown, so I don't think there are `<div>` within markdown we need to preserve.

![Screenshot 2024-04-24 at 5 26 59 AM](https://github.com/sourcegraph/cody/assets/68532117/08587a92-034e-4316-a209-7c0b4facafba)

**Comment by abeatrix** [comment]
> An example from the past was I remember hacking in something for guardrails attribution. Not sure if we have anything else like that.

Ah gotchat! I guess that's the "action menu bar" i'm referring to above then. I think that's where the guardrails attribution is now reside as well
