### ISSUE TITLE
[Cody Ignore] Process non-file URIs

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/cody#3893]
- Based on the thread here: https://github.com/sourcegraph/cody/pull/3771#discussion_r1567093677

**Comment by PriNova** [comment]
With the latest pre-release build with commit b67ea9b context fetching is totally broken.
I'm working on the Cody fork and asking questions on the chat with 'enhanced context' enabled and after fetching some files and lines I got the following error depicted in the image below.
![Screenshot 2024-04-23 131554](https://github.com/sourcegraph/cody/assets/31413214/91aaa831-9714-4ceb-bcbb-592cba2f5dea)

**Comment by PriNova** [comment]
Switching the return to 'true' in line 63 does solve it https://github.com/sourcegraph/cody/blob/1a8baaf5559f39a9c5cff090b50d4f4b6a39e178/lib/shared/src/prompt/prompt-string.ts#L57-L69

**Comment by PriNova** [comment]
> Switching the `resolve.every` to 'true' in line 63 does solve it
> 
> https://github.com/sourcegraph/cody/blob/1a8baaf5559f39a9c5cff090b50d4f4b6a39e178/lib/shared/src/prompt/prompt-string.ts#L57-L69
> 
> From the POV of logic this seems wrong, but semantically it seems right, because the functions are not following the happy path. #3092 fixes this issue

This is now obsolete for PLG users, because it works correctly without issue in the latest pre-release build since #3942 . The issue #3928 can be closed too, if PLG user.
