### ISSUE TITLE
bug: New chat window sometimes created instead of staying in current chat

### ISSUE THREAD

**Issue by ryan6416** [sourcegraph/cody#3906]
### Version

v1.15.1713625952 (pre-release)

### Describe the bug

When chatting with Cody after several back & forth messages, occasionally submitting a new message will open a brand new chat window. Submitted message & Cody's response appear in new window. It's unclear if context & chat history from previous window carry over to newly created one.

Steps to reproduce:

1. Open Cody chat
2. Send multiple messages back & forth with Cody (using Claude 3 Opus)
3. After several exchanges, submit another message
4. Observe sometimes a new chat window opens with latest message & response

### Expected behavior

Chat should remain in same window when a new message is submitted, maintaining continuity & context of conversation. A new chat window should not be created.

### Additional context

* Occurs intermittently, but has happened multiple times
* Uncertain if chat history & context from original window persist in newly created window
* Disruptive to conversational flow & productivity to manage separate chat windowss

**Comment by vijayabhaskar-ev** [comment]
@ryan6416 Is this issue reproducible only on Claude 3 Opus, or is it reproducible in other models too? I would like to work on it.
