### ISSUE TITLE
Request Failed: The prompt string contains a reference to a file that is not allowed by the context filters.

### ISSUE THREAD

**Issue by mountaindog** [sourcegraph/cody#3928]
### Version

v1.15.1713971622

### Describe the bug

Asking Cody AI, anything results in this message.
Request Failed: The prompt string contains a reference to a file that is not allowed by the context filters.

### Expected behavior

Some response other than an error.

### Additional context

![Screenshot 2024-04-24 at 11 55 43 AM](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/ffd9fc2f-a512-4971-8131-473f5a783a92/43b5106c-c1cf-4d3d-a327-334bfe03b61d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9mZmQ5ZmMyZi1hNTEyLTQ5NzEtODEzMS00NzNmNWE3ODNhOTIvNDNiNTEwNmMtYzFjZi00ZDNkLWEzMjctMzM0YmZlMDNiNjFkIiwiaWF0IjoxNzE0Nzc0NDE2LCJleHAiOjMzMjg1MzM0NDE2fQ.Lrh-vEx1Hy--RDG-AR1ljwumkV9ZabGoy11j7-Pu1K8 "=714x")

**Comment by jdorfman** [comment]
@dominiccooney another report here: https://community.sourcegraph.com/t/request-failed-the-prompt-string-contains-a-reference-to-a-file-that-is-not-allowed-by-the-context-filters/166

**Comment by sqs** [comment]
Sorry for this issue. Please use the VS Code release (not pre-release) version on the marketplace until we fix this (asap). The release version is not affected.
![image](https://github.com/sourcegraph/cody/assets/1976/c4c79bb4-2c7e-4387-b995-5c6daf4d19fd)

**Comment by sqs** [comment]
Thanks @dominiccooney. I just kicked off a new prerelease build.

**Comment by sqs** [comment]
@dominiccooney I am still seeing this with the latest prerelease build (just built from your commit at https://github.com/sourcegraph/cody/actions/runs/8826916122/job/24233359316#step:10:40):

![image](https://github.com/sourcegraph/cody/assets/1976/2efc67a7-b2df-45fa-ad10-76d866d5defc)

**Comment by Robertwadelinger** [comment]
This is fixed in release 1.16.1
