### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by chandrabuwana** [sourcegraph/cody#3955]
Type: **Bug**

## Extension Information

* Cody Version: 1.14.0
* VS Code Version: 1.88.1
* Extension Host: desktop

## Steps to Reproduce

1. 
2. 
3. 

## Logs

Extension version: 1.14.0
VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 22.6.0
Modes:

System Info

| Item | Value |
| -- | -- |
| CPUs | Apple M2 (8 x 24) |
| GPU Status | 2d_canvas: enabled |

canvas_oop_rasterization: enabled_on
direct_rendering_display_compositor: disabled_off_ok
gpu_compositing: enabled
multiple_raster_threads: enabled_on
opengl: enabled_on
rasterization: enabled
raw_draw: disabled_off_ok
skia_graphite: disabled_off
video_decode: enabled
video_encode: enabled
webgl: enabled
webgl2: enabled
webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|. --crash-reporter-id 2af6736a-e33e-4ecb-96ed-483bd52a7378|
|Screen Reader|no|
|VM|0%|

A/B Experiments

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideoc:31016891
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31022790
```

**Comment by dominiccooney** [comment]
It's unclear what the problem is here. @chandrabuwana if you can add details, please reopen this issue and I'll take a look.
