### ISSUE TITLE
bug: "Generate Tests" generates a valid test but missing `import` statement

### ISSUE THREAD

**Issue by noah-berman** [sourcegraph/cody#3963]
### Version

v1.15.1714144471 (pre-release)

### Describe the bug

Customer has reported that, for both sample TypeScript and Python files, "Generate Tests" has correctly populated valid unit tests, but instead of adding an `import` statement at the top of the file it simply lists the path of the new test file:

![image](https://github.com/sourcegraph/cody/assets/38916274/768acaf2-60b2-4d3c-84be-84443dd12d1d)
![image](https://github.com/sourcegraph/cody/assets/38916274/6e9aa849-405c-4881-977e-d5a991db246d)

### Expected behavior

Test file should have an `import` statement to correctly import the function/method in question

### Additional context

Customer is using Cody Pro with freshly spun-up TypeScript and Python repositories for testing.
Client has tried switching LLMs across Sonnet, Opus, GPT-3.5 Turbo, and GPT-4 Turbo

**Comment by sqs** [comment]
Notes:

- Should we run the VS Code "add all missing imports" action after generating a test? Might get it wrong but it's usually good.
- The inclusion of a file path at the top is a bug.

**Comment by umpox** [comment]
- Support running "add missing imports action"
- Separate file path prompt into a separate request. (Right now we try to get the LLM to provide _both_ the file name and the contents in the response, this is error prone)
- The fact it isn't adding any imports at all makes me think this is potentially a prompting issue. It could be that we're not telling the LLM that we're in a new file, so it's assuming we already have access? I think we can fix this reliably

**Comment by abeatrix** [comment]
@umpox we have a [newTestSuitePrompt](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/commands/execute/test-edit.ts?L103) that specifically asked the LLM not to include any imports if there is an existing test file, since the new test suite is appended to the file. Maybe we can remove it to support "add all missing imports"?
