### ISSUE TITLE
Clear editor tokens on sign out

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#3972]
We need to clear the editor tokens when a user signs out, to prevent them from hitting the max limit after each consecutive sign in. It should only clear the token associated to the editor they are signed in on, not all tokens. 

Users are reporting that they hit this limit and don't know what to do, see [thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1714412812153219?thread_ts=1714408058.516609&cid=C05AGQYD528)

**Comment by abeatrix** [comment]
@kalanchan this means we will need to send a request to backend to remove their access token, is that correct? What if the user is using the token somewhere else other than the editor though? 🤔
