### ISSUE TITLE
bug: Formatter hangs after generating code

### ISSUE THREAD

**Issue by kilyinov** [sourcegraph/cody#3995]
### Version

1.14.0

### Describe the bug

See the screencast below:
https://github.com/sourcegraph/cody/assets/866682/7e54e056-b3d1-4e62-bbee-77ea5612fad2

[cody.log](https://github.com/sourcegraph/cody/files/15173127/cody.log)

### Expected behavior

After generating code, Cody applies formatting as configured by VS Code and then offers to accept/redo the generated code

**Comment by umpox** [comment]
Thanks for reporting!

Will be fixed by these PRs:
https://github.com/sourcegraph/cody/pull/4113
https://github.com/sourcegraph/cody/pull/4111
