### ISSUE TITLE
feedback: Switch cody ignore directly from the explorer at folder and file level

### ISSUE THREAD

**Issue by PriNova** [sourcegraph/cody#4002]
### Version

Pre-release

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [X] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

The idea is to enable users to toggle files and/or folders on or off in the explorer as ignored context for Cody. Rather than modifying a Cody ignore file, users can directly ignore or grant context within the file and folder explorer. Items added as ignored context would be visually indicated with a Cody symbol.

### Describe the solution you'd like to see

This solution could significantly improve the user experience by eliminating the need for users to consider glob patterns and similar complexities.

**Comment by PriNova** [comment]
@jdorfman GitHub Co-Pilot, similar to other VS Code tools, utilizes the .gitignore file. However, I've noticed that no other tools offer the capability to visually toggle files or folders on and off in the file explorer.

This functionality is common in most 3D computer graphics applications, where it's used to exclude objects from rendering or to remove them from the viewport. I consider this to be a very user-friendly feature.

**Comment by jdorfman** [comment]
@PriNova got it thanks I will make sure the product team sees this
