### ISSUE TITLE
feedback: Pre-prompt

### ISSUE THREAD

**Issue by AizenvoltPrime** [sourcegraph/cody#4005]
### Version

1.14

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

I use a pre-prompt for claude 3 opus and each time I open a new chat have to manually paste it in.

### Describe the solution you'd like to see

You can select somewhere an LLM and fill in a pre-prompt so each time you select that LLM or open a new chat that the specified LLM is selected by default it automatically passes the pre-prompt as first chat.

### Describe any alternatives that could be considered

You could fix the edit functionality so that if I edit the second chat after the pre-prompt the results that I will get will be the same as if I started a new chat and pasted the pre-prompt as the first chat prompt and then in the second chat prompt wrote what I wanted to do. This way I could always use the same chat windows by editing the second prompt and it that way "refreshing" the context.

**Comment by abeatrix** [comment]
@AizenvoltPrime This sounds like the Pre Instruction setting we have in Cody for Chat and Edit command! Can you give this a try and let us know if this is different than what you have in mind?

<img width="1566" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/3b87d390-944f-4010-b8b8-af1c54f8faa3">

**Comment by AizenvoltPrime** [comment]
I want it just for the first chat. Because the preprompt is rather big in size I don't want to waste context tokens for it on every chat message.  Meaning first chat is the pre-prompt and the second is my actual task.

**Comment by abeatrix** [comment]
> I want it just for the first chat. Because the pre-prompt is rather big in size, I don't want to waste context tokens for it on every chat message.  Meaning, what I want is to write the pre-prompt as the first chat and the second chat is my actual task.

@AizenvoltPrime Gotcha! You can create a custom command so that every time you run the command it will start a new chat with the same prompt (like the explain command), would that work?

**Comment by AizenvoltPrime** [comment]
Yeah, I found out about that, I just figured it would be more convenient if when I click a new chat the command would run by itself instead of clicking the shortcut keys to open the menu and then clicking the custom command. If there is a way to use a shortcut key combination to run the command immediately then that would be good too.
