### ISSUE TITLE
bug: Cody asks for file contents despite @-mention

### ISSUE THREAD

**Issue by slaughters85j** [sourcegraph/cody#4009]
### Version

The latest?

### Describe the bug

When using the @ symbol to give the file reference, Cody routinely still asks for the code via copy and paste as if nothing was provided, and even if something is listed in the Context.  But no reply is provided.

### Expected behavior

Cody to review the file provided via @filename
![2024-05-02_00-33-25](https://github.com/sourcegraph/cody/assets/9493107/2876dd13-6b7a-49c0-855b-4832eb211160)

**Comment by sqs** [comment]
@slaughters85j Are you still experiencing this issue in the latest Cody?

**Comment by jtibshirani** [comment]
Apologies, I accidentally closed this out due to some automation we have.
