### ISSUE TITLE
feedback: Remember disabling of "enhanced context" on chat

### ISSUE THREAD

**Issue by Munawwar** [sourcegraph/cody#4020]
### Version

v1.14.0

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [x] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

I disable enhanced context until I am sure lots of files are needed for context. However chat window doesn't remember on the next time I open chat (either new chat or even the same chat re-opened from the chat list), that I disabled enhanced context the last time.

Enhanced context sometimes just send loads of files to the 3rd party services for trivial questions, and I have accidentally sent many files to OpenAI or Anthropic. This button is a "consent to read any of your source code and send it to a 3rd party" button, so it is sensitive.

### Describe the solution you'd like to see

I would like that when "enhanced context" is disabled on chat, it remains disabled on next chat or re-opening of the same chat.

### Describe any alternatives that could be considered

Alternatives? I am not sure.

Also should the option be remembered on a per session basis? I think no. It should be global, to prevent accidental file uploads.

**Comment by git-longcat** [comment]
Here's a proposed alternative.
Add an option in the settings screen that says "Display a warning when automatically sending file contents."

When this option is enabled, whenever the contents of files not specified with @ are automatically sent to the internet, display a list of which files will be sent in a popup window each time. 
The files will be sent when the user clicks a red "Send with automatically selected file contents included" button.

I believe that such a feature to prevent accidental sending of files is very important when using Cody for work. For example, there may be cases where a non-disclosure agreement has been signed.

I think this warning feature would not work well with the auto-complete feature.

**Comment by Munawwar** [comment]
I like the idea of showing a list of files which Cody will send, before the send. However for me personally, for some projects I *never* want to send any additional files, so having to disable the context button every time is annoying. The popup would prevent accidental sends, yes, but it's not the ideal experience for such projects.
