### ISSUE TITLE
feedback: Cody in tab

### ISSUE THREAD

**Issue by ShalokShalom** [sourcegraph/cody#4065]
### Version

1.90.0

### Areas for Improvement

- [X] UI/UX
- [X] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

![Screenshot_20240507_002121](https://github.com/sourcegraph/cody/assets/6344099/f2ff2c5f-7eb3-4ce8-b747-a4f4564b8e65)

### Describe the solution you'd like to see

Hi there. I hope this is not something that is already possible, and I simply missed it. 
But I would really love to have Cody in a tab, opposed to squeezing it onto my 14 inch.

Thanks a lot

**Comment by ShalokShalom** [comment]
OK, I can simply move the tab over *shame* 😄

**Comment by dominiccooney** [comment]
@olafurpg what's the thinking with reopening this... Apply the feedback to JetBrains?

**Comment by ShalokShalom** [comment]
This is VSCode

**Comment by dominiccooney** [comment]
Yes, I understand. I was just curious why my colleague reopened the issue.

**Comment by ShalokShalom** [comment]
You might add a configuration option, that it opens in a tab.
