### ISSUE TITLE
feedback: Ability to @ folders

### ISSUE THREAD

**Issue by dioro** [sourcegraph/cody#4082]
### Version

v1.17.1715094839

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [X] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

It would improve the QoL since you wouldn't have to manually @ every single file in a folder

### Describe the solution you'd like to see

Ability to @ folder from chat and inline edit.

**Comment by sqs** [comment]
Should be easy after search platform team added the new context search type filter

**Comment by elemental-mind** [comment]
I totally root for this as well! Biggest pain at the moment.

**Comment by dominiccooney** [comment]
Although the stress cases, like directories with a lot of context, or how you'd specify depth, mean it is not trivial.

**Comment by elemental-mind** [comment]
That's an afterthought. But for now even with limitations this is just a low hanging fruit. Is cody not displaying a warning already if you exceed the context with your inclusions? If that's the case you can still fall back to selectively including subfolders/files.

Also, I expect the context window to grow with every release...so it will become less of a problem over time.
