### ISSUE TITLE
Cody VSCode extension output swallows regex group labels, e.g. (<label>)

### ISSUE THREAD

**Issue by jlapier** [sourcegraph/cody#41]
- **Sourcegraph version:** v.0.4.2
- **Platform information:** OS X 11.7.7, VSCode 1.79.2 

#### Steps to reproduce:

1. open up Cody in VSCode
2. type something like:  ```hey Cody, check out this regex: /^(?<myLabel>[A-Za-z]+).(?<myOtherLabel>[A-Za-z]+)/```

#### Expected behavior:
I should see my own regex in the chat window, as I typed it. Likewise, any changes Cody offers should include labels in angle brackets, e.g. `<myLabel>`

#### Actual behavior:
The chat window hides anything in angle brackets, so what I see is more like: ```hey Cody, check out this regex: /^(?[A-Za-z]+).(?[A-Za-z]+)/```

All regex expressions should probably be marked up as code to avoid formatting issues. (Though TBH, the regex capabilities of the bot are lacking, so I won't be trusting it for a bit. 😉 )

![Screen Shot 2023-07-06 at 8 54 51 AM](https://github.com/sourcegraph/sourcegraph/assets/66530/c3f1a718-d4d8-4b8f-a2ed-707eb991b766)

**Comment by jdorfman** [comment]
Hi @jlapier, thanks for reporting this!
