### ISSUE TITLE
bug: pyright error pops due to walkthrough content

### ISSUE THREAD

**Issue by enriquegh** [sourcegraph/cody#4102]
### Version

1.17.1715181252

### Describe the bug

Since walkthroughs were added, I see a "problem" on the `Problems` tab coming from the vscode plugin.

<img width="1727" alt="Screenshot 2024-05-08 at 15 21 27" src="https://github.com/sourcegraph/cody/assets/6495540/14c5be51-af31-4e9a-9d7e-2996cbc993c5">

### Expected behavior

No errors on problems tab coming from Cody extension.

### Additional context

A workaround for this is to substitute:
```
def greet(name, surname):
    """Greets a user with a simple message"""
    p
#    ^ Autocomplete: Place cursor above
# When you see a suggestion, press Tab to accept or Opt+\ to generate another.
```
with

```
def greet(name, surname):
    """Greets a user with a simple message"""
    p # pyright: ignore[reportUndefinedVariable]
#    ^ Autocomplete: Place cursor above
# When you see a suggestion, press Tab to accept or Opt+\ to generate another.
```
(Add # pyright: ignore[reportUndefinedVariable] to the end of `p`)

**Comment by iezed** [comment]
Hi, 
This error persists in mt vscode, even after updating the plugin.

**Comment by enriquegh** [comment]
@iezed This should be included in the next release as it did not make the cut in our latest one.

In the meantime you can use the workaround mentioned here or you can switch to our pre-release version where this is included.
