### ISSUE TITLE
bug: Lagging on debian 12.5

### ISSUE THREAD

**Issue by AizenvoltPrime** [sourcegraph/cody#4119]
### Version

Any version since I started using debian 12.5 which is 2 and a half months ago

### Describe the bug

Cody on debian 12.5 in vscode is lagging a lot, from opening a new window to chat response time to everything. I watched a friend of mine use cody on ubuntu 22.04 and I didnt see the kind of lag I see on debian 12.5.

### Expected behavior

For cody not to lag.

**Comment by dominiccooney** [comment]
Is this specific to Cody, or is VSCode in general laggy? Could you share a log (Cody Sidebar, Settings & Support, …, Export logs)

**Comment by AizenvoltPrime** [comment]
It is a cody specific issue. 
[cody_1716364506318.log](https://github.com/sourcegraph/cody/files/15399898/cody_1716364506318.log)

**Comment by AizenvoltPrime** [comment]
I found the problem. Its not a debian specific issue, since it happens on windows too. I don't the cause, it could be vs code upades or Cody updates but after some time Cody begins lagging when opening new chats or responding to prompts. The only way I found that can fix this is uninstall vs code and delete all related folders of vscode on the system and then install it again. That fixes it but after some time be it weeks or a month it starts lagging again and it gets progressively worse so you need to do the uninstall again.

**Comment by PriNova** [comment]
Hey @AizenvoltPrime 

Can you confirm that this issue was solved for the newest Cody version on all OS'es?

Thank you

**Comment by AizenvoltPrime** [comment]
I have some time to notice lags so I guess it is.
