### ISSUE TITLE
VS Code: Free users can access different LLM.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#4120]
### Version

v1.16.6

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Free user
3. Open a new chat and choose any other LLM
4. Ask a question to Cody and verify that Cody will respond

### Observed behavior:
When selecting other LLM for the first time, user is not redirected to [https://sourcegraph.com/cody/subscription](https://sourcegraph.com/cody/subscription) page.

### Expected behavior

When user selects any other LLM with labeled as `Pro` then user should be redirected to [https://sourcegraph.com/cody/subscription](https://sourcegraph.com/cody/subscription) page and not allowed to use other LLM
Though, selecting different LLM second time will redirect user correctly, but this bug reproduced for a new chat session

### Additional context

**Video link:**

https://drive.google.com/file/d/11TIfxzhzFwW5rZ7_LWdn_coss1il3HwX/view?usp=drive_link

**Comment by jdorfman** [comment]
Good catch cc @chenkc805
