### ISSUE TITLE
bug: mainThreadExtensionService.ts:81 [sourcegraph.cody-ai]Unexpected token { in JSON at position 137

### ISSUE THREAD

**Issue by riccardo-unipg** [sourcegraph/cody#4135]
### Version

1.89.1

### Describe the bug

Hi, I'm using cody with Ollama with ssh on a remote computer, locally everything works and even remotely everything apparently seemed to work, in fact I can see and choose my ollama models and chat and do autocomplete with them. Sometimes the chats work while other times (without knowing the reason) the response generation is interrupted and this error is presented in the developer tools toolbox:
**mainThreadExtensionService.ts:81 [sourcegraph.cody-ai]Unexpected token { in JSON at position 137**

My remote settings are these:

{
  "cody.autocomplete.enabled": true,
  "cody.autocomplete.languages": {
   "cody.autocomplete.advanced.provider": "experimental-ollama",
   "cody.autocomplete.experimental.ollamaOptions": {
     "url": "http://xxx.xxx.xxx.xxx:11434",
     "model": "deepseek-coder"
   }
  }
}

### Expected behavior

I don't know what to do because sometimes it responds correctly, other times it doesn't, I can't understand what the problem is

**Comment by dominiccooney** [comment]
Thank you for this feedback. We need lib/shared/src/llm-providers/ollama/completions-client.ts to handle JSON output over buffer boundaries correctly.
