### ISSUE TITLE
bug: Can't generate commands on an empty cody.json file

### ISSUE THREAD

**Issue by ajaynz** [sourcegraph/cody#4144]
### Version

1.1.15

### Describe the bug

I tried creating a Cody command using the wizard in VS Code extension on a clean install with an empty json file

VS Code extension doesn't save the command in the generated file if the file is empty. However if the json file has commands stored or has an empty {} the extension does save new commands.

### Expected behavior

Cody should be able to save commands created via the wizard in the json file

**Comment by abeatrix** [comment]
> ### Version
> 
> 1.1.15
> 
> ### Describe the bug
> 
> I tried creating a Cody command using the wizard in VS Code extension on a clean install with an empty json file
> 
> 
> 
> VS Code extension doesn't save the command in the generated file if the file is empty. However if the json file has commands stored or has an empty {} the extension does save new commands.
> 
> ### Expected behavior
> 
> Cody should be able to save commands created via the wizard in the json file
> 
> ### Additional context
> 
> _No response_

Sorry for the late response, just came across this GitHub issue! 

This issue should be fixed couple patches ago. Can you tried upgrading to the latest version and let us know (or reopen this issue) if the issue persists? 

Much appreciated 🙇‍♀️
