### ISSUE TITLE
bug: All LLMs except Claude ignores the command output

### ISSUE THREAD

**Issue by mattia-consiglio** [sourcegraph/cody#4151]
### Version

1.89.1 (user setup)

### Describe the bug

When running the custom command 
```json
"commit-message": {
	"description": "Commit message for staged changes",
	"prompt": "Suggest an informative commit message by summarizing code changes from the shared command output. The commit message should follow the conventional commit format and provide meaningful context for future readers. The commit summary that includes the commit type (scope) has to be under 50 characters including spaces. Be sure to include the commit summary. Use bullet points for the description. The commit message should be presented in a code block.",
	"context": {
		"selection": false,
		"openTabs": false,
		"currentFile": false,
		"command": "git diff --staged --minimal -w"
	}
}
```
There are 3 different behavior:
1. GPT-3.5 Turbo, Mixtral (all), Ollama: The LLM recognize that has no access to the output of the terminal.
2. GPTP-4 Turbo: The LLM hallucinate the response giving a fake commit message, without saying it.
3. Claude (all): The LLM gives an appropriate answer. 

### Expected behavior

The LLM to be able to use the command output.

**Comment by jdorfman** [comment]
Thanks, @mattia-consiglio. I will get some eyes on this.
