### ISSUE TITLE
Bug: Issue with keyboard shortcut for opening chat

### ISSUE THREAD

**Issue by dicktornfeldt** [sourcegraph/cody#4194]
### Version

1.18.0

### Describe the bug

Im on a Swedish keyboard and the default character for opt+l is "ﬁ"

In version 1.16.7 I can select a codeblock and press opt+l and the Cody chat opens.

In version 1.18.0 the selected codeblock is replaced by the character "ﬁ"

### Expected behavior

The Cody chat should appear instead of the code block being replaced by the default character

**Comment by oscarmrom** [comment]
I think these are related https://github.com/sourcegraph/cody/issues/4178
