### ISSUE TITLE
bug: Cody is causing VSCode to coredump

### ISSUE THREAD

**Issue by gtirloni** [sourcegraph/cody#4196]
### Version

1.18.0

### Describe the bug

While in a chat, I ask it something and it replies. Some random short time later, VSCode crashes and coredumps.

### Expected behavior

No coredumps.

### Additional context

[vscode-cody-v1.18.0-stacktrace.txt](https://github.com/sourcegraph/cody/files/15340305/vscode-cody-v1.18.0-stacktrace.txt)

**Comment by dominiccooney** [comment]
Interesting. Do you have any more details about the cause of the coredump (which signal?)

Does your core handler have options to dump a memory map so we could see what region of memory this crash is in?

The symbolification is very light, it is hard to tell what is going on from this stacktrace alone… If you can symbolicate this, it would be a huge help.

**Comment by hariprasadiit** [comment]
cody extension is using high memory if the chat include large blocks of code causing extension host to crash with OOM
