### ISSUE TITLE
feedback: Rate-limit on pro plan is really annoying

### ISSUE THREAD

**Issue by ldubos** [sourcegraph/cody#4199]
### Version

1.18.0

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [X] Response Quality
- [X] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

The rate limiting on autocompletion in the Pro plan is so frustrating. Literally, on your pricing page, dashboard, and almost everywhere else, you say "Unlimited," but it isn't. At the same time, your autocompletions are too short and not so good at the end. Why do I pay?

### Describe the solution you'd like to see

Please provide the service that I pay for.

**Comment by 19h** [comment]
Really curious what you're doing that you hit that limit... I'm pretty much exclusively using gpt4o right now all day and haven't hit the limit (yet?). Is that a monthly or a daily limit?

**Comment by ldubos** [comment]
I only use the autocomplete feature, I never use the chat except for the "fix" feature, I program mostly in Rust and it seems like there is a daily limit, but here's the problem I pay for unlimited autocompletes, this kind of tool for me is really useful for Rust (when it works) to autocomplete where clauses and that kind of stuff that can be redundant and predictable but need an LLM to work.

**Comment by 19h** [comment]
I just realised that I configured phi3 via local ollama hence I probably don't run into the autocomplete limit .. it seems to perform way better than whatever is the default

**Comment by ldubos** [comment]
Does phi3 perform well with Rust?

**Comment by 19h** [comment]
I was actually shocked by how well it performs -- I tested it against falcon2:11b-q8_0, gemma:7b, codegemma:7b, deepseek-coder:33b, deepseek-coder:6.7b, hell even codellama:70b. It's extremely lightweight and produces by far the best results. That's for autocomplete though; for more complex tasks I still resort to GPT4.

**Comment by chenkc805** [comment]
Hey - if you're still running into rate limit issues, what's your sourcegraph username so I can look into this for you?

**Comment by ldubos** [comment]
@chenkc805 I stopped my subscription so I can't confirm if it was fixed, but the last time I tested it (~2 weeks ago) it was still an issue
