### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by eortegaz** [sourcegraph/cody#42]
- Issue Type: `Performance`
- Extension Name: `cody-ai`
- Extension Version: `0.4.2`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.79.2`

[sourcegraph.cody-ai-unresponsive.cpuprofile.txt](https://github.com/sourcegraph/sourcegraph/files/11917503/sourcegraph.cody-ai-unresponsive.cpuprofile.txt)

**Comment by jdorfman** [comment]
Thank you for reporting this @eortegaz 

Any updates since you open this issue?

**Comment by kampiamodikuesto** [comment]
i confirm the issue on macos  13.6 (22G120) with IntelliJ IDEA 2023.3.2 (Ultimate Edition) and plugin version 5.215221.

**Comment by hunterMG** [comment]
And Android Studio Hedgehog | 2023.1.1 Patch 1, plugin version 5.2.18630.
Maybe almost every JetBrains IDE.

**Comment by jdorfman** [comment]
@kampiamodikuesto @hunterMG 

Please use: https://github.com/sourcegraph/jetbrains/issues/new/choose
