### ISSUE TITLE
bug: Duplicated "Gemini model" options in new Cody AI chats

### ISSUE THREAD

**Issue by FisherKeyBr** [sourcegraph/cody#4207]
### Version

v1.18.0 (pre-release)

### Describe the bug

After configuring Gemini models for use with the Cody AI extension, opening a new chat results in duplicated "Gemini model" options being displayed in the model selection menu. This creates confusion and makes it difficult to select the desired Gemini model.

Steps to reproduce:

Configure Gemini models for use within the Cody AI extension.
Open a new chat within VS Code using Cody AI.
Observe the model selection menu – the "Gemini model" option will be duplicated.

### Expected behavior

The model selection menu should present a single, unique entry for each available Gemini model, avoiding duplicates.

### Additional context

![image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/62c2796a-7299-4f86-998f-78a4ff8476b2/231e531f-e820-42a7-af61-e4fd8ebd3623?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy82MmMyNzk2YS03Mjk5LTRmODYtOTk4Zi03OGE0ZmY4NDc2YjIvMjMxZTUzMWYtZTgyMC00MmE3LWFmNjEtZTRmZDhlYmQzNjIzIiwiaWF0IjoxNzE2MzM3MTM4LCJleHAiOjMzMjg2ODk3MTM4fQ.OS_w1iLajvq6qOqdU7Wt-lLRkl0kzzOjo8rLYNIl2fs)

![image (1)](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/f432ec6f-433e-4a18-a790-2929854fa23f/5aaa10ce-da3e-4751-be6e-33e843fafe6f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9mNDMyZWM2Zi00MzNlLTRhMTgtYTc5MC0yOTI5ODU0ZmEyM2YvNWFhYTEwY2UtZGEzZS00NzUxLWJlNmUtMzNlODQzZmFmZTZmIiwiaWF0IjoxNzE2MzM3MTM4LCJleHAiOjMzMjg2ODk3MTM4fQ.lPesKl214BTFpOAdQ7coqyDHKE5s-Kfqsl6INqIPPPM)

**Comment by abeatrix** [comment]
Thanks for reporting the issue @FisherKeyBr ! Can you confirm if this issue persist when you restart Cody?
