### ISSUE TITLE
bug: Since the latest version, I have intermitent issues with adding selection to the chat with option+l and opening chats with the same shortcut

### ISSUE THREAD

**Issue by mcheviron** [sourcegraph/cody#4215]
### Version

Version: 1.89.1 Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685 Date: 2024-05-07T05:14:32.757Z Electron: 28.2.8 ElectronBuildId: 27744544 Chromium: 120.0.6099.291 Node.js: 18.18.2 V8: 12.0.267.19-electron.0 OS: Darwin arm64 23.4.0

### Describe the bug

I have an issue where sometimes I'm able to add a selection to the chat, but other times it's greyed out. This also applies to opening a new chat with the same keyboard shortcut, Option+L, on my machine. This was perfectly fine before the latest update.

![image](https://github.com/sourcegraph/cody/assets/87418909/8566c324-de32-49c0-aa21-0ebf981e8f30)
![image](https://github.com/sourcegraph/cody/assets/87418909/dab3fcd5-1cb8-4b97-b48b-5b7bf319492f)

### Expected behavior

Option+L adds selection to the chat
Option+L opens a new chat when no selection is made
Right click gives the option to add the file to the chat if no selection is there (it's also greyed out)

**Comment by SphaeroX** [comment]
releated to https://github.com/sourcegraph/cody/issues/4178
