### ISSUE TITLE
feedback: Support changing the model when editing a chat message

### ISSUE THREAD

**Issue by no2catisme** [sourcegraph/cody#4220]
### Version

1.19.1716131761

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

I have suggestion some changes in ui of Cody.
Cody is really convenient. thank you.
And to make use of the multimodal function more efficiently, I would like to put the function to change the module next to 'Edit Last Message'.
In addition, I hope that you can change the module using the shortcut key.
(ex:
Open the menu that can cut the module with the X + Y shortcut key, select the keyboard direction key, and enter it.)

### Describe the solution you'd like to see

To make use of the multimodal function more efficiently, I would like to put the function to change the module next to 'Edit Last Message'.
In addition, I hope that you can change the module using the shortcut key.
(ex:
Open the menu that can cut the module with the X + Y shortcut key, select the keyboard direction key, and enter it.)

![image](https://github.com/sourcegraph/cody/assets/166674382/b9bb5567-6e29-424e-8aa5-752bd16ee3e4)

**Comment by dominiccooney** [comment]
Thank you for the feedback! This has been fixed in #4189
