### ISSUE TITLE
bug: Login page is not displayed after reloading with proxy change 

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#4232]
### Version

1.19.1716218119

### Describe the bug

bug: Login page is not displayed after reloading with proxy change that causes Cody no longer be able to communicate with the endpoint.

Originally reported by @arafatkatze in https://sourcegraph.slack.com/archives/C05AGQYD528/p1715779597673829

> I've encountered a recurring problem with Cody in vscode where it gets stuck on the loading screen after a VS Code restart. This seems to happen when Cody retrieves an enterprise token from the cache, particularly if there's a network issue or the instance host is facing connectivity problems. The logs indicate that the token is "retreived" from the cache, but Cody remains in an indefinite loading state without progressing to the sign-in page.
This issue seems to trigger a sort of dead initialization, where even after resolving proxy settings or other network-related configurations, the problem persists occasionally, hinting at a potential race condition or a deadlock in the initialization process. I suspect others might have faced similar issues. I'm open to sharing a video demonstration of this problem for those interested. If anyone has insights or potential solutions, especially regarding implementing a timeout for such scenarios, your input would be greatly appreciated.
How can we effectively clear the cache or bypass this stale token state to prevent Cody from being stuck?

### Expected behavior

Login screen should still be loaded when there is an auth issue.

### Additional context

Loom: https://www.loom.com/share/4865ebf0edd34bdcaf0084aeb31ea4f7

**Comment by arafatkatze** [comment]
Solved by #4243
