### ISSUE TITLE
feedback: ollama embeddings

### ISSUE THREAD

**Issue by csreekrishna** [sourcegraph/cody#4234]
### Version

1.18

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [X] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

Ollama now supports embedding models. If Cody can utilize these Ollama embeddings, the context for all queries will be entirely local.

### Describe the solution you'd like to see

Update Cody to enable local embeddings with Ollama. This will make my data safer and eliminate the need to use OpenAI.

**Comment by ChrisPappalardo** [comment]
Bumping this, this is a great extension for vscode and would be great if it were fully local (embeddings + chat)!

**Comment by chenkc805** [comment]
Prioritize for later until we understand the retention benefit of embeddings

**Comment by csreekrishna** [comment]
The primary advantage of this add-on lies in data security. Many individuals are hesitant to use OpenAI for developing patented ideas or trade secrets. This add-on focuses on running everything locally, ensuring that sensitive information remains secure.
