### ISSUE TITLE
bug: Authentication failed. Please ensure Cody is enabled for sourcegraph.com and verify your email address if required.

### ISSUE THREAD

**Issue by jxkd123** [sourcegraph/cody#4333]
### Version

Authentication failed. Please ensure Cody is enabled for sourcegraph.com and verify your email address if required.

### Describe the bug

Authentication failed. Please ensure Cody is enabled for sourcegraph.com and verify your email address if required.

### Expected behavior

Authentication failed. Please ensure Cody is enabled for sourcegraph.com and verify your email address if required.

**Comment by olafurpg** [comment]
Thank you for reporting! It's difficult to troubleshoot this error without more information. Do you have a VPN enabled or are you using an HTTP proxy by any chance?
