### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tanmoy02** [sourcegraph/cody#4348]
- Issue Type: `Performance`
- Extension Name: `cody-ai`
- Extension Version: `1.18.2`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.89.1`

![image](https://github.com/sourcegraph/cody/assets/1296341/908ea5b1-5d9a-48d7-8e37-39d82cf9ab17)

[sourcegraph.cody-ai-unresponsive.cpuprofile.txt](https://github.com/sourcegraph/cody/files/15481662/sourcegraph.cody-ai-unresponsive.cpuprofile.txt)

**Comment by avion23** [comment]
Cody is for me unusable, because it uses up all CPU as soon as I start chatting.

Maybe it's the streaming?

**Comment by RXminuS** [comment]
I'm just debugging this @avion23 Could you try setting these and report if the CPU is still ramping up? If possible and you have the time it would be great help if you could make a CPU profile like @tanmoy02 .*

![CleanShot 2024-06-03 at 15 18 09](https://github.com/sourcegraph/cody/assets/3949285/b632d8f9-6199-458f-bfd9-493b45cd9ff4)

* I think this is done by cloning the project, under Run & Debug selecting `Launch VSCode (Desktop)` (which opens a new window with the locally built extension running) and then in the original VSCode command window searching `Debug: Take Performance Profile` and then selecting this running instance. But maybe @tanmoy02 has some pointers on a quicker way?

**Comment by RXminuS** [comment]
@tanmoy02 correct me if I'm wrong but yours seemed to cause lag / high CPU load during typing correct? @avion23 is yours **only** during chat or during normal typing as well?

**Comment by avion23** [comment]
It's only while the chat window *is outputting a new response*

**Comment by tanmoy02** [comment]
@RXminuS For the past few days, my editor has been experiencing significant lag. The IntelliSense feature in VS Code was taking an excessively long time to load, often displaying the "loading" message for 30 to 40 seconds, even when looking for type definitions.
To investigate the cause of this lag, I opened the **Show Running Extensions** menu. There, I discovered that two extensions, Cody and another one, were responsible for a high CPU load. To pinpoint the main culprit, I disabled each extension individually to test the impact. However, both extensions were found to be causing the same issue.
As a temporary solution, I have decided to report the problem and disable both extensions until a fix is released by the developers.

**Comment by tanmoy02** [comment]
@RXminuS Yes, I'm working on a large Angular project & the service file I'm working on has around 13K lines of code & the test file has around 40k lines of code.
Will the next release include the fix you suggested(#4446)?

**Comment by RXminuS** [comment]
> Will the next release include the fix you suggested(#4446)?

It's been merged now so will be included in next release. I have a few more performance items I'm chasing down that I hope to include as well. Will keep this issue open until I have those PRs up.

**Comment by RXminuS** [comment]
@avion23 it might be that your issue will be fixed by https://github.com/sourcegraph/cody/pull/4459 . I haven't been able to re-create it otherwise.

**Comment by avion23** [comment]
I tried the context = None, and I think it lowered the cpu usage. But not totally. How do I produce nice graphs for cpu/ram usage in vscode to debug this?
The project is 44M LOC.

I'll try out v1.20.2

**Comment by RXminuS** [comment]
@avion23 have a look if 1.20.2 fixes it for you, we included two fixes.

W.r.t. the traces; I'm actually just writing some docs on this. But basically in VSCode open the command prompt (cmd+shift+P by default), and type `Developer: show running extensions`. 

![CleanShot 2024-06-05 at 12 44 30@2x](https://github.com/sourcegraph/cody/assets/3949285/3ff43268-1046-44b2-a1a5-4c683e65c11d)

There you should see Cody in the list. Right click on it and start a host profile. This will show you the running profile in the bottom right of the window. 

![CleanShot 2024-06-05 at 12 46 01@2x](https://github.com/sourcegraph/cody/assets/3949285/fe0fae58-4ac9-4caa-b67c-d6f6ce725e2f)

You can now just try and do the behavior that's causing the issue. Then by clicking the message in the bottom right you stop the trace.

Finally you need to go back to the `Developer: show running extensions` view, right click Cody and click "Save extension profile"

![CleanShot 2024-06-05 at 12 46 45@2x](https://github.com/sourcegraph/cody/assets/3949285/f9dea7c4-786e-41bb-8039-5be1cb3edef9)

I'll make this process easier in the future!

**Comment by avion23** [comment]
I did a few tests and subjectively, it improved. I don't see the hanging and grey window anymore. But the fan still spins up, I just think less severe.

Thanks for the detailed instructions!
[CPU-20240605T120451.817Z.cpuprofile.txt](https://github.com/user-attachments/files/15586751/CPU-20240605T120451.817Z.cpuprofile.txt)

**Comment by RXminuS** [comment]
Awesome thanks for sharing, I'll have a look through your trace as well and see if anything jumps out at me.

**Comment by RXminuS** [comment]
Closing this for now. I still have a few tweaks I want to get to but the immediate fire seems to be under control now.

**Comment by idan3** [comment]
The same happens on the JetBrains plugin. I didn't know where should I write it but I assume its reletaed.

**Comment by Joihnny579** [comment]
And for me it happens in the browser (without plugins), while Cody generates an answer.
