### ISSUE TITLE
bug: Latest release are unusable

### ISSUE THREAD

**Issue by phisanti** [sourcegraph/cody#4376]
### Version

v1.18 and 1.19

### Describe the bug

I have downgraded my cody extension for vscode to v1.15 because the latest versions are just unusable. Chat sometimes takes ages to respond to the first question. Then, subsequent questions are not answered. The three colour dots indicating loading are just iterating forever. Very frustrating. However, v1.15 works simply fine, so I don't understand what happened. 

### Expected behavior

The nice clean chat experience that I had before.

**Comment by sqs** [comment]
@phisanti Sorry for the issues. When you say the 3 color dots are iterating forever, do they ever finish? Can you please record a video? We haven't heard this reported by anybody else, so do you have any suspicions about what is going on?

**Comment by phisanti** [comment]
I have just seen that you have released the v1.20. I will test it through the day and it the error persist, I will let you know.

**Comment by kalanchan** [comment]
@phisanti any chance you're on a VPN or proxy setup?

**Comment by phisanti** [comment]
I happens when i work connected from the ethernet at work or from the vpn in remote. It, however, does not happen when i use the version when i use v1. 15. If you can tell me how to print some logs, i can share them here when using the v1. 20 and the v1. 15

**Comment by kalanchan** [comment]
We added Proxy Support in v1.20, so i'm guessing some changes were made and it's not picking up your default network settings. Could you follow these troubleshooting steps in the [docs](https://sourcegraph.com/docs/cody/capabilities/proxy-setup#running-cody-via-proxies) and see if it works afterwards?

**Comment by kalanchan** [comment]
@phisanti We added Proxy Support in v1.20, so i'm guessing some changes were made and it's not picking up your default network settings. Could you follow these troubleshooting steps in the [docs](https://sourcegraph.com/docs/cody/capabilities/proxy-setup#running-cody-via-proxies) and see if it works afterwards?

**Comment by dominiccooney** [comment]
I am going to close this because it is inactive. It would be great to get more detail with a recent version to make progress on this.
