### ISSUE TITLE
Authentication failed for VS code Extension

### ISSUE THREAD

**Issue by simofou** [sourcegraph/cody#4397]
I installed the VS code extension and it was working fine for a while. All of a sudden, maybe around the Claude 3 update, I can no longer sign in. 
I have verified my email and logged in on Sourcegraph. 
Every time I try to sign in using VS Code I end up in an infinite loop of token creation with no success. Errors in VS code are:

`Authentication failed. Please ensure Cody is enabled for sourcegraph.com and verify your email address if required.`

`Authentication failed. Please check your token and try again.`

Thanks for your help!

**Comment by olafurpg** [comment]
I just got this error now while trying to log in myself 

<img src="https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/ca44c531-7f7e-4e95-b114-a3951dac0c0b/b2725b1b-cdf2-4049-8a74-dd28146edf6a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9jYTQ0YzUzMS03ZjdlLTRlOTUtYjExNC1hMzk1MWRhYzBjMGIvYjI3MjViMWItY2RmMi00MDQ5LThhNzQtZGQyODE0NmVkZjZhIiwiaWF0IjoxNzE3NTk4ODgwLCJleHAiOjMzMjg4MTU4ODgwfQ.ywazkP87bnBBh4pKp9MQzJi6NGr7pNhYfZK12ntY6hw " alt="CleanShot 2024-06-05 at 16.46.58@2x.png" width="878" height="242" />

Looks like a backend issue that happens during re-deployment 🤔
