### ISSUE TITLE
Generate release notes in Cody is not finding all tags in the repo

### ISSUE THREAD

**Issue by vadi2** [sourcegraph/cody#44]
Generate release notes in Cody is not finding all tags in the repo, only it is showing the following:

![Workspace 1_004](https://github.com/sourcegraph/sourcegraph/assets/110988/4c0d1a61-689b-4075-843b-581624e909bd)

While I have these tags: https://github.com/Mudlet/Mudlet/tags

**Comment by jdorfman** [comment]
@vadi2 looks like this was fixed. I'm going to close, feel free to reopen.
