### ISSUE TITLE
feedback: show ALL context Cody uses, and allow me to add more folders

### ISSUE THREAD

**Issue by GuyPardon** [sourcegraph/cody#4421]
### Version

1.20.0

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [X] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

I like Cody but like most AI coding tools it messes up with context - or at least gives me ambiguous information about whether or not it can access my codebase.

1. Ideally, I want Cody to us all of my workspace, period. I don't understand why this is not the case.

2. If 1. is not possible, then at least offer a separate window that shows all files / folders is using for its answers in every chat. I don't want per-chat context: I use a coding assistant in my workspace so it should read ALL of my workspace.

3. Again if 1. is not possible, just allow me to add my workspace folders in one easy click.

Thanks
Guy

### Describe the solution you'd like to see

See above.

**Comment by ydennisy** [comment]
+1 on this, I use vscode workspaces it it seems cody defaults to a single folder.

Any workaround for this?
