### ISSUE TITLE
bug: Request Failed: Sourcegraph Cody Gateway: unexpected status code 400

### ISSUE THREAD

**Issue by ZebraSu** [sourcegraph/cody#4428]
### Version

1.20.0

### Describe the bug

I'm having some unsolvable problems with cody ai in vscode today, using gpt models, and claude models, and using both types of models prompts me to 

Request Failed: Sourcegraph Cody Gateway: unexpected status code 400: {"error": "request blocked - if you think this is a mistake, please contact support@sourcegraph.com and reference this ID: 4d7ab1267b25b581b98fd3a04567f59d"}

If I use the Mixtal model it works fine with cody ai

### Expected behavior

work well

**Comment by chenkc805** [comment]
Hello @ZebraSu , I can help with this. What is your Sourcegraph username (you can go to sourcegraph.com/cody/manage and click your profile icon on the top right to see what it is, it's probably something like "@name-asdf")?

**Comment by romanfurman6** [comment]
Hello @chenkc805 i have faced the same issue today

`Request Failed: Sourcegraph Cody Gateway: unexpected status code 400: {"error":"request blocked - if you think this is a mistake, please contact support@sourcegraph.com and reference this ID: ecb152d21bfb3d50f963bee68096a494"}`

username: roman.furman-nhxwn

**Comment by Silva-PT** [comment]
I've also been getting this error, my username is "@luisilva94-irbvt".

Tried changing models, relog, etc, but no luck...
