### ISSUE TITLE
feedback: add button in VS Code (Source control) for suggesting a commit message

### ISSUE THREAD

**Issue by scriptdealer** [sourcegraph/cody#4429]
### Version

latest

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

It would be cool to generate a commit messages

### Describe the solution you'd like to see

There are some extensions - say, "Auto commit message", for example. They are adding a button in 'Source control' section, which allows to generate commit messages

### Describe any alternatives that could be considered

Idk, just feed a git diff to LLM or see the sources of "Auto commit message"

**Comment by esafak** [comment]
I have the same request for IntelliJ.

**Comment by dedh121224** [comment]
I also hope to add this great feature
