### ISSUE TITLE
Cody reads unnecessary context files

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#443]
Cody is reading a lot of unnecessary context files in case of simple Chat input like"thankYou", "hey", or if I ask some simple questions.

Some examples of it:

![iScreen Shoter - Code - 230728204815](https://github.com/sourcegraph/cody/assets/44617923/e83c2a47-3ca6-409f-9959-db4bb36b4bc9)
![iScreen Shoter - Code - 230728204834](https://github.com/sourcegraph/cody/assets/44617923/283990a7-a406-4c72-9551-0bf55f321001)

**Comment by jdorfman** [comment]
We need a `.codyignore` file so users can define what is ok for Cody to scan and what not.

```
.json
.env
README*
```

Same functionality as https://git-scm.com/docs/gitignore
