### ISSUE TITLE
bug:  The Remove of Enhanced Context feature

### ISSUE THREAD

**Issue by mohalnassery** [sourcegraph/cody#4430]
### Version

1.20

### Describe the bug

We used to have enhanced context feature. It used to make my work easier as i can just describe what I need, then it will automatically pick the files needed for context. it used to have indexed search and git embiddings. 

Now whenever I want to do a task, i need to refer to all files related to the task with @ . 

### Expected behavior

There should be the same as previous version of using enhanced context. and automatically use files context related to the task i write the same as before. That what made cody AI better than others.

**Comment by sqs** [comment]
Hi @mohalnassery, this functionality is still there. The first `@`-mention is of the repository and includes all context from the repository, just like the "Enhanced context" did before. See https://sourcegraph.com/blog/cody-vscode-1-20-0-release for more information.
