### ISSUE TITLE
bug: Grey chat window is back with vengeance

### ISSUE THREAD

**Issue by Lebofly** [sourcegraph/cody#4431]
### Version

v1.21.1717254953

### Describe the bug

Very often the chat window will turn grey, it's happening after 10 minutes of use and occurs multiple times whether or not it's a new chat session. This is preventing me from further using Cody.

### Expected behavior

No grey chat window

### Additional context

![image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/7648ca2b-72a1-4bf5-861d-29d3679f5928/0bd12dab-9523-48a2-a49b-baf9064740b6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy83NjQ4Y2EyYi03MmExLTRiZjUtODYxZC0yOWQzNjc5ZjU5MjgvMGJkMTJkYWItOTUyMy00OGEyLWE0OWItYmFmOTA2NDc0MGI2IiwiaWF0IjoxNzE3NDE1MTI0LCJleHAiOjMzMjg3OTc1MTI0fQ.gGu4tjM7Qsa_19NUTR3PUGOgMUp9aZk77zyBZku1rzY)

**Comment by git-longcat** [comment]
I used v1.20.1 on Windows 11 for about an hour. The above problem occurred about 3 times.
On the other hand, I used v1.18.2 for several days, but this problem never occurred.

**Comment by dominiccooney** [comment]
That is probably the result of a WebView crash, for example OOM. The Chromium embedding API has a crash callback, we should find where VSCode surfaces that and trigger reloading the WebView. We should also add some Telemetry on this.
