### ISSUE TITLE
bug: Pro membership not showing

### ISSUE THREAD

**Issue by ecairncross** [sourcegraph/cody#4451]
Type: **Bug**

## Extension Information

* Cody Version: 1.20.1
* VS Code Version: 1.89.1
* Extension Host: desktop

## Steps to Reproduce

1. UPgrade to Pro. (including paying)
2. Return to VSCode (restart etc.)
3. Cody still thinks it's the free version

## Logs

Extension version: 1.20.1
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

System Info

| Item | Value |
| -- | -- |
| CPUs | AMD Ryzen 7 6800H with Radeon Graphics (16 x 3194) |
| GPU Status | 2d_canvas: enabled |

canvas_oop_rasterization: enabled_on
direct_rendering_display_compositor: disabled_off_ok
gpu_compositing: enabled
multiple_raster_threads: enabled_on
opengl: enabled_on
rasterization: enabled
raw_draw: disabled_off_ok
skia_graphite: disabled_off
video_decode: enabled
video_encode: enabled
vulkan: disabled_off
webgl: enabled
webgl2: enabled
webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.19GB (14.10GB free)|
|Process Argv|--crash-reporter-id 4a03b73a-b61a-4dcd-bab3-9a9e99eb618c|
|Screen Reader|no|
|VM|0%|

A/B Experiments

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31066414
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877
```

**Comment by imaurer** [comment]
I had to logout and re-login to get Cody to work again with the latest update 6.0.3.
