### ISSUE TITLE
feedback: 

### ISSUE THREAD

**Issue by GENnetuk-DEV** [sourcegraph/cody#4463]
### Version

Version: 1.89.1 (Universal) Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685 Date: 2024-05-07T05:14:24.611Z (4 wks ago) Electron: 28.2.8 ElectronBuildId: 27744544 Chromium: 120.0.6099.291 Node.js: 18.18.2 V8: 12.0.267.19-electron.0 OS: Darwin x64 23.5.0

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [X] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

This was a great extension, and it works fairly well for months before its ultimate collapse. The last version was unstable, and of course now everything just gives. "You've used all chat messages and commands for today." even when there have been no chat messages today, or yesterday. 

### Describe the solution you'd like to see

I can only imagine the company ran out of money, which is a shame because its better than co-pilot imo. 

### Describe any alternatives that could be considered

Co-pilot, and Codeium are alternatives, but not as functional as the earlier versions of cody.

**Comment by kalanchan** [comment]
hey @GENnetuk-DEV sorry about the experience you're having on the latest version. Could you provide some screenshots of what you're seeing so that we can look into it?

Thanks!

**Comment by GENnetuk-DEV** [comment]
<img width="622" alt="Screenshot 2024-06-09 at 10 25 57" src="https://github.com/sourcegraph/cody/assets/118559760/ca8862db-2bf9-4e1a-b63c-012ebcd257f0">

**Comment by kalanchan** [comment]
thanks @GENnetuk-DEV! we made some changes, are you still experiencing this? 

Are you on a pro plan at the moment?

**Comment by GENnetuk-DEV** [comment]
<img width="1103" alt="Screenshot 2024-06-10 at 19 02 37" src="https://github.com/sourcegraph/cody/assets/118559760/732a68a5-64fd-43ae-a3bd-dec7655d8ecc">
