### ISSUE TITLE
bug: Request Failed: Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}

### ISSUE THREAD

**Issue by alanmaulanaa** [sourcegraph/cody#4474]
Type: **Bug**

## Extension Information

* Cody Version: 1.20.3
* VS Code Version: 1.90.0
* Extension Host: desktop

## Steps to Reproduce

1. Just update my extension and restart extension
2. Any command using AI always result "Request Failed: Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}"
3. Already restart my VS Code and the result is same.

## Logs

█ logEvent: CodyVSCodeExtension:CodySavedLogin:executed
█ telemetry-v2: recordEvent: cody.extension/savedLogin
█ AuthProvider:init:lastEndpoint: Token recovered from secretStorage [https://sourcegraph.com/](https://sourcegraph.com/)
█ GraphQLTelemetryExporter: evaluated export mode: 5.2.5+
█ openctx: OpenCtx is enabled in Cody
█ featureflag: refreshed
█ featureflag: refreshed
█ featureflag: refreshed
█ LocalEmbeddingsController: constructor
█ featureflag: refreshed
█ ContextFiltersProvider: setContextFilters
█ ChatManager:constructor: init has local embeddings controller
█ ChatPanelsManager:constructor: init
█ LocalEmbeddingsController: start
█ CodyEngineService: constructor
█ SymfRunner: unsafeEnsureIndex file:///c%3A/Users/ALAN/Documents/GitHub/myportosite
█ CommandsController:init: watchers created
█ main:deserializeWebviewPanel: reviving last unclosed chat panel
█ LocalEmbeddingsController: start
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatus \[{"displayName":"myportosite","providers":\[{"kind":"embeddings","state":"indeterminate","embeddingsAPIProvider":"sourcegraph"}\]}\]
█ SimpleChatPanelProvider:revive: registering webview panel
█ SimpleChatPanelProvider:registerWebviewPanel: registering webview panel
█ SimpleChatPanelProvider: postContextStatus \[{"displayName":"myportosite","providers":\[{"kind":"embeddings","state":"indeterminate","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}\]}\]
█ CodyEngine: using downloaded path "c:\\Users\\ALAN\\AppData\\Roaming\\Code\\User\\globalStorage\\sourcegraph.cody-ai\\cody-engine\\cody-engine-5.4.3547-windows-x64"
█ CodyEngineService: spawnAndBindService service started, initializing
█ LocalEmbeddingsController: spawnAndBindService service started, initializing
█ getLocalOllamaModels: failed : Please make sure the Ollama server is up & running.
█ SimpleChatPanelProvider: postContextStatus \[{"displayName":"myportosite","providers":\[{"kind":"embeddings","state":"indeterminate","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}\]}\]
█ CodyEngine: spawnBfg:stderr
█ CodyEngine: spawnBfg:stderr
█ CodyEngine: spawnBfg:stderr
█ LocalEmbeddingsController: spawnAndBindService initialized
█ CodyCompletionProvider:initialized: fireworks/starcoder-hybrid
█ telemetry-v2: recordEvent: cody.context.embeddings/loaded
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatus \[{"displayName":"myportosite","providers":\[{"kind":"embeddings","state":"ready","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}\]}\]
█ Cody:publishConfig: configForWebview
█ ContextProvider:onConfigurationChange: using codebase
█ logEvent: CodyVSCodeExtension:Auth:connected
█ telemetry-v2: recordEvent: cody.auth/connected
█ telemetry-v2: recordEvent: cody.context.embeddings/loaded
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatus \[{"displayName":"myportosite","providers":\[{"kind":"embeddings","state":"ready","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}\]}\]
█ LocalEmbeddingsController: index-health {"commit":"c084dbe5a40481366754ca5ffd4ae2ea349f2f79","dimension":768,"format":"LocalEmbeddings","model":"sourcegraph/st-multi-qa-mpnet-base-dot-v1","numFiles":26,"numItems":254,"numItemsDeleted":0,"numItemsFailed":0,"numItemsNeedEmbedding":0,"repoName":"[github.com/alanmaulanaa/myportosite","type":"found](http://github.com/alanmaulanaa/myportosite%22,%22type%22:%22found)"}
█ SimpleChatPanelProvider: handleInitialized
█ LocalEmbeddingsController: index-health {"commit":"c084dbe5a40481366754ca5ffd4ae2ea349f2f79","dimension":768,"format":"LocalEmbeddings","model":"sourcegraph/st-multi-qa-mpnet-base-dot-v1","numFiles":26,"numItems":254,"numItemsDeleted":0,"numItemsFailed":0,"numItemsNeedEmbedding":0,"repoName":"[github.com/alanmaulanaa/myportosite","type":"found](http://github.com/alanmaulanaa/myportosite%22,%22type%22:%22found)"}
█ SimpleChatPanelProvider: updateViewConfig
█ UpstreamHealth: Ping took 1401ms (Gateway: 651ms)
█ LocalEmbeddingsController: start
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatus \[{"displayName":"myportosite","providers":\[{"kind":"embeddings","state":"ready","embeddingsAPIProvider":"sourcegraph"}\]}\]
█ SimpleChatPanelProvider:registerWebviewPanel: registering webview panel
█ SimpleChatPanelProvider: postContextStatus \[{"displayName":"myportosite","providers":\[{"kind":"embeddings","state":"ready","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}\]}\]
█ telemetry-v2: recordEvent: cody.context.embeddings/loaded
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatus \[{"displayName":"myportosite","providers":\[{"kind":"embeddings","state":"ready","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}\]}\]
█ LocalEmbeddingsController: index-health {"commit":"c084dbe5a40481366754ca5ffd4ae2ea349f2f79","dimension":768,"format":"LocalEmbeddings","model":"sourcegraph/st-multi-qa-mpnet-base-dot-v1","numFiles":26,"numItems":254,"numItemsDeleted":0,"numItemsFailed":0,"numItemsNeedEmbedding":0,"repoName":"[github.com/alanmaulanaa/myportosite","type":"found](http://github.com/alanmaulanaa/myportosite%22,%22type%22:%22found)"}
█ SimpleChatPanelProvider: postContextStatus \[{"displayName":"myportosite","providers":\[{"kind":"embeddings","state":"ready","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}\]}\]
█ SimpleChatPanelProvider: handleInitialized
█ SimpleChatPanelProvider: updateViewConfig
█ logEvent: CodyVSCodeExtension:chat-question:submitted
█ telemetry-v2: recordEvent: cody.chat-question/submitted
█ DefaultPrompter.makePrompt: Ignored context due to context limit: user=0, enhanced=0, previous=0
█ logEvent: CodyVSCodeExtension:chat-question:executed
█ telemetry-v2: recordEvent: cody.chat-question/executed
█ SimpleChatPanelProvider: streamAssistantResponse
█ CompletionLogger:onError: {"type":"completion","endpoint":"[https://sourcegraph.com/.api/completions/stream?api-version=1&client-name=vscode&client-version=1.20.3","status":"error","duration":836,"err":"Sourcegraph](https://sourcegraph.com/.api/completions/stream?api-version=1&client-name=vscode&client-version=1.20.3%22,%22status%22:%22error%22,%22duration%22:836,%22err%22:%22Sourcegraph) Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}\\n"}
█ SimpleChatPanelProvider: postError: Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}

█ logEvent: CodyVSCodeExtension:chatResponse:noCode
█ telemetry-v2: recordEvent: cody.chatResponse/noCode
█ logEvent: CodyVSCodeExtension:statusBarIcon:clicked
█ telemetry-v2: recordEvent: cody.statusbarIcon/clicked
█ openctx: OpenCtx is enabled in Cody
█ LocalEmbeddingsController: setAccessToken is dotcom
█ LocalEmbeddingsController: setAccessToken is dotcom
█ openctx: Failed to load OpenCtx client: Error: command 'openctx.toggleEnable' already exists
█ getLocalOllamaModels: failed : Please make sure the Ollama server is up & running.
█ featureflag: refreshed
█ ContextProvider:onConfigurationChange: using codebase
█ UpstreamHealth: Ping took 339ms (Gateway: 378ms)

Extension version: 1.20.3
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

System Info

| Item | Value |
| -- | -- |
| CPUs | Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208) |
| GPU Status | 2d_canvas: enabled |

canvas_oop_rasterization: enabled_on
direct_rendering_display_compositor: disabled_off_ok
gpu_compositing: enabled
multiple_raster_threads: enabled_on
opengl: enabled_on
rasterization: enabled
raw_draw: disabled_off_ok
skia_graphite: disabled_off
video_decode: enabled
video_encode: enabled
vulkan: disabled_off
webgl: enabled
webgl2: enabled
webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.22GB free)|
|Process Argv|--crash-reporter-id 74b4b6e4-3c1f-49a2-909e-2bbf22c56069|
|Screen Reader|no|
|VM|0%|

A/B Experiments

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideoc:31016891
chatpanelt:31048053
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
newcmakeconfigv2:31067619
26j00206:31048877
```

**Comment by helpisdev** [comment]
Any updates on this? The plugin worked properly until unexpectedly it didn't with the same error. I'm using the PRO subscription.

**Comment by GeroWalther** [comment]
I have the same issue.
Is there a fix?
