### ISSUE TITLE
feedback: bring the stop button back again!

### ISSUE THREAD

**Issue by SphaeroX** [sourcegraph/cody#4488]
### Version

v1.21.1717686938 (pre-release)

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

![image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/8ac2df19-f968-4a71-8af0-16a11da4b0bb/72ac4dbf-96e8-41a3-bbec-b8e9e567b79c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy84YWMyZGYxOS1mOTY4LTRhNzEtOGFmMC0xNmExMWRhNGIwYmIvNzJhYzRkYmYtOTZlOC00MWEzLWJiZWMtYjhlOWU1NjdiNzljIiwiaWF0IjoxNzE3Nzg1NTkxLCJleHAiOjMzMjg4MzQ1NTkxfQ.31pTHEHf-VNuYSwqwBm-W_pKIVbymzABNR4VtX4d9lo)

there no more stop button

### Describe the solution you'd like to see

bring back the stop button, sometimes u wont wait for the full answer. time is money :)

### Describe any alternatives that could be considered

*No response*

### Additional context

*No response*

```[tasklist]
### Tasks
```

**Comment by sqs** [comment]
Yes, we will bring this back. In the meantime, you can press <kbd>Esc</kbd> (hidden keyboard shortcut).

However: It is not possible to reply until the message has completed yet. We could make this possible, but we're not sure of the impact of a partial chopped-off message on the reply response quality. You can edit your message while it's still streaming in. We also turned off autoscroll by default, so you should be able to just ignore the message continuing to stream in. Not disputing that a button is useful and expected, but I'm curious about why you actually want it or if it just feels bad for the message to keep streaming in.

**Comment by kiraum** [comment]
I think the idea is to stop the message (ESC button does the trick), not edit, and trigger a new message. Not sure if possible, why not make those options configurable?
