### ISSUE TITLE
bug: cody's chat not loading on latest VSCode Insiders

### ISSUE THREAD

**Issue by ryan6416** [sourcegraph/cody#4491]
### Version

v1.20.3

### Describe the bug

After updating VSCode Insiders to version 1.91.0-insider, cody's chat is showing blank.

### Expected behavior

Before update, cody's chat shows up and was able to chat fine. Issue does not occur on regular VSCode version 1.89.1, where cody's chat appears and works fine.

### Additional context

![CleanShot 2024-06-07 at 07 58 34@2x](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/c349d94d-4b8b-459b-bc99-4e6140d56b1c/197e1459-a5a0-4567-a7b5-b82e1339b167?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9jMzQ5ZDk0ZC00YjhiLTQ1OWItYmM5OS00ZTYxNDBkNTZiMWMvMTk3ZTE0NTktYTVhMC00NTY3LWE3YjUtYjgyZTEzMzliMTY3IiwiaWF0IjoxNzE3Nzg1NTM5LCJleHAiOjMzMjg4MzQ1NTM5fQ.eHZrsflPhr11aIwQwEA3GZ2PRRCzlpHCXJ7VFGL6ZvA)

![CleanShot 2024-06-07 at 07 58 39@2x](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/4f0d51d9-44e4-4811-b244-1059d264d835/c853b237-5d58-4175-b5a1-96cba3427f13?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy80ZjBkNTFkOS00NGU0LTQ4MTEtYjI0NC0xMDU5ZDI2NGQ4MzUvYzg1M2IyMzctNWQ1OC00MTc1LWI1YTEtOTZjYmEzNDI3ZjEzIiwiaWF0IjoxNzE3Nzg1NTM5LCJleHAiOjMzMjg4MzQ1NTM5fQ.h2nS979elYrjKfM0uYq6Qm1bz2bKXLjyqPPie2SQHq0)

**Comment by ichim-david** [comment]
Can confirm, even though I am up to date on insider and cody pre-release it no longer loads.
![cody-loading](https://github.com/sourcegraph/cody/assets/152852/20b02963-6280-41ed-b3b2-6fd11cf8c837)

Using vs code non-insider works.
Tried to uninstall and re-install and still no resolution.

**Comment by tylergannon** [comment]
Same.  Furthermore, running the extension "Cody Debug: Report Issue" causes the following popup.
![Screenshot 2024-06-08 at 5 59 32 PM](https://github.com/sourcegraph/cody/assets/50593/496ea061-3011-4e88-890f-513f3845fce2)

**Comment by sqs** [comment]
Hmm, so there is nothing in the `Cody by Sourcegraph` output channel? Does Cody autocomplete work? Is there a status bar icon?

Can you try setting `"cody.debug.verbose": true` in your VS Code user settings and seeing if anything shows up in the output channel?

**Comment by ichim-david** [comment]
> Hmm, so there is nothing in the `Cody by Sourcegraph` output channel? Does Cody autocomplete work? Is there a status bar icon?
> 
> Can you try setting `"cody.debug.verbose": true` in your VS Code user settings and seeing if anything shows up in the output channel?
> 
> Also, can you poke around and see if there are any other errors in the extension host output channel or anything else suspicious?

@sqs here is what vs code developer tools shows when i search for cody
![cody-devtools-error](https://github.com/sourcegraph/cody/assets/152852/2f92d432-8018-4c92-81a5-2544acbc38c7)

**Comment by ichim-david** [comment]
No output when settings debug
![cody-settings](https://github.com/sourcegraph/cody/assets/152852/38ddc0fd-f5b9-4fd5-904f-7a24bff01506)

**Comment by ichim-david** [comment]
Here is the other error I keep getting.
![github-pull-requests](https://github.com/sourcegraph/cody/assets/152852/dd513d08-90a7-4ec4-9e29-893a17fbc20a)
I've uninstalled GitHub pull request extension and the same issue.
Hopefully, this might help in the bug-finding quest.

**Comment by renatogalera** [comment]
Same bug here, vscode insiders.

I tried installing olders versions, without success

**Comment by marcelo-amorim-mobrj** [comment]
Any update? Same problem here with stable and insiders versions. I'm using VSCode Insiders.

**Comment by sqs** [comment]
**Workaround:** If you are experiencing this problem and are using VS Code Insiders, switch to VS Code 1.90 (stable, non-insiders). I am referring to the versions of VS Code itself, not the Cody extension.

---

The problem appears to occur only with recent builds of VS Code Insiders (i.e., not related to a recent change in Cody).
 Someone reported this on our community forums as well (https://community.sourcegraph.com/t/cody-extension-hangs-on-extension-activation-after-installing-latest-can-t-use-it-help-requested/499/2) and found that it works on VS Code non-Insiders or the VS Code Insiders build from a few days ago:

> This appears to be a breaking change in the latest release of VS Code Insiders (1.91.0-Insiders), releases within the past day or so. I was able to resolve the problem by switching back to the previous Insiders build.

We will investigate to see what Cody might be doing that is triggering this issue.

**Comment by sqs** [comment]
We just published a Cody prerelease build (v1.21.1717993747) to the VS Code marketplace that should fix this issue. Please try that and report back if it works for you. Thanks!

**Comment by ichim-david** [comment]
> We just published a Cody prerelease build (v1.21.1717993747) to the VS Code marketplace that should fix this issue. Please try that (with `Switch to Pre-release Version` in the VS Code extension view for Cody) and report back if it works for you. Thanks!

@sqs confirm working again with latest pre release for me at least on a mac.

**Comment by sqs** [comment]
Awesome, thank you!
