### ISSUE TITLE
bug: Rate Limit Exceeded

### ISSUE THREAD

**Issue by nn1k4** [sourcegraph/cody#4530]
### Version

1.89.1

### Describe the bug

I am encountering an issue that is affecting my ability to use your
plugin Cody: AI Coding Assistant with Autocomplete & Chat. I keep
receiving the error "Rate Limit Exceeded," and this happens every day.
This significantly hinders my usage of the plugin, which is
unacceptable given that I have a paid subscription.

### Expected behavior

Please look into this matter as soon as possible and provide a solution.

### Additional context

![screen](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/115b3729-f55f-4ad9-8b14-08ebbc238725/154423fd-62d5-4afb-a3f9-c90081892161?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy8xMTViMzcyOS1mNTVmLTRhZDktOGIxNC0wOGViYmMyMzg3MjUvMTU0NDIzZmQtNjJkNS00YWZiLWEzZjktYzkwMDgxODkyMTYxIiwiaWF0IjoxNzE4NDA0ODQ0LCJleHAiOjMzMjg4OTY0ODQ0fQ.4UkkoH6GTk3YguXhgubw5X9IK-CvQO_tSxsWu4ZkIhA)

**Comment by chenkc805** [comment]
Hey - if you're still running into rate limit issues, what's your sourcegraph username so I can look into this for you?
