### ISSUE TITLE
feedback: Unclear error message

### ISSUE THREAD

**Issue by ShalokShalom** [sourcegraph/cody#4540]
### Version

1.90.0

### Areas for Improvement

- [X] UI/UX
- [X] Onboarding
- [X] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

I dont know, what to make of this. It seems to come from an old project, and yes, I dont have a git file in there. What does this mean? Why is this important? What do I need to do, so that this error message goes away? 

![Screenshot_20240612_103229](https://github.com/sourcegraph/cody/assets/6344099/051ecb15-8d88-4ecc-ad88-478246969edc)

### Describe the solution you'd like to see

I suggest to include more info, particulary, what I can do about it. Thanks a lot

**Comment by jdorfman** [comment]
Thanks @ShalokShalom. I will make sure the product team sees this in the weekly community feedback report. They can triage from there!

**Comment by ShalokShalom** [comment]
What has been concluded at the triage?
