### ISSUE TITLE
bug: UNABLE TO SEND MESSAGE You've used all chat messages and commands for today.

### ISSUE THREAD

**Issue by mcheviron** [sourcegraph/cody#4549]
### Version

Version: 1.90.0 Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573 Date: 2024-06-04T19:34:48.028Z Electron: 29.4.0 ElectronBuildId: 9593362 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Darwin arm64 23.5.0

### Describe the bug

Since this morning I have been getting this error message:
UNABLE TO SEND MESSAGE
You've used all chat messages and commands for today.

All while I am a Pro member. The issue arose for me after the 1.22.0 update

![image](https://github.com/sourcegraph/cody/assets/87418909/7acc5a3f-225e-4c70-9713-86d868164bd9)

### Expected behavior

To have chat working normally

**Comment by mcheviron** [comment]
Can this be fixed soon. It's making the whole thing unusable for me which is lacklustre for my work

**Comment by kalanchan** [comment]
@mcheviron @kolmakova sorry about this, could you file a ticket in our [support form](https://help.sourcegraph.com/hc/en-us/requests/new) instead? This will help us keep track of account issues more closely

**Comment by mcheviron** [comment]
@kalanchan thanks for the response. I already did this but had no response so far so I didn't if there are other mediums of conversation since as you can guess this is a bit crippling. Is there a faster way to get a response?

Thanks
