### ISSUE TITLE
feedback: Rename chat

### ISSUE THREAD

**Issue by iezed** [sourcegraph/cody#4554]
### Version

1.22

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

Hello,
I don't understand why the option to change the chat name has been removed.
 Is it possible to have it back?

### Describe the solution you'd like to see

But back rename chat.

**Comment by jdorfman** [comment]
Thanks for addressing this @iezed. I will make sure the product team sees this in the weekly community feedback report.
