### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by ALAXAY** [sourcegraph/cody#4558]
### Version

Cody: AI Coding Assistant with Autocomplete & Chat v1.23.1718291782 (pre-release)

### Describe the bug

UNABLE TO SEND MESSAGE
You've used all chat messages and commands for today.

Learn More
Usage will reset today at 9:25 PM

Try again with different context
Public knowledge only
Add context...

### Expected behavior

UNABLE TO SEND MESSAGE
You've used all chat messages and commands for today.

Learn More
Usage will reset today at 9:25 PM

Try again with different context
Public knowledge only
Add context...

### Additional context

ALAXAY

**Comment by kalanchan** [comment]
closing this in favor of https://github.com/sourcegraph/cody/issues/4515
