### ISSUE TITLE
bug: error 400 with Gemini 1.5 pro :  Invalid JSON payload received. Unknown name \"stream\": Cannot find field.

### ISSUE THREAD

**Issue by quentin-lior** [sourcegraph/cody#4566]
### Version

1.22.0

### Describe the bug

When using the new Gemini 1.5 pro, I get the following error : 
Request Failed: Sourcegraph Cody Gateway: unexpected status code 400: { "error": { "code": 400, "message": "Invalid JSON payload received. Unknown name \"stream\": Cannot find field.", "status": "INVALID_ARGUMENT", "details": [ { "@type": "type.googleapis.com/google.rpc.BadRequest", "fieldViolations": [ { "description": "Invalid JSON payload received. Unknown name \"stream\": Cannot find field." } ] } ] } }

### Expected behavior

It should properly answer the request.

### Additional context

I am getting the error even without context.

**Comment by abeatrix** [comment]
@quentin-lior Thanks for reporting the issue!  We were able to locate the issue and has bee been fixed now 😄

**Comment by abeatrix** [comment]
Close by https://github.com/sourcegraph/sourcegraph/pull/63258
