### ISSUE TITLE
bug: UNABLE TO SEND MESSAGE You've used all chat messages and commands for today.

### ISSUE THREAD

**Issue by ALAXAY** [sourcegraph/cody#4575]
### Version

Cody: AI Coding Assistant with Autocomplete & Chat v1.23.1718291782 (pre-release)

### Describe the bug

I ask for feedback, I write to email and support. cody has been down for 5 days. Last night, Kyiv time, Ukraine started working at about 3:20, and then 30 minutes later it did not respond again and showed the error UNABLE TO SEND MESSAGE You've used all chat messages and commands for today.

### Expected behavior

I ask for feedback.

**Comment by thatmike1** [comment]
Have the same thing, but just started today. I was using gemini 1.5 pro all day yesterday without issues. Now i get this message and waiting doesnt solve anything :/

**Comment by ALAXAY** [comment]
how to contact developers via discord

**Comment by thatmike1** [comment]
Oh buddy, you seem to be as helpless as i am without it :D. I know it sucks, but try and take this time to actually read docs and understand the code by yourself. That being said, i think you can find their discord by searching "sourcegraph" in the discord server search(invite on website is broken)

**Comment by ALAXAY** [comment]
scam?

**Comment by thatmike1** [comment]
lmao what ? Cody is definitely not a scam :D

**Comment by kalanchan** [comment]
hey @thatmike1 @ALAXAY would you be able to file a request ticket [here](https://help.sourcegraph.com/hc/en-us/requests/new)?

@ALAXAY what type of questions are you asking Cody? We've reset your account multiple times but the rate limits seem to be persistent

**Comment by thatmike1** [comment]
hey @kalanchan Jim on discord helped me already, but thanks anyway :)
