### ISSUE TITLE
bug: rate limit

### ISSUE THREAD

**Issue by AlfSandoval** [sourcegraph/cody#4576]
### Version

V1.22.1

### Describe the bug

Rate limited  on Pro plan - web page explicitly says unlimited

### Expected behavior

No rate limit

**Comment by Dolvido** [comment]
I am experiencing the same.
![image](https://github.com/sourcegraph/cody/assets/88521481/8e9c4ce7-2788-4424-a463-0a7cc111e448)

Rate limit was encoutnered yesterday and did not reset for today either.

**Comment by kalanchan** [comment]
hey @AlfSandoval @Dolvido sorry about that, could you file a request ticket [here](https://help.sourcegraph.com/hc/en-us/requests/new), we'll get to it right away
