### ISSUE TITLE
VS Code: "Generate Unit Tests" is not working correctly for new files.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#4602]
### Version

v1.23.1718550982

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Free/Pro user
3. Create a new source code file
4. Right click and choose "Cody > Generate Unit Tests" 
5. Verify that two test files will be created

### Observed behavior:
Two test files will be created but the Cody is not generating any unit tests.

### Expected behavior

Only one test file should be created and Cody should generate unit tests correctly.

### Additional context

**Video link:**

https://drive.google.com/file/d/1i2s8yJfqigS9xnni3trbieeP4a9NP0lj/view?usp=drive_link

**Comment by justinmilner1** [comment]
@jay-fibi Thanks for posting the video!
It looks like you might also be experiencing [this bug](https://github.com/sourcegraph/cody/issues/4581)? (where untitled empty files are created by Cody). It's possible these issues are linked. 

I'm trying to gather more info about when these accidental files are created - your video shows an untitled file being created when you created the new java file, does this happen consistently for you? Have you noticed untitled files being created in other scenarios?

**Comment by jay-fibi** [comment]
@justinmilner1 Yes, most probably they are linked. I will re-test this once a fix is available. Thank you :)

**Comment by justinmilner1** [comment]
@jay-fibi fyi the [untitled file bug](https://github.com/sourcegraph/cody/issues/4581) just got closed out

**Comment by jay-fibi** [comment]
@justinmilner1 this issue is resolved now, I have verified with v1.26.7. Closing it out.
