### ISSUE TITLE
(No-)Context full control

### ISSUE THREAD

**Issue by ce94** [sourcegraph/cody#4651]
### Version

1.22.4

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [ ] Commands
- [X] Context
- [X] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

1. When I set **"Cody: Use Context" to "none"** in the Cody extension settings for Cody Chat (ext:sourcegraph.cody-ai chat) in VSCode, I expect that no files or repositories are selected by default when starting new chats. This is crucial because the included data can significantly impact the response, and I need full control over the data I share to ensure the quality of the answers.
2. Additionally, I don't always work in repositories. Although I understand that it may not make a difference in such cases, I still delete the first-bold-tag manually each time.
3. The most important point is that even if I put a question without any tagged files, the response still references the file as context.

### Describe the solution you'd like to see

I would like the "Cody: Use Context: none" setting to ensure that no files or repositories are ever included by default when starting new chats. This would give me complete control over the data I share, improving the accuracy and relevance of the responses.

### Describe any alternatives that could be considered

An alternative solution could be to provide a more easily accessible toggle option for selecting or deselecting files as context. The top 3 files could be placed directly next to the "@" icon as tags to toggle (blue, selected -> will be included, grey, deselected -> will not be included), allowing users to quickly manage their context without clicking on the "@" icon for most important files.

**Comment by taylorsperry** [comment]
Hi, @ce94, sorry for the slow reply here. We've updated the chat UI in VSC to make it easier to add/remove context (if there's nothing `@-mentioned` in the input, Cody won't read any context). I'd love to hear what you think!
