### ISSUE TITLE
bug: Invalid value for autocomplete.advanced.model: llama-code-13b. Valid values are: , starcoder-16b, starcoder-7b

### ISSUE THREAD

**Issue by rfluck** [sourcegraph/cody#4687]
### Version

v1.22.4

### Describe the bug

my auto complete is not working.  I do not have llama-code in my json settings.  I have uninstalled cody multiple times and this will not resolve.  I continue to get this error message.  The only thing functioning is the cody chat.

There has to be something in a cache file somewhere since it is loaded with all my settings on a fresh install.

### Expected behavior

autocomplete should be working without an error.  It will not currently complete a single line of code.  This is not working at all.

**Comment by justinmilner1** [comment]
@rfluck I see you mentioned llama-code isn't in your json settings, but for debugging purposes, what are your 'cody.autocomplete.advanced.model' and 'cody.autocomplete.advanced.provider' values set as?

If you manually set the values to the following in the settings json, does it work?
```
    "cody.autocomplete.advanced.model": "starcoder-7b",
    "cody.autocomplete.advanced.provider": "fireworks", 
```

**Comment by rfluck** [comment]
Hi Justin thank you for reaching out.

I did solve this issue.  The problem was that the json was being saved in my workspace configuration.  So when the resource was removed from Cody, it was still being called by my workspace.

I am now leaving settings blank for the most part in Cody since these can be unsupported at any time.


Thanks!



Rich Fluck | Data Analyst

Tipperary Sales, Inc. d.b.a. La-Z-Boy Furniture Galleries®

729 Paragon Way, Rock Hill Sc. 29730

Phone: 980-201-3340<tel:980-201-3340> Ext: 93803

Email:  ***@***.******@***.***>

***@***.***> | Website<http://www.lazboysoutheast.com/> | Facebook<https://www.facebook.com/LazboySoutheast/>



________________________________
