### ISSUE TITLE
bug: runtime install of external packages bypasses proxy settings

### ISSUE THREAD

**Issue by MAFulator** [sourcegraph/cody#4689]
### Version

v1.23.1719415066 (pre-release)

### Describe the bug

Every time vscode launches with the cody extension,  the following popup in notifications:

```
Failed to download symf: AxiosError: Request failed with status code 400

Failed to download bfg from URL https://github.com/sourcegraph/bfg/releases/download/v5.4.6040/bfg-linux-x64.zip: AxiosError: Request failed with status code 400
```

### Expected behavior

Startup without errors.

### Additional context

Platform:  x86_64+Fedora-39.0

Most likely the problem is that the downloads of 'symf' and 'bfg' are bypassing all proxy settings, because I do not see the http requests in the proxy logs. 
All proxy settings (system, vscode proxy settings, and http_proxy env vars) are pointing to the same proxy server.
I am certain the proxy is working because I can see the copious requests from cody  e.g. 
```
2024-06-27 01:29:36.125 7f364ea906c0 Request: sourcegraph.com:443/
```
in the logs. Also cody would not work at all if the proxy was misconfigured.
These download operations should obey the same proxy settings as cody.

**Comment by vanmartin** [comment]
I am also experiencing this exact behaviour when using the plugin behind a proxy.
