### ISSUE TITLE
Cody codebase doesn't detect the forked repo name

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#47]
As Cody 0.0.9 version has been released, which has the new features to autodetect codebase from the git clone URL, but it missed these two cases when it should work to detect the URL:
1. It doesn't detect the codebase name for the forked repo clone.
2. Many users have multiple Github accounts, so their GitHub hostnames are different per the ssh config.

#### Expected behaviour:
It should detect codebase settings for these cases too.

#### Actual behaviour:
It just says the codebase was not detected for the forked repo clone with a different hostname than Github.

**Comment by jdorfman** [comment]
Going to close this out. Feel free to reopen.
