### ISSUE TITLE
feedback: support for Code - OSS

### ISSUE THREAD

**Issue by SamEdwardes** [sourcegraph/cody#4708]
### Version

1.24.0

### Areas for Improvement

- [ ] UI/UX
- [X] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [X] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

I am using a fork of VS Code (Code - OSS Version: 1.90.0). I can install the Cody extension from Open VSX (https://open-vsx.org/extension/sourcegraph/cody-ai). When I try to login with GitHub, after logging in the browser tries to direct me to the "official" VS Code installed on my computer.

Is there a way I can get this working with my fork?

### Describe the solution you'd like to see

Support for forks of VS Code.

**Comment by SamEdwardes** [comment]
Remove stale

**Comment by jdorfman** [comment]
Hey @SamEdwardes try logging in with a token:

Generate the token/key: https://sourcegraph.com/user/settings/tokens
URL to use: https://sourcegraph.com

LMK if that works or not.

<img width="360" alt="Zight 2024-09-06 at 8 25 22 AM png" src="https://github.com/user-attachments/assets/b84a379f-e1b9-4139-a2e7-feb11bdc19f6">

**Comment by SamEdwardes** [comment]
Thank you I will give this a try.

**Comment by jdorfman** [comment]
Sounds good. Feel free to close if it works :)

**Comment by SamEdwardes** [comment]
Thank you @jdorfman. I tried today with an access token and it worked!
