### ISSUE TITLE
bug: Chat 'Pop-Out' opens an existing Chat with empty transcript

### ISSUE THREAD

**Issue by PriNova** [sourcegraph/cody#4734]
### Version

9b042b6c

### Describe the bug

When using the 'Pop Out' button ![Screenshot 2024-07-01 101410](https://github.com/sourcegraph/cody/assets/31413214/1e3c7f77-7d74-4af3-9d14-770b39a23d80) in a Cody chat with a transcript, the popped-out chat opens but the transcript does not. The title remains intact. After closing the pop-out window, it reopens in the editor view, also without the transcript.

### Expected behavior

I anticipate that the transcript will remain in the newly opened pop-out window.

**Comment by umpox** [comment]
This is likely due to "technical limitations" in VS Code: https://code.visualstudio.com/updates/v1_88#_custom-labels-for-open-editors:~:text=Note%3A%20due,the%20first%20time.

We need to somehow detect the window has become floating, and then restore the state of the chat.
