### ISSUE TITLE
bug: Move chat to sidebar disappearing chat

### ISSUE THREAD

**Issue by ksjogo** [sourcegraph/cody#4790]
### Version

1.4.21 Prerelease

### Describe the bug

New chats open automatically in an Editor view.
Clicking the "Move Chat to Sidebar" button hides the current chat, but it doesn't get opened in the sidebar.

### Expected behavior

Chat gets opened in sidebar.
Some configuration option to open new chats in sidebar.

**Comment by umpox** [comment]
cc @beyang

**Comment by beyang** [comment]
Please reopen if this is still an issue.
