### ISSUE TITLE
VS Code: Commands can only be executed using default "Claude 3 Sonnet" LLM for Free users.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#4799]
### Version

v1.24.2

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Free user
3. Open Cody and set LLM to `Gemini 1.5 Pro`
4. Open source code file, right click to open context menu
5. Choose "Cody > Explain Code" command

### Observed behavior:
Command executed using `Claude 3 Sonnet` instead of `Gemini 1.5 Pro` LLM

### Expected behavior

Command should be executed using the LLM of user choice.

### Additional context

**Note:** 
This issue does not repro for `Pro` user.

**Video link:**
https://drive.google.com/file/d/1eOeoaB92C4Yb4hY9q842UI090FHuxCds/view?usp=drive_link

**Comment by justinmilner1** [comment]
@jay-fibi I took a look into this. You can actually set the default model for right click commands via the edit alt+k menu. 
Ex: if you select gpt-4o as your model, now when you use right-click-> explain cody, it will utilize gpt-4o.
![Screenshot from 2024-07-23 14-42-11](https://github.com/user-attachments/assets/b2c9b978-f025-4b20-b068-282230b103eb)

I agree it's pretty confusing - there should probably be a more visible method for setting the default model for commands.
One thought is to add a button in the commands sidebar section (either as a gear icon in the heading or as a dropdown item)
![Screenshot from 2024-07-23 14-50-12](https://github.com/user-attachments/assets/1bce3a8b-a522-426b-a234-63385e5b089d)
