### ISSUE TITLE
Cody can't reply when using local sourcegraph instance. `completions.stream` returns 500

### ISSUE THREAD

**Issue by giuscri** [sourcegraph/cody#48]
- **Sourcegraph version:** 2023.03.23+209542.7216ba 
- **Platform information:** macOS 13.2.1, Intel 

#### Steps to reproduce:

1. Configure the VSCode Cody extension to use http://127.0.0.1:3080 and sign-in using an Access Token
2. Send a text message to the Cody chat

#### Expected behavior:
Cody should reply

#### Actual behavior:
Cody prompt blinks indefinitely without any reply being shown. Specifically the console shows
```
1681983532763420000	ERROR	external.http	trace/httptrace.go:256	github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1	unexpected status code 500	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "ip-172-20-10-2.eu-west-1.compute.internal"}, "Attributes": {"route_name": "completions.stream", "method": "POST", "url": "/.api/completions/stream", "code": 500, "duration": 0.001208606, "shouldTrace": false, "user": 1}}
``` 
<details>
<summary>Full console logs</summary>
Thu Apr 20 11:23:06 CEST 2023 CONTROL START
✱ Sourcegraph App version: 2023.03.23+209542.7216ba
[31;43;1m|------------------------------------------------------------------------------|[0m
[0m[31;43;1m| Docker is unavailable                                                        |[0m
[0m[31;43;1m|------------------------------------------------------------------------------|[0m
[0m[31m[31;43;1m|[0m Sourcegraph is better when Docker is available; some features may not work:  [31;43;1m|[0m[0m
[0m[31m[31;43;1m|[0m                                                                              [31;43;1m|[0m[0m
[0m[31m[31;43;1m|[0m - Batch changes                                                              [31;43;1m|[0m[0m
[0m[31m[31;43;1m|[0m - Symbol search                                                              [31;43;1m|[0m[0m
[0m[31m[31;43;1m|[0m - Symbols overview tab (on repository pages)                                 [31;43;1m|[0m[0m
[0m[31m[31;43;1m|[0m                                                                              [31;43;1m|[0m[0m
[0m[31;43;1m|------------------------------------------------------------------------------|[0m
[0mtmpfriend.go:95: tmpfriend: Removing /tmp/.searcher.tmp/tmpfriend-68269-3098070499
1681982594592317000	ERROR	service	run/util.go:47	github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/run.newQueueTelemetryOptions	Failed to get docker version	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "ip-172-20-10-2.eu-west-1.compute.internal"}, "Attributes": {"error": "'docker version -f {{.Server.Version}}': : exec: \"docker\": executable file not found in $PATH"}}
1681982594595032000	ERROR	service	run/util.go:47	github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/run.newQueueTelemetryOptions	Failed to get docker version	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "ip-172-20-10-2.eu-west-1.compute.internal"}, "Attributes": {"error": "'docker version -f {{.Server.Version}}': : exec: \"docker\": executable file not found in $PATH"}}

[38;5;15m   [38;5;244m                [38;5;131m╓[38;5;166m╦╬╬╬╦[38;5;131m╖
[38;5;131m[38;5;15m   [38;5;244m               [38;5;166m╬[38;5;202m╬╬╬╬╬╬╬╬
[38;5;202m[38;5;15m   [38;5;244m              [38;5;131m╞[38;5;202m╬╬╬╬╬╬╬╬╬[38;5;166m╬           [38;5;97m╓[38;5;128m╦╦╦╦[38;5;97m┐
[38;5;97m[38;5;15m   [38;5;244m               [38;5;202m╬╬╬╬╬╬╬╬╬╬[38;5;131m╕        [38;5;128m╔[38;5;129m╪╪╪╪╪╪╪╪[38;5;134m╕
[38;5;134m[38;5;15m   [38;5;244m               [38;5;131m╘[38;5;202m╬╬╬╬╬╬╬╬╬╬      [38;5;128m╔[38;5;129m╪╪╪╪╪╪╪╪╪╪╪
[38;5;129m[38;5;15m   [38;5;244m                [38;5;166m╬[38;5;202m╬╬╬╬╬╬╬╬╬[38;5;166m╗   [38;5;134m╔[38;5;129m╪╪╪╪╪╪╪╪╪╪╪╪[38;5;134m┘
[38;5;134m[38;5;15m   [38;5;244m   [38;5;67m╓[38;5;74m╦[38;5;38m╦╖[38;5;67m┐         [38;5;202m╬╬╬╬╬╬╬╬╬╬ [38;5;134m╔[38;5;129m╝╪╪╪╪╪╪╪╪╪╪╪[38;5;128m╜
[38;5;128m[38;5;15m   [38;5;66m [38;5;38m╬[38;5;39m╪╪╪╪╪╪╪╪╬[38;5;38m╗╦[38;5;67m╖   [38;5;166m╠[38;5;202m╬╬╬╬╬╬╬╬[38;5;126m╝[38;5;129m╪╪╪╪╪╪╪╪╪╪╪╪[38;5;128m╜
[38;5;128m[38;5;15m   [38;5;38m╠[38;5;39m╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪[38;5;31m╝[38;5;23m╝[38;5;238m╬[38;5;94m╬[38;5;130m╬[38;5;166m╬[38;5;125m╝[38;5;129m╪╪╪╪╪╪╪╪╪╪╪╪[38;5;128m╜
[38;5;128m[38;5;15m   [38;5;67m└[38;5;39m╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪[38;5;32m╪[38;5;26m╪╪[38;5;56m╪╪[38;5;129m╪╪╪╪╪╪[38;5;128m╩
[38;5;128m[38;5;15m   [38;5;244m  [38;5;38m╙╩[38;5;39m╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪[38;5;32m╪[38;5;26m╪╪[38;5;61m╖
[38;5;61m[38;5;15m   [38;5;244m       [38;5;67m└[38;5;38m╙╩[38;5;39m╬╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╬[38;5;38m╦[38;5;74m╗[38;5;67m┐
[38;5;67m[38;5;15m   [38;5;244m              [38;5;73m╙[38;5;38m╜[38;5;32m╪[38;5;39m╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪[38;5;38m╗╦[38;5;73m╖
[38;5;73m[38;5;15m   [38;5;244m              [38;5;97m┌[38;5;129m╬╪╪[38;5;93m╪[38;5;56m╪╪[38;5;26m╪[38;5;32m╪[38;5;39m╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╬
[38;5;39m[38;5;15m   [38;5;244m            [38;5;97m┌[38;5;128m╗[38;5;129m╪╪╪╪╪╪╪╪╪╪╪[38;5;92m╪[38;5;239m╬[38;5;238m╬[38;5;24m╬[38;5;31m╪[38;5;39m╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪
[38;5;39m[38;5;15m   [38;5;244m          [38;5;97m┌[38;5;128m╗[38;5;129m╪╪╪╪╪╪╪╪╪╪╪╪[38;5;126m╬[38;5;166m╬[38;5;202m╬╬╬╬╬[38;5;166m╬[38;5;95m╬ [38;5;73m╙[38;5;38m╜╩[38;5;39m╪╪╪╪╪╪╪╪╪╪╪╪[38;5;38m╜
[38;5;38m[38;5;15m   [38;5;244m        [38;5;97m┌[38;5;128m╦[38;5;129m╪╪╪╪╪╪╪╪╪╪╪╝[38;5;133m╙[38;5;166m╬[38;5;202m╬╬╬╬╬╬╬╬╬       [38;5;67m└[38;5;38m╙╩[38;5;39m╬╪╪╝[38;5;38m╜
[38;5;38m[38;5;15m   [38;5;244m       [38;5;128m╦[38;5;129m╪╪╪╪╪╪╪╪╪╪╪╪[38;5;134m┘  [38;5;166m╠[38;5;202m╬╬╬╬╬╬╬╬╬[38;5;166m╬
[38;5;166m[38;5;15m   [38;5;244m      [38;5;129m╬╪╪╪╪╪╪╪╪╪╪╪[38;5;134m┘     [38;5;202m╬╬╬╬╬╬╬╬╬╬[38;5;131m┐
[38;5;131m[38;5;15m   [38;5;244m      [38;5;128m╙[38;5;129m╪╪╪╪╪╪╪╪╪[38;5;128m╜       [38;5;131m╘[38;5;202m╬╬╬╬╬╬╬╬╬╬
[38;5;202m[38;5;15m   [38;5;244m       [38;5;97m└[38;5;128m╩[38;5;129m╪╪╪╪╝[38;5;134m╙          [38;5;166m╬[38;5;202m╬╬╬╬╬╬╬╬╬[38;5;166m╕
[38;5;166m[38;5;15m   [38;5;244m                         [38;5;137m└[38;5;202m╬╬╬╬╬╬╬╬╬[38;5;131m╛
[38;5;131m[38;5;15m   [38;5;244m                           [38;5;166m╩[38;5;202m╬╬╬╬╬[38;5;166m╬[38;5;131m┘

[30;42;1m|------------------------------------------------------------------------------|[0m
[0m[30;42;1m|                                                                              |[0m
[0m[30;42;1m| Sourcegraph is now available on http://127.0.0.1:3080                        |[0m
[0m[30;42;1m|                                                                              |[0m
[0m[30;42;1m|------------------------------------------------------------------------------|[0m
1681982930390430000	ERROR	external.http	trace/httptrace.go:256	github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1	unexpected status code 500	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "ip-172-20-10-2.eu-west-1.compute.internal"}, "Attributes": {"route_name": "completions.stream", "method": "POST", "url": "/.api/completions/stream", "code": 500, "duration": 0.000931706, "shouldTrace": false, "user": 1}}
1681982965598543000	ERROR	external.http	trace/httptrace.go:256	github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1	unexpected status code 500	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "ip-172-20-10-2.eu-west-1.compute.internal"}, "Attributes": {"route_name": "completions.stream", "method": "POST", "url": "/.api/completions/stream", "code": 500, "duration": 0.001190306, "shouldTrace": false, "user": 1}}
1681983463481786000	ERROR	external.http	trace/httptrace.go:256	github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1	unexpected status code 500	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "ip-172-20-10-2.eu-west-1.compute.internal"}, "Attributes": {"route_name": "completions.stream", "method": "POST", "url": "/.api/completions/stream", "code": 500, "duration": 0.001041789, "shouldTrace": false, "user": 1}}
1681983510668692000	ERROR	external.http	trace/httptrace.go:256	github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1	unexpected status code 500	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "ip-172-20-10-2.eu-west-1.compute.internal"}, "Attributes": {"route_name": "completions.stream", "method": "POST", "url": "/.api/completions/stream", "code": 500, "duration": 0.00109827, "shouldTrace": false, "user": 1}}
1681983532763420000	ERROR	external.http	trace/httptrace.go:256	github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1	unexpected status code 500	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "ip-172-20-10-2.eu-west-1.compute.internal"}, "Attributes": {"route_name": "completions.stream", "method": "POST", "url": "/.api/completions/stream", "code": 500, "duration": 0.001208606, "shouldTrace": false, "user": 1}}
1681983653689596000	ERROR	external.http	trace/httptrace.go:256	github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1	unexpected status code 500	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+209542.7216ba", "service.instance.id": "ip-172-20-10-2.eu-west-1.compute.internal"}, "Attributes": {"route_name": "completions.stream", "method": "POST", "url": "/.api/completions/stream", "code": 500, "duration": 0.000850368, "shouldTrace": false, "user": 1}}
Thu Apr 20 11:43:29 CEST 2023 CONTROL KILLING sourcegraph process 68438
Thu Apr 20 11:43:29 CEST 2023 CONTROL KILLING embedded postgres instance
"/Users/g.crino/Library/Application Support/sourcegraph-sp/postgresql/bin/bin/pg_ctl" stop -w -D "/Users/g.crino/Library/Application Support/sourcegraph-sp/postgresql/data" -m immediate
Thu Apr 20 11:43:29 CEST 2023 CONTROL END
</details>

**Comment by jdorfman** [comment]
Hi @giuscri I know this is from a while back, but we made big changes to getting authenticated. Going to close this out but feel free to reopen. Thanks
