### ISSUE TITLE
VS Code: New "Shot Diff" is marking the code snippet incorrectly and causing confusion.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#4800]
### Version

v1.24.2

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Free/Pro user
3. Open a source code file and right click
4. Choose "Cody > Edit Code" and ask `generate document` and hit enter
5. Wait for Cody to change the code and check the diff status

### Observed behavior:
The diff is marked incorrectly and causing confusion.

### Expected behavior

The diff should correctly highlight the changed area.

### Additional context

**Video link:**

https://drive.google.com/file/d/1zXNQonrS-9A2jI1I3eDllX1fMos2akwz/view?usp=drive_link

**Comment by umpox** [comment]
Thanks for raising @jay-fibi. It looks like the diff is technically correct, but the LLM is wrong as it tries to replace the whole function with a new class.

Could you try with Claude 3.5 Sonnet, we have noticed it is much better with this kind of tasks, or possibly with improved instructions. 

I'm updating the default to 3.5 in [this PR](https://github.com/sourcegraph/cody/pull/4806), and will look at any prompt improvements we can make on our side separately

**Comment by jay-fibi** [comment]
Sure @umpox I will re-test once the PR gets merged.
