### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by XXGOJISXX** [sourcegraph/cody#4801]
- Issue Type: `Performance`
- Extension Name: `cody-ai`
- Extension Version: `1.24.2`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.91.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Orsen/AppData/Local/Temp/sourcegraph.cody-ai-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by vadi2** [comment]
@XXGOJISXX you seem to have missed attaching the file in question, want to upload it?

**Comment by XXGOJISXX** [comment]
hello my computer is a 4070ti i91300 32gb 2tb but it goes to like 4000
memory in the red its weird not all the time but mayb i got to much windows
open on vcs but anyways please help me sign in with cody sourcegraph i paid
for 2 subscriptions and cant get it to work idk whats up with it i tried
for days still trying....
