### ISSUE TITLE
bug: custom command "enclosed between the <OUTPUT0412> tags" output not visible

### ISSUE THREAD

**Issue by awesomebytes** [sourcegraph/cody#4819]
### Version

1.91.0

### Describe the bug

I tried to make my first custom command, with the idea to put a python script in there later on that grabs some data and makes a nice prompt-friendly format for it for the context:
```json
{
  "testcmd": {
    "prompt": "Given the context, provide a useful answer referring to the part of the context that references it",
    "context": {
      "selection": false,
      "command": "uname -a"
    },
    "mode": "ask"
  }
}
```

The response from Sonnet 3.5 states: "Based on the output from the `uname -a` command, which is enclosed between the `<OUTPUT0412>` tags, we can infer the following:"
However, this `<OUTPUT0412>` bit is nowhere to be seen (so if I would like to debug if my future script is doing what it's supposed to do, I wouldn't be able to).

Clicking on the blue `\uname -a` file-button-icon shows "The editor could not be opened because the file was not found." as seen in the following screenshot:

![Uploading command_output_not_viewable.png…]()

I cannot find the output anywhere. I tried on mouse-over, finding a temp file, I asked sonnet a follow up question about it:
"show me the <OUTPUT0412> tags and contents, also tell me where this is stored"

Answer (including the empty space):
```
The <OUTPUT0412> tags and their contents are:

This output is typically stored in the system's memory or cache when the uname -a command is executed. The uname command retrieves information about the current system, and the -a option stands for "all", which displays a comprehensive set of system details.
```

### Expected behavior

I expected to be able to inspect the output of the shell command I have executed. As stated by the response prompt with the `<OUTPUT0412>` tag.

**Comment by awesomebytes** [comment]
I don't think I can 'un-stale' the issue.

**Comment by PriNova** [comment]
@awesomebytes Since the terminal commands are executed internally, there is no other visual indication as the context file item in the context list.

We are moving away from custom commands to the Prompt Library: https://sourcegraph.com/prompts

Thank you
