### ISSUE TITLE
bug: Cannot send git command Custom Commands

### ISSUE THREAD

**Issue by Overload119** [sourcegraph/cody#4830]
### Version

2024-07-05, 08:53:08

### Describe the bug

Context is not being included. It's being exluded for some reason.

![screenshot 2024-07-10 at 12 34 43@2x](https://github.com/sourcegraph/cody/assets/1012072/bb62dfc0-fae3-4c67-b12b-e2f7bd92906e)

My repo:

.cody/ignore
```
sorbet/
spec/fixtures/
public/packs/
```

### Expected behavior

It should be included

**Comment by abeatrix** [comment]
If you hover over the link it should say the file/output was too large to be included. In this case, breaking the commit into smaller parts could help. You can also try only include the files that's more relevant to generate the commit message first before staging all the files 😃

**Comment by Overload119** [comment]
In that case maybe the bug is that it didn't actually say that - I hovered over it. I will reproduce on Monday and follow up.

**Comment by Overload119** [comment]
https://github.com/user-attachments/assets/c854783e-80e1-4360-8c8f-d7e69a8844f6

That did indeed seem to be the error! but as you can see, it did not show me a tooltip on why.
