### ISSUE TITLE
bug: Cody (engine) seems to be locking git files causing git command to fail

### ISSUE THREAD

**Issue by eamodio** [sourcegraph/cody#4869]
### Version

v1.26.2

### Describe the bug

Cody (engine) seems to be locking files in the `.git` folder, specificially `packed-refs` which is causing issue when trying to delete branches, gc, etc

### Expected behavior

Cody should not lock `.git` files

**Comment by jdorfman** [comment]
Hey @eamodio thanks for reporting. I will make sure the product team sees this in the weekly community feedback report.

**Comment by eamodio** [comment]
I still see this, though far less frequently than before. But it causes me to have to regularly disable Cody.
