### ISSUE TITLE
Image Upload Feature for Cody Extension

### ISSUE THREAD

**Issue by FisherKeyBr** [sourcegraph/cody#4893]
### Description:

We are trying to solve the problem of users having to switch between multiple platforms to upload images and get AI assistance in implementing designs. Currently, users need to use external sites to upload images of prototypes or designs before they can ask AI to implement them. This process is inefficient and disrupts the workflow.

### Objectives:

The end goal is to integrate an image upload feature directly into the Cody extension. This will allow users to seamlessly upload design images and prototypes within the same environment where they're working with the AI, streamlining the process of turning designs into code.

### Acceptance Criteria:

Users can upload image files (JPG, PNG, GIF) directly through the Cody extension interface.
Uploaded images are immediately available for reference in conversations with Cody.
Users can easily link or reference uploaded images in their prompts to Cody.
The extension supports multiple image uploads in a single session.
Uploaded images are securely stored and accessible only to the user who uploaded them.
The extension provides a simple way to manage (view, delete) uploaded images.
Image upload feature is intuitive and doesn't disrupt the existing workflow.
The feature works consistently across all supported IDEs and platforms where Cody is available.

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

**Comment by adilheartin** [comment]
I'm surprised that this issue was marked stale and still not much activity here. I'm using Cody since 2 months and there have been so many instances where I had to switch to the Claude website or Chat GPT app to upload my screenshots. I wish if image upload feature could be implemented soon.

**Comment by Ma-nav** [comment]
Same - wish for screenshot feature ASAP!!

**Comment by miPwn** [comment]
What the hell this is essential

**Comment by nishu3210** [comment]
When will it come? Without this it’s hard to explain html code :(

**Comment by mazmaa** [comment]
By now Cody is for me not usable w/o this feature. At least I wanted to place this here before leaving.
