### ISSUE TITLE
VS Code: Error occurred while running command for Enterprise account

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#4899]
### Version

v1.26.3

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Enterprise user
3. Perform `Explain Code` command for any file

### Observed behavior: 
Error occurred and command failed to run.
```
Request to https://sg02.sourcegraphcloud.com/.api/completions/stream?client-name=vscode&client-version=1.26.3 failed with 400 Bad Request: unsupported chat model "undefined/undefined" (default "anthropic::2023-06-01::claude-3-sonnet_cg")
```

### Expected behavior

Command should run without any error.

### Additional context

**Screenshot:**

<img width="536" alt="Screenshot 2024-07-17 at 2 53 33 AM" src="https://github.com/user-attachments/assets/aa3484ed-fffc-471a-898b-ac65253c1ff8">

**Comment by taylorsperry** [comment]
Created Linear issue https://linear.app/sourcegraph/issue/CODY-2898/vs-code-error-occurred-while-running-command-for-enterprise-account
