### ISSUE TITLE
bug: Offline mode not available

### ISSUE THREAD

**Issue by PriNova** [sourcegraph/cody#4922]
### Version

commit 0731d28

### Describe the bug

The button to use Cody in offline mode like described here #4691 does not appear.

### Expected behavior

I expected to see using Cody in Offline mode with Ollama.

### Additional context

![Screenshot 2024-07-18 133951](https://github.com/user-attachments/assets/76b31f53-9dcd-4205-903c-0184391edbbb)

Current welcome screen in Offline mode.

I'm on Ubuntu 22.04 in WSL.

Version: 1.92.0-insider (user setup)
Commit: 4a103b0eea7de96d12fc2cbada846ca7ef4f1298
Date: 2024-07-17T05:03:59.373Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26120

**Comment by nviraj** [comment]
Facing this as well. Installed for the first time and there seems to be no way to use it locally without signing up.

**Comment by ibrykov-mdsol** [comment]
Same here. Using it on Mac OS
