### ISSUE TITLE
bug: ⌥ + L opens new chat instead of adding an @

### ISSUE THREAD

**Issue by im-fabian** [sourcegraph/cody#4945]
### Version

Version: 1.91.1 (Universal) Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729

### Describe the bug

When I hit ⌥ + L  a new cody chat is opened instead of a @ being added into a chat for adding context.

### Expected behavior

A @ should be added .

**Comment by bdnk** [comment]
I added 
```
{
    "key": "alt+l",
    "command": "cody.chat.newEditorPanel",
    "when": "cody.activated && editorTextFocus" 
} 
```
to my keybindings.json and it worked again. 

Though I'm not entirely sure why since it's the default keybind, so your mileage may vary.
