### ISSUE TITLE
feedback: Please provide command to show most recent chat

### ISSUE THREAD

**Issue by smojef** [sourcegraph/cody#4946]
### Version

v1.26.5

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [X] Chat
- [X] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

I found no way of brigning the last chat window into view with a shortcut.
There is a `Cody: New Chat` command, but this always create a new conversation with the chatbot.
Therefore, the ALT+L shortcut always create a new chat, which loses context and adds friction to the experience.

### Describe the solution you'd like to see

I want a `Cody: Show Last Chat` command that I can remap to the ALT+L shortcut.
This command should open the most recent chat window if it is closed or bring it into view if it is already open.
If no chat exists in history, then create a new one.

### Describe any alternatives that could be considered

By default ALT+L should show last chat instead of creating a new one.

**Comment by jiri-bajer** [comment]
Try the `Cody: Focus on Chat View` command (`cody.chat.focus`) -- in my case it shows the last chat in the left sidebar. I mapped it to Ctrl+Shift+K and it works for me. The sidebar is terribly thin but that's another issue...
