### ISSUE TITLE
bug: Extension always says downloading symf and bfg; never updates the search index

### ISSUE THREAD

**Issue by ned-pcs** [sourcegraph/cody#5000]
### Version

v1.26.7

### Describe the bug

Every time I start up VS Code, I see notifications that Cody is downloading `bfg` and `symf`, and that it is updating the search index.
However, these notifications never go away.
![Screenshot from 2024-07-24 11-40-43](https://github.com/user-attachments/assets/9412d518-3d31-48ca-860a-fc04696179bf)

### Expected behavior

I expect the downloads to complete and the search index to be updated.

### Additional context

Here's the output from Cody:
```
█ telemetry-v2: recordEvent: cody.extension/savedLogin 
█ AuthProvider:init:lastEndpoint: Token recovered from secretStorage https://sourcegraph.com/
█ GraphQLTelemetryExporter: evaluated export mode: 5.2.5+
█ openctx: OpenCtx is enabled in Cody
█ featureflag: refreshed
█ SymfRunner: unsafeEnsureIndex file:///home/ned/PCS/Pyrenees/Chihuahua-Firmware
█ LocalEmbeddingsController: constructor
█ symf: downloading symf from https://github.com/sourcegraph/symf/releases/download/v0.0.12/symf-x86_64-linux-musl.zip
█ ContextFiltersProvider: setContextFilters 
█ ChatManager:constructor: init has local embeddings controller
█ ChatPanelsManager:constructor: init
█ LocalEmbeddingsController: start
█ CodyEngineService: constructor
█ LocalEmbeddingsController: start
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatus [{"displayName":"Chihuahua-Firmware","providers":[{"kind":"embeddings","state":"indeterminate","embeddingsAPIProvider":"sourcegraph"}]}]
█ RepoNameResolver:getCodebaseFromWorkspaceUri: error 
█ SimpleChatPanelProvider: postContextStatus [{"displayName":"Chihuahua-Firmware","providers":[{"kind":"embeddings","state":"indeterminate","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"indexing"}]}]
█ CodyEngine: downloading bfg from https://github.com/sourcegraph/bfg/releases/download/v5.4.6040/bfg-linux-x64.zip
█ ClientConfigSingleton: refreshing configuration
█ ClientConfigSingleton: refreshed {"codyEnabled":true,"chatEnabled":true,"autoCompleteEnabled":true,"customCommandsEnabled":true,"attributionEnabled":false,"smartContextWindowEnabled":true,"modelsAPIEnabled":false}
█ CodyCompletionProvider:initialized: fireworks/deepseek-coder-7b
█ UpstreamHealth: Ping took 1068ms (Gateway: 978ms) 
█ SimpleChatPanelProvider: postContextStatus [{"displayName":"Chihuahua-Firmware","providers":[{"kind":"embeddings","state":"indeterminate","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"indexing"}]}]
```

**Comment by ned-pcs** [comment]
I have tried uninstalling and reinstalling the extension.

**Comment by jdorfman** [comment]
Thanks @ned-pcs I will let the product team know now. How large is the repo (files and size)

**Comment by ned-pcs** [comment]
My `~/.config/Code/User/workspaceStorage` directory does not include a `sourcegraph.cody-ai` directory. All of its directories have hex names. And none of those directories include a `symf` or `cody-engine` directory.

**Comment by RXminuS** [comment]
Ok, I think I have something. For some reason the version naming scheme seems to have changed. I'm investigating now

**Comment by RXminuS** [comment]
Ok, that's great. You are correct that it's the `globalStorage` directory; I mixed it up when looking up the linux directory online (I'm on macOS). Thanks for taking the time to get those details regardless, it helps a lot!

The process for downloading looks like this:
1. Check if the correct version exists
2. Have processes race to make a .lock file so nobody else is downloading at the same time (we've eliminated that this has become stale causing the issue ✅ )
4. Download release from GitHub to .tmp dir
5. Unpack the binary in the zip to a file named the same as the lockfile but without the `.lock`

So if we now first check if there's a zip file inside the `.tmp` dir we can see if there's a problem with the downloading or the unpacking. Could you check this?

If there are zip files in there we can verify they're the same as if manually downloaded from `https://github.com/sourcegraph/bfg/releases/download/v5.4.6040/bfg-linux-x64.zip` and `https://github.com/sourcegraph/symf/releases/download/v0.0.12/symf-x86_64-linux-musl.zip`

If they are, then we can verify if installing them manually resolves things. You can do this by unzipping the archive and copying the contents to the directory where the lockfiles are. Then you rename the binary to match the lockfile name (without `.lock`), remove the lockfile and tmp dir, and restarting VSCode. If that works then there's some problem in unpacking these archives.

In the meantime I'll make sure to add some better error handling / reporting on these downloads

**Comment by RXminuS** [comment]
I also just noticed in the download code https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/local-context/download-symf.ts?L113-171 that I added a different message for when it's extracting vs. downloading. 

Given that the image you sent shows "downloading" I'm guessing that for whatever reason https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/local-context/utils.ts?L38-49 isn't getting resolved.

I'm looking into why we're not receiving a `finish` signal.

**Comment by ned-pcs** [comment]
OK, after clearing out the `cody-engine` and `symf` dirs and restarting VS Code, I see no trace of `bfg` in the `cody-engine` dir. However,  there are _partial_ `cody-engine` and `symf` zip files there:
```
536768 Jul 25 09:03 ./cody-engine/cody-engine-5.4.6040-linux-x64.tmp/cody-engine-5.4.6040-linux-x64.zip
278201 Jul 25 09:03 ./symf/symf-v0.0.12-x86_64-linux.tmp/symf-v0.0.12-x86_64-linux.zip
```
I don't have the download link for the `cody-engine` zip file; I could try unpacking that plus the `bfg` zip in the `cody-engine` dir, and the `symf` zip in the `symf` dir if that's what is needed.

**Comment by ned-pcs** [comment]
> Thanks @ned-pcs I will let the product team know now. How large is the repo (files and size)

This is a repo containing submodules; most of the files are not of interest, but overall there are:
```
53290 C files
4369 Python files
2173 Javascript files
as well as a number of miscellaneous binary blobs, documents, and other things.
```
I don't see how to limit the scope of the search.

**Comment by RXminuS** [comment]
Ok I think the indexing is separate from the downloading / installation issue. I'll create a separate internal issue for it so we can get the right people looking at that one.

For the downloading; I think the issue might be that for some reason the previous request might have gotten interrupted and there were partial files left that prevented writing. This could maybe happen if VSCode restarted right as it was downloading. Alternatively...did you at any point start VSCode as `sudo`? I'll need to dig a little deeper to form a bit more solid theory.

The "cody-engine" is this file https://github.com/sourcegraph/symf/releases/download/v0.0.12/symf-x86_64-linux-musl.zip , it's just named differently. And although it will check for the latest versions every time you open Cody it won't re-download it if it's already available.
