### ISSUE TITLE
VS Code: Old UI is shown for Enterprise users.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#5086]
### Version

v1.28.1

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Enterprise user
3. Check the Cody UI

### Observed behavior:
Old UI is shown instead of new UI.

### Expected behavior

New UI should be shown for Cody. 
For Free & Pro users, new Cody UI will load correctly. 

### Additional context

Screenshot:

![Enterprise_Old_Chat_UI](https://github.com/user-attachments/assets/6eb55e1c-8771-446f-9efd-6f41bd37efc4)

**Comment by kalanchan** [comment]
new ui is already shipped this is expected
