### ISSUE TITLE
no puedo usar cody en vsc

### ISSUE THREAD

**Issue by Rosi374** [sourcegraph/cody#5109]
### Version

1.92.0

### Describe the bug

no puedo hacer q cody ande en el vsc, me tira q me fije los planes o que me haga pro y yo ya soy pro.

### Expected behavior

esperaba q al pagar para usar cody, se me iba a poner solito pq ya lo tenia instalado el chat en vscode, pero no, me sigue diciendo que me haga PRO o que mire planes y yo acabo de comprar el plan y nada, sigue bloqueado los mjs para chat

### Additional context

nada

**Comment by PriNova** [comment]
Hola @Rosi374 

Por favor, prueba a cerrar e iniciar sesión tanto en VS Code como en el browser.
Si eso no ayuda, vaya a la paleta de comandos en VS Code y busque `Sourcegraph: Switch Account' y utiliza el método URL y Access Token. Utiliza https://sourcegraph.com como URL, pulsa 'return' e introduce el token de acceso en el segundo campo.

Gracias

Please try logging out and logging in in both VS Code and the browser.
If that doesn't help, go to the command palette in VS Code and search for `Sourcegraph: Switch Account' and use the URL and Access Token method. Use https://sourcegraph.com as the URL, hit 'return' and enter the access token in the second field.

Thank you
