### ISSUE TITLE
bug: context doesn't update

### ISSUE THREAD

**Issue by trubear1010** [sourcegraph/cody#5132]
### Version

1.28.1

### Describe the bug

I'm using claude 3.5 sonnet. Cody retains old project context for too long which leads it to believe files that were deleted still exist in the repo. This leads cody to rely too much on cached context when updated context is required and response quality drastically degrades over time.

Tried fixes (none worked):
- Create new chat
- Restart VScode
- Ask chat to forget prior context using natural language

### Expected behavior

Context updates dynamically or at least on scheduled intervals that are no longer than 5 minutes.

### Additional context

Feature request: a CLI command or button to clear context and re-index the workspace.

**Comment by janhartman** [comment]
This should have been fixed in https://github.com/sourcegraph/cody/pull/5135.
