### ISSUE TITLE
bug: Invisible icon on status bar

### ISSUE THREAD

**Issue by LatenPath** [sourcegraph/cody#5136]
### Version

1.30.0

### Describe the bug

In the new version, there is an invisible icon next to Cody icon.

![image](https://github.com/user-attachments/assets/fb9317f7-af3e-48ae-ac90-16df9b7f261f)

Clickable, not show up in right-click menu.
![image](https://github.com/user-attachments/assets/46e30844-313a-4282-a9ee-1a0ccbeffe53)

My VSCode Theme: Catppuccin Mocha.

### Expected behavior

Theme color conflict or icon error. If it's a important setting, then change the tooltip to "OpenCTX enabled/disabled" is better. But, if it just turns on/off an option, then we need to able to hide that icon if we don't need to use it.

**Comment by jdorfman** [comment]
Thanks @LatenPath for reporting. I will make sure the product team sees this in the weekly community feedback report.

**Comment by LatenPath** [comment]
fixed in the version 1.40:
![image](https://github.com/user-attachments/assets/7a3a86a1-898f-4c3f-9609-617bbfb8b5ec)
