### ISSUE TITLE
bug: Request Failed: Connection closed without receiving any events

### ISSUE THREAD

**Issue by Fabryz** [sourcegraph/cody#5152]
### Version

v1.30.1

### Describe the bug

I entered the prompt as usual and added the repository as a context, the message returned was an error: _"Request Failed: Connection closed without receiving any events"._
If I try again I could finally receive the correct response after a while.

### Expected behavior

I expected to receive a response from the AI

### Additional context

![image](https://github.com/user-attachments/assets/ad20861f-60fb-48d8-8c03-200781194bbc)

**Comment by jdorfman** [comment]
Hi @Fabryz this was due to a Claude outage yesterday. Should be good now according to https://status.anthropic.com/

<img width="493" alt="Zight 2024-08-09 at 8 52 30 AM png" src="https://github.com/user-attachments/assets/90400156-e027-4e1f-a764-58e7b7331cfb">

**Comment by PetarBelberov** [comment]
The same is to me:
![image](https://github.com/user-attachments/assets/0514b410-c616-423c-bef1-996dd909d77f)

**Comment by jdorfman** [comment]
Hey @PetarBelberov they are having another issue:

> Investigating - We are currently investigating this issue.

While it is out of our control, we understand your frustration (me personally, I needed to code something this morning). For now, if you could choose a different model, that would be great until they fix the issue.
