### ISSUE TITLE
VS Code: Scrollbar is not shown for LLM Dropdown

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/cody#5176]
### Version

v1.30.3

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Any user
3. Click & Open LLM Dropdown

### Observed behavior:
Scrollbar is not shown for LLM Dropdown

### Expected behavior

Scrollbar should be shown for LLM Dropdown

![Scrollbar not available for LLM dropdown](https://github.com/user-attachments/assets/5eba9115-4192-4dbf-8bcf-7b8729775069)

**Comment by jdorfman** [comment]
Thanks, @RajatNagoria. I will make sure the product team sees this in the weekly community feedback report (today).

**Comment by dominiccooney** [comment]
Is the scrollbar not shown simply because the content is not overflowing?

On main rn, yes, I have a scrollbar when the content overflows and it seems fine.

![Screenshot 2024-08-29 at 18 12 15](https://github.com/user-attachments/assets/fd3ab2b1-72a6-4df2-8b80-dc529b1418bd)

**Comment by jdorfman** [comment]
Thanks @dominiccooney 

@RajatNagoria can you confirm whether this is still an issue?

**Comment by RajatNagoria** [comment]
Closing this issue as it looks fine
