### ISSUE TITLE
bug: Sourcegraph website 524's, rendering Cody unusable

### ISSUE THREAD

**Issue by JeongJuhyeon** [sourcegraph/cody#5180]
### Version

Irrelevant

### Describe the bug

![image](https://github.com/user-attachments/assets/4b9e34bf-af0e-4d22-a5b3-af29eb694682)

`Cloudflare Ray ID: 8b26ae00db458b60`

### Expected behavior

[Sourcegraph status](https://sourcegraphstatus.com/) should show degraded performance

### Additional context

It seems like anything not-static (e.g. that hits SourceGraph's Graphql APIs) fails to respond. Only the purely static pages (like https://sourcegraph.com, https://sourcegraph.com/enterprise) respond.

**Comment by ichim-david** [comment]
@JeongJuhyeon try now, I had the same problem but I was able to login again a few minutes ago. Must of been a short term glitch on Sourcegraph end.

**Comment by JeongJuhyeon** [comment]
@ichim-david Thanks, works now
