### ISSUE TITLE
bug: When edit code only processes one line of code, undo will cause problems

### ISSUE THREAD

**Issue by HangLu123** [sourcegraph/cody#5209]
### Version

latest

### Describe the bug

![image](https://github.com/user-attachments/assets/bcf22e4d-4fa5-4fc0-bc8d-fbe78010da69)

When edit code only processes one line of code, undo will cause problems
![image](https://github.com/user-attachments/assets/e1fcb94d-d5b3-439d-9d75-cf481d4a867d)
![image](https://github.com/user-attachments/assets/dc4a56e2-2fe1-4fdd-bae9-b5d6351abd01)

### Expected behavior

right behavior

**Comment by HangLu123** [comment]
The inserted content is placed on the same line as the next line, and executing undo will not restor

**Comment by umpox** [comment]
Should be fixed by: https://github.com/sourcegraph/cody/pull/5259
