### ISSUE TITLE
bug: commands doesnt work anymore

### ISSUE THREAD

**Issue by SphaeroX** [sourcegraph/cody#5227]
### Version

v1.30.3

### Describe the bug

after i made custom commands in user.json the extension wont be able to run commands (custom and system)

https://github.com/user-attachments/assets/9f348262-196f-4558-9682-5834277e42a1

Error:
```
█ CommandsController:execute: command not found  {
  "commandKey": "API"
}
█ ClientConfigSingleton: refreshed {"codyEnabled":true,"chatEnabled":true,"autoCompleteEnabled":true,"customCommandsEnabled":true,"attributionEnabled":false,"smartContextWindowEnabled":true,"modelsAPIEnabled":false}

```

### Expected behavior

it should work

**Comment by kalanchan** [comment]
hello is this still an issue? if so please reopen and we'll investigate further
