### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by fisforfaheem** [sourcegraph/cody#5321]
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.33.1724426143
- VS Code Version: 1.92.2
- Extension Host: desktop

##  Steps to Reproduce

1.
2.
3.

## Logs

Extension version: 1.33.1724426143
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.23GB free)|
|Process Argv|C:\\Users\\fisfo\\OneDrive\\Documents\\GitHub\\erpfy_pos_app|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by faheemstepsharp** [comment]
![image](https://github.com/user-attachments/assets/8782bdd1-9cc6-45e4-b109-850f937942a2)
 PLEASE TELL wh y its takes wrong context? instead of whole project?? please tell

**Comment by kalanchan** [comment]
hey there, could you route this to the community forum? we'll explain more in detail on how context fetching works!
