### ISSUE TITLE
Cody attributing anothe repo with the repo indexed recently

### ISSUE THREAD

**Issue by anujkumar-df** [sourcegraph/cody#545]
![image](https://github.com/sourcegraph/cody/assets/22525920/db4f1add-863b-457f-98d9-48242256277a)

Where is the association of other repo happening?

**Comment by jdorfman** [comment]
Hi @anujkumar-df thanks for the screenshot. Can you provide us with anything so we can try to reproduce the issue? Which extension are you using? Version number, etc.

**Comment by anujkumar-df** [comment]
I am using Cody App (cody_2023.7.11+1384.7d20a90ce7_amd64) on Linux.
