### ISSUE TITLE
bug: Smart apply suggest code to be applied in project-root/project-root/**/file instead of project-root/**/file

### ISSUE THREAD

**Issue by ichim-david** [sourcegraph/cody#5489]
### Version

1.34.0

### Describe the bug

Smart apply fails in my project as seen in the screenshots I have attached because it tries to pass to the LLM a path that duplicates the project root.
Once that happens applying never goes aways it's always spinning icon with Applying text

### Expected behavior

Path given to the LLM is proper without duplicating the project root

### Additional context

![1-original-file-path](https://github.com/user-attachments/assets/d2d034cb-15a7-40f5-ba21-392f1bc01c06)
![2-wrongly-created-file-path](https://github.com/user-attachments/assets/5640e99b-cab8-46c3-ac85-0fcc9ec51a44)
![3-cody-prompt-text](https://github.com/user-attachments/assets/5d90b41b-89d5-4881-9598-9b05176f069b)

**Comment by ichim-david** [comment]
![uri-handle-smart](https://github.com/user-attachments/assets/0b55a37a-ca89-4b77-a475-dc3d9beecbeb)

@abeatrix the problem comes from this line https://github.com/sourcegraph/cody/blob/main/vscode/src/services/utils/codeblock-action-tracker.ts#L143
If you look at the debug session you will see that fileUri contains the path from the workspace and workspaceUri has the full filesystem path.
The problem is that node path is too stupid to recognize that fileUri contains the folder path (both joinPath and resolvePath from vscode-uri) have the same issues.

I added a removeWorkspaceDuplication function to fix this issue but honestly, for me the cleanest things would be:
const uri = activeEditor?.document.uri;
In case there are some usecases that I don't know of I guess it's safer to check from workspaceUri like you can see in my patch
https://gist.github.com/ichim-david/76392df43c1442c44be65e3abaf4d702

**Comment by pkukielka** [comment]
I think it should be already fixed by my recent PR:
https://github.com/sourcegraph/cody/pull/5466

**Comment by ichim-david** [comment]
> I think it should be already fixed by my recent PR: #5466

@pkukielka it looked like a decent fix, however until it's merged into the main branch it's of no use to me as a VS Code user. A bit funny how fixes made it into the jetbrains release & didn't end up on the vs code side given that it's usually the other way around (meaning that features are first developed and tested in vs code and then they are ported to the other supported editors).

I have tried your code https://github.com/sourcegraph/cody/pull/5466/files#diff-d46d9cc0e23f55ef14eba64e436ca42b1b161d6382d7fc41890cca8162be2a1bR140
the fileUri is "eea-website-frontend/src/addons/volto-block-toc/src/Block/variations/SideMenu.jsx" which path.isAbsolute will not find it to be true.
I made a screenshot 
![isAbsolute](https://github.com/user-attachments/assets/963b5aae-112f-44fd-abb9-e666bfdfdaca)
where I show what is the difference between the vscode.Uri.file(fileUri) and activeEditor?.document.uri 
![isNewFile](https://github.com/user-attachments/assets/a8f71950-a90a-434f-9c69-8c5cca206d5c)

Hopefully this info will help find a better fix than what I've proposed as your solution doesn't work for my use case.

**Comment by pkukielka** [comment]
> > I think it should be already fixed by my recent PR: #5466
> 
> @pkukielka it looked like a decent fix, however until it's merged into the main branch it's of no use to me as a VS Code user. A bit funny how fixes made it into the jetbrains release & didn't end up on the vs code side given that it's usually the other way around (meaning that features are first developed and tested in vs code and then they are ported to the other supported editors).
> 
> I have tried your code https://github.com/sourcegraph/cody/pull/5466/files#diff-d46d9cc0e23f55ef14eba64e436ca42b1b161d6382d7fc41890cca8162be2a1bR140 the fileUri is "eea-website-frontend/src/addons/volto-block-toc/src/Block/variations/SideMenu.jsx" which path.isAbsolute will not find it to be true. I made a screenshot ![isAbsolute](https://private-user-images.githubusercontent.com/152852/365645554-963b5aae-112f-44fd-abb9-e666bfdfdaca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjA4NTQsIm5iZiI6MTcyNTk2MDU1NCwicGF0aCI6Ii8xNTI4NTIvMzY1NjQ1NTU0LTk2M2I1YWFlLTExMmYtNDRmZC1hYmI5LWU2NjZiZmRmZGFjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwOTI5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjg5Yjg3ZjQ3YWU2NzZmODZhODgwZGFjMmQ1NWE0ZmI1NjdlMWMxNzk4YTAwZWE4MTYwNTQ0NzU2YmVmY2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XiSE3aVT66TAYTo6FXYvKrAEzq5_lD8pHDP5Qq-5ZK4) where I show what is the difference between the vscode.Uri.file(fileUri) and activeEditor?.document.uri ![isNewFile](https://private-user-images.githubusercontent.com/152852/365647406-a8f71950-a90a-434f-9c69-8c5cca206d5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjA4NTQsIm5iZiI6MTcyNTk2MDU1NCwicGF0aCI6Ii8xNTI4NTIvMzY1NjQ3NDA2LWE4ZjcxOTUwLWE5MGEtNDM0Zi05YzY5LThjNWNjYTIwNmQ1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwOTI5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTc0ZGJlYTA1MTY4MjM1N2FkYmZhZDUwZjY4YWU3ZDI3MGI5ZTg4NTY0M2VlMWY2YWVjYjU1YjkyYjk5ZDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E7wnjTzwXrav3GpYs5VHg9g1qjFxwE56hR4q5IkeZuw)
> 
> Hopefully this info will help find a better fix than what I've proposed as your solution doesn't work for my use case.

>the fileUri is "eea-website-frontend/src/addons/volto-block-toc/src/Block/variations/SideMenu.jsx" which path.isAbsolute will not find it to be true.

Which... is correct? :) Or maybe I misunderstood you.
If `isAbsolute` will return `false` then `Utils.joinPath(workspaceUri, fileUri)` code part will be executed.
Is that incorrect in your case?

I do not think removing workspace duplication as in your gist would work either, as sometimes files can come from outside of the workspace (and in such case they should have an absolute path).

**Comment by pkukielka** [comment]
As for this code landing in JetBrains first it is kind of exceptional situation, as we wanted to freeze the version we were in for the 7.0 release and only add couple of bugfixes. But we will be merging all the fixes back to main now.

**Comment by ichim-david** [comment]
> Which... is correct? :) Or maybe I misunderstood you. If `isAbsolute` will return `false` then `Utils.joinPath(workspaceUri, fileUri)` code part will be executed. Is that incorrect in your case?
> 
> I do not think removing workspace duplication as in your gist would work either, as sometimes files can come from outside of the workspace (and in such case they should have an absolute path).

I don't think you've looked at the screenshot,  comments and video I uploaded because if you were to look you would see that with the workspace duplication it creates a new file instead of applying the changes to the file that has requested the changes to be applied.  Please look closer starting with the first comment from the issue description and then hopefully it will all make sense. I understand the need to have absolute path for files that contain spaces but that is not enough to fix my file duplication bug.
Thank you for being interested in it though and I hope that this extra back and forth leads to a fix you all agree upon.

**Comment by pkukielka** [comment]
I understand it now, sorry for the confusion - it is different than other path-related issues reported so far.

I raised a PR with a backport, and added a code for a bit smarter joining of the paths:
https://github.com/sourcegraph/cody/pull/5527/files

It only works for paths like `a/a/b/c/` + `c/d/e`, but hopefully that is enough.
Removing whole path part until workspace name does not seem to be safe, I think if the paths does not overlap cleanly we should probably apply different fix on the code generation side. 

CC @abeatrix

**Comment by ichim-david** [comment]
> I understand it now, sorry for the confusion - it is different than other path-related issues reported so far.
> 
> I raised a PR with a backport, and added a code for a bit smarter joining of the paths: https://github.com/sourcegraph/cody/pull/5527/files
> 
> It only works for paths like `a/a/b/c/` + `c/d/e`, but hopefully that is enough. Removing whole path part until workspace name does not seem to be safe, I think if the paths does not overlap cleanly we should probably apply different fix on the code generation side.
> 
> CC @abeatrix

> I do not think removing workspace duplication as in your gist would work either, as sometimes files can come from 
> outside of the workspace (and in such case they should have an absolute path).

@pkukielka 
It's true that your code to check for absolute https://github.com/sourcegraph/cody/pull/5527/files#diff-d46d9cc0e23f55ef14eba64e436ca42b1b161d6382d7fc41890cca8162be2a1bR173 is useful when you open a file outside of the workspace and this was missing from current logic.

I still prefer the simplicity of my removeWorkspaceDuplication although I should of used path.sep instead of '/' for windows like you did but I can confirm that your "smartJoinPath" function works for my use case.

Checked also the use case where I'm asking smart apply to create a file and it creates it fine using the smartJoinPath however there is another smart apply bug where it inserts the text where needed however you get the spinning  Applying which never resolves as you can see from this screenshot.
![smart-apply-new-file](https://github.com/user-attachments/assets/8efb1ddc-b78a-4aaa-afa9-b74cbbc4cf81)

**Comment by abeatrix** [comment]
@kalanchan @taylorsperry can you help us with triaging this issue please 🙇‍♀️

**Comment by ichim-david** [comment]
@abeatrix this issue is fixed by  this merge https://github.com/sourcegraph/cody/pull/5527
I will add another issue for the applying bug that I mentioned in the last comment
https://github.com/sourcegraph/cody/issues/5489#issuecomment-2341846652
as I can still reproduce it with the main branch up to date.
