### ISSUE TITLE
Small fonts on Jetbrains

### ISSUE THREAD

**Issue by madeupname** [sourcegraph/cody#5516]
Fonts in the Jetbrains plugin are small across the board: UI labels, generated text, and code:

![image](https://github.com/user-attachments/assets/88373b4c-2522-4926-b4f1-86d7cbea32d5)

**Note:** I took the screenshot with the built-in "snipping tool" that applies a zoom effect I can't control. It looks big in the screenshot, but very small on my monitor and others on the forum have complained about this.

In the image, text on the left is my editor, 17pt. 

I'm using Windows 11 with a 32" 4K monitor with a 150% scaling factor, yet it's still hard to read. 

Small fonts are not an issue for any other plugin, just this one. I see no settings to increase fonts size, which is an accessibility issue.

**Comment by lmueller** [comment]
extremely hard to see for me. For the love of God...

**Comment by pkukielka** [comment]
Hey,

This is issue with the IntelliJ itself.
It was working in past, then it get broken, and I verified that it is fixed in 2024.3:
https://youtrack.jetbrains.com/issue/IJPL-44512

Respecting font size settings by Cody was fixed in: https://github.com/sourcegraph/jetbrains/pull/2654
and will be released soon.

**Comment by madeupname** [comment]
Sorry, nothing is different. I have done the following:

- upgraded to 2024.3 with the new UI
- increased font size in editor
- went to Appearance, chose custom font, set very large
- increased Markdown editor size (since your referenced bug is related to Markdown)
- went to Markdown settings, increased Markdown preview size 

**None** of these things changed the size of the Cody plugin fonts. I don't know what you did to test that your plugin's font size changed. Your comment makes it sound like you're assuming this IntelliJ bug fix would solve your problem. 

I'll respectfully reiterate that every other plugin looks fine, including your direct competitors like GitHub Copilot and JetBrains Assistant. I haven't tried Qodo personally, but just had a demo of this and it looked fine as well. It's just Cody that has this problem.

If you have specific instructions to increase Cody font size, please let me know. Otherwise, this bug still exists.
