### ISSUE TITLE
feedback: UI font is too small. Unable to read it at all.

### ISSUE THREAD

**Issue by Nembus** [sourcegraph/cody#5517]
### Version

JetBrains latest Cody plugin

### Areas for Improvement

- [X] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience and include a screenshot.

The UI font for the Cody plugin is too small to be able to read. There is no way to adjust this at all. Using the zoom in the Webstorm's prefs does not change the font size of the Cody UI at all. As much as I'd like to use Cody, I cannot.

![image](https://github.com/user-attachments/assets/8a26c4d4-fae4-4d6d-a1d9-642ff17aaa5d)

### Describe the solution you'd like to see

Off a way to bump up the font size universally across the entire Cody plugin. Even small, medium, large would be better than nothing.

**Comment by FoxMcWeezer** [comment]
This has been complained about many times. I doubt they know how to fix it.

**Comment by Nembus** [comment]
That's very likely. I'm not familiar with Jetbrains plugin API, but I imagine it's not a straightforward process. However, as AI assistants become more and more involved and will have even more crowded UIs, scaling down the font can only get you so far. Maybe it's high time to abandon IDEs and editors and create purpose built tools, since getting a small section of the IDE  allocated to do arguably the most important part of the task, makes little sense. Maybe it's time to ditch the legacy constraints and rethink Cody from the ground up?

**Comment by Yandrik** [comment]
I can recommend looking at [Aider](https://aider.chat) if you want to explore that direction a bit more. I think they did a really good job with their tool, plus it's completely OSS and free. I really like the way Cody works though, because I think the editor is still a very important part of the equation. We as developers are still the one making the final choices, and reading code is still the main part of the job, even if it is just to decide what to feed to the AI, at least in my opinion.

I think there are completely AI agent-based editors out there now though, checking the tools in the leaderboard of the SWE-Bench is generally a cool way to find a lot of them in my opinion. Other than that, VS code has a more capable plugin, although JetBrains is catching up.

**Comment by Nembus** [comment]
Thanks Yandrik. I do use Aider and Claude Dev, and they both have a lot of potential. I think if the context windows will get bigger and cheaper, then many more guard rails could be put in place in the form of cyclical markdown documents containing, for example, things like: [CORE PRINCIPLES], [INITIAL PROJECT ASSESSMENT], [DEVELOPMENT WORKFLOW], [DOCUMENTATION MANAGEMENT], [DEVELOPMENT PLANNING AND COMMUNICATION], [USER INTERACTION], [CODE GENERATION AND BEST PRACTICES], [ERROR HANDLING], [ADAPTIVE LEARNING], [COMPLETION AND HANDOVER], etc. This way the LLM completes a task based on some predetermined rules embedded in the document, updates its tasks list, enters any errors in the [ERRORS] section, etc. I tried this with Claude Dev running Sonnet 3.5 and it was very impressive in terms of how hands off the process seemed. I quickly ran out of my token allowance (daily rate limit with Anthropic), and could not complete the task, but it did demonstrate a different approach. This is all to say that, yes, now we still need editors, but in some foreseeable future, it will be more of an orchestration process than actual coding, since the more LLMs generate code, the more the human in the loop will need to raise above the code and delegate actual needs since grokking all the generated code will take too long.
Getting back to Cody, I had to uninstall it since it began crashing Webstorm. That and the tiny font made it unusable. I'm not sure what Cody offers that's unique here, since other AI assistants can select all or some files or even Symbols to the LLMs with each chat submission.

**Comment by ichim-david** [comment]
@pkukielka I know you are working on the jetbrains plugin, is still feedback something that you are aware of and can provide any help for this user?

**Comment by ichim-david** [comment]
@Nembus Apparently the development of the jetbrains plugin is done in this repo https://github.com/sourcegraph/jetbrains as such the devs that work on it might check the issues more if it were added here https://github.com/sourcegraph/jetbrains/issues.
You have for instance the wrong label  clients/vscode when in fact you refer to the jetbrains plugin. This might also decrease the posibility of the jetbrains developers checking this feedback.

Some better info on how and where to add feedback would be nice to have directly from Sourcegraph but for the time being making sure we provide the right context would at least get us closer to having our issues seen.

**Comment by Nembus** [comment]
Thanks for the heads up, @ichim-david. I posted it here when I was looking for the jetbrains issues page and couldn't find it. I'll try to repost it there.

**Comment by kqvanity** [comment]
@Yandrik  Does cody offer integrate aider?
