### ISSUE TITLE
Cannot Submit Bug Report

### ISSUE THREAD

**Issue by jsnelgro** [sourcegraph/cody#5606]
Hi there, not sure if y'all are aware of this or not, but I'm not able to submit a bug report when the plugin throws an error. Seems important to make sure your error reporting is working, otherwise everything probably looks fine on your end 😅 

Cody is throwing an NPE for me but clicking the "report error" button in the popup toast just leads me to a github page that says the url is too long. It looks like it's trying to add all sorts of debug info, including info about other plugins that are installed, which could potentially be a very large list.
Is there a way to submit that template as a POST + body request on click instead of a GET + url params?

**Comment by kalanchan** [comment]
hey @jsnelgro could you paste the url that you're getting sent to? 

thanks!
