### ISSUE TITLE
Add apiVersion to Cody completions site config, so that Cody Chat can use Azure OpenAI models

### ISSUE THREAD

**Issue by marcleblanc2** [sourcegraph/cody#574]
1. Strategic prospect [1584](https://github.com/sourcegraph/accounts/issues/1584) needs **_Cody Chat_** to support Azure OpenAI models, which require an api-version query parameter
2. Swagger API spec here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-03-15-preview/inference.json
4. This api-version parameter is successfully configured for **_completions_** in the VS Code extension, as `"cody.autocomplete.advanced.serverEndpoint": "https://customer.openai.azure.com/openai/deployments/model/completions?api-version=2023-03-15-preview"`
3. We've tried appending `?api-version=2023-03-15-preview` to the end of the `completions.endpoint` url in site config, but it seems to get sanitized out by input validation
5. In a default installation, the completions site config block is used for both chat and completions, but `cody.autocomplete.advanced.serverEndpoint` was created for a different strategic customer to be able to send completion requests directly from the extension to their LLM provider, bypassing the Sourcegraph instance. In this case, for chat, where embeddings have a much higher impact on user experience, this traffic needs to route through the Sourcegraph instance, so that embeddings are added in the chat context window before being sent to the Azure model.

**Comment by cbart** [comment]
Note: I've assigned this to myself, but between meetings I might be able to start working on it tomorrow. Please feel free to steal this if you're ready earlier.

**Comment by cbart** [comment]
Confirmed that both api-versions work:

```
curl "https://$PROJECT.openai.azure.com/openai/deployments/$DEPLOYMENT/chat/completions?api-version=2023-05-15" \
  -H "Content-Type: application/json" \
  -H "api-key: $KEY" \
  -d "{
  \"messages\": [{\"role\":\"user\",\"content\":\"Hello\"}],
  \"max_tokens\": 800,
  \"temperature\": 0.7,
  \"frequency_penalty\": 0,
  \"presence_penalty\": 0,
  \"top_p\": 0.95,
  \"stop\": null
}"
```

```
curl "https://$PROJECT.openai.azure.com/openai/deployments/$DEPLOYMENT/chat/completions?api-version=2023-03-15-preview" \
  -H "Content-Type: application/json" \
  -H "api-key: $KEY" \
  -d "{
  \"messages\": [{\"role\":\"user\",\"content\":\"Hello\"}],
  \"max_tokens\": 800,
  \"temperature\": 0.7,
  \"frequency_penalty\": 0,
  \"presence_penalty\": 0,
  \"top_p\": 0.95,
  \"stop\": null
}"
```
