### ISSUE TITLE
VSCode extension just a waste of memory and screen space without access to code in editor

### ISSUE THREAD

**Issue by bradykelly** [sourcegraph/cody#576]
### Discussed in https://github.com/sourcegraph/cody/discussions/575

<div type='discussions-op-text'>

<sup>Originally posted by **bradykelly** August  5, 2023</sup>
In chatting with Cody within VS Code, it has told me the following:

- It does not have access to any of the code in the project I have open in VSCode!
- That to provide it with access to my code I could do the following. 
>  "build a VSCode extension that communicates with Cody through a WebSocket or another protocol". 
- What then is the purpose of the official SourceGraph Code VSCode extension?
- The Cody VSCode extension only allows it to analyse code I provide in the chat window.
- When I ask Cody how I can communicate with it without using the VSCode extension, it has the audacity to say it is 
> designed to provide helpful information related to code directly within the editor. 
- This is just after it told me it cannot access the code in my editor.

I have not made any config changes on the extension, and some may be necessary to enable the basic features expected of an AI-based editor extension, but the config values required for this should be set to the correct values by default, and clearly highlighted in high-level documentation for the extension.

I have been quite excited to try out Cody, but my experience with the VSCode extension has left me extremely disappointed and angry at my water of time. I should go back to using GitHub Coplit which simply works very well and is aware of the editing context I am working in, or maybe I will try some other less convoluted and more helpful AI assistants.

At this point, I am ready to recommend against all our organization's engineering teams using Cody until we can evaluate other tools.

</div>

**Comment by jdorfman** [comment]
Hey @bradykelly I'm going to close this and move it over to the #575
