### ISSUE TITLE
Support ticket for Rider

### ISSUE THREAD

**Issue by SuperSecretSquirrel** [sourcegraph/cody#5771]
https://community.sourcegraph.com/t/cody-and-customer-service-feedback/1149

I’ve been trying out the free version and like it so far, but using rider in dark mode means I have to restart my IDE every time, as Cody’s UI never loads correct the first time (not sure if photo upload will work)-

![image](https://github.com/user-attachments/assets/5376726f-dd79-4844-95b9-9b1559682849)

Having a way to manually reload in editor would be great.

**Comment by SuperSecretSquirrel** [comment]
Just found I can disable and re-enable Cody in the Rider menu and it will fix it after a few tries. Faster than restarting the IDE, still kind of a pain.

**Comment by Jirdus** [comment]
I find this terribly irritating. I see the Cody panel like this practically all the time. Even restarting Riderdoesn't work and I don't have time for x attempts. Disabling and enabling the Cody plugin requires a restart, so that solves nothing. Do something about it!

**Comment by SuperSecretSquirrel** [comment]
Assuming Rider is just not a supported platform. Closing ticket because its annoying getting these updates with no update.
