### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Kno0ux** [sourcegraph/cody#5787]
- Issue Type: `Performance`
- Extension Name: `cody-ai`
- Extension Version: `1.36.0`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.93.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Knoux/AppData/Local/Temp/sourcegraph.cody-ai-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by faheemstepsharp** [comment]
Agree, Cody is taking huge time to load and also high memory cpu usage

**Comment by sqs** [comment]
Sorry about this issue. Can you please paste the contents of the `Cody by Sourcegraph` VS Code output channel so we can see what might be causing it?

**Comment by arafatkatze** [comment]
Hi everyone,
To help us identify and resolve performance issues with Cody, we’d appreciate it if you could follow these steps to create a performance profile and share the generate file with us through a GitHub issue.

Steps to Create and Share a Performance Profile:

Enable the Extension Host Profiler in VS Code:
• Open VS Code.
• Press Ctrl+Shift+P (Windows/Linux) or Cmd+Shift+P (macOS) to open the Command Palette.
• Type Developer: Show Running Extensions and select it.
• A list of running extensions will appear. Next to Cody (or the extension you suspect is causing slowness), click rick click on it and click on start extension host profile.
Reproduce the Issue:
• While the profiler is running, perform the actions that typically cause the performance slowdown (e.g., chatting, using Cody, loading files).
• Once the issue has been reproduced, stop the profiler by returning to the list of running extensions and right clicking and doing Stop Extension Host Profile.
3. Save the Profile:
• Right click on Cody and click "save extension host profile " This will generate a .cpuprofile file. Save this file to a location on your computer.
4. Attach the Profile to a GitHub Issue:
• Attach the .cpuprofile file to this issue by uploading it along with a brief description of the issue you’re experiencing, including any specific steps that caused the slowdown.
I know this is a lot of steps but we have found this to be the case only with certain distributions and haven't been able to replicate it so we wanted to do this as its the best route to figure out the causality for your case.

🙇

**Comment by beyang** [comment]
This should be fixed now, please update to 1.36.1 (the latest stable release)!
