### ISSUE TITLE
bug: Minion panel showing empty page on Cursor

### ISSUE THREAD

**Issue by anyb1s** [sourcegraph/cody#5824]
### Version

1.37.17

### Describe the bug

Hello, I wanted to try the new experimental Minion panel, but when I open it, it doesn't show anything. I've added the Anthropic key, but it doesn't load. Am I missing something? 

### Expected behavior

Then we should show the planning phase for the task you are doing. https://github.com/sourcegraph/cody/pull/4416

**Comment by theronburger** [comment]
This is a dupe of https://github.com/sourcegraph/cody/issues/5296
I provide possible reasons here. spoiler alert, cody spams state hard and crashes it

**Comment by PriNova** [comment]
@anyb1s 

The minion panel is an experimental feature and will not be maintained anymore.
thank you for reporting.
