### ISSUE TITLE
Fixup: Improve instruction flow

### ISSUE THREAD

**Issue by umpox** [sourcegraph/cody#588]
## Description

I think we should change how we see the “explain, refactor, document, test” workflows. The problem with the existing approach is that there’s no flexibility. I click “Document code” but there’s no way for me to specify that I want to create a JSDoc, or maybe I want to produce a README file. I click “Generate a unit test” but actually I want to create an E2E test, do I need a custom prompt for this? We should avoid that.

Here’s what I think we should do:
`Explain|Refactor|Document|Test` are special cases for our commands. They
Do not open the sidebar. Explain opens inline chat for the range. Refactor|Document|Test will execute a fixup or a /touch.
Prompt the user for additional input. We can provide a default value if the user just wants to skip through but we should definitely allow users to change their instruction.

I don’t think we necessarily need to change these commands in the sidebar, but in the command palette and in files we should provide a lot more control.

Example:

https://github.com/sourcegraph/cody/assets/9516420/cf6369d9-a00d-4641-b88b-2adc1248671e

Code for example:  https://github.com/sourcegraph/cody/pull/584

## Implementation

1. Implement https://github.com/sourcegraph/cody/pull/584
2. Remove the additional commands for the fixup input - instead rely on intent detection for any additional context

**Comment by toolmantim** [comment]
I like the idea of triggering inline chat when those commands are executed, vs re-opening the Cody panel.
