### ISSUE TITLE
bug: after a long conversation the reply is taking too long ,the perfromence is slowing down...

### ISSUE THREAD

**Issue by bxf1001g** [sourcegraph/cody#5887]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by PriNova** [comment]
Hey @bxf1001g 

the performance decrease on long conversations was already fixed.
If the issue persists, please fill out a new issue and provide all the information needed to reproduce the error:

Thank you

**Comment by bxf1001** [comment]
@PriNova  
Hi,

Thank you for the fix! I’ve noticed a significant improvement, and I currently have no issues with the performance during long conversations.

However, I’m facing another challenge with the OpenAI 01 Preview: the responses are often incomplete, and I need to type "continue" repeatedly to get the full response. This can disrupt the workflow.

Is there any way to address this or a setting to ensure the responses are complete in one go?

Thank you......
