### ISSUE TITLE
Fixup: Integrate /touch recipe with non-stop fixup logic

### ISSUE THREAD

**Issue by umpox** [sourcegraph/cody#589]
## Description

The non-stop fixup logic gives us a lot of benefits, for example:

1. Parallel fixups
2. Fixup tracking
<img width="518" alt="image" src="https://github.com/sourcegraph/cody/assets/9516420/ce009298-c384-430d-adaf-20e740744a32">

We should integrate `inline-touch` with this flow so we get similar benefits here too. This will allow commands like "Generate a test" to integrate easily with other fixes.

## Implementation

1. Update `FixupManager` to support executing `fixup` or `inline-touch` recipes.
2. Add the concept of "type" to `FixupTask`. It could either be `inline` or `file`.
  a. Depending on the type we render different UI for the fixup. We probably just want to list the fixup somewhere and then prompt the user when the new file is ready?

**Comment by beyang** [comment]
Is this still relevant or can we close?

**Comment by dominiccooney** [comment]
This is a refactoring @umpox had planned, which I plan to help out with, but did not get to yet.

**Comment by beyang** [comment]
/touch is internal only, so perhaps we can just skip this?

**Comment by dominiccooney** [comment]
Closing this; "touch" is gone.
