### ISSUE TITLE
Connection to the server

### ISSUE THREAD

**Issue by NeoInvester** [sourcegraph/cody#5898]
Type: <b>Bug</b>

Hi.
I am having issues when asking Cody to produce code....
It is the delay, everytime this day, that the reply from Cody (Writing Python code) is timing out as it takes so long for 160 lines of code to write to the AI.

I have checked my internet connections, latency, and connection integrity, which are all working just fine!!!

I have cross-tested the code writing using Chat GPT, which works, without pause, or delay...

Please advise.

Gary

Extension version: 1.36.3
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.91GB (9.38GB free)|
|Process Argv|--crash-reporter-id 15929e55-22be-481d-a033-d8eb6ff51492|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31157159
showbadge:31153266
5fd0e150:31155592

```

</details>

**Comment by NeoInvester** [comment]
Resolved...

There should be a notice that states when the chat reaches a certain length, the Cody response is limited....
Oddly enough, I have had longer chats, but never this time out issue

**Comment by PriNova** [comment]
Issue will be closed as resolved reported from the user.
