### ISSUE TITLE
URL contexts not working in Cody Web

### ISSUE THREAD

**Issue by beingPurple** [sourcegraph/cody#5913]
![Screenshot_20241015_161600_Chrome](https://github.com/user-attachments/assets/09b346f9-35b0-4075-877e-38cd8714b5d9)
Type: Bug

Extension Information
Cody Version: unsure
Cody Web

Steps to Reproduce
1.I instruct Cody to view a web page
2. See if the response contains information from the Web page

Expected Behaviour
Cody should be able access the web page and tell me information about it. This is especially useful if I'm reviewing code snippets that have been shared to me.

Logs
N/a

**Comment by PriNova** [comment]
Hey @beingPurple 

If you use the Web-URL mention feature and input a webpage URL you need to wait 1-2 seconds until the selection menu shows the URL and the previous 'No results' disappears.

If the issue still persists, please report a new issue.

Thank you
