### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by mrmaomaomao** [sourcegraph/cody#5933]
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.38.1
- VS Code Version: 1.95.0-insider
- Extension Host: desktop

##  Steps to Reproduce

1.
2.
3.

## Logs

Extension version: 1.38.1
VS Code version: Code - Insiders 1.95.0-insider (62a233cc87dc8d52a817739bc0d917089d4d103b, 2024-10-17T05:09:34.012Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.79GB (17.78GB free)|
|Process Argv|--crash-reporter-id 10b6b017-bafb-430a-bc25-1686258705f9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
cp13037t-nofilt:31155934
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
cppperfnew:30980852
pythonait:30973460
9c06g630:31013171
dvdeprecation:31040973
dwnewjupytercf:31046870
2f103344:31071589
nb_pkg_only:31057982
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
i21gd607:31141543
iacca1:31150324
notype1:31143044
showbadge:31139796
f8igb616:31140137
dwcopilot:31158714
g7688163:31155431
iconenabled:31158249

```

</details>

**Comment by kalanchan** [comment]
Hi, thanks for your report, but it looks empty/incomplete, please make sure all details are filled so we can help you!
