### ISSUE TITLE
bug: Keeps telling me to modify files that don't exist. Repeatedly

### ISSUE THREAD

**Issue by mindcodemediator** [sourcegraph/cody#5940]
### Version

?

### Describe the bug

bug: Keeps telling me to modify files that don't exist. Repeatedly

### Expected behavior

To direct me to the correct file to modify that actually exists

### Additional context

It hallucinates and sends me to non existent files within the repo

**Comment by endolith** [comment]
Same as this? https://github.com/sourcegraph/cody/issues/5324

**Comment by PriNova** [comment]
Hey @mindcodemediator @endolith 

Please update to the latest Cody version. If the issue still persists, open up a new bug report with all the necessary steps to reproduce the issue, like Cody Version, OS, Screenshots and the detailed steps.

Thank you
