### ISSUE TITLE
Cody does not fetch any context at all

### ISSUE THREAD

**Issue by emicovi** [sourcegraph/cody#5966]
### Version

v1.38.2

### Describe the bug

![image](https://github.com/user-attachments/assets/3b540c55-acb5-47d1-9563-835f8e36c9a2)
Cody is completely hallucinating files and code.

### Expected behavior

I thoguth it would retreive useful info from codebase?

**Comment by Kynlos** [comment]
When asking questions for specific files, the best practice is to use the @-mention feature so Cody knows exactly which file you are referring to.<br><br>If this issue still persists in the latest version of Cody, when using the @ mention feature, please reopen the issue.<br><br>Thanks

**Comment by PriNova** [comment]
Hey @emicovi 

Please update to the latest Cody version. We now have a new model called DeepCody for Pro users, which can dynamically fetch context from your project. It is also advisable to use English for context retrieval.

If the issue still persists, open up a new bug report with all the steps to reproduce the issue.

Thank you.
