### ISSUE TITLE
bug: capacity read code base

### ISSUE THREAD

**Issue by dungeng** [sourcegraph/cody#5989]
Type: <b>Bug</b>

Now I want Cody to read and understand the codebase, like in a WordPress project where the wp folder contains the entire WordPress site. I noticed the website is slow and wanted to ask about this:

imagesloaded.min.js?ver=5.0.0:13 Uncaught TypeError: h is not iterable at new n (imagesloaded.min.js?ver=5.0.0:13:433) at i.fn.imagesLoaded (imagesloaded.min.js?ver=5.0.0:13:4286) at woodmartThemeModule.imagesGalleryMasonry (combine.min.js?ver=7.0.3:1:18258) at HTMLDocument.<anonymous> (combine.min.js?ver=7.0.3:1:18616) at j (vnfaster-order.min.js?ver=3.0.0:1:27244) at Object.fireWith [as resolveWith] (vnfaster-order.min.js?ver=3.0.0:1:28057) at Function.ready (vnfaster-order.min.js?ver=3.0.0:1:29891) at HTMLDocument.J (vnfaster-order.min.js?ver=3.0.0:1:30257)

Can Cody automatically locate this imagesloaded.min.js file, read it, and handle other related files in the codebase that are mentioned or related to this issue?"

Let me know if you'd like any adjustments!
## Extension Information

- Cody Version: 1.38.2
- VS Code Version: 1.94.2
- Extension Host: desktop

##  Steps to Reproduce

1.
2.
3.

## Logs

Extension version: 1.38.2
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.57GB free)|
|Process Argv|--crash-reporter-id 03188f9e-5f39-4476-90d1-1b12574a3e2f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by PriNova** [comment]
Hey @dungeng 

You can reference the file explicitly in the Cody Chat via the @-mention feature or you can use our newest model DeepCody on the Pro plan, which dynamically fetches context files per user prompt.

Please update to the latest version of Cody.

Thank you
