### ISSUE TITLE
Execute in Terminal Stops working after a while

### ISSUE THREAD

**Issue by tech-and-ai** [sourcegraph/cody#6005]
### Version

v1.38.3

### Describe the bug

After a while sometimes after only a few minutes, the Execute - in terminal button stops working. Now I've managed to get this working again by doing two things: rm -rf ~/Library/Application\ Support/Code/User/globalStorage/ms-vscode.terminal
but sometimes if that doesn't work I have to delete everything in User/  - rm -rf ~/Library/Application\ Support/Code/User/ but this is drastic. I know that VSCODE terminal manager is a bit flakey, but is there a particular file that's causing this issue that I can pinpoint and delete? 

### Expected behavior

The execute in terminal button runs the bash/shell in terminal.

### Additional context

Many thanks, Leo.

**Comment by PriNova** [comment]
Hey @tech-and-ai 

Thanks for reaching out to us. Please update to the latest version of Cody. The issue should be solved.
In the unlikely event that it still persists, please open up a new report with all the steps needed to reproduce the issue.

Thank you
