### ISSUE TITLE
bug: Prompt does not get submitted

### ISSUE THREAD

**Issue by petterip** [sourcegraph/cody#6007]
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.38.3
- VS Code Version: 1.94.2
- Extension Host: desktop

##  Steps to Reproduce
1. Enter a prompt into Cody AI's chat window in VS Code
2. Enter a follow-up prompt to the chat window's text field

## Expected Behaviour
An answer.

## Actual Behaviour
The prompt content never gets submitted by pressing either enter key or the chat prompt field's submit button. Instead the Cody AI seems to get stuck. Only opening new chat window allows a new prompt to be submitted, but then again the same issue occurs with follow-up prompts.

If I try to edit the prompt, and attempt to send it again, Cody occasionally displays an error in the chat window: 
* Cannot set new context used for bot message
* Request Failed: Failed to edit prompt

## Logs
█ telemetry-v2 recordEvent: cody.humanMessageEditor/submit: {
  "parameters": {
    "version": 0,
    "metadata": [
      {
        "key": "isFirstMessage",
        "value": 0
      },
      {
        "key": "isEdit",
        "value": 0
      },
      {
        "key": "messageLength",
        "value": 115
      },
      {
        "key": "contextItems",
        "value": 1
      },
      {
        "key": "intent",
        "value": 0
      },
      {
        "key": "tier",
        "value": 1
      }
    ],
    "billingMetadata": {
      "product": "cody",
      "category": "billable"
    }
  },
  "timestamp": "2024-10-27T10:53:25.877Z"
}
█ telemetry-v2 recordEvent: cody.humanMessageEditor/submit: {
  "parameters": {
    "version": 0,
    "metadata": [
      {
        "key": "isFirstMessage",
        "value": 0
      },
      {
        "key": "isEdit",
        "value": 0
      },
      {
        "key": "messageLength",
        "value": 115
      },
      {
        "key": "contextItems",
        "value": 1
      },
      {
        "key": "intent",
        "value": 0
      },
      {
        "key": "tier",
        "value": 1
      }
    ],
    "billingMetadata": {
      "product": "cody",
      "category": "billable"
    }
  },
  "timestamp": "2024-10-27T10:53:26.211Z"
}
█ telemetry-v2 recordEvent: cody.humanMessageEditor/submit: {
  "parameters": {
    "version": 0,
    "metadata": [
      {
        "key": "isFirstMessage",
        "value": 0
      },
      {
        "key": "isEdit",
        "value": 0
      },
      {
        "key": "messageLength",
        "value": 115
      },
      {
        "key": "contextItems",
        "value": 1
      },
      {
        "key": "intent",
        "value": 0
      },
      {
        "key": "tier",
        "value": 1
      }
    ],
    "billingMetadata": {
      "product": "cody",
      "category": "billable"
    }
  },
  "timestamp": "2024-10-27T10:53:26.541Z"
}
█ ClientConfigSingleton refreshing configuration:
█ ClientConfigSingleton refreshed: {"codyEnabled":true,"chatEnabled":true,"autoCompleteEnabled":true,"customCommandsEnabled":true,"attributionEnabled":false,"smartContextWindowEnabled":true,"modelsAPIEnabled":false,"latestSupportedCompletionsStreamAPIVersion":5}

---

Extension version: 1.38.3
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600K (16 x 3686)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (15.76GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/petterip/git/birdnet-go --remote=wsl+Ubuntu --crash-reporter-id f007efc4-d25f-4652-a81c-7a25c917d2a1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Go Build Environment|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600K (16 x 0)|
|Memory (System)|15.50GB (12.55GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31156133
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by PriNova** [comment]
Hey @petterip 

Please update the latest Cody version and if the issue still persists, please report a new issue with all the steps needed to reproduce the issue.

Thank you for reporting
