### ISSUE TITLE
Cody is adding a "Reload Window" action to many views

### ISSUE THREAD

**Issue by eamodio** [sourcegraph/cody#601]
![image](https://github.com/sourcegraph/cody/assets/641685/467a88a8-db5c-4ede-b57e-8a1b54b5b385)

Took me a while to track down which extension, and then to find exactly where, but this looks like the culprit. I'm not sure of the intent here, but since there isn't a `when` condition it will apply to all views

https://github.com/sourcegraph/cody/blob/main/vscode/package.json#L623-L627

**Comment by toolmantim** [comment]
Thank you for tracking this down and filing this @eamodio! 🙏🏼
