### ISSUE TITLE
Cody icon not appearing in Activity Sidebar

### ISSUE THREAD

**Issue by temucin** [sourcegraph/cody#6050]
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.41.1730474489
- VS Code Version: 1.94.2
- Extension Host: desktop

##  Steps to Reproduce

1. Installing Cody AI from Extensions
2. 
3.

## Expected Behaviour

The Docs say the Cody icon should automatically appear in my sidebar, it does not. The Sidebar is working for other icons. There is no option to include Cody in the sidebar settings either. 

## Logs

Extension version: 1.41.1730474489
VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 21.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 6, 6|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|. --crash-reporter-id d2675dc8-bb34-4814-bdff-45de61140c59|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by temucin** [comment]
Not sure what is happening here but I was able to drag and drop the Cody icon over once loading it from the command pallete.

**Comment by Kynlos** [comment]
Based on your update, I am marking this issue as resolved/closed.<br><br>If you still need help, please re-open a report and let us know 🙂 <br>Thanks!
