### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by Zheka17** [sourcegraph/cody#6060]
### Version

1.95.1

### Describe the bug

Attempting to sign-in to the extension with Google or GitHub, i get a new Authorization tab in the browser, but upon clicking on "Authorize" another/ new empty tab opens while Cody in VScode remains stuck in Signing-in.

### Expected behavior

sign-in successful and extension usable

### Additional context

Cody v1.40.x-1.41.x, VSCode 1.94.2 and 1.95.1, Debian 12 and Firefox 132...had it in the past as well...not under proxy, VPN or anything

Runtime Status
Activation
Activated by onLanguage event: 1ms

Uncaught Errors (2)
Cannot write headers after they are sent to the client
Cannot write headers after they are sent to the client

**Comment by dominiccooney** [comment]
Oh, I bet this is because app link redirects are disabled or something like that.
