### ISSUE TITLE
This feature has been disabled by your Sourcegraph site admin.

### ISSUE THREAD

**Issue by rumanto00** [sourcegraph/cody#6104]
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.40.2
- VS Code Version: 1.85.2
- Extension Host: desktop

##  Steps to Reproduce

1. when cody appling the code, this error comming
2. it stop caapbility apply cod
3.

## Logs

Extension version: 1.40.2
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Connection to 'wsl+ubuntu-22.04' could not be established
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (11.45GB free)|
|Process Argv|--crash-reporter-id a968d3d2-69a2-47c1-a9ba-1f11f93950cf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|Memory (System)|15.49GB (8.19GB free)|
|VM|0%|

Connection to 'wsl+ubuntu-22.04' could not be established

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|Memory (System)|15.49GB (8.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|Memory (System)|15.49GB (8.19GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by huzi8t9** [comment]
I have the same problem.

**Workaround**
1. View the extension tab `Cody: Chat`
2. Click the person in the circle
3. Click sign out
4. Reauthenticate

This is works for me, I have to do it too often though

**Comment by PriNova** [comment]
Hey @rumanto00 @huzi8t9 

Could you please update to the latest version of Cody and check if the issue is resolved for you.
At least the re-login mentioned above helps as a workaround.

Sorry for the inconvenience.

**Comment by majidghafoorzade** [comment]
I have similar problem with the latest version of Cody installed. any solution?

**Comment by PriNova** [comment]
Hey @majidghafoorzade @huzi8t9 

It is a known bug and the team is currently on it.
The simplest solution without re-login is to reload the IDE and the issue should be gone for now.
This happens, if there is a network hiccup on the authentication server and the client ping fails, therefore a reload of the IDE triggers this ping again and resolves this issue.

Sorry for the inconvenience.
