### ISSUE TITLE
No way to use Cody chat

### ISSUE THREAD

**Issue by neilmendoza** [sourcegraph/cody#6106]
### Version

RD-242.23726.100 on MacOS

### Describe the bug

Cody chat was being pretty unusable, e.g. didn't have the file I was editing as context, chat box was unselectable. In trying to fix it, I accidentally removed the chat icon and now there's no way to get it back at all. Cody has better suggestions the Copilot but seems like Jetbrains plugins are pretty buggy at the moment.

### Expected behavior

Chat window working reliably.

Options to add chat icon back in if it's removed from side bar.

**Comment by PriNova** [comment]
Hey @neilmendoza 

Sorry for the late reply.
Could you please create a new bug report here https://github.com/sourcegraph/jetbrains/issues/new/choose with all the important information to understand the problem.

Thank you very much.
