### ISSUE TITLE
ai engine 

### ISSUE THREAD

**Issue by PATEL-BHAVIK2306005** [sourcegraph/cody#6117]
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.40.2
- VS Code Version: 1.95.2
- Extension Host: desktop

##  Steps to Reproduce

1.ai engine disappier
2.
3.not responsive after many time

## Logs

Extension version: 1.40.2
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.74GB (0.74GB free)|
|Process Argv|C:\\RUBANS\\HOME.HTML --crash-reporter-id 6b7c0ed4-e951-4b1f-8683-4121cfe9f0b7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
h409b430:31177055

```

</details>

**Comment by PriNova** [comment]
Hello @PATEL-BHAVIK2306005 

What do you mean with "ai engine"?

It may help the developers if you can describe the bug in more detail for reproducibility. Please fill out the GitHub issue again with all steps and your expected behaviour. If you have screenshots or a video of the bug to share, it will also help.

Thanks in advance.
