### ISSUE TITLE
Resizable components of chat window

### ISSUE THREAD

**Issue by cartermp** [sourcegraph/cody#613]
I'd love to resize the chat window. Here's how it loaded on my vscode:

<img width="261" alt="image" src="https://github.com/sourcegraph/cody/assets/6309070/b60c5dde-9664-4373-af0f-5e4f615ef47b">

I actually want to keep the width, but I want to "pull up" the chat bar so that it's taller.

I do this frequently with other windows, such as the terminal, where I'll often pull it up or down depending on the command I'm running and the output it gives.

**Comment by dominiccooney** [comment]
Another option is to make the box resize with the input. (Browsing through history might be a bit jarring though without some transitions/hysteresis.)
