### ISSUE TITLE
"Skip to end" button occupies excessive space — prevents text selection in adjacent areas

### ISSUE THREAD

**Issue by SnzFor16Min** [sourcegraph/cody#6133]
### Version

1.41.1731027960

### Describe the bug

"Skip to end" button at the bottom occupies more space than it visually should. Specifically, there is an invisible area around the button (indicated in red in the attached screenshot) where text cannot be selected:
![image](https://github.com/user-attachments/assets/243a1a59-6d08-463d-81e5-936b154c84b5)
This makes it difficult to select any text that falls within this area.

Steps to Reproduce:
1. Open the CODY: CHAT panel in VS Code.
2. Chat until the content is scrollable.
3. Scroll above to see the "Skip to end" button appear.
4. Attempt to select text adjacent to the "Skip to end" button but you can't.

### Expected behavior

- The "Skip to end" button should only occupy its visible space.
- Users should be able to select any text outside the visible boundaries of the button.

### Additional context

This might be due to the class applied to the button, causing its interactive area to extend beyond the visible button.

**Comment by ichim-david** [comment]
@SnzFor16Min I've added a pull request that handles this issue. 
https://github.com/sourcegraph/cody/pull/6143
I'll keep you posted if this gets merged and released.

**Comment by SnzFor16Min** [comment]
@ichim-david Great to hear that! Thanks for you efforts and waiting for the release :)

**Comment by ichim-david** [comment]
@SnzFor16Min update to latest pre-release (last one was released 10h ago) and you should see that the bug has been indeed fixed.

**Comment by SnzFor16Min** [comment]
@ichim-david Thanks! Can confirm this has been fixed as of version `1.45.1732320290`.
