### ISSUE TITLE
Insert at Cursor button rendered behind codeblock

### ISSUE THREAD

**Issue by cartermp** [sourcegraph/cody#614]
In my txt file (a prompt for an experiment I'm doing), I decided to have Cody "explain code" when I highlighted the whole file.

I saw this rendered twice:

<img width="255" alt="image" src="https://github.com/sourcegraph/cody/assets/6309070/acbfafb0-44b6-4ad3-9c54-d5f16b9b6994">

Note the clickable button behind the code block.

**Comment by jdorfman** [comment]
Hey @cartermp, thanks for the screenshot. What version of the Cody extension are you running?

**Comment by cartermp** [comment]
Looks like `v0.6.5` in my vscode-insiders build. I always just update to latest though, so this answer's going to change soon 🙂

**Comment by jdorfman** [comment]
Oh ok so it could be an issue with the vscode-insiders build? I'm running `Version: 1.81.0` and unable to replicate so maybe that might be the case. Either way I want to get this fixed for you :)

**Comment by dominiccooney** [comment]
I can reproduce this at 9c8ded85b76ddac6d4f6ea7d5a357a18d03e0671. 

The buttons aren't actually behind the code, as you can see if you drag to select the text (see screenshot.) But painting the background and text in a different order like that is part of the awesome power of web compositing. This could be a browser bug but it's probably something to do with how something like z-index, position, opacity changes on hover.

![Screenshot 2023-08-17 at 14 15 08](https://github.com/sourcegraph/cody/assets/55120/042c3a63-b50a-43a8-8301-c3ca67d7eb61)

**Comment by dominiccooney** [comment]
Ah, it is even simpler than that. The buttons have a hover style which gives them a transparent background.
