### ISSUE TITLE
Allow manually pasting auth token instead of relying on "vscode://" link

### ISSUE THREAD

**Issue by EmilHeilbo** [sourcegraph/cody#6140]
Type: <b>Feature Request</b>

## Extension Information

- Cody Version: 1.42.0
- VS Code Version: 1.95.1
- Extension Host: desktop

##  Steps to Reproduce

1. Start auth flow
2. Finish auth flow, you can view the token. Browser asks if you'd like to use your System Handler for using vscode:// links.
3. Link seemingly doesn't work, and I'd like to be able to log in despite this, instead of debugging my system.

## Expected Behaviour

I'd like a button to manually add the token.

## Logs

```
█ GraphQLTelemetryExporter evaluated export mode:: 5.2.5+
█ GraphQLTelemetryExporter Error exporting telemetry events:: Error: Variable "value" has invalid value null.
Expected type "JSONValue!", found null.
█ UpstreamHealth Ping took 279ms (Gateway: 268ms): "url=https://sourcegraph.com/healthz status=200 cf-ray=8e3908773eafebcd-CPH"
█ telemetry-v2 recordEvent: cody.webview.auth/simplifiedSignInGitLabClick: {
  "parameters": {
    "version": 0,
    "metadata": [
      {
        "key": "tier"
      }
    ]
  },
  "timestamp": "2024-11-16T16:59:38.134Z"
}
```

Extension version: 1.42.0
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Linux x64 6.6.61-1-lts
Modes:

**Comment by EmilHeilbo** [comment]
Oh, it seems like it didn't register me switching from Bug Report to Feature Request, sorry 😅

**Comment by Kynlos** [comment]
> Oh, it seems like it didn't register me switching from Bug Report to Feature Request, sorry 😅

This is already possible by using `CTRL-SHIFT-P` to open the `command palette`, selecting `Cody: Switch Accounts` > `Sign in with URL and Access Code` > URL: `https://sourcegraph.com` > `TOKEN`

**Comment by PriNova** [comment]
@EmilHeilbo I created a feature request of your submission at our community forum for better tracking with the Product and Design team here: https://community.sourcegraph.com/t/button-to-add-access-token-manually/1447

Thank you for reporting
