### ISSUE TITLE
Code blocks not scrollable on macOS with two-finger swipe

### ISSUE THREAD

**Issue by cartermp** [sourcegraph/cody#615]
Given a code block like so, with the width narrow so that it needs to scroll:

<img width="224" alt="image" src="https://github.com/sourcegraph/cody/assets/6309070/849c34fe-f51c-4c10-85e8-718cb850cc82">

I cannot hover over with the cursor and two-finger swipe to sidescroll. I have to click the scroll bar at the bottom and manually drag it.

**Comment by cartermp** [comment]
MMM actually this is caused by https://github.com/sourcegraph/cody/issues/614

My cursor went to the button! and that had the effect of not letting me scroll.

**Comment by jdorfman** [comment]
@cartermp I'm going to close this issue out and continue on #614. Reopen if needed.
