### ISSUE TITLE
Improve Generate Unit Tests

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#619]

**Comment by rakeshjosh2003** [comment]
For one of the clients we recently observed that unit tests do not generate for files that rely on parameters from a construct in a base file i.e files that have a dependency on other files.

[Slack thread](https://sourcegraph.slack.com/archives/C058H9W5VCK/p1690176424323429)

[Customer](https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001Xiai9AAB/view)

**Comment by abeatrix** [comment]
@rakeshjosh2003 can you confirm which version the client is on? 

When you say `unit tests do not generate`,  do you mean Cody did not response with any unit tests? Or did Cody generate unit tests, but they do not work due to dependency missing? 

Would you happen to have an example you can show me since the slack thread did not have any?

**Comment by rakeshjosh2003** [comment]
Hey @abeatrix ,

It is able to generate unit tests but not able to specify the parameters in those tests for the files with dependencies.

**Comment by abeatrix** [comment]
@rakeshjosh2003 do you have an example of what the failed tests look like? just to make sure we are on the same page, thanks!

**Comment by rakeshjosh2003** [comment]
Hey @abeatrix , I have contacted the customer to share some examples as it looks scenario based. Will update once I hear back, thank you!

**Comment by abeatrix** [comment]
End of sprint update: https://github.com/sourcegraph/cody/pull/907

- Improved context and prompt for the unit tests command that generates tests with higher quality consistently.
- The way the tests are presented could be clearer and need follow-up work. Going to work with @toolmantim on exploring options to see what's the best way to handle this
