### ISSUE TITLE
Missing local prompts form json

### ISSUE THREAD

**Issue by macdrorepo** [sourcegraph/cody#6212]
### Version

1.95.3

### Describe the bug

After latest cody update plugin stopped reading / showing locally defined prompts kept in cody.json located in ~/.vscode/cody.json. Only prompts being see are one defined in web console in prompt library. Pycharm is showing local prompts ok.

### Expected behavior

Vscode cody plugin to show locllay defned prompts as usual
<img width="1055" alt="Screenshot 2024-11-28 at 09 56 07" src="https://github.com/user-attachments/assets/9b6ea154-3925-4754-b047-838a62ea34ae">

**Comment by PriNova** [comment]
@macdrorepo 

Thank you for providing the Cody version.
Since the commands are migrated to the new Prompt Library in VS Code, they may disappear if the internal migration was triggered,
Have a read here: https://sourcegraph.com/blog/announcing-prompt-library for more information.

Thank you
