### ISSUE TITLE
New Cody Pro install, unable to send message

### ISSUE THREAD

**Issue by jakemertel** [sourcegraph/cody#6234]
### Version

1.46.0

### Describe the bug

Just signed up for Cody Pro and am unable to send chat messages when using GPT-4o as model. Messages consistnetly produce the follwing error:

**Unable to Send Message
You've used all of your chat messages and commands for today.**

### Expected behavior

Messages sent in the chat box are sent to ChatGPT and response given.

**Comment by PriNova** [comment]
Hey @jakemertel 

On Cody Pro and Enterprise plans, usage is unlimited but controlled by Fair Usage. This means that some users occasionally experience a limitation placed on their account. This limitation resets within 24 hours. If this issue persists, contact us through our [community forum](https://community.sourcegraph.com/), Discord, or email [support@sourcegraph.com](mailto:support@sourcegraph.com).

**Comment by jakemertel** [comment]
As explained, this is a brand new subscription. I was at no point ever to
initiate a conversation with ChatGPT. Surely fair use is more than 0.
