### ISSUE TITLE
Hitting Cody message limits 

### ISSUE THREAD

**Issue by tech-and-ai** [sourcegraph/cody#6273]
### Version

v1.48.0

### Describe the bug

I have a pro account which is unlimited and hit this limit, I also signed up for a new pro account because of this issue and hit the same limit within a few hours. 

Deep Cody
Unable to Send Message
You've used all of your chat messages and commands for today.

### Expected behavior

I'm not expecting limits on an unlimited account.

### Additional context

Please look into this as I'm unable to progress.

**Comment by PriNova** [comment]
Hey @tech-and-ai 

On Cody Pro and Enterprise plans, usage is unlimited but controlled by Fair Usage. This means that some users occasionally experience a limitation placed on their account. This limitation resets within 24 hours. If this issue persists, contact us through our [community forum](https://community.sourcegraph.com/), Discord, or email [support@sourcegraph.com](mailto:support@sourcegraph.com).

Thank you

**Comment by chenkc805** [comment]
What's your sourcegraph username? You can go to https://sourcegraph.com/settings and find it at the top, in between the parantheses `()`. For example, here my username is `kevin.chen`. 
<img width="622" alt="Screenshot 2024-12-08 at 5 28 26 PM" src="https://github.com/user-attachments/assets/fd27a180-58c0-4e59-9e3f-cc7893771403">

**Comment by tech-and-ai** [comment]
Hi Kevin, 

it was fixed from one of your colleagues on Twitter. For info my two accounts are ***@***.*** ***@***.***> and ***@***.*** ***@***.***> can you please whitelist me as not a bad actor to trigger your guard rails? 

Many thanks,

Leo.

Leo Ruocco
***@***.*** ***@***.***>
 <https://about.me/leoruocco?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>	
Leo Ruocco
about.me/leoruocco <https://about.me/leoruocco?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
