### ISSUE TITLE
llm-providers need proxy agent supports

### ISSUE THREAD

**Issue by Luoyayu** [sourcegraph/cody#6281]
https://github.com/sourcegraph/cody/blob/1f926b54570591658310a6735f51f66db666f2e1/lib/shared/src/llm-providers/google/chat-client.ts#L50

**Comment by PriNova** [comment]
Hey @Luoyayu 

Thank you for reaching us out.
For feedback or feature suggestions, please use our https://community.sourcegraph.com/ community forum instead.

Thank you
