### ISSUE TITLE
"This feature has been disabled by your Sourcegraph site admin."

### ISSUE THREAD

**Issue by alexwgold** [sourcegraph/cody#6291]
### Version

1.48.1

### Describe the bug

I'm using Cody on VSC on my macbook.  Everything going great but all of sudden I can't use control + k to edit or add code; it pops up with "This feature has been disabled by your Sourcegraph site admin." on the bottom right.

I'm a paid user and thought there were no limits, but it sounds like this might be bug instead?  (I also tried setting the chat to Claude 3.5 Sonnet instead of Deep Cody with no effect).

### Expected behavior

Normal control + k behavior where I enter a prompt and Cody does it's thing.

### Additional context

![Screenshot 2024-12-09 at 11 49 31 PM](https://github.com/user-attachments/assets/dc0294f2-cb2c-4865-913f-628edbec1f5d)

**Comment by alexwgold** [comment]
Update: quitting and restarting VCS fixed it, so no biggie. But I'll leave this issue submitted in case it helps y'all!

**Comment by vadi2** [comment]
I also hit this now using 1.61.1737039427, and restarting did fix it.
