### ISSUE TITLE
Clean Up Quickpick & Keyboard Shortcut Interactions

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#631]
The new Cody quickpick is the main in-editor experience for interacting with Cody, but a few things have happened since the initial design[^1]:
- `Refactor` commands were added to it as part of 0.6.5
- Internal testing and feedback that have outlined a number of problems and room for improvement
- Keyboard shortcuts are inconsistent (or missing)

We need to:
- Update the quickpick to handle refactors and better match the chat pane command interface
- Consolidate and clarify keyboard shortcuts
- Review editor contribution points (editor buttons, codelenses, status bars, etc)
- And overall, just ensure it's clear and simple to interact with Cody

Figma:
https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=4560-11184&mode=design&t=tINkTrd8OIADm9jT-4

- [x] Design
- [x] Reviewed & ready to go

[^1]: ![image](https://github.com/sourcegraph/cody/assets/153/ddcb4258-c593-4960-a72d-633298ff5f63)

**Comment by toolmantim** [comment]
[Design](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=4560-11184&mode=design&t=tINkTrd8OIADm9jT-4) ready for feedback:

![image](https://github.com/sourcegraph/cody/assets/153/e1d64039-9293-4f66-9863-b5a92d9f0f53)

**Comment by toolmantim** [comment]
Updated based on feedback:
![image](https://github.com/sourcegraph/cody/assets/153/c80a69ed-abf6-4f68-90cc-6eb3cbe48e36)

**Comment by chenkc805** [comment]
Looks great! 

Can we add back code spells as a command in 0.8.0? It's a pretty highly used and liked feature both qualitatively and quantitatively

Quant: https://sourcegraph.looker.com/explore/sourcegraph/cody?qid=KuBRB9BGwmUcMVaOrogrZG&origin_space=562&toggle=fil,vis
Qual: https://sourcegraph.slack.com/archives/C05AGQYD528/p1691595505023259

**Comment by toolmantim** [comment]
@chenkc805 yep, code smells are coming back.

Added to the Figma.

![image](https://github.com/sourcegraph/cody/assets/153/e3a0a12a-c64d-468b-b66b-4e2fefb75ffb)

This one is ready for some eng help now I reckon!

**Comment by toolmantim** [comment]
Considering this done! 🙌🏼
