### ISSUE TITLE
Improve first time user experience for the command changes

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#633]
In 0.6.5 we removed the small bit of onboarding we did have (the recipe buttons in the chat). We also removed the Recipes tab. We need to design better solutions to ensure people experience value, get the most out of trying Cody for the first time, and we improve day 1 retention.

- [x] Design
- [x] Reviewed & ready to go

**Comment by toolmantim** [comment]
@abeatrix’s suggestion:

![image](https://github.com/sourcegraph/cody/assets/153/d415527f-622a-4066-940f-cdc05c3cd7e4)

**Comment by chenkc805** [comment]
Can we tell the user about the shortcut in this intro text as well? Something like:

"Hello! I'm Cody. I can write code and answer questions for you.

Recipes are now Commands! **You can start using them with the CMD+Shift+V shortcut**. See Getting Started to learn more about Cody Commands"

**Comment by toolmantim** [comment]
Design ([Figma link](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=4615-12199&mode=design&t=14p1lRTa5m9H1bb3-4)):
<img src="https://github.com/sourcegraph/cody/assets/153/f23cb4f7-aecf-4b51-b4a9-503bc43c88c7" width="275"/>

Loom walkthrough:
https://www.loom.com/share/a46f952e764c49668614b87c54ba6767

Eng notes:
- I can implement the in-chat parts, as the SVG + protips is mostly front-end (and we already some good prop support from the old button code)
- Adding the command button to the input I'd need someone to take on, but that can come later

Questions:
- @abeatrix @umpox do you see any problems with moving the "Editor Title Button" feature on by default (not "Experimental") and remove it from the toggleable settings? (given you can hide it by right clicking and unchecking)
- There's no difference between the first chat, and new chats here. Probably fine for now! But it's easy to adapt anything for the new chat case if we need.
- There's no link to getting started guide… for first time install they open that open already, and I didn't want to distract them from starting to use Cody. But keen to sanity check this with others.

**Comment by chenkc805** [comment]
Left feedback in the Figma! Overall I think we need to simplify the onboarding flow, it's too difficult to grok right now

**Comment by toolmantim** [comment]
@chenkc805 had a chat and agreed that breaking the onboarding steps down into a more actionable, step-by-step experience is the goal.

But for 0.8.0 we can do something iterative in the welcome message, encouraging people to experience the following features (in priority order):

1. Autocomplete
2. In-editor commands
3. Chat

<img src="https://github.com/sourcegraph/cody/assets/153/1f80ff66-5909-4f07-828e-6f83b2e1afc2" width="275" />

It's a bit wordier than is ideal, but it's a tricky balance to include in a single screen. I've err'd on the side of helping those people that need some guidance. But in the future, breaking this up would help.

For now we can use this same design for both the first chat and new chats, and look at creating a "new chat" version after.

Dependencies:
- This would require making the Cody editor title button on-by-default (it's currently has to be enabled by the user in settings, and is marked as experimental)

**Comment by abeatrix** [comment]
> do you see any problems with moving the "Editor Title Button" feature on by default (not "Experimental") and remove it from the toggleable settings? (given you can hide it by right clicking and unchecking)

Id like that! It was on by default but Quinn made a good point about adding it when the feature is ready and surely lovable. 

Should we also add one to the chat view title bar?

**Comment by toolmantim** [comment]
> Id like that! It was on by default but Quinn made a good point about adding it when the feature is ready and surely lovable.

Okay, sounds like that itself is dependent on #631 — which integrates a number of Quinn’s feedback items

> Should we also add one to the chat view title bar?

My gut says don't think so to start with. We have a command button already in the chat input, and mention the keyboard shortcut. It would be an easy add though.

**Comment by chenkc805** [comment]
Thanks Tim! Agree that it's a lot of text but in lieu of a sequential conversational onboarding flow this will suffice for now. 

> My gut says no to start with, only because we want to drive them to the editor one for first time experience. And we have a command button already in the chat input, and mention the keyboard shortcut. It would be an easy add though.

Agree with this

**Comment by abeatrix** [comment]
@toolmantim thank you Tim! 
On another note, I actually find myself using the Cody code lens a lot! I know some people might hate it but I do think beginners would find it helpful, and the code lens lives inside the text doc too. Could that be something we can mention in the onboarding flow?

**Comment by toolmantim** [comment]
Yeah! Though there's only so many things we can point people to at once. Does it show in every type of file/language?

**Comment by toolmantim** [comment]
Also, I don't think they can miss the Cody code lens in the code! Which means maybe it doesn't need to be pointed out.

**Comment by abeatrix** [comment]
@toolmantim its currently behind a feature flag that needs to be enabled manually for it to pop up.
It will show up above any first level function, for all languages.

**Comment by toolmantim** [comment]
Updated to call out Cody Commands:

<img src="https://github.com/sourcegraph/cody/assets/153/568dda35-fce6-472b-9c65-527283a1fb37" width="275">
