### ISSUE TITLE
Not allowed to use GPT-4o with enterprise account

### ISSUE THREAD

**Issue by olejorgenb** [sourcegraph/cody#6370]
### Version

v1.50.0 (vscode: 1.95.3)

### Describe the bug

Use the edit code feature, specify GPT-4o as model. I get a dialog box with "Upgrade to cody pro". I'm logged into my enterprise account user. 

### Expected behavior

I can use GPT-4o (I'm allowed to use it from pycharm using same account)

**Comment by PriNova** [comment]
Hello @olejorgenb 

As an enterprise user, please open up a support ticket via the enterprise support channel.
So, we can better coerce such issues into the dedicated channel.

Thank you
