### ISSUE TITLE
Unable to sign in to Enterprise Instance 

### ISSUE THREAD

**Issue by iskyOS** [sourcegraph/cody#642]
When trying to sign in to a Sourcegraph instance (Sourcegraph's S2 server in this case), I am getting no response in the Cody extension. The error logging makes it look like a certificate issue, but S2's certificate isn't expired.

![Errors](https://github.com/sourcegraph/cody/assets/13739780/e62a8d2d-be55-47b4-b8de-560d049d2938)

https://github.com/sourcegraph/cody/assets/13739780/69646f0c-b39e-427c-8daa-898f925fb715

Devtools console:
```
console.ts:137 [Extension Host] FetchError: request to https://sourcegraph.sourcegraph.com/ failed, reason: certificate has expired
	at ClientRequest.<anonymous> (/Users/alexisken/.vscode/extensions/sourcegraph.cody-ai-0.6.5/dist/extension.node.js:15855:18)
	at ClientRequest.emit (node:events:525:35)
	at TLSSocket.socketErrorListener (node:_http_client:481:9)
	at TLSSocket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by iskyOS** [comment]
> @iskyOS what's the version of the plugin?

@jdorfman v0.6.5

**Comment by jdorfman** [comment]
@iskyOS what happens when you go to: `https://sourcegraph.sourcegraph.com/users/YOUR-USER-NAME/settings/tokens/new/callback?requestFrom=CODY` in a browser?

**Comment by iskyOS** [comment]
It does prompt me to open VS Code, but then I don't get any feedback after it attempts to authenticate:
https://github.com/sourcegraph/cody/assets/13739780/f541c3ac-396f-48fa-b72d-e0ae2f435afe

![CleanShot 2023-08-10 at 11 33 24](https://github.com/sourcegraph/cody/assets/13739780/dea1aa49-ede1-46ef-bc18-1470f9eca1ef)

**Comment by jdorfman** [comment]
Thanks for the video!

Try the following:

1. `⌘+shift+p`
1. type command Clear Editor History
1. Press Enter

Then try again. If that fails, 

1. Remove Cody
1. Run Clear Editor History
1. Reinstall Cody

**Comment by iskyOS** [comment]
No luck :/ I'm getting the same error.

![CleanShot 2023-08-10 at 11 56 36](https://github.com/sourcegraph/cody/assets/13739780/0badcac1-c89d-40b0-b42a-d8ee9119c166)

I also tried uninstalling VS Code, removing all VS Code and extension files from my mac via terminal, and then reinstalling VS Code and using a new profile without settings sync. That had the same result too.

**Comment by iskyOS** [comment]
I've found a solution for now. I'm using the workaround found here: https://github.com/microsoft/vscode/issues/136787#issuecomment-969065291

I switched this setting to false: `http.systemCertificates`. Now it is letting me log in to S2.

![CleanShot 2023-08-10 at 14 33 42](https://github.com/sourcegraph/cody/assets/13739780/e156ffb9-ff36-461b-822f-e5f376bda1e3)

**Comment by iskyOS** [comment]
Resolved for now with the fix above.

**Comment by jdorfman** [comment]
@MaedahBatool this might be a good canidate for the docs
