### ISSUE TITLE
Грузит до бесконечности, а при изменении запроса, выдает ошибку 

### ISSUE THREAD

**Issue by TheEmirka** [sourcegraph/cody#6445]
Type: <b>Feature Request</b>

## Extension Information

- Cody Version: 1.52.0
- VS Code Version: 1.96.2
- Extension Host: desktop

##  Steps to Reproduce

1.
2.
3.

## Logs

Extension version: 1.52.0
VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by PriNova** [comment]
Hey @TheEmirka 

Thank you for reporting the issue. We are not able to reproduce this issue. Please open a new bug report with a detailed description of the steps about this issue.

Thank you
