### ISSUE TITLE
o1-preview early termination

### ISSUE THREAD

**Issue by AlfredoSandovalx** [sourcegraph/cody#6453]
[cody_1735031928433.log](https://github.com/user-attachments/files/18238249/cody_1735031928433.log)
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.53.1734972437
- VS Code Version: 1.96.2
- Extension Host: desktop

##  Steps to Reproduce
Open or create the MATLAB file (.m extension) in Visual Studio Code where the Cody extension is active.
Copy and paste your entire script (approximately 675 lines) into the Cody Chat window, and request an action such as:
“Fix any broken MATLAB syntax” or “Refactor this code”.
In this case, Cody abruptly stopped generating output around line 182, leaving the remainder of the code incomplete (lines 183–675 missing). This similarly occured with Flash2.0

Expected Behaviour
Cody should process the entire code snippet and provide complete suggestions or transformations, without prematurely cutting off the output.

Actual Behaviour
The o1-preview ends early or truncates the code response, causing incomplete suggestions and halting mid-code. This does not occur with o1 or o1pro in the web UI or W11 desktop app. 

## Logs

Extension version: 1.53.1734972437
VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13950HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.76GB (33.70GB free)|
|Process Argv|--crash-reporter-id cf5f6ea1-7412-4295-b444-0ccb15194787|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by PriNova** [comment]
Hey @AlfredoSandovalx 

This is a known issue and the cause is that the output window size is capped at 4k tokens. If the reply exceeds this limit, then an error appears.

The team is evaluating if an increase makes sense in this tier plan.

Sorry for the inconvenience.
