### ISSUE TITLE
Delete/Update old context in a chat.

### ISSUE THREAD

**Issue by blazgocompany** [sourcegraph/cody#6485]
### Version

1.95.3

### Describe the bug

If I give Cody context, then I change it manually, and want Cody to see the new stuff, I have to mention it in context again... This is ok... but now with gemini 2 flash, It keeps looking back to the oldest version for some reason (I think). So I think the old context should be deleted or updated.

### Expected behavior

N/A?

**Comment by PriNova** [comment]
Hey @blazgocompany 

What can help here with Gemini Flash is to explicitly mention the changes made during the conversation. If it is too tedious, you can use that instruction in the pre-instruction settings for the chat, found in the Cody settings.
Another option is to start a new chat and mention the changed file.

Thank you
