### ISSUE TITLE
Copy Message Button

### ISSUE THREAD

**Issue by AlfredoSandovalx** [sourcegraph/cody#6493]
Type: <b>Feature Request</b>

Could we get a copy message button? I would like to paste some of my cody chat messages into my obsidian notebook. 

Extension version: 1.55.1735238533
VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by PriNova** [comment]
Hey @AlfredoSandovalx 

We appreciate your feedback. For this we have a community forum, where this request has already been made: https://community.sourcegraph.com/t/copy-button-on-responses/1713

Thank you very much
