### ISSUE TITLE
Update notice w/ link to release post

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#653]
We need a way for notifying people that there's been a Cody release (minor version, not patch), w/ a link to an announcement post to explain what's changed. The goal being to bring people on the journey with us as we improve Cody: understand the changes, get excited, a share it with their colleagues and the world.

- [x] Design
- [x] Reviewed & ready to go

**Comment by toolmantim** [comment]
<img src="https://github.com/sourcegraph/cody/assets/153/02408042-d6b6-4efa-b3f5-a0196cc0a181" width="275">

https://github.com/sourcegraph/cody/assets/153/bb45f229-cb55-4e94-acb7-9f6b4b61967b

Figma:
- [Design](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=4655-12897&mode=design&t=nkSBtl6vjShXNV9H-4)
- [Prototype](https://www.figma.com/proto/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?page-id=3250%3A136841&type=design&node-id=4655-12898&viewport=1373%2C-18668%2C1&t=NwKfMw7l4wgK5npR-1&scaling=min-zoom&starting-point-node-id=3532%3A142502&show-proto-sidebar=1&mode=design)

Notes:
- Top position was chosen instead of bottom to avoid clashing with the command menu and stop generating button
- It uses the same styles as the [command popup menu](https://github.com/sourcegraph/cody/blob/main/vscode/webviews/ChatCommands.module.css) aside from the border-radius
- Sparkles SVG should use `var(--vscode-textLink-foreground)`

**Comment by philipp-spiess** [comment]
This is so pretty ✨

**Comment by toolmantim** [comment]
I'll get started on the frontend side of this (and #667)

**Comment by toolmantim** [comment]
Versions could also add callouts for specific big changes, e.g. recipes → commands:

<img src="https://github.com/sourcegraph/cody/assets/153/4648c8af-72aa-4c67-aa46-e14681875a6e" width="275">
