### ISSUE TITLE
[Research] VS Code - First time experience for /commands

### ISSUE THREAD

**Issue by meglynst** [sourcegraph/cody#654]
Target week: August 14

Designer: @toolmantim

Design issue: https://github.com/sourcegraph/cody/issues/633

Prototype:

Questions to answer:
- How discoverable are commands?
- What expectations do users have about /commands before using them?
- Do users try a command during their first use of Cody?
- Evaluate usability of /commands for first time users.

Test Plan(s):
[VS Code Cody - First time experience /commands (Aug 14)](https://app.usertesting.com/st/XPG7y7PCUGUqEB2Yu4SU?shared_via=link&share_id=aNScpiALCu)

Results:
https://docs.google.com/spreadsheets/d/1ZWHrw2PWLL4x0bg4woWtRo-dmd4ycQfBeG9s7RQLMis/edit?usp=sharing

Share out:
https://sourcegraph.slack.com/archives/C05KNUVR9CL/p1694525153676509

**Comment by meglynst** [comment]
@toolmantim This is the research issue I've created in regards to user testing for the new first time UX in VS Code (slack: https://sourcegraph.slack.com/archives/C05AGQYD528/p1691674809056849). Some asks for you:

1. Are the research questions good? Would you alter or add any? I try to keep a limit of 3 - 4 questions since the test itself will be about 10 - 15 minutes max.

2. What were you thinking in terms of a prototype? Figma prototype? Or live in VS Code (this will require testers to install the Cody extension first)? I just need to know to better write the test plan. 

For these kinds of quick tests, I'll build the test plan right in usertesting.com and link to it right here in the ticket. Once we've agreed on questions to answers, I'll go ahead and build that test plan and then follow up to get you (and the team's -- > @abeatrix @chenkc805 etc.) feedback about the plan itself.

**Comment by chenkc805** [comment]
Thanks for kicking this off! Excited to learn more. CC: @csells and @taylorsperry for visibility into commands

I'm curious what people's expectations are of commands. So when they see the command palette, asking them "What do you expect each of these things to do?"

**Comment by meglynst** [comment]
@toolmantim @abeatrix
Currently, I'm having users start from the VS Code marketplace page (https://marketplace.visualstudio.com/items?itemName=sourcegraph.cody-ai) and clicking install for this test.
If we ran this test right now, what authentication options do users have after they've installed the extension? Do we need to have users create Sourcegraph accounts for this test? Since we're not testing those first few steps (installing, signing in, etc.), just commands, I want to make it as frictionless as possible so we can get them to using commands as quickly as possible.

One option is to have them sign in with an [S2 account we use for testing purposes](https://docs.google.com/document/d/1RdP5cQua3RwpCU04YdkV-_KKNMvHUKY34vQzkccPVs0/edit). However, will this affect other people (e.g. they won't have a true "first time" experience) if each tester is logging into the extension with the same credentials? Does this put S2 at risk in any way?

**Comment by chenkc805** [comment]
I think it's fine to use the S2 account for testing purposes, since our onboarding is evolving all the time at the moment and the goal of this is to get feedback regarding commands and the command interface. 

The current onboarding flow is too cumbersome to go through for UXR purposes (they'll have to create an account, get confused because they'll think they have to download a cody app, etc.)

**Comment by meglynst** [comment]
This is the test plan I have for this test at the moment in usertesting.com:

![Image](https://github.com/sourcegraph/cody/assets/9790559/cd3e4af9-ac85-4c07-8a52-bf0ff9a797d4)

The two "Image Tasks" are how to log in and sign out of Cody AI (it's a little tough to describe so I wanted to use images).

@toolmantim (and team) let me know what you think!

**Comment by toolmantim** [comment]
I agree it's a good idea just to give them some credentials to use.

> This is the test plan I have for this test at the moment in usertesting.com

That test plan looks good to me! Are 3+4 meant to repeat?

Tiny nit: we've standardised on Cody instead of Cody AI.

> Does this put S2 at risk in any way?

No idea! That's a question for tech ops / engineering.

**Comment by meglynst** [comment]
There was repetition! I've removed Task 4.

In regards to Cody AI, I wasn't sure if we should keep referring to it as "Cody AI" or "Cody" for VS Code tests going forward because the extension itself is called "Cody AI."
