### ISSUE TITLE
Cody for IntelliJ - Thumbs up/down feedback button

### ISSUE THREAD

**Issue by baristaGeek** [sourcegraph/cody#694]
I'm using Cody for IntelliJ and it would be very nice to add the thumbs up/down feedback button the same way the VS Code version has it. It's a very nice UX that helps the end user give feedback to the model. 

IntelliJ doesn't have the buttons:
<img width="1079" alt="Screen Shot 2023-08-15 at 11 50 52 AM" src="https://github.com/sourcegraph/cody/assets/8325094/282e3825-e13a-494b-afed-c7a50ad518f4">

VS Code has them: 
<img width="474" alt="Screen Shot 2023-08-15 at 12 03 47 PM" src="https://github.com/sourcegraph/cody/assets/8325094/88afaede-69ff-4791-a8b6-41a242e7e499">

**Comment by jdorfman** [comment]
Thanks @baristaGeek, great feedback.
