### ISSUE TITLE
`/search` does not pin scroll position

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#699]
Repro steps:

In Cody 0.6.7, open chat, scroll to the bottom, type `/search foo`

Expected behavior:

Search results scroll into the viewport.

Actual behavior:

Search results appear "below the fold" and you have to scroll to see them.

**Comment by deepak2431** [comment]
@dominiccooney I can reproduce this issue. Will fix it and make a PR for this.

**Comment by deepak2431** [comment]
Also, I realised that the search is more like a command, so shall we include this in to list of commands?
CC: @abeatrix WDYT?

**Comment by deepak2431** [comment]
@abeatrix Got that, so shall I wait until the refactor is done to work on the first part of this issue too?

**Comment by abeatrix** [comment]
I think the UI will still be the same so I'd say yes. Thanks for checking 😊
