### ISSUE TITLE
Not recognizing correct language

### ISSUE THREAD

**Issue by ToddHoward42069** [sourcegraph/cody#709]
I have this issue for a long time now. When I want something from cody, I write in english but instead of answering my question or request, it says that my prompt, apparently is German and that it cannot understand German, eventough I wrote my prompt in english.
![problem](https://github.com/sourcegraph/cody/assets/89554916/aebd6ade-a3f1-474a-bb20-18b356051dfd)

**Comment by jdorfman** [comment]
Interesting. @deepak2431 is this something you have come across?

**Comment by deepak2431** [comment]
Hey @jdorfman, I never came across this issue, and not sure how Cody responds in a language other than English.
@ToddHoward42069 Are you using the VSCode or the JetBrains extension? Also, please drop some logs here if the issue is still there.

**Comment by arafatkatze** [comment]
https://github.com/sourcegraph/cody/assets/11155207/1d00accb-76d3-4c5f-86c9-09c64a185bfe

**Comment by jdorfman** [comment]
@deepak2431 VS Code. And yes, thank you for the screenshot @ToddHoward42069, logs would be great if possible.

**Comment by dominiccooney** [comment]
Cody picks up a language code from the VScode locale, so if it wants to speak German, that could be one likely cause (although from your screenshot I see the menus are in English...) @ToddHoward42069, you can confirm this by going to Settings and checking Cody > Debug: Enable, then going View, Output, change the dropdown to Cody by Sourcegraph, do a chat and search for "in the language with RFC5646/ISO language code" and see what comes right after that. For English should be "en". Cmd-Shift-P Configure Display Language can change this.

Could you starting a new chat with + and see if the problem persists with a short transcript?

**Comment by jdorfman** [comment]
@ToddHoward42069 can you please confirm if ⬆️ works for you? We want to make sure you are taken care of. :)

**Comment by ToddHoward42069** [comment]
Hello again! I couldn't find the "in the language with RFC5646/ISO language code" section in the output and all the logs are somehow empty. I did a little chat with it, marking some code and asking a question in English. It answered back in German, telling me that it couldn't understand my "German" request and that I should tell it in English but I think, since the last (2 ?) updates, it got better. It still has that issue but when I told it, that my question was in English, it answered my request perfectly fine in English. It understood my request, even tough it thought it being German

**Comment by kalanchan** [comment]
@ToddHoward42069 can you provide some screenshots of the terminal output (logs)? 

it should look something like this:

<img width="993" alt="CleanShot 2023-08-21 at 15 55 24@2x" src="https://github.com/sourcegraph/cody/assets/51868853/ec7ff8ae-4d3f-4fd3-9755-83c035b354ed">

**Comment by abeatrix** [comment]
I can also reproduce the issue when asking Cody "What is React" (什麼是React) in Chinese:
![image](https://github.com/sourcegraph/cody/assets/68532117/e1a69ce3-aa16-4e76-9163-f00f4908f382)

However, it seems like it only happens to the first question if it's asked in a language that is not the same as the default language of your VS Code:
![image](https://github.com/sourcegraph/cody/assets/68532117/4f9b7794-90bd-419e-a1b5-66014c66d24e)

**Comment by dominiccooney** [comment]
@ToddHoward42069 you may also need to check Cody Debug Verbose in Settings to get complete log output.

Could you tell us your OS version, system language, and VScode version? It would be great if you are able to share a Cody log file with us for analysis. These contain your chat messages, some source code content, and so on. It would be very interesting to see the logs around the time it started to do this.  You can get logs in VScode from the command palette, Developer, Open Extension Logs Folder and there will be an output_logging_.../...Cody by Sourcegraph.log log file in there.

CC @jdorfman

I also tried to reproduce this yesterday, and had basically the same observation was @abeatrix .

**Comment by deepak2431** [comment]
> Hello again! I couldn't find the "in the language with RFC5646/ISO language code" section in the output and all the logs are somehow empty. I did a little chat with it, marking some code and asking a question in English. It answered back in German, telling me that it couldn't understand my "German" request and that I should tell it in English but I think, since the last (2 ?) updates, it got better. It still has that issue but when I told it, that my question was in English, it answered my request perfectly fine in English. It understood my request, even tough it thought it being German

Hey @ToddHoward42069, In case your logs are empty after enabling both `Cody > Debug: Enable` and `Cody > Debug: Verbose` then can you please check your Cody `settings.json` file it should not have an option as `cody.debug = true` because somehow this setting overrides the other two.

**Comment by DanielProg39** [comment]
I have the same issue. I use VSCode with russian language pack. Cody complains about me writing in russian if the language pack is enabled or display language is set to russian. If I set display language to English, Cody works as intended.
![image](https://github.com/sourcegraph/cody/assets/63293432/c070648c-5b96-4508-92ac-433b1bb1d003)

**Comment by DanielProg39** [comment]
So unfortunately, the extension is not working at all at the moment, so I may stick to other AI assistants until this issue is resolved.

**Comment by jdorfman** [comment]
Thanks for reporting @DanielProg39 

We will dig in.

**Comment by DanielProg39** [comment]
This seems to have been fixed a long time ago, I don't have any problems anymore. Thanks to the developers for noticing and fixing it. Can be closed, I guess.
