### ISSUE TITLE
Update Sourcegraph Sign In page to have email form inlined

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#716]
As part of the sign in changes of #632 there will be a single link in VS Code for existing and new users to login with email and password.

Without changes, the flow will be:
1. Click "Continue with email" in VS Code, be taken to sign up email page
2. Click "Existing user? Sign In" and be taken to sign in page
3. Click "Other login options" and be taken to a form to enter email/username and password
4. Enter login details

We want to remove step 3, and simplify this for existing users:
1. Click "Continue with email" in VS Code, be taken to sign up email page
2. Click "Existing user? Sign In" and be taken to sign in page
4. Enter login details

We can do this by combining the following two screens into one:

<img width="1324" alt="Screenshot 2023-08-16 at 10 55 1" src="https://github.com/sourcegraph/cody/assets/153/c914799e-7f6d-472a-9118-64ecdfe9cfcc">

<img width="1324" alt="Screenshot 2023-08-16 at 10 55 2" src="https://github.com/sourcegraph/cody/assets/153/0262ac9b-0fe1-4f4d-aac3-61c5503eb87b">

The form needs to be placed inline, below the GitHub/Gitlab sign in buttons.

**Comment by toolmantim** [comment]
Designs:
https://www.figma.com/file/Lof1Rm85caih7S0J749ZSZ/Untitled?type=design&node-id=0-1&mode=design

| Dark | Light |
| - | - |
| <img src="https://github.com/sourcegraph/cody/assets/153/43a2a515-c0e5-4049-bafb-ca1791a7409a" width="565"> | <img src="https://github.com/sourcegraph/cody/assets/153/2222e1e0-2782-4859-ad26-e9e14c2b3326" width="565"> |

**Comment by chenkc805** [comment]
Thank you Tim!!

**Comment by toolmantim** [comment]
Closing for now, as email login has been removed

**Comment by toolmantim** [comment]
@chenkc805 sorry, just realised you were assigned to this, and not me! Feel free to re-open and I'll leave it alone until I'm needed

**Comment by vdavid** [comment]
I'll reopen it then!
