### ISSUE TITLE
Can't use commands

### ISSUE THREAD

**Issue by perrylets** [sourcegraph/cody#736]
Every time I run "Cody Commands" in VS Code, this error message appears:

```
Command 'Cody: Commands' resulted in an error
Expected ',' or '}' after property value in JSON at position 1632
```

I'm guessing this is a typo I made in the cody commands configuration but the line number is too big for that and every time I try to open the json file nothing happens.

**Comment by jdorfman** [comment]
Hi @perrylets can you share lines `1620` - `1640` from your `cody.json` file?

**Comment by perrylets** [comment]
Where would it be located?

**Comment by deepak2431** [comment]
@perrylets You can find the `cody.json` file under your .`vscode` folder which would be present in your project root directory. 
You are right about your guess, if you have added any new custom commands manually then you might have done some syntax error while doing so.

**Comment by perrylets** [comment]
@deepak2431 It's not there. I tried finding in in the global vscode files but I can't find it.
![image](https://github.com/sourcegraph/cody/assets/62119804/765f6cd9-dfa4-4244-94a0-033da6f5bc85)

**Comment by deepak2431** [comment]
Not sure, but it should be present there. Can you try to open the commands window with the shortcut `Option + C`, click the `Configure Command Window` option, and you will see a window to open the `cody.json` file? You can check it there once. Hope this helps!
![iScreen Shoter - Code - 230819112851](https://github.com/sourcegraph/cody/assets/44617923/137eec8a-731b-4a0d-9842-5a899aa0253e)

**Comment by jdorfman** [comment]
@perrylets if you are still stuck we can hope on a call. DM me on [our Discord](https://discord.com/servers/sourcegraph-969688426372825169)

**Comment by perrylets** [comment]
> Not sure, but it should be present there. Can you try to open the commands window with the shortcut `Option + C`, click the `Configure Command Window` option, and you will see a window to open the `cody.json` file? You can check it there once. Hope this helps! ![iScreen Shoter - Code - 230819112851](https://user-images.githubusercontent.com/44617923/261777962-137eec8a-731b-4a0d-9842-5a899aa0253e.jpg)

I'm using Windows so it would be `alt + c` (but that doesnt matter). But when I press it I get the same error message, but as a VS Code notification.

**Comment by deepak2431** [comment]
Hey @perrylets , I tried to reproduce this by deleting the `cody.json` file, but that won't cause any issue, as `cody.json `is in case you want to use custom commands. Also,  if the cody.json doesn't exist, one is created automatically. 
So, I am really not sure what is causing this. I hope you will be able to sort this out during the call with Justin.
