### ISSUE TITLE
Add info to autocomplete analytics events about embeddings availability.

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/cody#754]
Add info to autocomplete analytics events about embeddings availability.

[Relevant Slack thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1692354105120879).

**Comment by chenkc805** [comment]
Hey Valery, could you clarify specifically which analytics events we're adding this metadata to, and what the expected outputs of info mean (TRUE = this, FALSE = this, NULL = that)? Thanks
