### ISSUE TITLE
Improve context search display text

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#756]
The display text is just the query input for the context search. It would be good to update the display text as `"Query for: "query_name"` or `Search for query_text`. 

This is how it is now:
![iScreen Shoter - Code - 230821125155](https://github.com/sourcegraph/cody/assets/44617923/7a1b5ba7-360d-4643-8f9f-76da0ad7a106)

CC: @toolmantim WDYT of this?

**Comment by jdorfman** [comment]
Thanks @deepak2431!

**Comment by deepak2431** [comment]
@toolmantim If you have checked this, can you please let me know your views on this?
