### ISSUE TITLE
Stop generating button shows error message in UI

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#757]
On clicking the stop generating button after asking Cody something it shows a new error message in the UI as `Request failed: Socket hangup` or `Request failed: Aborted`

https://github.com/sourcegraph/cody/assets/44617923/57c61308-fe99-46c3-83ba-00d6e0371dde

CC: @abeatrix @philipp-spiess

**Comment by jdorfman** [comment]
@deepak2431 ty. What version of the plugin?

**Comment by deepak2431** [comment]
@jdorfman While testing in the dev mode, I came across this issue.
