### ISSUE TITLE
Command menu button doesn't work during Edit

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#758]
The Cody commands menu button in the input field doesn't work while Editing the input query.

https://github.com/sourcegraph/cody/assets/44617923/8b5b0215-339b-4f17-b6d1-67e214c1b66c

CC: @toolmantim WDYT? I think it would be better to hide the commands menu button from the text field during the edit.

**Comment by jdorfman** [comment]
ty @deepak2431 what version?

**Comment by deepak2431** [comment]
@jdorfman While testing in the dev mode, I came across this.
