### ISSUE TITLE
It shows '&gt' instead of '>' in inline chat

### ISSUE THREAD

**Issue by adarmanto** [sourcegraph/cody#780]
When I used inline chat, the result is a bit messy:

![image](https://github.com/sourcegraph/cody/assets/26041956/910607be-907f-44e9-9f96-298ee9957b51)

Cody AI v0.8.0
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-79-generic

**Comment by jdorfman** [comment]
Thanks @adarmanto for all of the details! I will make sure to get some eyes on this.

**Comment by abeatrix** [comment]
Fixed in https://github.com/sourcegraph/cody/pull/1349
Will be included in the next release 0.16.0
