### ISSUE TITLE
Cody app stops generating if you CMD+TAB away

### ISSUE THREAD

**Issue by chambliss** [sourcegraph/cody#805]
Sometimes I'll ask a question and then context switch to do something else while I wait for the generation to finish, but Cody seems to prefer to have window focus while generating. If I tab away to do something else, it'll stop generating, and won't continue until I come back. @jdorfman was able to repro when we chatted on Discord.

Example screencast: I ask a question, tab away, it doesn't start generating until I tab back in, I tab away again, and it again stops until I come back. 

I did find that it continued generating when I tabbed away to edit the video, so unfortunately it seems to be nondeterministic 😂

Let me know if there would be anything else helpful to add here! I'm on an M1 Pro, MacOS Ventura 13.4.1 (c). Cody app version is Version 2023.7.11+1384.7d20a90ce7 (20230711.153956).

https://github.com/sourcegraph/cody/assets/43484165/98211df7-fb84-4dd2-8ab4-2fa70c03d310

**Comment by jdorfman** [comment]
Thanks @chambliss for creating this issue and providing the screen recording.
