### ISSUE TITLE
Ask Cody fix doesn't work perfectly

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#824]
The Quick Fix "Ask Cody" results are not that good. It just can't suggest fix for some minor issues like import issues, or variable typos in some cases. Also, I think it should have some more context about the codebase when it suggests the fix.

**Comment by arafatkatze** [comment]
Hi @deepak2431,
Can you provide some examples of the precise problems that you are facing? My understanding is that this issue is very analogous to this issue -> https://github.com/sourcegraph/cody/issues/585 but I would still love to see concrete examples to know the problem to solve

**Comment by arafatkatze** [comment]
@deepak2431 there was a lot of work done on this issue so you should be a lot happier with the current results. Feel free to raise it again if you face any troubles
