### ISSUE TITLE
Adding GPT4 with 32K support as enterprise option would be amazing

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#843]
<img width="584" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/bea3d824-85b3-4577-be98-f97696c843f5">

[Original Blog post](https://openai.com/blog/introducing-chatgpt-enterprise)

I understand that switching LLMs etc is easy in cody but knowing this ability to offer high speed and unlimited usage of GPT4 with 32 K window can be great for the future of Cody.

**Comment by jdorfman** [comment]
Hey @arafatkatze do you have an enterprise instance? If so I can get you in touch with your technical advisor and see if this is something we can turn on. _Might be possible_.

**Comment by arafatkatze** [comment]
@jdorfman I do not, I was just very interested in somehow getting access to GPT-4-32K window and use it for my private work, I don't have the key permissions for 32K just yet but I would be very curious to get it down the line and try that out.

**Comment by arafatkatze** [comment]
This feature already exists
