### ISSUE TITLE
VS Code should show indexing status progress when Cody App is indexing

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#85]
When a repository is being indexed by Cody App, we should show some indication of progress within VS Code:

<img width="412" alt="Screenshot 2023-06-27 at 10 25 19 am" src="https://github.com/sourcegraph/sourcegraph/assets/153/841803f7-3266-471f-ab73-46c8d4a0b63c">

[Figma](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/🤖-Cody-VS-Code-[Main]?type=design&node-id=3880-144460&mode=design&t=yiKLUGyI26gkpoYS-4)

**Comment by abeatrix** [comment]
new design available
