### ISSUE TITLE
Cody Gateway access not enabled Error 403

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#859]
Cody was working perfectly for me when all of  a sudden I started getting this error 
<img width="415" alt="Screenshot 2023-08-29 at 9 50 45 PM" src="https://github.com/sourcegraph/cody/assets/11155207/419310a0-db30-4efd-8774-1a4903059fb6">

<img width="742" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/5c272d79-e9bd-4532-8460-c3cfb8aa8dbc">

I removed the cody desktop app and installed it again and now the error went away but I wonder why I faced the transient error in the first place and perhaps other people are facing it too. I thought it was a versioning issue but then reloading my deleted app and compared it with my latest downloaded app, they were both the same version.

Nothing serious but if this is a common thing then it's worth looking into.

**Comment by jdorfman** [comment]
Thanks for reporting @arafatkatze 

Didn't see anything on our [status page](https://sourcegraphstatus.com/) so It could have been a hick-up on our end.

**Comment by arafatkatze** [comment]
Thanks for letting me know.

**Comment by arafatkatze** [comment]
The issue has been solved ages ago
