### ISSUE TITLE
VS Code embeddings status should use new icons and tooltips

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#86]
VS Code embeddings status should use new icons and tooltips, and should link to the correct page on Cody App or the SG Instance where they can inspect that repository and take action (e.g. for SG instances: an admin can click "Embeddings" on the SG instance’s repo page and try to fix it. For Cody App: the repositories settings page).

[Figma with all the icons and tooltips](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=3863-147807&mode=design&t=Fxwsn8RfZRYm3QVt-4)

https://github.com/sourcegraph/sourcegraph/assets/153/b7f9c5aa-dc0e-4144-811c-17eaa639ca55

**Comment by abeatrix** [comment]
new design available
