### ISSUE TITLE
L: Extensions must configure autocomplete provider client-side even if proxied through Sourcegraph instance

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/cody#931]
Currently the autocomplete provider in the extension must be manually selected if a user is not using the default Anthropic provider.

Sourcegraph instances can be be configured to use the following providers for autocomplete:

- Sourcegraph gateway 
- Anthropic (using own keys)
- Azure OpenAI (using own keys)

When an extensions connects to a sourcegraph instance the correct autocomplete provider should be defaulted based on the how the instance is configured.  For example if the sourcegraph instance is using the Azure OpenAI provider the extension should default to using the `unstable-openai`

**Comment by chwarwick** [comment]
Some potential solutions:

- Extending the current feature flag based solution to work for instances that are not sourcegraph.com

_I think this is a reasonable approach if we end up in a situation where we need a quick solution but isn't ideal_


- Extending the current logic that gets the [LLMConfiguration](https://sourcegraph.com/github.com/sourcegraph/cody@9f441116ca2ca8f599c5b567ec417454f5ed01c9/-/blob/lib/shared/src/sourcegraph-api/graphql/client.ts?L264:18&popover=pinned)  to include enough information to properly select an autocomplete provider.  To me this feels like a better long term solution.

_To properly select the extension autocomplete provider the site completion provider and model are potentially needed.  When using the sourcegraph provider the model will be prefixed with the type openai, anthropic etc... If using Azure OpenAI the provider is the relevant piece of information as the model name is user defined and therefore isn't useful._

**Comment by taras-yemets** [comment]
- https://github.com/sourcegraph/sourcegraph/pull/56568
- https://github.com/sourcegraph/cody/pull/1035
