### ISSUE TITLE
Error when running Cody in VSCode Remote Development

### ISSUE THREAD

**Issue by mihem** [sourcegraph/cody#942]
When running VSCode remotely via ssh and Remote Deveopment, VSCode advises to re-install Cody AI.
However when using Cody the following error occurs:

```
Request failed: {"message": "rate limit exceeded"} 
```

My remote machine uses Ubuntu 22.04.3 LTS, my local machine uses the same OS and CodyAI with VSCode works fine here.

I am not sure if this is this a bug or a feature request because remote usage is not supported yet.

Thanks!

**Comment by jdorfman** [comment]
@mihem we had to cap our quotas due to an incident. You can get more up to date info here: https://discord.com/servers/sourcegraph-969688426372825169

Going to close this.
