### ISSUE TITLE
Autocomplete: Cody suggests the same code non-stop

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#944]
As mentioned in https://github.com/sourcegraph/cody/issues/811#issuecomment-1699218349

> once a suggestion is accepted, Cody suggests the same code completion again.

I can reproduce this when asking Cody to make suggestions at the end of file:

![image](https://github.com/sourcegraph/cody/assets/68532117/52291ad1-ca99-4434-a035-04576eec7291)

### Video

https://github.com/sourcegraph/cody/assets/68532117/f5194527-ff64-4034-a638-16a85e5823b2

**Comment by philipp-spiess** [comment]
@abeatrix I’m curious what the difference between this issue and #811 is? 🤔

**Comment by abeatrix** [comment]
might be a misunderstanding 😅 

I thought https://github.com/sourcegraph/cody/issues/811 is about cody suggesting code that is already presented in the code, without suggesting it repeatedly:
![nonrepeated](https://github.com/sourcegraph/cody/assets/68532117/b92f9889-08f2-471f-89c0-f9476345a1de)

where this one https://github.com/sourcegraph/cody/issues/944 is about suggesting code that has already been accepted.

**Comment by philipp-spiess** [comment]
@abeatrix Oh, gotcha. I think in this case it's the same root cause though since we do a new completion request

**Comment by abeatrix** [comment]
resolved with new infill mode: https://github.com/sourcegraph/cody/pull/974
