### ISSUE TITLE
Autocomplete: Audit cache and last candidate behavior

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#969]
> After making some minor changes to the surrounding code, I am still getting the suggestion returning from cache 

![image](https://github.com/sourcegraph/cody/assets/458591/6549c6a9-c4c2-41dc-9a84-d7adb7058420)
![image](https://github.com/sourcegraph/cody/assets/458591/f329e4fd-0250-4bbe-8275-b5cf845c5d09)

> Deleting a line should force a new creation always

We should validate these things:

- Does the last candidate properly reset if you delete a line (and thus reject the completion)
- Does the last candidate reset if you change the prefix
- Do we still need the network cache at all? What is the current value it provides?
- I noticed that hovering over a single line completion generates a variant right now

**Comment by abeatrix** [comment]
umbrella 
- [ ] audit cache behavior
- [ ] audit the last candidate's behavior
- [ ] https://github.com/sourcegraph/cody/issues/1030
