### ISSUE TITLE
Update /get-cody for app-less onboarding experiment

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#978]
Mock: https://docs.google.com/drawings/d/1O-tB3SUljrJxztvWn5Nmtzlxme5mypMjFIiyhqwAuAI/edit

**Comment by chenkc805** [comment]
working on getting designs from @traceyljohnson at the moment

**Comment by chenkc805** [comment]
Btw - @dominiccooney did we discuss you working on updating /get-cody and /sign-in? It's alright if not, I can ask @thenamankumar if he can take this work on

**Comment by dominiccooney** [comment]
@chenkc805 we talked about it in general, but I have my hands full with VScode so if @thenamankumar can do it, that's great. I will share more in Slack.

**Comment by chenkc805** [comment]
Mock 2 and Mock 3 are no longer relevant since we've disabled email+pw due to the security incident. The Google drawing has been updated to reflect this.

**Comment by thenamankumar** [comment]
I am taking this up

**Comment by vdavid** [comment]
I got tagged in the mock so went ahead and created [this PR](https://github.com/sourcegraph/sourcegraph/pull/56578) as a quick fix before noticing this issue. Naman, do you think we need anything else here?

**Comment by traceyljohnson** [comment]
[Figma file](https://www.figma.com/file/bzrwwnI9GXjG3WbkvN2rMM/Get-Started-with-Cody?type=design&node-id=910%3A3334&mode=design&t=awooI0li6HgrLO4Q-1) is ready @thenamankumar
