### ISSUE TITLE
Remove email+pw signup from marketing website

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#979]
Places to remove email+pw signup on public properties:

TODO:
- https://sourcegraph.com/cody - Replace "Or, continue with email" with "Google SSO"
- https://sourcegraph.com/get-cody -Replace "Continue with Email" CTA with "Google SSO"

Done:
- https://about.sourcegraph.com/
- Modal on about.sourcegraph.com
- https://about.sourcegraph.com/cody 

Update on github.com/sourcegraph/about

**Comment by chenkc805** [comment]
CC: @dominiccooney @toolmantim @danielmarquespt @unknwon @bobheadxi

**Comment by rrhyne** [comment]
This should cover the about required about site changes:

https://github.com/sourcegraph/about/pull/6478

**Comment by chenkc805** [comment]
Reassigning back to me for prioritization.

**Comment by chenkc805** [comment]
This is already done
