### ISSUE TITLE
Split Chat & Autocomplete configuration

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/cody#987]
Currently Chat and Autocomplete share configuration this means that it is not possible to use a different provider for chat & autocomplete:

This issue is to spilt the configuration for Chat & Autocomplete so they can be configured separately.  A future issue may add functionality to enable/disable chat and autocomplete independently.

**Comment by cbart** [comment]
@chwarwick is this ready to be closed?

**Comment by chwarwick** [comment]
@cbart  I didn't get it into 5.2 and due to no longer needing this for a customer I haven't revived it yet. Thats why I kicked it back over to the long term pile.

**Comment by cbart** [comment]
Thank you!
