### ISSUE TITLE
[Chat]: Allow specifiying primary response language for Cody Chat

### ISSUE THREAD

**Issue by shanoaice** [sourcegraph/cody#988]
It seems like that by default Cody Chat seems to detect the display language of the system (or Visual Studio Code perhaps?) and response in that language (in my case it's zh_CN), but sometimes I may want to have Cody Chat defaults to using for example English for its response disregarding any display language sort of thing.
```[tasklist]
### Tasks
```

**Comment by jdorfman** [comment]
Hi @shanoaice. Thanks for bringing this to our attention. We have seen this issue with other languages (German). 

@abeatrix do you want me to put together a list of other similar issues?
