### ISSUE TITLE
Updated experiment code to include "null" values for users not enrolled in the experiment

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#989]
**Requirements:**

- Add a null value for experiment bucketing, in addition to "true" and "false". See example below.

For experiments that are less than 50/50 (like 10/10), can should bucket in the following way:

- 10% who are in control have false

- 10% who are in test have true

- 10% who are not in the experiment at all have null

That way enrollment is still balanced between control and test, and then we exclude everyone that wasn't meant to be in the test (the null group)

This will help with clean data analyses for experiments

**Comment by chenkc805** [comment]
CC: @philipp-spiess

**Comment by vdavid** [comment]
We don't seem to be working on this so moving this back to the backlog
